CHANGES.rst
README.rst
docs/cubeviz/import_data.rst
docs/imviz/import_data.rst
docs/mosviz/import_data.rst
docs/mosviz/index.rst
docs/specviz/import_data.rst
docs/specviz2d/import_data.rst
jdaviz/cli.py
jdaviz/core/launcher.py
jdaviz/jdaviz_cli_launcher.ipynb
pyproject.toml

This pull request adds a first-pass (i.e. ugly) launcher for Jdaviz with the ability to either select a config from a button or a filepath through #2124. Additional work is necessary to get this to the visual level of our wireframe.
https://github.com/spacetelescope/jdaviz/assets/25206008/5a75b3c1-2740-4b12-836a-b48277fd01a4
Because this is a UI element, this is expected to reduce coverage.
@mariobuikhuizen is investigating why the launcher isn't showing in voila, something Mario foresaw when prototyping this in April
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look …

Jdaviz Launcher

---

jdaviz/configs/default/plugins/line_lists/line_lists.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py

This pull request replaces list and dictionary re-assignment to force traitlets to update with the cleaner `send_state(traitlet_name)`.

replace all hacky traitlet replacements with send_state

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
jdaviz/configs/imviz/tests/test_simple_aper_phot.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/core/template_mixin.py

This pull request is a follow-up to https://github.com/spacetelescope/jdaviz/pull/2276#discussion_r1248082434 and refactors the plugin `Subset` component to use the same `filters` infrastructure as other components instead of its own `allowed_type`.  In doing so, this also implements new `is_not_annulus` and `is_not_composite` filters which can then be used directly by the aperture photometry plugin for the aperture subset dropdown component.
Fixes #2280

subset plugin components to use filter instead of allowed_type

---

CHANGES.rst
jdaviz/__init__.py
jdaviz/cli.py
jdaviz/core/data_formats.py
jdaviz/core/launcher.py

This pull request extends #2257 when a filepath is provided, identify the file and enable/disable the relevant config buttons that are compatible. Then allow the user to select the configuration they would like to load with the data selected:
https://github.com/spacetelescope/jdaviz/assets/25206008/fd4855de-e866-437f-a2f8-d6edc8fe05a5

Jdaviz Launcher: Identify compatible configs and request user to select config

---

CHANGES.rst
docs/imviz/displayimages.rst
jdaviz/app.py
jdaviz/components/toolbar_nested.py
jdaviz/components/toolbar_nested.vue
jdaviz/configs/imviz/plugins/tools.py
jdaviz/configs/imviz/tests/test_tools.py
jdaviz/core/tools.py

This pull request adds logic in jdaviz's custom nested toolbar to handle visibility, active, and "primary" status of tools based on whether they are currently applicable.
For Imviz, this is currently implemented for the blink and "matched zoom" tools, reacting to the number of active layers and viewers, respectively:
https://github.com/spacetelescope/jdaviz/assets/877591/a0fbf1ac-3239-4814-b8ee-36cf1baeded9
In specviz, this is implemented for the spectral line selection tool, reacting to the number of spectral lines plotted in the viewer:
https://github.com/spacetelescope/jdaviz/assets/877591/98d55fcd-c23e-4c33-8b8c-52e3b556e568
In the case where a tool is "removed" but was already active, the tool is deactivated and the default tool selection takes place (for cubeviz, the slice tool …

nested toolbar logic to hide inapplicable tools

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/viewers.py
jdaviz/configs/default/plugins/viewers.py
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/specviz/plugins/viewers.py
jdaviz/core/template_mixin.py
jdaviz/tests/test_subsets.py
jdaviz/utils.py

This pull request continues the work that @kecnry started in https://github.com/spacetelescope/jdaviz/pull/2207 and I continued in #2266. This fixes the first bug found in https://github.com/spacetelescope/jdaviz/pull/2182#issuecomment-1546124249 . It also applies the fix in coords info so that the collapsed composite spatial subset can be hovered over.

Add composite subset fixes

---

CHANGES.rst
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue

This PR incorporates user feedback that the Redshfit from Centroid section from the Line Analysis plugin should only be shown if lines are actually plotted.
Because this is a UI element, coverage is expected to decrease

Hide Centroid Redshift when lines aren't loaded

---

jdaviz/configs/imviz/tests/test_parser_roman.py
pyproject.toml

The latest releases of `roman_datamodels` (0.16.1) and `rad` (0.16.0) have updated schema. If we run tests with these latest releases, the Roman WFI package data can't be read, raising `jsonschema.exceptions.ValidationError: 'read_pattern' is a required property` (since https://github.com/spacetelescope/rad/pull/233 was released). 
This PR updates the ASDF package data file, and revises the test to remove a catch for a formerly expected warning that's been resolved upstream.

Update roman WFI test file for latest rad/rdm

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue

In Cubeviz (including example notebook), if you open the Plot Options plugin and switch between flux-viewer (or uncert-viewer) and spectrum-viewer, you will likely get a traceback in your log. Plot Options creates a histogram figure for flux-viewer and uncert-viewer, and switching to spectrum-viewer currently also calls the `PlotOptions._update_stretch_histogram` method, which leads to a failure because no histogram should be shown or updated. 
It looks like this was introduced in #2153, but the bug is hard to notice unless you flip between image and spectrum viewers in this one plugin.
Dev tests are still expected to fail due to glue-jupyter. …

Fix for hanging plot options in cubeviz

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py
jdaviz/core/marks.py

This pull request is to address point 4 of this comment https://github.com/spacetelescope/jdaviz/pull/2097#issuecomment-1499143076
Before
After
EDIT: Removed original image, here is the latest:
Add vmin and vmax lines to plot options histogram. [2301]

Add vmin and vmax lines to histogram

---

jdaviz/core/launcher.py

The launcher introduced an extra HTML-element, interrupting the height chain. We can use the same CSS selector as for the popout window to fix this (8f15a38f).
Fixes #2307

fix: content overflows when opening plugin tray in standalone

---

jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py

This pull request is to address point 3 in this comment https://github.com/spacetelescope/jdaviz/pull/2097#issuecomment-1499143076
Before:
After:
Add option to set bin size in plot options plugin and API call to change histogram viewer limits. [#2309]

Histogram bin size and limits

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/imviz/plugins/compass/compass.py

Seen in Imviz on windows and/or with large images, the browser can throttle the pings from #2295, which can result in `is_active` toggling repeatedly.  This coupled with an expensive call to update the stretch histogram resulted in extremely laggy behavior.  This PR tracks whether there are any known changes since the last time `is_active` was toggled, and skips re-computing the histogram unless needed.
This PR also fixes some minor layout issues where multiple widgets were placed in the same row, causing undesired outcomes when changing the width of the plugin tray.
Not really sure how to add a regression test for this... but suggestions welcomed!
Fixes #2317
Closes #2318
should add a …

Fix ping lag in plot options

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_export_plots.py
jdaviz/configs/default/plugins/export_plot/export_plot.py

This pull request is to accomplish 2 things:
* Throw explicit exception when a given path to save_figure in Export Plot plugin contains directory that does not exist (instead of failing silently).
* Also refactor the plugin to use `pathlib.Path` as @duytnguyendtn wanted.
I added tests for the exceptions but I cannot test the actual file saving functionality because CI will hang when the saving is farmed out to JS by bqplot (https://github.com/bqplot/bqplot/pull/1397/files#r726500097).

BUG: Throw error on invalid path in save_figure

---

CHANGES.rst
jdaviz/components/plugin_dataset_select.vue
jdaviz/components/plugin_layer_select.vue
jdaviz/components/plugin_subset_select.vue
jdaviz/components/plugin_viewer_select.vue
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py
jdaviz/configs/imviz/tests/test_viewers.py
jdaviz/core/template_mixin.py

This pull request fixes the defaulting behavior of a plugin select component with multiselect enabled.  Previously, even if the previous selection was valid, the current selection would be overwritten.  Now, the previous selection is maintained.  To reproduce: in imviz, create a second viewer, open plot options, enable multiselect, make a selection for the viewer, create or remove a viewer.
This type of workflow is more evident in #2341, so that should be rebased on top of this.

multiselect support for dropdown default

---

CHANGES.rst
jdaviz/configs/imviz/plugins/parsers.py
jdaviz/configs/imviz/tests/test_parser.py
jdaviz/configs/imviz/tests/test_parser_asdf.py
jdaviz/configs/imviz/tests/test_parser_roman.py
jdaviz/conftest.py
pyproject.toml

There are lots of "Roman-like" ASDF files that do not pass validation by `roman_datamodels`, but currently on `main`, attempting to parse a file that cannot be fully parsed by `roman_datamodels` raises an error. 
A minimal "Roman-like" image in an ASDF file could be constructed with:
```python
import asdf
import numpy as np
tree = {
'roman': {
'data': np.arange(16).reshape((4, 4)),
},
}
af = asdf.AsdfFile(tree=tree)
```
If the above ASDF file is passed to `roman_datamodels`, an error is raised, even though it's pretty clear that we could parse the `data` node as an image:
```python
>>> import roman_datamodels.datamodels as rdd
>>> rdd.open(af)
TypeError: Unknown datamodel type: <class 'dict'>
```
This PR allows the parser to use `asdf` to look for the usual Roman tree structure in files …

Improve Imviz parser for Roman-like ASDF files

---

.github/workflows/standalone.yml

Trying this again with (hopefully) secrets access for this PR so the build job will actually run and I can debug.
This build was passing in https://github.com/spacetelescope/jdaviz/pull/1960, trying to figure out what changed. Note that I temporarily enabled the stand alone build for PRs so I can see test it here, this will be dropped before merge.

Debug standalone build

---

docs/known_bugs.rst

Reverts spacetelescope/jdaviz#2278
Close #2263

Revert "Add doc for windows latency issue"

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/cubeviz/plugins/slice/slice.py
jdaviz/configs/cubeviz/plugins/viewers.py
jdaviz/configs/default/plugins/collapse/collapse.py
jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py
jdaviz/configs/default/plugins/line_lists/line_lists.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py
jdaviz/configs/mosviz/plugins/viewers.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/core/events.py
jdaviz/core/template_mixin.py
jdaviz/tests/test_app.py

This PR adds a public method to `Application` for updating viewer reference names. A lot of generalization was done in https://github.com/spacetelescope/jdaviz/pull/1681 to remove many hard-coded references to viewer reference names like `flux-viewer` and `spectrum-viewer` in favor of attributes on each helper, though no public methods were added for self-consistently changing viewer reference names. This is functionality has been implemented downstream in https://github.com/spacetelescope/lcviz/pull/19, where it is useful for dynamically generating new viewers with custom names. 
This PR moves that functionality into jdaviz, with a few generalizations to make it compatible with both jdaviz and LCviz. I've also found a bunch of places in plugins where we can use a `property` tag to …

Support for viewer reference name updates

---

jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/viewers.py
jdaviz/core/astrowidgets_api.py
jdaviz/utils.py

Blocked by:
* https://github.com/spacetelescope/jdaviz/pull/2358
MNT: glue-jupyter compatibility for import for https://github.com/glue-viz/glue-jupyter/pull/379 . If we end up needing to bump minversion of glue-jupyter to 0.18 anyway for other reasons, then we do not need the compatibility layer and can just switch straight to new import.
~TST: Temporarily ignore DeprecationWarning from astropy/numpy dev that is already fixed in https://github.com/astropy/astropy/pull/15116 . This should go away on its own when astropy uploads new dev wheel and then we can remove the ignore added here. I just need this out of the way to see if we get all the glue-jupyter stuff.~
~TST: Use legacy numpy print option so we don't have to deal with the new print, yet.~
list the proposed change log here for …

MNT: glue-jupyter compatibility for import

---

CHANGES.rst
docs/imviz/plugins.rst
jdaviz/app.py
jdaviz/components/plugin_editable_select.vue
jdaviz/components/tooltip.vue
jdaviz/components/tray_plugin.vue
jdaviz/configs/default/plugins/line_lists/line_lists.vue
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/imviz/imviz.yaml
jdaviz/configs/imviz/plugins/__init__.py
jdaviz/configs/imviz/plugins/footprints/__init__.py
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/plugins/footprints/footprints.vue
jdaviz/configs/imviz/plugins/footprints/preset_regions.py
jdaviz/configs/imviz/plugins/footprints/tests/test_footprints.py
jdaviz/configs/imviz/plugins/viewers.py
jdaviz/core/marks.py
jdaviz/core/template_mixin.py
jdaviz/core/user_api.py
pyproject.toml

**IMPORTANT**: this PR currently require `pysiaf` to be installed or the plugin is disabled.  We may want to either remove this dependency entirely or make it an official dependency that is installed with jdaviz.
This pull request implements a new plugin in Imviz to plot an arbitrary number of user-configured footprints from any JWST instrument, adapted from code written by @melanieclarke in https://github.com/spacetelescope/jwst_novt.  In the future, this could easily be extended to other instruments or to a generic "overlays" or "regions" plugin.
Basic support for adding and customizing any number of footprints (**NOTE** some names have been changed to be more general with "overlay"/"preset" instead of "footprint"/"instrument"): …

Footprints plugin

---

pyproject.toml

This pull request is to ignore the warning reported upstream to:
* https://github.com/scipy/scipy/issues/19065
The dask one is already fixed on their main branch, but I don't want to pull in dev dask for our test suite. We don't use it directly.

TST: Ignore array_api experimental warning when scipy-dev imports numpy-dev

---

tox.ini

This pull request is to install bqplot dev from its `master` branch again instead of 0.12.x branch. This would future-proof against incompatibility with 0.13.x when that happens.
Fixes #955
* https://github.com/bqplot/bqplot-gl/issues/12
* https://github.com/bqplot/bqplot/pull/1533
* https://github.com/spacetelescope/jdaviz/issues/1613 that needs https://github.com/voila-dashboards/voila/pull/1046 (have to wait for voila 0.4, https://github.com/voila-dashboards/voila/issues/1146)

TST: Use bqplot dev from master branch

---

pyproject.toml

because they fixed it while I was sleeping
* https://github.com/scipy/scipy/issues/19065#issuecomment-1678482617
* also related https://github.com/scipy/scipy/pull/19067
Reverts 2 out of 3 from #2369

TST: Un-ignore numpy warnings from scipy-dev

---

jdaviz/configs/default/plugins/export_plot/export_plot.py

This pull request catches when a previous call to `save_figure` is incomplete and raises a user-friendly error message (instead of a more-cryptic error from lower in the codebase).  Attempts to sit in a wait loop were unsuccessful, but could be an alternative option.

user-friendly error message when detecting png callback incomplete

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py

When subsets are selected in Plot Options in Imviz/Cubeviz, the stretch histogram update raises an error. This PR adds a `return` to drop out of the stretch histogram update method when the selected layer is a subset, avoiding the error.
This bug was discovered in #2387, splitting it out so it can be merged before 3.6.2.

fix subset histogram bug in plot options

---

jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/imviz/plugins/compass/compass.py
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/core/template_mixin.py

This pull request implements (and uses) a `@skip_if_no_updates_since_plugin_last_active` decorator for plugin methods that observe `is_active` (among other traitlets) to avoid queuing of expensive calls that can result in laggy behavior when browser throttle the pings resulting in constant toggling of `is_active`.  This is essentially a more generic implementation of the same principal as #2326 and then applied to all plugins which currently use `is_active`.
Currently this only needs to be updated from the flattening plugin in lcviz: https://github.com/spacetelescope/lcviz/pull/38, and eventually the [binning plugin (unmerged)](https://github.com/spacetelescope/lcviz/pull/28).
should add …

plugin is_active skip_if_no_updates_since_plugin_last_active decorator

---

CHANGES.rst
docs/cubeviz/plugins.rst
jdaviz/app.vue
jdaviz/configs/cubeviz/plugins/viewers.py
jdaviz/configs/mosviz/plugins/viewers.py
jdaviz/configs/specviz/plugins/viewers.py

This pull request is to make spectrum viewer axes more readable.
Right now:
* Axis label font stuff is hardcoded in `app.vue`.
* Tick label font stuff is not applied until data is loaded.
⬇️ Lab + Dark mode + 27" monitor
⬇️ Notebook + Light mode + 13" monitor (the viewer didn't fit on the whole screen)
⬇️ Standalone (voila) + Dark mode + 13" monitor (Y-axis label cut off on spectrum viewer)
⬇️ Lab + Dark mode + 27" monitor
⬇️ Notebook + Light mode + 13" monitor (the viewer didn't fit on the whole screen, Y-axis label got cut off a little)
⬇️ Standalone (voila) + Light mode (cannot get dark mode to work and it is out of scope anyway and Mosviz parser is not really that robust in standalone mode) + 13" monitor (Y-axis label cut off on spectrum viewer, both spectrum viewers really not …

Better axis fonts for spectrum viewers

---

CHANGES.rst
docs/imviz/displayimages.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue

This PR is the first towards @PatrickOgle's feature request for Photoshop's "curves" tool.  Curves shows a histogram of the pixel counts overlaid on a normalized representation of the colormap scaling. I've added a similar curve to the Plot Options histogram for image layers in Imviz or Cubeviz:
https://github.com/spacetelescope/jdaviz/assets/3497584/7e8b7667-40b7-4b59-88c8-c4c8aca66d1e

Adding colormap "curve" to Plot Options stretch histogram

---

CHANGES.rst
jdaviz/core/template_mixin.py

This pull request fixes turning off multiselect mode for a dropdown when no selections are currently made.  Previously this resulted in a traceback, but now applies the default selection for single-select mode (which may either be empty or the first entry, etc, depending on the options for that dropdown).
To reproduce:
* load any viz tool with multiple layers and/or viewers
* open plot options
* select advanced multiselect mode in top right
* in either viewer or layer, clear the selection
* click the button again in the top right to enter single-select mode
* on main, this crashes, but is handled gracefully in this PR (for plot options, the dropdown remains empty)
Note: further improvements to these edge cases could be made (to hide all other plot options information when either viewer or …

fix case of a multiselect dropdown becoming single when no selection

---

CHANGES.rst
jdaviz/core/template_mixin.py

This is a manual backport (change log conflict) of #2404.

Manual backport of PR 2404: fix case of a multiselect dropdown becoming single when no selection

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue

This pull request improves the performance of the stretch histogram and the stretch curve, especially for large images, by downsampling the data sent to the histogram and by making use of #2386 for the stretch curve introduced in #2390.
https://github.com/spacetelescope/jdaviz/assets/877591/3a99859d-2b85-4e33-a8a1-517aa837bbb6

improve stretch histogram performance (downsampling and decorator)

---

CHANGES.rst
jdaviz/core/template_mixin.py

This pull request handles the case of multiple tracebacks raised by the ping infrastructure when a popout window sends the ping, but without the timestamp in the payload.  It handles this case by assuming the _received_ time as the ping timestamp.

handle ping without timestamp

---

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue
jdaviz/configs/cubeviz/plugins/slice/slice.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/default/plugins/collapse/collapse.vue
jdaviz/configs/default/plugins/export_plot/export_plot.vue
jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue
jdaviz/configs/default/plugins/line_lists/line_lists.vue
jdaviz/configs/default/plugins/markers/markers.vue
jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.vue
jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
jdaviz/configs/imviz/plugins/catalogs/catalogs.vue
jdaviz/configs/imviz/plugins/compass/compass.vue
jdaviz/configs/imviz/plugins/footprints/footprints.vue
jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.vue
jdaviz/configs/imviz/plugins/links_control/links_control.vue
jdaviz/configs/imviz/plugins/rotate_canvas/rotate_canvas.vue
jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.vue
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/core/template_mixin.py

Similar to #2392, this pull request allows downstream apps which inherit plugins defined in jdaviz to override the "Learn More" link to point to their own docs.  If not provided in the plugin class, then the value hardcoded in the .vue file in jdaviz will still apply.  This should not affect users of jdaviz in any way.
See https://github.com/spacetelescope/lcviz/pull/43 for how this would be used in lcviz.

allow downstream apps to override docs link

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py

This pull request includes the stretch histogram (in plot options) in 2d spectrum viewers in specviz2d and mosviz, and fixes a bug related to handling zoom-limits when the x-axis is inverted (caused by linking between pixels and the spectral axis in the 1d spectrum viewer).

enable stretch histogram in 2d spectrum viewers

---

CHANGES.rst
jdaviz/core/launcher.py
jdaviz/core/launcher.vue

This pull request fixes the event handling on the click event in the launcher.
Note: v3.6 does not have this full version of the launcher, so this should not need to be backported.
Fixes #2414

fix event handling for choosing config from launcher

---

notebooks/SpecvizExample.ipynb

Some of the text here seems orphaned from when the code cell had different contents, I think this is better.

Fix explanation in markdown cell of SpecvizExample notebook

---

CHANGES.rst
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/tests/test_footprints.py

This pull request fixes respecting user-changed traitlets (specifically color, but also applies to the preset selection) when those traitlets were set in the API before the overlay objects are fully initialized when the plugin is first opened.
See the included regression test or the following example:
```
fp = imviz.plugins['Footprints']
fp._obj.vue_link_by_wcs()
fp.color = '#ff33ff'
fp.open_in_tray()
```

fix footprint defaults when changing traitlets before plugin active

---

CHANGES.rst
docs/imviz/plugins.rst
jdaviz/components/plugin_subset_select.vue
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/tests/test_subset_centroid.py
jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py
jdaviz/core/template_mixin.py
jdaviz/tests/test_subsets.py

This pull request adds multiselect support to the subset plugin for the purposes of recentering in Imviz.
Demo: 
https://github.com/spacetelescope/jdaviz/assets/7179333/248f2929-e1bf-4ef2-adf0-bb91751e6806
- Adds multiselect support to the subset plugin for recentering.

Enable multiselect in subset plugin for recentering

---

jdaviz/app.py
jdaviz/configs/cubeviz/cubeviz.yaml
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_helper.py
jdaviz/configs/default/default.yaml
jdaviz/configs/default/plugins/export_plot/export_plot.py
jdaviz/configs/default/plugins/export_plot/export_plot.vue
jdaviz/configs/imviz/imviz.yaml
jdaviz/configs/mosviz/mosviz.yaml
jdaviz/configs/specviz/specviz.yaml
jdaviz/configs/specviz2d/specviz2d.yaml

This pull request creates a traitlet in the "Export Plot" plugin so that notebooks running a standalone UI can disable the capability for cubeviz movies (#2264).  The movie implementation saves the movie on the python/server-side, so would for cases where the python/server and browser/client are on different machines, it may make sense to disable (at least until we re-implement to send the movie _through_ the browser's save file dialog).
This can be done in the launching notebook via: `cubeviz.plugins['Export Plot']._obj.movie_enabled = False`.
Alternatively, this will _default_ to `True` if the configuration sets `server_is_remote: true`, _before_ the plugin is first initialized.
should …

API access (hidden) to disable cubeviz movie UI

---

pyproject.toml

This pull request ignores the deprecation warning from traitlets:
```
E   DeprecationWarning:
E               Sentinel is not a public part of the traitlets API.
E               It was published by mistake, and may be removed in the future.
```
looks like bqplot imports traittypes, which has an `import *`, which includes the line `Empty = Sentinel('Empty', 'traittypes',` which is triggering the deprecation warning 🤔 

TST: ignore sentinel deprecation warning from traitlets

---

CHANGES.rst
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/tests/test_simple_aper_phot.py
jdaviz/core/template_mixin.py

This pull request implements the (not-yet public*) plugin API for batch processing of aperture photometry.  The main method (`plugin.batch_aper_phot`) takes a list of dictionaries with traitlets names and values as inputs, loops over the list, sets the traitlets, and calls the existing internal method to compute aperture photometry.  The results are then available in the results table (from the plugin UI or API, once its public) and the state of the plugin, including the plot, is left based on the last iteration from that list.  Any value that is not provided in a dictionary will be adopted from the "current" state at the time (either the original plugin state or as it was left from the previous iteration).  *This is something we may want to reconsider - perhaps restoring to the original …

Aperture photometry batch mode API

---

jdaviz/configs/imviz/tests/test_astrowidgets_api.py
jdaviz/configs/mosviz/tests/test_parsers.py

Reverts spacetelescope/jdaviz#2451 now that https://github.com/spacetelescope/gwcs/pull/475 is merged upstream. 🤞
xref https://github.com/spacetelescope/jdaviz/issues/2446

Revert "TST: Ignore ASDF warning about gwcs-1.0.0 schema"

---

CHANGES.rst
jdaviz/core/template_mixin.py
jdaviz/tests/test_plugin_is_active.py

This pull request aims fix lag and "flickering" issues within the `is_active` ping logic, hopefully for the last time 🤞 .
See:
* #2295 
* #2326 
* #2386
**TODO**: 

improvements to is_active ping logic

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue
jdaviz/tests/test_subsets.py
jdaviz/utils.py

This pull request is a continuation of #2421, which enables freezing of subsets. This converts them to a `MultiMaskSubsetState` which in this PR can be returned through `app.get_subsets()` and is visible  in the Subset Plugin. If `simplify_subset` is set to True and there are `MultiMaskSubsetState` objects in the Composite subset, they will be ignored so that the Range objects can be combined into a SpectralRegion object.
To get the Freeze button to appear:
```
plugin = viz.app.get_tray_item_from_name('g-subset-plugin')
plugin.can_freeze = True
```
- Add support for MultiMaskSubsetState in get_subsets() and the subset plugin.
This checklist …

Add masked subset support

---

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_helper.py

Similar to #2440 (and using the same solution), this pull request allows disabling the support for saving a moment map to a fits file until we change that implementation to save through the browser client-side.

API access (hidden) to disable moment map server-side saving

---

docs/dev/release.rst

This PR adds a section to the release docs explaining how to set the vX.Y.x  branch back up for development after a bugfix release from that branch (to close https://jira.stsci.edu/browse/JDAT-3738). I also added a section describing a scenario where there is a change log section for a planned bug fix release, but that release is skipped in favor of a major/minor release, and those entries need to be moved and the bug fix section removed.

update bugfix release instructions

---

jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py

I don't know why it increased to 15. I just want the green checkmark back.
Fixes #2476 

TST: Fix specviz2d test failure

---

CHANGES.rst
jdaviz/app.py

https://github.com/spacetelescope/jdaviz/pull/2338 implemented viewer reference name updates, with an option to update viewer IDs as well. That feature is intended for internal use in lcviz. 
Subsequent development in lcviz exposed a bug in the jdaviz method when `update_id=True` (https://github.com/spacetelescope/lcviz/pull/35). Each viewer's entry in the viewer store has a hidden attr `_reference_id` which should match `viewer_item['id']`, but #2338 did not update that attr.
Also, the ID is only updated if `update_id=True` _and_ `viewer_item['id'] == old_reference`, but the latter condition is satisfied if the ID matches the reference name (which is not required elsewhere).
This PR adds the missing update to the hidden reference_id attr, and removes the unnecessary second condition for …

bugfix for viewer rename when viewer ID is different from reference name

---

jdaviz/core/tests/test_autoconfig.py

Noticed this while working on something else (#2431). No reason to roll our own temporary directory here. Must have slipped past PR review stage.

TST: Use tmp_path in test_autoconfig

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py

This pull request is to hook the Moment Map logic into our existing hack for everything else in Cubeviz.

BUG: Moment map retains WCS on write

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/fitting_backend.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
jdaviz/configs/specviz/plugins/parsers.py
jdaviz/core/template_mixin.py

This PR passes the `filter_non_finite` flag (set to True), to `specutils.fitting.fit_lines`. This allows non-finite values in the uncertainty/weights array to be filtered out before fitting, allowing the fit to proceed without NonFiniteValueError.
Closes #2328

add fit_non_finite flag to model_fitting 1D

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/specviz/plugins/viewers.py
jdaviz/configs/specviz/tests/test_helper.py

This pull request is to see if we can handle spectrum with incompatible flux unit without having to introduce more links.
While I was at it, I also try the "hold sync" trick on a couple of plotting code, like Maarten said. Technically irrelevant to the bug but doesn't hurt?
Fixes #2459

BUG: Handle incompatible Specviz flux unit

---

CHANGES.rst
docs/specviz/displaying.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue

This pull request adds swatches to the color picker. The colors in the swatch were picked with consultation from OPO.

Preset palettes

---

docs/mosviz/import_data.rst

This pull request is to fix Mosviz doc in regards to NIRSpec level 2 parsing.

DOC: Fix Mosviz parser file list for NIRSpec

---

CHANGES.rst
docs/imviz/plugins.rst
jdaviz/components/plugin_dataset_select.vue
jdaviz/components/plugin_layer_select.vue
jdaviz/components/plugin_subset_select.vue
jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py
jdaviz/configs/imviz/helper.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
jdaviz/configs/imviz/tests/test_parser.py
jdaviz/configs/imviz/tests/test_simple_aper_phot.py
jdaviz/core/region_translators.py
jdaviz/core/template_mixin.py
notebooks/concepts/imviz_advanced_aper_phot.ipynb
notebooks/concepts/imviz_simple_aper_phot.ipynb

TODO before merge:
Follow-up efforts:
This pull request updates the aperture photometry plugin to:
* allow overriding individual traitlet names as optional inputs to API methods (requiring significant moving of code),
* renames `subset` -> `aperture` and `bg_subset` to `background`,
* renames the plugin from "Imviz Simple Aperture Photometry" to "Aperture Photometry" since its no longer simple and that is easier to remember for accessing the user API, 
* generalizes some re-used logic and make use of caching when possible,
* exposing basic components/traitlets and methods through the user API (if we're not ready to commit to the exposed names, that can easily be disabled for this PR and re-introduced later),
* changes the [batch methods](https://github.com/spacetelescope/jdaviz/pull/2401) …

Aperture photometry: refactor, batch mode, enable user API

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/parsers.py

This pull request is to address the wavelength unit portion of #2502 . 
* Extension name is DATA.
* CUNIT3 is AWAV (no E).
With this patch:
Performance issues with large cube still exist and are out of scope here.

BUG: Cubeviz to recognize VLT MUSE data

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/tests/test_subsets.py

* https://github.com/glue-viz/glue-astronomy/pull/96 (actually don't think this is needed after all)
- ~Update `glue-astronomy` pin in `pyproject.toml` after the PR above is merged and released.~
Adds API to export sky regions for spatial subsets, as part of get_subsets(). If  'export_sky_region'=True, both a pixel and a sky region will be returned from get_subsets. 
JDAT 3498
~Requires https://github.com/glue-viz/glue-astronomy/pull/96~

Add Sky Regions to get_subsets()

---

tox.ini

We still cannot escape having to install spectral-cube because of https://github.com/glue-viz/glue-astronomy/issues/62 . So we need:
* https://github.com/radio-astro-tools/spectral-cube/pull/891 and
* https://github.com/radio-astro-tools/radio-beam/pull/116
to be released upstream.
Example failure: https://github.com/spacetelescope/jdaviz/actions/runs/6500257549/job/17655283046

TST: Grab dev spectral-cube and radio-beam to fix devdeps

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/core/template_mixin.py
jdaviz/core/tests/test_tools.py
jdaviz/core/tools.py

Opening as draft since I'll need a test and changelog entry.

Add stretch bounds tool to plot option histogram viewer

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/imviz/tests/test_delete_data.py

Docstring for `app._reparent_subsets` from #2409 suggests that the user can provide as arguments `Data` objects or their labels as strings. The logic for supplying strings wasn't covered by the tests, and fails when used. This PR fixes that bug and tests for it.

Bugfix: enable str arguments for app._reparent_subsets

---

docs/conf.py

This pull request is to explicitly set `navigation_with_keys` to silence `pydata-sphinx-theme warning` that is failing RTD.

DOC: Explicitly set navigation_with_keys

---

CHANGES.rst
docs/imviz/displayimages.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py
jdaviz/core/template_mixin.py
notebooks/concepts/imviz_colorbar_mpl.ipynb

This pull request is a different approach to encode colorbar information on the Plot Options histogram. Previous attempt to use pure bqplot (#2514) failed. This one lifts code from glue-core to compute the colors using matplotlib and then throw them on the bqplot histogram directly.
Known issues due to it listening to too many things at once, I think. Not sure how to make it cleaner:
* Wonky after toggling multiselect on/off.
* Wonky after selecting/deselecting subset.
* Wonky after zooming in/out too fast while having it follow zoom.
* Possibly unrelated bug of it crashing when destroying viewer. https://github.com/spacetelescope/jdaviz/issues/2521
should add a …

Colorbar on histogram

---

pyproject.toml

Remove warning filters that are no longer needed for testing

---

CHANGES.rst
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/core/template_mixin.py

This pull request is to show "sum" as scientific notation.
This already exists:
With this PR, this also matches:

Imviz: Aperture photometry sum in scientific notation

---

jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py
jdaviz/core/template_mixin.py

This pull request:
* consolidates code introduced in #2525, #2517, #2513, and #2390 to be in a single loop and avoid code duplication.
* consolidates the UI itself by moving redundant input options (vmin, vmax, etc - now that these are editable interactively in the plugin plot) into an expandable menu.
* removes infrastructure code added in #2390 to support multiple layers in the stretch histogram as that is no longer planned, and if we do ever want to introduce it, would require more general code and design with these new capabilities built on top.
* scales the curve to 0.9 to avoid overlapping the colorbar
* shows the stretch curve by default
No changelog entry needed as none of these changes have seen a release yet.
Note: this is expected to have a merge conflict with #2537, but should …

consolidate stretch histogram code

---

jdaviz/app.vue
jdaviz/configs/cubeviz/plugins/slice/slice.vue
jdaviz/configs/default/plugins/export_plot/export_plot.vue
jdaviz/configs/default/plugins/line_lists/line_lists.vue
jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue

This pull request removes the negative margin for expansion panels _within_ plugins.
**Before**:
**After**:

UI: improve margin in expansion panels in plugins

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py

The Plot Options stretch histogram curve from #2390 looks fine in Gray colormap, but does not look fine in other colormaps. Here's an image with a linear stretch showing a nonlinear curve in the stretch histogram:
In reproducing the logic in [glue's CompositeArray module](https://github.com/glue-viz/glue/blob/4de2cfd31670acb9aae60d198be4a5f83ebd8c0e/glue/viewers/image/composite_array.py#L137-L139), I apply the stretch, contrast, and bias correctly, but then I went one line too far and also applied the _colormap_ to the values that should represent the curve. That's not what we want! In the gray colormap case, the colormap is linear+monotonic so you don't notice the problem. 
This PR corrects the implementation to work with any colormap:
list the proposed change log here for review and add …

Bugfix: correction to Plot Options stretch function curve

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/imviz/tests/test_viewers.py

Closes #2521 , turned out to be very simple once I tracked it down. This was previously causing an error if the viewer was deleted, since `None` has no `state`.

Don't try to update viewer state if it was deleted

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.vue

This pull request puts viewer settings before layer settings.
- Reorder viewer and layer settings in the plot options plugin. [2543]

Have viewer settings come before layer settings in Plot Options

---

jdaviz/components/viewer_data_select.vue

This pull request changes the default "collapse/expanded" state for the "show data not in viewer" section of the viewer's data menu to be opened when there is no data loaded in the viewer.  Note that this default only applies when the menu is _first_ opened, but saves an extra click and perhaps some confusion when first creating a new (empty) viewer.  We could potentially automatically re-open the section when all data is manually unloaded, but that would take more logic to catch those events, and arguably there is more feedback and the user isn't confused by an empty viewer when they were the ones who removed everything from it.
Before:
After: …

expand "show data not in viewer" for empty new viewer

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/core/template_mixin.py

This pull request removes the stretch bounds tool, introduced in #2513 (milestoned to 3.8, so no need for a bugfix here), from all viewers except the stretch histogram.

only include stretch tool in stretch histogram

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.vue

#2543 re-ordered entries in the plot options so that viewer-level options occur before the layer dropdown.  This is confusing when the visibilities of some of these entries depend on the selected layer.  This PR makes it so that the visibility of these viewer-level options is only based on the selected viewer(s) and not layer(s).
For example, in Imviz with multiselect enabled and NO layer selected, colormap was not showing at all before this PR, but now shows regardless of the selected layer(s).
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not …

always show viewer-level options regardless of selected layer

---

codecov.yml

This pull request is to address codecov now setting patch threshold to zero in PRs, rendering patch coverage meaningless.
https://docs.codecov.com/docs/commit-status#patch-status

TST: Adjust threshold for codecov patch to be non-zero

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py

Pretty self explanatory, I hope. Ready for everyone to try to break it. Demo with 6 layers (note that I changed the button text and decided to set stretch to 99% for all layers since I made this recording):
https://github.com/spacetelescope/jdaviz/assets/39831871/7f7a3f0f-f39f-4236-be3c-3ceca5efab63

Add button to automatically apply RGB presets

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py

As requested in https://github.com/spacetelescope/jdaviz/pull/2558#issuecomment-1811030409.

Reverse preset color order

---

CHANGES.rst
jdaviz/components/plugin_add_results.vue
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/default/plugins/collapse/collapse.py
jdaviz/configs/default/plugins/collapse/collapse.vue
jdaviz/configs/default/plugins/export_plot/export_plot.py
jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py
jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/plugins/catalogs/catalogs.vue
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/core/template_mixin.py

This pull request implements re-usable infrastructure via a `@with_spinner()` method, which sets the `spinner` traitlet to True at the beginning of a method, and resets to False when it completes (successfully or not).  This traitlet can then be used to disable and change the icon on the action button by passing it to `<plugin-add-results :action_spinner='spinner'>`.  For expensive operations, this provides immediate feedback that something is happening and avoids the user clicking the button again before the action completes.
For more advanced cases, individual boolean traitlets can be added to the plugin and controlled separately by passing the name of the traitlet to the decorator.  For example `@with_spinner('spinner_custom')`.
All the logic lives in `template_mixin.py` and …

plugins: disable action button while computing

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/slice/slice.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/default/plugins/collapse/collapse.py
jdaviz/configs/default/plugins/export_plot/export_plot.py
jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py
jdaviz/configs/default/plugins/markers/markers.py
jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/plugins/compass/compass.py
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/plugins/links_control/links_control.py
jdaviz/configs/imviz/plugins/rotate_canvas/rotate_canvas.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/core/template_mixin.py
jdaviz/core/user_api.py

This pull request adds a new method to all plugin user APIs to close the item in the tray (useful for demos and notebook workflows, especially when the plugin in question has live-previews enabled).  By default, it does not close the tray itself, but accepts an optional argument to close the entire tray.

plugin API method to close_in_tray

---

jdaviz/core/template_mixin.py

Glue scatter viewers plot 2D scatter points, with an option for custom sizes and colors, mapped onto any of the glue `Data`'s components. In order for this to work correctly, the [glue `ComponentIDComboHelper`s](https://github.com/glue-viz/glue/blob/47012410f0a60ef59a2bb00725e464e189609bbc/glue/core/data_combo_helper.py#L118) like the `cmap_att_helper`, which can be found at `viewer.layers[0].state.cmap_att_helper`, must have a list of `choices` which are in sync with all of that layer's `Data` components. If components can be added or renamed, the component choices within `PlotOptionsSyncState` _should_ be updated. I was using this feature in LCviz today, and I found that those component choices do not get updated (😱). 
I traced the problem back to one line, and implemented a fix in this …

Allow change in cmap_att on change in data components

---

docs/installation.rst

In installation.rst, the order of development install instructions have been changed (primarily to move the editable environment to the last step). The addition of IPython magic commands were included as an optional suggestion for developers, and a brief description to code contribution instructions (hyperlink to astropy instructions) was added so a new developer can briefly understand what is hyperlinked; and a general suggestion to virtual environments is now suggested.
**Original Instructions**
**Updated Instructions** …

Update jdaviz developer installation instructions

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_export_plots.py
jdaviz/configs/cubeviz/plugins/tests/test_regions.py
jdaviz/configs/cubeviz/plugins/viewers.py
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/viewers.py
jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py
jdaviz/configs/imviz/tests/test_footprints.py
jdaviz/configs/imviz/tests/test_linking.py
jdaviz/configs/imviz/tests/test_regions.py
jdaviz/configs/imviz/tests/test_simple_aper_phot.py
jdaviz/configs/imviz/tests/test_tools.py
jdaviz/configs/imviz/tests/utils.py
jdaviz/core/helpers.py
jdaviz/core/template_mixin.py
jdaviz/core/user_api.py
jdaviz/tests/test_app.py
jdaviz/tests/test_subsets.py
jdaviz/tests/test_user_api.py
notebooks/concepts/imviz_color_display.ipynb
notebooks/concepts/imviz_dithered_gwcs.ipynb

This pull request adds access to viewer user-APIs (in the same way that plugin user-APIs are handled) with access to `zoom`/`zoom_level` (as well as _all_ astrowidgets API methods that were previously available through `imviz.default_viewer`) for image viewers and `set_lims(x_min=None, x_max=None, y_min=None, y_max=None)` for other viewers.  This also point `imviz.default_viewer` to this user-API layer for consistency and to prevent accessing methods/attributes that are not currently considered public.
~In order to add `zoom`/`zoom_level` to image viewers in Cubeviz, this also adds the astrowidgets mixin to the image viewers in cubeviz.~
For example:
```
imviz.viewers['imviz-0'].zoom(2)
cubeviz.viewers['spectrum-viewer'].set_lims(x_min=4000, y_max=1.3)
```
list the proposed change log …

viewer user-APIs exposing zoom/limit options

---

jdaviz/configs/default/plugins/plot_options/plot_options.vue

I noticed `style` was getting set here twice, this removes the second one and some stray white space that snuck in at some point.

Don't set style twice

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py

This pull request generalizes and approves the stretch histogram's support for the new separate multiselect modes introduced in #2574 - the stretch curve and colorbar now works correctly regardless of whether the viewer and/or layer are in multiselect mode, supports multiple viewers selected (in which case vmin/vmax lines are currently shown based on the first entry - we could eventually somehow represent mixed state here somehow, but it isn't clear if that is necessary yet).  Note that the entire histogram is hidden if the select layer is a subset OR if multiple layers are chosen.
This checklist is meant to remind the package maintainer(s) …

stretch histogram support multi-select

---

jdaviz/configs/imviz/tests/data/ds9_annulus_01.reg
jdaviz/configs/imviz/tests/test_regions.py

Fix `ds9_annulus_01.reg` test case. No user-facing functionality is affected. Just that the test was poorly written. My bad.
Thanks to @cshanahan1 for catching this!

TST: Fix ds9_annulus_01.reg test case

---

CHANGES.rst
jdaviz/components/tooltip.vue
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/default/plugins/collapse/collapse.py
jdaviz/configs/default/plugins/collapse/collapse.vue
jdaviz/configs/default/plugins/collapse/tests/test_collapse.py

This PR adds functionality to the cubeviz collapse plugin to save an output FITS file.

save collapsed spectrum to FITS

---

pyproject.toml

#2152 removed support for python 3.8, but the min version in pyproject.toml was not updated

update min python in pyproject

---

CHANGES.rst
jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py
jdaviz/configs/imviz/tests/test_line_profile_xy.py

This pull request is to address plotting line profiles when NaN is present. With this patch, the plot should now look like this instead of a blank plot:
I still see this in the browser dev console but does not seem to break Imviz:

BUG: Fix Line Profile when there is NaN

---

.github/CODEOWNERS
.mailmap
CITATION.cff

This pull request adds @gibsongreen to the codeowners, mailmap, and citation file.
**TODO**:

add @gibsongreen to codeowners/mailmap/citation

---

CHANGES.rst
jdaviz/components/toolbar_nested.py

This pull request fixes the case where clicking a tool in the toolbar dropdown menu could lose the ability to select other suboptions.  This was happening because the "has_suboptions" on the tool was originally set to False and not updated later when it then became the "primary" tool in the sub-menu.  This fix is perhaps overly conservative, but ensures that the "has_suboptions" will always be kept up-to-date in advance of choosing a new tool.
This could be reproduced in specviz2d by selecting the non-synced zoom tool in either viewer. …

fix nested toolbar losing suboptions

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue
jdaviz/core/template_mixin.py

This pull request implements support for continuum subtraction within the moment map plugin in cubeviz.  It does so by refactoring code in line-analysis into a reusable component, showing the same input options and visualization (but with additional descriptive text to explain that the continuum is re-computed per-spaxel when computing the moment map).
https://github.com/spacetelescope/jdaviz/assets/877591/012d84cf-a7a9-4a12-ad54-53b18387146d
This PR also includes a commit (since reverted but left in the PR diff in case we want to revisit it) which would enable exporting the continuum as a cube back into the app.
**TODO**:
This checklist is …

Moment map continuum subtraction

---

CHANGES.rst
jdaviz/configs/default/plugins/line_lists/line_lists.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py

This pull request fixes the case where removing data from a cube viewer in cubeviz would raise a traceback from the plugins through the spectral viewer.  To reproduce: load cubeviz, open moment maps, calculate moment map (adding to viewer or not, does not matter), use the data-menu in the uncertainty viewer to remove the moment map.  Previously this resulted in a callback from either line lists or line analysis.

fix removing cube data from cubeviz

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/core/template_mixin.py
jdaviz/core/tests/test_tools.py
jdaviz/core/tools.py

This draft pull request is to test Tom's implementation for enabling custom stretches. At the moment, the setters for the knots haven't been finalized yet. However, we can currently set the knots' (x, y) values dynamically and observe the updates of both x and y on the image viewer and the histogram.
```
viewer.state.layers[0].stretch = 'spline'
viewer.state.layers[0].stretch_parameters['knots'] = ([0,0.2,0.4,1.0],[0, 0.3, 0.5, 1.0])
viewer.state.layers[0].stretch_object
viewer.state.layers[0].stretch_object.knots
``` …

Interactive spline

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py

Updates the recent Moment Maps unit work to better align with PO specs by displaying the actual physical units (including flux units for moment 0), and giving the option to reduce all higher moments to velocity rather than velocity^N.

Moment units redux

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue

This pull request implements the "mixed state overlay" for the stretch histogram when ANY of the inputs (stretch function, vmin, vmax, color mode, color, colormap - and knots should be added either her or #2545, whichever is merged second) are mixed and unmixes ALL of them when clicking.
https://github.com/spacetelescope/jdaviz/assets/877591/da6bb1f7-5dd0-4d1d-a20e-90ef10579222

stretch histogram: handle mixed state

---

jdaviz/tests/test_subsets.py

This pull request adds a test that makes sure renaming a subset does not change the result of a `get_data` call.

Test get_data when changing a subsets label

---

jdaviz/main_styles.vue

This pull request always hides the "x" button in the top right of a golden layout panel (which otherwise would close all viewers in that tab group), so that we can prevent closing specific viewers via css filters on the tab itself.  Otherwise, users could move a "protected viewer" tab with "x" disabled into a group, and then ultimately delete the viewer by closing the entire group.

always hide button to close group of tabs

---

.github/workflows/standalone.yml

Turns out this isn't a drop-in replacement. Now I see weird standalone build failure for Windows, so reverting.
xref https://github.com/actions/upload-artifact/issues/472

Revert "Bump actions/upload-artifact from 3 to 4 in /.github/workflows"

---

CHANGES.rst
jdaviz/components/viewer_data_select.vue

This pull request implements a patch where the collapsed spectrum data entry did not show in the spectrum viewer data menu in cubeviz if the flux cube's label was [SCI] instead of [FLUX].  In a future refactor that moves this logic into python, we can do a more general check instead of having to rely strictly on the label.

fix [SCI] data not showing in cubeviz spectrum viewer's data menu

---

CHANGES.rst
jdaviz/configs/default/plugins/viewers.py
jdaviz/core/helpers.py
jdaviz/tests/test_user_api.py

This pull request implements `viz.data_labels`, `viz.viewers[...].data_labels_loaded`, and `viz.viewers[...].data_labels_visible` which are each a read-only list.  This is intended to provide an alternative to suggesting users access `viz.app.data_collection` to inspect the list of data labels eligible to be passed to `viz.get_data()`, etc.
In the future, `viz.viewer[...].data_labels` as a list of all data entries supported by a specific viewer (those loaded as well as those in the expanded data menu) would be convenient, but currently all that logic lives in vue, not python.
See https://github.com/spacetelescope/jdat_notebooks/pull/203 for how this would allow us to remove non-public API from public-facing notebook examples.
list the proposed change log here for review and add to …

helper and viewer-level access to data_labels properties

---

jdaviz/components/viewer_data_select.vue

This pull request updates the logic for data-item visibility within the data-menu for lcviz (currently upstream until we refactor and have a way to override this downstream) to handle the new flexibility introduced by https://github.com/spacetelescope/lcviz/pull/74 

lcviz support: fix data-menu item visibility cloned phase-viewer

---

notebooks/ImvizExample.ipynb

This pull request is to remove `my_mask` from `ImvizExample` notebook because it is crashing some other cells. `my_mask` was originally designed with `ImvizDitheredExample` in mind and simply copied over to `ImvizExample` later. It is not critical for typical Imviz operations.
Fixes #2638

DOC: Remove my_mask from ImvizExample

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue

This pull request implements a spinner showing when the data for the stretch histogram is updating.

spinner while stretch histogram data updating

---

CHANGES.rst
jdaviz/app.vue

This pull request implements a minor styling tweak so that the app top-bar aligns with the rest of the app across notebook/lab/popout/mast.
Before (look at 1 pixel white space in the popout to the left and right of the top toolbar):
After:

fix top app bar style to align in notebook, popout, and mast

---

jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py

This pull request is to handle second warning in `test_all_nan_uncert_subset` because pytest 8 will turn it into exception but it is hidden in older pytest. Noticed this in #2654 when pytest 8.0rc1 doesn't crash for other reasons (log: https://github.com/spacetelescope/jdaviz/actions/runs/7450389588/job/20269179809?pr=2654).
You can prove this to yourselves by `pip install pytest --pre -U` locally and then run the test suite. 
xref https://github.com/spacetelescope/jdaviz/issues/2643

TST: Handle second warning in test_all_nan_uncert_subset

---

jdaviz/configs/imviz/tests/test_catalogs.py
pyproject.toml
tox.ini

We are letting real bugs through waiting on shapely to acknowledge numpy 2.0, so I think it is less risky to disable numpy-dev for now so we can test dev versions of the rest.
<hr/>
TST: Add pyerfa-dev to devdeps and remove unnecessary tox requirements.
BLD: No longer need to specify wheel in build requirements.
xref https://github.com/astropy/astropy/issues/15638
* https://github.com/scikit-image/scikit-image/issues/7249
* https://github.com/glue-viz/glue/issues/2469
* https://github.com/shapely/shapely/issues/1949
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look …

TST: Fix devdeps job

---

CHANGES.rst
jdaviz/configs/cubeviz/helper.py
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py

https://github.com/spacetelescope/jdaviz/assets/42986583/f160e86a-2813-4c14-8897-7caa97ab9c57
This PR resolves a traceback bug that arises when loading datasets with N = 0 or N > 1 in one or both Cubeviz image viewers. Previously, this issue disabled spectral extraction, as the extraction process assumed the presence of only one dataset in each viewer. The patch introduced in this PR tracks when the parser adds uncertainty and flux data to the data collection (via metadata) and selects the now labeled data for spectral extraction. 
Notes:
Cubeviz plugin tests pass including parsers tests, spectral extraction tests are not passing. 
GIF parser does not differentiate data type (flux,  uncert., mask, etc.) until after the add_data function, disabling the ability to add metadata. 
list the …

 Resolving traceback bug in cubeviz spectral extraction

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue

This pull request exposes the spatial subset opacity in the plot options (UI and API).

expose spatial subset opacity in plot options

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py

This now converts the spectral axis of the input cube to velocity prior to sending it through the moment calculation rather than attempting to convert the result afterward, thus fixing the display units of the result. 
I believe that the reported unrealistic negative values for moment 2 are an artifact of doing continuum subtraction on pixels that are essentially noise around the continuum - the calculation is `np.sum(flux * (dispersion - m1) ** order, axis=axis) / m0`, so even though the dispersion term is getting squared, with negative flux values (especially far from m1) you can end up with a negative second moment in those cases. Everything looks ok when you do the moment calculation without continuum subtraction. Here's an example of the spectrum at a pixel that results in a negative …

Fix display units of moments in velocity

---

CHANGES.rst
docs/cubeviz/displaycubes.rst
jdaviz/configs/cubeviz/plugins/tests/test_tools.py
jdaviz/configs/cubeviz/plugins/tools.py

Now shows spectrum and auto-scales spectrum viewer when hovering with the single-spaxel subset tool activated, see demo:
https://github.com/spacetelescope/jdaviz/assets/39831871/98b989f0-d798-4a25-b529-30d74e3db1a0
Opened as draft since I still need to add tests and update docs. Outstanding question: do we want to reset the spectrum viewer limits to the default when deactivating the tool/leaving the viewer area?

View spectrum from single spaxel on hover

---

CHANGES.rst
jdaviz/app.py
jdaviz/components/viewer_data_select.vue

As an alternate option to #2669, this decouples each data-menu from other instances in the same viewer (so only a single menu will be open if multiple instance of the app are being shown).
Fixes #2581
Close #2669

remove state-sync for data menu open

---

CHANGES.rst
jdaviz/configs/imviz/plugins/footprints/footprints.py

This pull request fixes the footprint plugin after #2179 was merged so that the footprint updates when the orientation is changed.

update footprint on change to orientation

---

jdaviz/app.py

This pull request generalizes the logic for adding a new viewer so other configs/viewers that don't use the concept of reference data and wcs-linking (introduced in #2179) do not raise a traceback.
This is a minor change to a feature not-yet-released, so does not need a changelog entry of its own (although we could append the PR number to the image rotation PR if a link between the PRs in GitHub is not sufficient papertrail).

fix new viewer after image rotation

---

CHANGES.rst
jdaviz/components/plugin_section_header.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/core/marks.py
jdaviz/core/template_mixin.py

This pull request implements the basic UI framework for planned spectral extraction work in cubeviz, including:
* background subtraction
* live-previews
* sub-pixel support
* wavelength dependent (cone) support for apertures and background
All of these are currently behind "feature-flags" so do not show for the user if/when merged into main.  As each individual feature is completed, we can remove the feature flag.
Changes that this makes to main _now_:
* adds section headers (aperture & extraction) and selects which is active according to mouseover
* updates styling for action subsection in specviz2d spectral extraction
* moves function dropdown to bottom of plugin (in extraction section)
**Without feature flags** (ie. how users will see this now): …

feature-flagged wireframe for cubeviz spec extraction plan

---

jdaviz/components/viewer_data_select.vue
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/imviz/plugins/coords_info/coords_info.py

This pull request:
* ~adds an lcviz exception to which indices from the cube array to pull mouseover information.  This would be nice to generalize in a way that the helper or viewer can store the order, but is difficult to do.~. Refactor coords_info (mouseover information) so that lcviz can override the dimensions to grab from the cube in https://github.com/spacetelescope/jdaviz/pull/2678.
* generalizes plot options stretch histogram to pull from the layer attribute rather than assuming to plot this histogram of the first component
* extends on existing lcviz exceptions in the data menu filtering logic to only show TPF entries in cube viewers (and exclude them from light curve viewers) based on data dimensionality
This is not expected to change any behavior in jdaviz itself.
To test in …

lcviz cube support

---

jdaviz/configs/imviz/plugins/orientation/orientation.py

This pull request is to address an alleged crash that I cannot reproduce. But from the given traceback, I think this patch would have fixed it but maybe Kyle (the reporter) or Brett (the original code author) can confirm. Since this is to patch an unreleased feature (#2179), there is no need for change log.
Instead of crashing, I see the subset highlighted for the fake WCS layer, which I think is a completely different issue. This screenshot shows the subset overlay on the small fake WCS layer as a rectangle (it was drawn as a circle): …

BUG: Only access meta when it exists

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
jdaviz/configs/imviz/tests/test_parser.py
jdaviz/configs/imviz/tests/test_simple_aper_phot.py
jdaviz/core/template_mixin.py

This pull request allows non-apertures as choices in subset dropdowns for aperture photometry and spectral extraction and validates them during selection (or on a change to the underlying subset) with the following behavior:
* aperture photometry's aperture: only allow apertures (no composite, no annulus) and disable the compute button when not valid
* aperture photometry's background: allow any subset (in the future if we implement active sections, highlighting will not be done for non-apertures)
* spectral extraction's aperture: non-apertures disable wavelength dependence (for aperture and background) and subpixel support, with in-plugin warnings
* spectral extraction's background: non-apertures disable wavelength dependence (background only) and subpixel support, with in-plugin …

Aperture validate after selection

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py

This pull request is to fix how output cube gets loaded back into the app to prevent error when input cube has invalid 3D WCS (e.g., just the spectral WCS without spatial info).

BUG: Cube fit should work even without valid 3D WCS

---

CHANGES.rst
jdaviz/components/viewer_data_select.vue
jdaviz/container.vue

This pull request fixes the issue of the cut-off data menu in smaller viewers when the list is longer.
https://github.com/spacetelescope/jdaviz/assets/66814693/96b50038-ff37-490f-b5a4-2296c44cfe0d
Fixes #2551 

Fix data menu cutoff in smaller viewers

---

notebooks/concepts/imviz_roman_asdf.ipynb

The work to support Roman L2 data products in https://github.com/spacetelescope/jdaviz/pull/1822 used some very simple package data with fake sources to demonstrate that it worked. Those data have been re/moved, and the concept notebook isn't useful without example data.
Since https://github.com/spacetelescope/jdaviz/pull/1822, Roman DMS now maintains "example data" for Roman L2 products on Box. This PR updates the concept notebook with links to the Box data, and updates the notebook to conform with best practices in the latest version of jdaviz.
This checklist is meant to remind the package maintainer(s) who will review this pull request of …

Imviz+Roman updates for latest example Roman data

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue

This pull request clarifies the test for the `reference_wavelength` input in moment-maps that the provided wavelength is the observed, not rest, value.

Clarify moment-map reference_wavelength hint text

---

jdaviz/app.py

This pull request generalizes the logic to determine whether the app is currently linked by WCS to not raise an error if the helper does not have `default_viewer` defined.  This is so that other configs (in this case - downstream lcviz) that use image viewers, but not not have the concept of a default viewer or app-wide WCS linking do not choke.

fallback on linked_by_wcs for configs without default_viewer

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/viewers.py
jdaviz/configs/imviz/helper.py
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/imviz/plugins/parsers.py
jdaviz/configs/imviz/wcs_utils.py
jdaviz/core/template_mixin.py
jdaviz/utils.py

This pull request filters out the wcs-only subset layer (when linked by WCS in imviz) for the subset visibility toggle as well as in the visibility mixed-state logic in the viewer tabs.
**Previously**:
https://github.com/spacetelescope/jdaviz/assets/877591/2462baa9-5a5e-4fd2-b54c-68831a8002be
**After this PR**:
https://github.com/spacetelescope/jdaviz/assets/877591/dbe81e6b-3bc3-40a9-83c3-9866f26b7a68
Note that the first click is still showing mixed state - that is a broader bug than the scope of this effort.  I did some investigation, and `PlotOptionsSyncState` _is_ requesting that both be updated to be hidden and its not clear where that bug is coming from.
should add a …

exclude WCS-only layer subsets from plot options

---

jdaviz/app.py
jdaviz/style_registry.py

In #2580 we fixed support for custom style in combination with ipypopout. However, this uses a global widget, which does not work with solara, since multiple virtual kernels would then share the same widget.
This is using a singleton decorator that makes sure each virtual kernel will create only 1 StyleRegistry widget.

fix: custom styles work in solara server

---

CHANGES.rst
jdaviz/components/viewer_data_select.vue

This pull request avoids JS console messages introduced by #2630 by gracefully existing if `parentElement` is not defined.

avoid errors in JS console from new data menu scrolling logic

---

CHANGES.rst
docs/imviz/displayimages.rst
jdaviz/configs/imviz/plugins/viewers.py
jdaviz/configs/imviz/tests/test_tools.py

This pull request is to remove single-pixel tool from Imviz but it is still available in Cubeviz. Because Cubeviz inherits from the class that Imviz used, I could not remove the class, but should not matter for end-users.

Remove single-pixel tool from Imviz

---

jdaviz/configs/imviz/plugins/orientation/orientation.vue

This pull request fixes a vue syntax error introduced in #2709 which resulted in the overflow of the orientation plugin

fix overflow of orientation plugin

---

jdaviz/configs/mosviz/tests/test_parsers.py
jdaviz/configs/specviz/tests/test_helper.py
jdaviz/configs/specviz2d/tests/test_parsers.py

The direct links for the files in mosviz_test_data got changed, updating them so the tests will stop failing. I also noted which files the links point to.

Fix direct links in remote tests

---

jdaviz/components/plugin_section_header.vue

This pull request fixes dark-mode support for the plugin-section-header when used in the viewer's data menu (currently only used for "Orientation")
Before:
After:

fix dark-mode support for section header when used in data-menu

---

CHANGES.rst
jdaviz/configs/default/plugins/line_lists/line_list_mixin.py
jdaviz/configs/default/plugins/line_lists/line_lists.py
jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py
jdaviz/configs/specviz/plugins/viewers.py

This pull request is to address the following ticket:
https://jira.stsci.edu/browse/JDAT-2780
Where observed wavelengths are showing the correct shifted value but are being plotted at rest wavelengths until there is some interaction with the redshift in which case they immediately update to the correct position.
Pre-PR Behavior:
https://github.com/spacetelescope/jdaviz/assets/42986583/c690234c-85b6-442d-92b4-5c3010132c29
Post-PR Behavior:
https://github.com/spacetelescope/jdaviz/assets/42986583/636e517e-87f6-4576-adcf-b1c0bda1cc59
This checklist is meant to remind the package maintainer(s) who will review this pull …

loading line lists at redshifted wavelength

---

jdaviz/configs/imviz/helper.py
jdaviz/configs/imviz/tests/test_delete_data.py
jdaviz/configs/imviz/tests/test_orientation.py
jdaviz/configs/imviz/tests/test_wcs_utils.py
jdaviz/configs/imviz/wcs_utils.py
pyproject.toml

This pull request is a follow-up of #2179 to increase test coverage and prevent future regressions (within reason).

TST: Increase Imviz rotation test coverage

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py

@camipacifici noticed that the RGB colors at n>5 were reversed compared to at n<=5. This fixes the problem.
Before:
After:

Reverse gist_rainbow colors to match order of manual presets

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py

This pull request is to address problem of extracted spectrum being NaN when cube has NaN.
I cannot find option to do this upstream in `astropy.nddata`. Example code upstream: https://github.com/astropy/astropy/blob/47a8dac8f1dab6ce592be6048f70140adead4e1d/astropy/nddata/mixins/ndarithmetic.py#L633-L634
This is also a problem in v3.8.x but direct backport is probably tough with the recent refactoring. If you really want to backport, please change the milestone and set backport label.

Cubeviz spectral extraction to ignore NaNs by masking them out

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/imviz/tests/test_delete_data.py
jdaviz/configs/imviz/tests/test_orientation.py

Previously, the subset reparenting didn't properly handle the rotation between two different orientations. This fixes it. I'll add test coverage tomorrow.

Fix reparenting subsets between rotation orientations

---

CHANGES.rst
jdaviz/app.py
jdaviz/components/plugin_previews_temp_disabled.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/core/marks.py
jdaviz/core/template_mixin.py

This pull request implements live-previews for spectral extraction in cubeviz.  Since this may become expensive and to mitigate potential lag, this also migrates the functionality to time expensive live-previews and temporarily disable them from lcviz to here as a decorator which is then used in the implementation of live-previews in cubeviz's spectral extraction.
lcviz can then remove its own implementation to make use of this PR in https://github.com/kecnry/lcviz/pull/3
NOTE: this screen recording was done with the timeout lowered to 0.1 seconds to show how the pausing works.  In the PR, this value is set to 0.3 and usually does not trigger for the default cube.  The "entire cube" does not display any preview because of a known bug where nans in the cube are resulting in a spectrum of …

cubeviz spectral extraction live-previews

---

jdaviz/app.vue
jdaviz/components/tooltip.vue

This pull request improves the toolbar viewer creator (currently only available in the default application) to:
* add a tooltip
* generalize the logic for vertical dividers to avoid a divider between the import button and the viewer creator button (but maintain dividers between successive entries)
Before:
After:

Improve viewer creator styling

---

jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/core/template_mixin.py

This pull request "fixes" the viewer select to allow it to become empty if all viewers are removed from the app.  It also hides elements in the plot options plugin that are not applicable if no viewers are selected.
None of the configs in jdaviz currently allow deleting all viewers, so this should not affect users in any way.  

support deleting all viewers without crashing app

---

jdaviz/core/registries.py

This pull request adds support for overwriting existing registry entries, which is particularly useful for downstream apps that want to modify something already in the registry without having to give it a new name.

allow overwriting existing registry entries

---

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue

Change moment input field text to 'rest wavelength'

---

jdaviz/configs/imviz/plugins/tools.py
jdaviz/configs/imviz/plugins/viewers.py
jdaviz/configs/imviz/tests/test_tools.py

Fixes https://github.com/spacetelescope/jdaviz/issues/2749

BUG: Fix click to center on multiple visible layers when linked by WCS

---

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue

My last PR (#2748 ) was not actually what was wanted, due to my misreading the Jira ticket and conflicting asks. "Observed" is what is wanted now.

Fix moment reference wavelength text again

---

docs/cubeviz/plugins.rst
docs/dev/ui_style_guide.rst
jdaviz/components/tray_plugin.vue
jdaviz/configs/default/plugins/plot_options/plot_options.vue

This pull request is to address inconsistent capitalization across UI elements.

Fix inconsistent capitalization across UI elements

---

CHANGES.rst
docs/imviz/plugins.rst
jdaviz/app.py
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/export/export.vue
jdaviz/configs/default/plugins/markers/tests/test_markers_plugin.py
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/core/events.py
jdaviz/core/helpers.py
jdaviz/core/template_mixin.py
jdaviz/core/user_api.py

This pull request adds support for exporting plugin tables via the new export plugin.
**Up for discussion**:
- how should these tables be labeled?  Here I have `{plugin_name}:{table_name}` where `table_name` defaults to `table`.  This adds flexibility for multiple tables per-plugin, but does NOT support multiple plugin instances of the same plugin (i.e. creating an independent instance of model fitting after app initialization will not be registered here).  We probably will want to follow the same convention for plugin plots, in that case we _know_ that we have multiple plugin plots in at least the line profile plugin in Imviz.
- are we ready to expose `helper.plugin_tables` or should we keep that private for now?
- do we want a follow-up effort for consistent handling of checking and …

Export plugin: table support

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/imviz/tests/test_orientation.py

This fixes a few bugs with adding, changing and deleting orientations when multiple viewers exist. I don't believe there was an issue open for these to close.
Fixes:
- An if statement that was checking against a callback dict instead of an entry in the dict
- Selecting a new orientation in the viewer data menu will now only change the selection in the Orientation plugin if the correct viewer is selected in the plugin.
- Deleting an orientation in a viewer data menu will not result in Default Orientation being selected in any viewers where the deleted orientation was currently selected.

Debug orientation operations with multiple viewers

---

jdaviz/configs/specviz/tests/test_viewers.py

This pull request is to add a test plaguing https://github.com/spacetelescope/lcviz/pull/93 but for specviz.

Add test similar to lcviz

---

jdaviz/app.py
jdaviz/configs/imviz/plugins/parsers.py
jdaviz/configs/imviz/plugins/viewers.py
jdaviz/core/template_mixin.py
jdaviz/tests/test_app.py

This PR adds a dictionary `_data_associations` to the `Application` class, and methods for finding associations between glue Data entries in the `DataCollection`. 
Suppose you have two layers A and B which are associated with one another, e.g., layer B is the DQ array for the science data in layer A. You could load these layers and specify their association like so:
```python
imviz_helper = Imviz()
shape = (10, 10)
data_parent = np.ones(shape, dtype=float)
data_child = np.zeros(shape, dtype=int)
imviz_helper.load_data(data_parent, data_label='A')
imviz_helper.load_data(data_child, data_label='B', parent='A')
```
which gets represented as a dictionary:
```python
>>> imviz_helper.app._data_associations
{
"A": {
"parent": None,
"children": [
"B"
]
},
"B": {
"parent": "A",
"children": []
}
} …
```

Implement associations between Data layers

---

jdaviz/components/plugin_action_button.vue
jdaviz/main_styles.vue

This pull request is to improve the color contrast of plugin action buttons in dark mode.
Before: 
After:

Improve plugin action button contrast in dark mode

---

docs/dev/ui_style_guide.rst
jdaviz/app.py
jdaviz/app.vue
jdaviz/components/tray_plugin.vue
jdaviz/configs/cubeviz/plugins/slice/slice.vue
jdaviz/core/helpers.py
jdaviz/core/template_mixin.py

This pull request implements infrastructure for plugins to determine when they are relevant/irrelevant based on the state of the application as a whole (data, viewers, units, etc).  When a plugin determines itself to be irrelevant, then:
* the plugin itself will _not_ appear in the tray, or will be removed if it already existed
* the plugin user API will no longer be listed in `viz.plugins`
* any existing UI instances (non-tray) of the plugin are replaced with the specified message (in the same way as the disabled message)
* TBD: any existing user API instances currently will continue to function.  Should these instead raise an error or have the message in the repr?
* the plugin will be considered not "active" meaning any live preview and auto-updating logic should be paused, even if UI …

Context-aware plugin relevancy

---

CHANGES.rst
jdaviz/configs/imviz/plugins/tools.py
jdaviz/core/tools.py

This pull request enables the option in the matched zoom within Imviz to disable matched zoom tools in other viewers to avoid unintended recursion.  This is consistent with the handling in specviz2d for a similar issue there.  We could instead implement some tolerance to break out of the recursion, but I fear that won't be robust and might not behave consistently.
~Perhaps #2751 would avoid the need for this, since this was not necessary before the new image rotation work broke roundtripping of the zoom limits.~
Note that this was not an issue in 3.8.x, so is not milestoned for backporting.
This checklist is meant to remind the package …

Prevent recursive matched zoom in Imviz

---

jdaviz/configs/default/plugins/data_quality/__init__.py
jdaviz/configs/default/plugins/data_quality/dq_utils.py
jdaviz/configs/default/plugins/data_quality/tests/test_data_quality.py
jdaviz/data/data_quality/jwst.csv
jdaviz/data/data_quality/roman.csv

This PR adds data quality flag definitions for JWST and Roman. This PR is independent from #2761, and can be merged before or after.
The flag definitions are written in `stdatamodels` ([see here](https://github.com/spacetelescope/stdatamodels/blob/41d4a43c1bec37d097a25866c1a76d93460ee306/src/stdatamodels/jwst/datamodels/dqflags.py#L26)) and `roman_datamodels` ([see here](https://github.com/spacetelescope/roman_datamodels/blob/62d7c96ea993bb354acf4b05e7e265ba0c7d32fa/src/roman_datamodels/dqflags.py#L27)) respectively. 
We could use the flag maps stored in these dependencies directly, since jdaviz already depends on `stdatamodels`, and `roman_datamodels` is an optional dependency. In this PR, I've chosen to save the definition tables as jdaviz package data in static CSV files. This ensures …

Adding default DQ flag mappings and IO methods

---

jdaviz/app.py
jdaviz/configs/default/plugins/markers/tests/test_markers_plugin.py
jdaviz/configs/imviz/helper.py
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/imviz/tests/test_linking.py
jdaviz/configs/imviz/tests/test_orientation.py
jdaviz/configs/imviz/tests/test_wcs_utils.py

I corrected the test first. Will push commit(s) out later when I can figure out how to fix it properly.
Fixes #2724

Fix reference data for WCS to Pixels to WCS

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py

This pull request is to address storing the scale factor in metadata so that data can be "translated" between surface brightness and flux units. In addition, to add internal API functionality to translate from MJy/sr <-> Jy/pix.
https://github.com/spacetelescope/jdaviz/assets/42986583/5c663962-6397-416c-8d98-1df6a1e638b0

add pixel scale factor to metadata and API translation

---

CHANGES.rst
docs/cubeviz/plugins.rst
docs/imviz/plugins.rst
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/export/export.vue
jdaviz/configs/default/plugins/export/tests/test_export.py

* #2755 
This PR adds the ability to export non-composite spatial subsets through the export plugin.
(JDAT 4239)
(I branched off of https://github.com/spacetelescope/jdaviz/pull/2755, which should be merged first.)

Add ability to export subsets

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.vue

This pull request removes and unused/closed div, and fixes indentation inadvertently introduce in #2760.

Fix broken div in export plugin

---

CHANGES.rst
docs/dev/ui_style_guide.rst
jdaviz/components/tray_plugin.vue
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue
jdaviz/configs/cubeviz/plugins/slice/slice.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/default/plugins/collapse/collapse.vue
jdaviz/configs/default/plugins/export/export.vue
jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue
jdaviz/configs/default/plugins/line_lists/line_lists.vue
jdaviz/configs/default/plugins/markers/markers.vue
jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.vue
jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
jdaviz/configs/imviz/plugins/catalogs/catalogs.vue
jdaviz/configs/imviz/plugins/compass/compass.vue
jdaviz/configs/imviz/plugins/footprints/footprints.vue
jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.vue
jdaviz/configs/imviz/plugins/orientation/orientation.vue
jdaviz/configs/imviz/plugins/rotate_canvas/rotate_canvas.vue
jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.vue
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/core/template_mixin.py
jdaviz/core/tools.py

This pull request implements `plugin.open_in_tray(scroll_to=False/True)` functionality as well as using this within the plugin shortcut buttons in the viewer toolbar.
Up for discussion:
* should this default to True or False (for the API)?
https://github.com/spacetelescope/jdaviz/assets/877591/3dcf67a9-b99a-4b31-b465-273e9142c23e

plugins: scroll-to functionality

---

jdaviz/app.py
jdaviz/components/viewer_data_select.vue

This pull request opens the data menu by default for a new, blank, viewer.
https://github.com/spacetelescope/jdaviz/assets/877591/0c014474-fe06-4632-ac2a-dd456f082a7c

Open data menu on new blank viewer

---

jdaviz/components/viewer_data_select.vue

This pull request extends on #2742 but avoids opening the data menu in cases where data is not yet loaded into the app.

do not open data menu on new data if no data in app

---

jdaviz/configs/default/plugins/export/export.vue

To be more in line with how radio buttons work, if a selection is made in one of the section export plugin sections, it can't be deselected. The only way to deselect is to select something in another section of the plugin. This fixes https://jira.stsci.edu/browse/JDAT-4381.

enforce selection made for radio buttons in export plugin

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/export/export.vue

Adding a disabled message for this case until we can fix it.

Disable cubeviz spectrum-viewer PNG export for now

---

jdaviz/configs/default/plugins/export/export.py

Adds a case to catch this in `export` as well. Follow up from #2777 .

Also disable bad viewer+format combo from API

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py

This consolidates the filename logic for exporting to fix the standalone case for all export types, not just movies. I wasn't sure whether to put the changelog in with the other Export stuff or in Bug Fixes, since I think the standalone issue was present in 3.8.

Consolidate filename normalization for exports

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/export/tests/test_export.py

This pull request disables writing data products to FITS files due to unsupported DN/s units in Astroquery's internal.

Disable export for unsupported units

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py

This pull request fixes #2792.
Note that before this:
* export should still work, just will be using ecsv by default
* changing the format would still work from the API, this bug is isolated to the dropdown UI element itself.

fix typo in vue file affecting plugin table format

---

CHANGES.rst
jdaviz/configs/imviz/plugins/footprints/footprints.py

This pull request is to address Footprints not appearing when created via the API. When Footprints were added, the overlay dictionary did not contain the default footprint, and _mark_visible was unable to plot the default and any subsequent Footprints created via API. By adding a check to make sure that the default is within the _overlay dictionary, all Footprints are plotted.
https://github.com/spacetelescope/jdaviz/assets/42986583/46a1f546-b2ef-4b27-b3a9-d4ff5f74feb9

ensure footprints overlay when created by API

---

notebooks/MosvizNIRISSExample.ipynb

Update link to dataset in Mosviz NIRISS example notebook

---

CHANGES.rst
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/imviz/tests/test_orientation.py
jdaviz/core/freezable_state.py

This improves the orientation code to catch the error and raise a snackbar warning if an orientation is added before loading data into the viewer, and stops the backend from trying to set bounds to `inf` if an orientation is selected in the data menu before data is loaded.

Fix Orientation selection/creation with no loaded data

---

CHANGES.rst
jdaviz/cli.py

This feature closes jdaviz (voila) when a kernel closes, which should happen when a browser page/tab is closed.
Voila itself does not have this feature, although jupyter-server has something along these lines, but only polls every 60 seconds:
https://github.com/jupyter-server/jupyter_server/blob/de6d9047fa414859856198b7b2dfe80e60edd010/jupyter_server/serverapp.py#L2547
This change makes it immediate, but requires monkey patching. This API has been stable from the start of Voila when we wrote it, so I am not too worried that is will break, and I also believe Voila is pinned.

feat: stop jdaviz/voila when the browser window closes

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/cubeviz.yaml
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/configs/cubeviz/plugins/slice/slice.py
jdaviz/configs/cubeviz/plugins/slice/tests/test_slice.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/viewers.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue
jdaviz/core/helpers.py
jdaviz/core/marks.py
jdaviz/core/template_mixin.py

This pull request enables unit conversion in cubeviz only for spectral conversions. The following plugins also need to be updated to account for possible spectral axis unit changes:
Potential follow-up efforts:
- Enable spectral unit conversion in cubeviz and update plugins [2758]

Enable spectral conversion in cubeviz

---

CHANGES.rst
jdaviz/configs/imviz/tests/test_linking.py
jdaviz/core/freezable_state.py

This pull request is to hopefully address the problem of Ricky (and others) sometimes seeing a WCS orientation getting flipped.

BUG: Fix random flip in WCS orientation

---

CHANGES.rst
jdaviz/configs/imviz/tests/test_linking.py
jdaviz/core/freezable_state.py

This pull request is to manually backport #2802 because auto backport failed because #2789 was not backported.

Backport PR 2802 to v3.9.x (BUG: Fix random flip in WCS orientation)

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py

This pull request allows moment map to work with spectral axis units in frequency.
Fixes #2801 

Fix moment map when spectral units are in frequency

---

CHANGES.rst
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/tests/test_footprints.py

This PR is to address when footprints are added via API prior to linking by WCS. Only the last footprint added was visible in the viewer once linked, even when all footprints are set to be visible. 
https://github.com/spacetelescope/jdaviz/assets/42986583/6160d9a8-16d7-46da-9012-67b976c2ce30

ensure footprints display when added before linking

---

CHANGES.rst
jdaviz/app.py
pyproject.toml

This pull request implements a temporary workaround for glue >= 1.19.  This is a revival and slight modification of #2812.
Fixes #2811

fix support for glue 1.19

---

CHANGES.rst
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue

Previously, the line menu under `Redshift from Centroid` showed the name and originally defined value for the lines, which could have been in different units. Now it shows name + rest value in current units + unit.
Before: 
Now:

Better menu selection labels for spectral lines in line analysis plugin

---

CHANGES.rst
jdaviz/configs/cubeviz/helper.py
jdaviz/configs/cubeviz/plugins/viewers.py
jdaviz/configs/default/plugins/viewers.py
jdaviz/configs/imviz/helper.py

This pull request considers bitmap and contour_visible switches (instead of only the global layer visibility switch from the data menu) in determining the top image layer (used for mouseover).  We could also extend this to consider opacity here or in the future.
https://github.com/spacetelescope/jdaviz/assets/877591/33b8a8e6-2093-4373-9976-22fd0b143ead
This PR also consolidates some repeated logic between cubeviz and imviz (where the only exception before was allowing for cube data in the cubeviz case which should be able to safely be moved to the more general case).
This checklist is meant to remind the package maintainer(s) who will review …

consider bitmap/contour_visible in logic for top image layer

---

jdaviz/app.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py

This pull request fixes internal references to plugin names which changed to be the human-friendly name in #2680 (not yet released), but missed updating a few cases, resulting in moment maps not being linked correctly.

fix reference to plugins in metadata

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/export/tests/test_export.py

This pull request re-enables support for exporting the cubeviz spectrum viewer (to png or svg) by temporarily "cleaning" any unicode from the marks (which currently exist for the slice indicator).
The cleaning/restoring part of this PR could be reverted if support for unicode is fixed upstream (likely in bqplot).

Re-enable exporting cubeviz spectrum viewer

---

CHANGES.rst
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue

#2816 was merged with a small bug where the Redshift from Centroid section would misbehave if no lines were loaded. Now that section is properly hidden if there are no lines. Thanks @kecnry for finding this.

Fix Line Analysis behavior before any lines are loaded

---

CHANGES.rst
jdaviz/components/plugin_add_results.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/core/template_mixin.py

This pull request removes user-access to auto-updating plugin results for the 3.10 release (will be used internally for #2827 and may or may not be exposed to the user in the future).

disable user-access to auto-updating results

---

CHANGES.rst
docs/cubeviz/plugins.rst
docs/imviz/plugins.rst
jdaviz/app.py
jdaviz/components/tooltip.vue
jdaviz/components/viewer_data_select.vue
jdaviz/components/viewer_data_select_item.vue
jdaviz/configs/cubeviz/cubeviz.yaml
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/default/plugins/data_quality/data_quality.py
jdaviz/configs/default/plugins/data_quality/data_quality.vue
jdaviz/configs/default/plugins/viewers.py
jdaviz/configs/imviz/imviz.yaml
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/core/template_mixin.py

This PR follows #2767 to extend the DQ plugin for Cubeviz.
https://github.com/spacetelescope/jdaviz/assets/3497584/31e95fb0-0529-4947-b66b-fa74141ef3a4
The plugin has only one difference from Imviz – it assumes that the `flux-viewer` is the only viewer that will contain the DQ layer. Since the DQ layer will have the same dimensions as the cube, I wanted to make sure no one ever tries to use the cube DQ in the spectrum viewer, for example.
The data dropdown menu offers the DQ layer as a child of the (single) cube loaded into `flux-viewer`.  …

DQ support for Cubeviz

---

CHANGES.rst
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/mosviz/plugins/parsers.py
jdaviz/configs/specviz2d/tests/test_parsers.py
jdaviz/conftest.py

This pull request is to address user finding the app crashing when providing `ext` for Specviz2d loader.

BUG: Fix specviz2d loader with ext keyword

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/parsers.py

I noticed that these extension names were not recognized properly while investigating something else using Cami's private data cube. Might as well add them in?

Cubeviz should recognize ERROR and DATA_QUALITY extension names

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue

This PR updates the language within spectral extraction in cubeviz to be self-consistent for the aperture validity messages shown in the UI.

cubeviz spectral extraction: consistent language for aperture/bg validity messages

---

jdaviz/configs/cubeviz/plugins/parsers.py

Noticed these while investigating something else. Technically a bug but it is buried so deeply in the internals I don't think users would notice, so probably don't need a change log.

Fix logic flow in _parse_hdulist for Cubeviz

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/core/template_mixin.py

This PR introduces spectral extraction to cubeviz for composite subsets. The implementation converts the composite subset to a boolean mask, and applies it in the NDData collapse. The only supported aperture extraction method is "center," since this approach completely avoids the photutils pixel weighting methods.
https://github.com/spacetelescope/jdaviz/assets/3497584/62c4da05-8df8-4d7c-91d7-9521f189594b
I've added a test that extracts two spectra from individual non-composite subsets, and compares their sum with the spectrum of a composite subset that spans the same area as both subsets combined. …

Spectral extraction in Cubeviz with composite subsets

---

jdaviz/core/tests/test_autoconfig.py

This pull request is to mark `test_autoconfig` as slow because it is very slow as it loops through multiple remote datasets and then try to guess, quite a pain when running the whole test suite locally with remote data. I hereby propose to also mark it as slow, so only `--run-slow` would also run it.
https://github.com/spacetelescope/jdaviz/blob/a3b29d3b87bb19662ca12c251ddd3cf6fdb94d9e/.github/workflows/ci_workflows.yml#L72

TST: Mark test_autoconfig as slow

---

jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py

Remove `flux_unit` from the unit conversion user API since we're likely to rename it.

Hide flux_unit from unit conversion

---

.github/workflows/standalone.yml

See https://github.com/actions/upload-artifact/issues/485, it seems for now the answer is to use upload-artifact version 3. The scipy dylib deletions are attempts to get the mac build working.

Downgrade upload-artifact to version 3, delete scipy dylib files

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue
jdaviz/configs/specviz/plugins/viewers.py
jdaviz/configs/specviz/tests/test_viewers.py
jdaviz/core/validunits.py
jdaviz/tests/test_app.py

This pull request is to address adding a UI toggle for translating between surface brightness and flux within the unexposed Unit Conversion Plugin. 
Main Notes:
PR (buggy) behavior:
https://github.com/spacetelescope/jdaviz/assets/42986583/fe8c0150-e12f-42e9-9b4a-a1224a94bf66

toggle flux <-> surface brightness units

---

.github/workflows/standalone.yml

Previously was pinned on 5.13, I'm curious to see if the symlink issue is a 6.x problem.

Try pinning pyinstaller<6

---

CHANGES.rst
jdaviz/configs/default/plugins/data_quality/data_quality.py
jdaviz/configs/default/plugins/data_quality/tests/test_data_quality.py

This PR prevents the DQ plugin from applying array compositing logic on spatial subsets that should be specific to image layers. I added a regression test that causes an AttributeError on main (thanks to @javerbukh for reporting!).

Prevent composite array calls on subsets

---

CHANGES.rst
jdaviz/components/plugin_table.vue
jdaviz/core/template_mixin.py

Hello Jdaviz Team!
This PR is a small change to the Plugin Table component to expose the Vuetify row selection attributes for the Virtual Observatory plugin I'm working on. Because this is a frontend component, no new tests were added. A changelog entry will follow the publication of this PR, once a PR number is assigned.
It was great to sync my fork again :)

Enable Row Selection on Plugin Table Component

---

CHANGES.rst
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py

This pull request is an alternative to #2861 to address repeated calls to update spectral extraction previews (especially for "expensive" trace calls) in specviz2d.

Prevent repeatedly updating previews in specviz2d spectral extraction

---

CHANGES.rst
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py

This pull request is to manually backport https://github.com/spacetelescope/jdaviz/pull/2862 onto v3.10.x
The diff don't match exactly. I think @kecnry should review.

Backport PR 2862 onto v3.10.x (Prevent repeatedly updating previews in specviz2d spectral extraction)

---

.github/workflows/ci_workflows.yml

This won't be used in PRs from forks but is needed to upload coverage from `main`.

Use codecov token to upload coverage

---

jdaviz/configs/imviz/tests/test_wcs_utils.py
jdaviz/configs/imviz/wcs_utils.py

While debugging an issue with GWCS coordinates with @bmorris3, I found that one issue is that if an image with a bounding box is used, and if we were to not reset the bounding box to ``None`` as we do currently in jadviz, the compass properties will fail in some cases - this is because before this PR, the pixel scale along the N and E directions was determined by adding 1 deg to the RA and Dec, but this is too large as this may then fall outside the image and return NaN (with https://github.com/spacetelescope/gwcs/pull/497).
In any case, I think it makes sense to use small angular offsets when trying to do this calculation regardless of whether we decide to not disable the bounding box etc. I don't think there is any downside to using small offsets, and it will be more future-proof.
list …

Use small angular offsets when determining compass properties

---

CHANGES.rst
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue

This pull request disables the "update" button when no subset selected.
https://github.com/spacetelescope/jdaviz/assets/877591/95bd46d2-97c7-4c27-987a-9143ec0dcd79

subset plugin: disable update button when no subset selected

---

jdaviz/components/toolbar_nested.vue

This pull request adds support for clicking on the carrot to open the viewer toolbar's submenu, along with edits to the tooltip and a hover animation to help aid whether the button or the carrot is being clicked.
https://github.com/spacetelescope/jdaviz/assets/877591/67c8aba9-1de6-4679-81b8-355c259233fb

viewer toolbar: allow clicking carrot to show submenu

---

jdaviz/core/tools.py

I was overthinking this, ended up being simple. I confirmed with @Jenneh that we should go ahead and also apply this to the zoom preview fill (which this does). I'm debating whether this needs a changelog, tagged it as not for now.

Override fill color for bqplot selector tools

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/core/marks.py
jdaviz/core/template_mixin.py
jdaviz/tests/test_app.py

This pull request implements support for background subtraction in cubeviz's spectral extraction.
Since this has now gone far beyond "collapsing", this PR also takes this and the 4.0 major version bump as an excuse to rename `collapse_to_spectrum(...)` to `extract(...)` and then also adds a new `extract_bg_spectrum(...)` (using the same name as in specviz2d in case we ever do want to support extracting the background as well... we could consider just naming this to `extract_background(...)` if we don't want to account for that possibility down the road).
https://github.com/spacetelescope/jdaviz/assets/877591/cdc5eebe-2405-4dda-9aab-df3e659334d0
**TODO**:
should add a …

Background subtraction in spectral extraction (cubeviz)

---

CHANGES.rst
jdaviz/app.py

This pull request sets the plugin tray to be open by default when the application is shown.

Plugin tray open on show

---

CHANGES.rst
docs/reference/api_plugins.rst
jdaviz/configs/cubeviz/cubeviz.yaml
jdaviz/configs/default/default.yaml
jdaviz/configs/default/plugins/__init__.py
jdaviz/configs/default/plugins/about/__init__.py
jdaviz/configs/default/plugins/about/about.py
jdaviz/configs/default/plugins/about/about.vue
jdaviz/configs/default/plugins/about/tests/test_about_plugin.py
jdaviz/configs/imviz/imviz.yaml
jdaviz/configs/mosviz/mosviz.yaml
jdaviz/configs/specviz/specviz.yaml
jdaviz/configs/specviz2d/specviz2d.yaml
pyproject.toml

This pull request is to add a new plugin to let user know which Jdaviz version, etc.
<table>
<tr>
<td valign="top">
</td>
<td>
</td>
</tr>
</table>

About plugin

---

CHANGES.rst
docs/imviz/displayimages.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py
jdaviz/core/template_mixin.py
notebooks/concepts/cubeviz_ndarray_gif.ipynb
notebooks/concepts/imviz_colorbar_mpl.ipynb
notebooks/concepts/imviz_dithered_gwcs.ipynb

This pull request renames the "Monochromatic" color mode option to "Color" and adds descriptions within the dropdown.  Setting `color_mode = 'monochromatic'` from the plot options plugin API is still supported with a deprecation message.
https://github.com/spacetelescope/jdaviz/assets/877591/0210160e-fc7b-42b8-aca1-da5f8b1eb57e

Rename monochromatic color mode and add descriptions

---

jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.vue

This pull request removes vertical spacing between key-value pairs and comments to tighten the layout and improve grouping visibility.
Before: 
After:

Tighten metadata layout and improve grouping

---

jdaviz/app.py
jdaviz/tests/test_app.py

While looking at issues with limits not updating when changing to certain units, I spotted an unrelated issue. In ``to_unit``, the units on the original data should be irrelevant, and if glue asks for a conversion from e.g. Jy to MJy, we should ignore the original units on the data, since they might already have been previously converted to Jy which is why glue is asking for Jy to MJy. So looking at spec.unit.bases is not the right thing to do. A lot of the change here is indentation so be sure to check the diff ignoring whitespace.
I've expanded the test for to_unit.
There are other issues with the ``to_unit`` code as written currently, but I thought I'd break it up into conceptual chunks.
list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, …

Fix unit conversion from flux to surface brightness

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/tests/test_app.py

This pull request updates the scale-factor used for converting a spectrum between surface-brightness and flux units to use the wavelength-dependent aperture area (array) instead of the cone's scale factor at the current slice (float).
This should be rebased on top of main after #2859 is merged.  See https://github.com/spacetelescope/jdaviz/pull/2859#discussion_r1594009067 for more details.

fix SB/flux scale factor

---

jdaviz/app.py
jdaviz/tests/test_app.py

I have expanded the test suite for ``to_unit`` and found that an error occurred when converting limits from Fnu to Flam. The issue in this specific case was that ``if '_pixel_scale_factor' in spec.meta:`` was  ``True`` so the clause relating to ``len(values)==2`` was never invoked, resulting in an issue with incompatible dimensions.
In addition to fixing this logic, I have made it so that we just use one wavelength/frequency in this case for the conversion, as it doesn't specifically make sense to use the first and last spectral axis value. When converting limits we are probably interested in the values being right at the start of the spectral axis.
This builds on top of https://github.com/spacetelescope/jdaviz/pull/2888 and should be rebased once …

Fix unit conversion of limits from Fnu to Flam

---

pyproject.toml

We need to pin Matplotlib to a more recent version that works, since ESA Datalabs builds a docker image that has an older incompatible version by default.
3.9 is newer and we could pin that, but I locally had 3.8.4 and know it works.

Pin min version of matplotlib

---

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/tests/test_simple_aper_phot.py
jdaviz/core/tests/test_tools.py
jdaviz/tests/test_utils.py

Compatibility patch with the following upstream changes:
* https://github.com/astropy/photutils/pull/1760 (affects our tests only)
* https://github.com/astropy/specutils/pull/1141 (affects Cubeviz)

Fix devdeps

---

pyproject.toml

Keeps our supported versions in lines with https://scientific-python.org/specs/spec-0000/ rather than the semi-random version I originally pinned (thanks @pllim ).

Change matplotlib min version to 3.6

---

pyproject.toml

Backport PR #2911 on branch v3.10.x (Change matplotlib min version to 3.6)"

---

share/jupyter/nbconvert/templates/jdaviz-default/index.html.j2

This pull request is to add browser title "jdaviz" to standalone. Previously, it would launch with a default localhost:... .
Before:
After:

Add browser title jdaviz

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/core/helpers.py
jdaviz/core/template_mixin.py
jdaviz/tests/test_app.py

This pull request is to address a bug that exists on `main` but was made more apparent by #2873 . Currently there is just a couple lines in the unit conversion test that triggers this in CI, but the traceback can also be seen by running the following lines in the cubeviz example notebook after data has been loaded:
```
uc = cubeviz.plugins['Unit Conversion']._obj
la = cubeviz.plugins['Line Analysis']
la.open_in_tray()
uc.show_translator = True
uc.flux_or_sb.selected = 'Flux'
```
and in a new cell after the Line Analysis plugin has opened and the continuum is visible:
`la.get_results()`
This checklist is meant to remind the package …

Add test that triggers handle_display_units bug

---

CHANGES.rst
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/tests/test_footprints.py

When the Orientation plugin changes reference data to rotate a viewer, the footprint method that's currently used to update each of the footprints' properties tries to act on the selected overlay only, not all overlays. 
This PR makes a separate method that gets triggered by changes in reference data, and explicitly calls the relevant method (`_change_overlay`) on each overlay.

Update footprint orientations on viewer rotation

---

.github/workflows/ci_workflows.yml
CHANGES.rst
jdaviz/utils.py

This pull request is to address a problem when loading data from a windows computer. The `os.path.sep` is different on a windows and linux computer, which does not work for our example notebooks.

Fix uri on pc

---

.github/workflows/publish.yml
pyproject.toml
tox.ini

This pull request is to address failing CI tests which relate to https://github.com/pypa/twine/issues/977#issuecomment-2189807324

Pin importlib_metadata to version 7.2.1

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/specviz/plugins/line_analysis/tests/test_lineflux.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/conftest.py
jdaviz/core/helpers.py
jdaviz/tests/test_app.py
jdaviz/utils.py

This pull request sets the extracted spectrum to the correct units when using the sum function with flux units in per steradian.
- Set correct sum units when flux units are in per steradian.

Correct sum units for per steradian

---

jdaviz/utils.py

This pull request is to fix data loading in "standalone app". Turns out to be a trivial fix. `os.environ` always returns a string but `/` operator is used but that only works for `Path` object.
Introduced in https://github.com/spacetelescope/jdaviz/pull/2875 that is unreleased, so no need for change log. Not sure how to add a meaningful test either.
Also moved the check farther down because this operation is pointless for no-op.

BUG: os.environ does not return Path object

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/export/export.vue
jdaviz/configs/default/plugins/export/tests/test_export.py

This pull request is to address displaying the default file path in the Export plugin UI. The default path shall update if the user inputs a relative or absolute path into the filename input field in the UI.
It also re-enables exporting for them the API. If a user provides a path via in the API, the file shall be exported there. 
In the UI, the default filepath will be used (cwd), or, if a user provides a path, it will export to that location instead of exporting only to the users Downloads directory. 
Follow up tickets are needed to address:
This checklist is meant to remind the package maintainer(s) who will review this pull request of …

Show path to file

---

.github/workflows/ci_workflows.yml
jdaviz/tests/test_utils.py
jdaviz/utils.py

I couldn't easily do this without adding a new `dryrun` option to `download_uri_to_path`.
This follows up on #2875 and #2923 to avoid failure seen in #2924 but without using `--remote-data` on the entire Windows job to avoid unnecessary server hits.
Since this is to patch unreleased code, no need for change log.

TST: Test Windows path handling without remote data

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py

There was a line pertaining to `Path` filenames, but `_normalize_filename` now turns everything into a string. Exporting movies works for me now.
Not sure what we're milestoning things at at this point...

Fix Cubeviz movie export

---

pyproject.toml
standalone/jdaviz-cli-entrypoint.py

Unclear what the real underlying issue is. Code comments give a possible explanation.
Fixes https://github.com/spacetelescope/jdaviz/issues/2921

fix: make standalone work with matplotlib >= 3.9.0

---

.github/workflows/standalone.yml

This pull request is to make sure standalone build fires off properly when label is applied in PR.

Fix standalone build events for PR

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/core/template_mixin.py

This pull request fixes the case of exporting the stretch histogram from the export plugin before the plot options plugin has ever been opened.  It does so by implementing an optional callback on the `Plot` object itself to call a plugin method to update itself, which will be called if the "parent" plugin is not considered active.  In cases where no widget exists because the parent plugin has never been opened, it also renders the widget offscreen in the export plugin.
I'm not really sure the best way to test this since the previous behavior didn't result in errors, just a blank image - but open to any suggestions!
This checklist is meant to …

support exporting a plot from an unopened/inactive plugin

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/core/template_mixin.py

See #2934.  Only conflict was in changelog.

Manual backport of #2934

---

docs/conf.py

The HTML docs on RTD like [this page](https://jdaviz.readthedocs.io/en/stable/sample_notebooks.html) point to directories on github like https://github.com/spacetelescope/jdaviz/tree/main/notebooks. We've changed the default RTD page to `stable`, which isn't the same as `main`, so the notebooks linked on RTD will be out of sync with the rest of the HTML docs whenever `main != stable`.
This PR gets the git commit hash at the time the docs are built, and injects that hash into the github URLs for docs links.
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This …

Sync notebook github links in HTML docs to the git commit used to build them

---

jdaviz/configs/specviz/helper.py

This is a direct follow-up of https://github.com/spacetelescope/jdaviz/pull/2875 . Since it is not released, no need for change log.
To see for yourself, run the Specviz example notebook but provide a local path.
```python
local_path = "somewhere/not/here"
specviz.load_data("mast:JWST/product/jw02732-o004_t004_miri_ch1-shortmediumlong_x1d.fits", data_label="myfile", local_path=local_path, cache=True)
```
Without this patch, it downloads to the `notebooks` source checkout no matter what is given.
[🐱](https://jira.stsci.edu/browse/JDAT-4647)

BUG: Specviz to respect local_path when provided

---

CHANGES.rst
jdaviz/core/tools.py

This pull request prevents the previous zoom tool from updating the image zoom 4 times.

delay callback when calling previous zoom

---

CHANGES.rst
jdaviz/utils.py

If you create a subset in Imviz while WCS-linked, the subset appears in the Orientation plugin's "orientation in viewer" dropdown. It does not appear in the data dropdown. This is an artifact of the way that WCS-only layers are filtered in `LayerSelect`. I've tweaked the filter to be sure to exclude subsets.

Exclude subsets from WCS-only layer filter

---

jdaviz/app.py
jdaviz/core/template_mixin.py

This pull request cleans up some logic in generating docs links from plugins and now includes the version tag for the help button in the top app bar for the default app (does not change anything when a config exists).
Found these while investigating the solution for https://github.com/spacetelescope/lcviz/pull/128, but is not required for the downstream implementation.

docs link cleanup

---

CHANGES.rst
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/tests/test_footprints.py

In prepping #3102, I realized #2918 needed a manual backport too.

Backport PR #2918: Update footprint orientations on viewer rotation

---

CHANGES.rst
jdaviz/utils.py

Backport PR #3097: Exclude subsets from WCS-only layer filter

---

docs/installation.rst
docs/sample_notebooks.rst
jdaviz/configs/imviz/tests/test_parser_roman.py
jdaviz/core/astrowidgets_api.py

In #2767 I corrected the ASDF extensions loaded by default in the Imviz parser. The optional Imviz parser tests for Roman data products hadn't been updated to match. I fixed them in this PR.
This PR needs the `Extra CI` label to run the Roman tests. That means the link check also gets run on this PR, so I've also discovered and fixed some broken links in this same PR.

Fix for Imviz parser romandeps test after update to defaults

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py

[This PR has a significant update below](https://github.com/spacetelescope/jdaviz/pull/3088#issuecomment-2243114249). I'm keeping the original description here for traceability.
Fixes #3086
In (somewhat) recent changes, the default y-axis on the spectrum-viewer in Cubeviz is MJy and the spectral extraction plugin is used directly to produce the default spectrum in the spectrum viewer. If a user makes a spatial subset in Cubeviz that appears to cover every data spaxel, one might expect the live-extracted spectrum to match the default spectral extraction, but it doesn't, see #3086.
This appears to come from the calculation of the pixel area in steradians to convert the flux unit from MJy/sr to MJy. The spectral extraction plugin currently counts every element in the spectral cube towards …

Bugfix for flux unit conversion in spectral cubes

---

.github/workflows/ci_workflows.yml
CHANGES.rst
docs/imviz/plugins.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/tests/test_catalogs.py

Probably an oversight to only run slow tests on devdeps. I bet it would also fail on stable astropy but let's see. Yes, it did. I bet the code never worked in the first place. It was trying to append rows with incompatible data types.
[🐱](https://jira.stsci.edu/browse/JDAT-4677)

TST: Also run slow test in non-dev env, fix Catalog Search bug

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/tests/test_app.py

This PR makes the plotted model fit results update properly when toggling between flux and surface brightness. It also removes one use of `aperture_area_along_spectral` that was missed in #3088 that was leading to the converted model fit being incorrect.

Update model fit result units after toggling flux/surface brightness

---

CHANGES.rst
jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py
jdaviz/configs/imviz/tests/test_line_profile_xy.py
jdaviz/core/helpers.py
notebooks/concepts/imviz_line_profiles.ipynb

This pull request renames "Imviz Line Profiles (XY)" to ~"Line Profiles (XY)"~ "Image Profiles (XY)" along with deprecation for API access (although the plugin API itself is still not exposed).
~If we want to name this to something more general (especially if we would ever want to re-use this for 2d spectra and want to avoid confusion with spectral lines) now would be the time to do so.~

"Imviz Line Profiles (XY)" renamed to "Image Profiles (XY)"

---

CHANGES.rst
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/utils.py

This pull request adds the functionality for the mouse over on the image viewers to listen to the unit conversion plugin.

Update the mouse over units by listening to the unit-conversion plugin

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/core/launcher.py

TST: Fix tests downloading data into source dir.
MNT: Remove unnecessary astropy check.

TST: Fix tests downloading data into source dir, MNT: Remove unnecessary astropy check

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
jdaviz/core/template_mixin.py

This fixes a bug where toggling to Cube Fit in the model fitting plugin when a spectral subset was selected would result in a traceback and no data being available in the dataset menu. It appears that the dataset is briefly set to None in this case before the appropriate cube data is populated in the menu.

Fix cube fit toggle with spectral subset selected

---

CHANGES.rst

I milestoned #3123 to the wrong version and added a changelog entry that wasn't needed - this bug was never released so I don't think we need a changelog entry for the fix at all.

Remove incorrect changelog entry

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/configs/specviz/plugins/line_analysis/tests/test_lineflux.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue
jdaviz/core/helpers.py
jdaviz/core/validunits.py
jdaviz/utils.py

This pull request is to address:
- The surface brightness drop down will become read-only text
- A new drop down will be created for the solid angle unit
- Surface brightness will update when changes to flux or the angle are made
- the “flux or sb” dropdown will no longer update automatically when making a selection to the flux/angle/sb unit drop downs
To be done:
https://github.com/user-attachments/assets/809aff5d-6409-4a15-ac3c-326b156fce01
Currently, we enable the selection of the surface brightness unit drop down. This ticket will make the surface brightness drop down read-only. A new dropdown will be added, for selecting the denominator, the square angle unit. Surface brightness will then be calculated from the selected flux and angle unit. 
list the proposed …

Surface brightness -> solid angle conversion updates

---

docs/video_tutorials.rst

Added the newest videos to the docs.

Adding newest videos to the docs

---

jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue

The warning about PIXAR_SR should not be shown in Specviz. And I realized I didn't like `x_u` and `y_u` as variable names so I went ahead and made them more descriptive.

Unit conversion bugfix and variable name change

---

CHANGES.rst
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/core/helpers.py
jdaviz/core/template_mixin.py

This pull request fixes `viz.get_data(use_display_units=True)` on a 1d spectrum to respect the user choice of surface brightness or flux units.  This then fixes the previews in line-analysis, which are calling `get_data(use_display_units=True)` under-the-hood when computing the continuum.
https://github.com/user-attachments/assets/693fcb14-be3a-4f8a-9df4-8bdfafbdc7e7

get_data(use_display_units=True) to respect flux or sb selection

---

.github/workflows/standalone.yml

This pull request upgrades the upload-artifact action to v4 following the closing of https://github.com/actions/upload-artifact/issues/485 by release [4.3.5](https://github.com/actions/upload-artifact/releases/tag/v4.3.5) which allows the v4 action to handle a large amount of files in the artifact zip file.

upgrade upload-artifact to v4

---

jdaviz/app.py
jdaviz/core/validunits.py

This pull request is to address removing magnitude units from the Unit Conversion plugin, as there may be incorrect scientific calculation made in spectral extraction and aperture photometry when a magnitude unit is selected. 

remove magnitude units from display units list

---

jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py

In my ongoing work to generalize unit conversion to support non-steradian surface brightness units, traitlets for flux, angle, flux/sb toggling separately. This PR represents some of that reorganization so that rebasing on my eventual PR for others working on unit conversion is less complicated, and to make sure this change doesn't impact anything.
One change to note here is that previously there was some logic to broadcast a GlobalDisplayUnitChange that could either be flux or surface brightness, but in reality it could only ever be flux if you look at the logic (there is a return if 'name' is ever not flux, so that would just never be encountered), so that change is made here as well. 
Anything subscribed to GlobalDisplayUnitChange looking for a change in surface brightness should …

observe display traitlets separately in unit conversion, remove redundant GlobalDisplayUnitChange broadcast

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_helper.py
jdaviz/configs/cubeviz/plugins/tests/test_parsers.py
jdaviz/configs/cubeviz/plugins/tests/test_tools.py
jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py
jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
jdaviz/conftest.py

Fixes #3117
Opening as draft since I still need to address the aperture photometry test failures.

Debug cubeviz spectrum1d parser

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py
jdaviz/tests/test_subsets.py

This pull request is to fix bug found in https://github.com/spacetelescope/jdaviz/pull/2941#discussion_r1672866076

BUG: Fix get_subsets when XOR is involved

---

jdaviz/configs/imviz/plugins/coords_info/coords_info.py

This pull request ensures the units in the markers plugin are in string and fixes adding a marker to the spectrum viewer followed by one of the cube viewers.  This bug is confirmed to not be present in 3.10.x, so should not need backporting or a changelog entry.

markers: ensure units stored as string

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue

Update all display and outputs of aperture photometry app to reflect selected display unit in cubeviz.
The output photometry table now has a separate column for Unit.

Aperture photometry plugin reflects display unit selection

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue

As a follow-up to #3142, this pull request adds an in-line alert within the spectral extraction plugin when the currently selected `function` would _natively_ result in units inconsistent with those shown on the y-axis of the spectrum viewer.
https://github.com/user-attachments/assets/0e43acbd-c166-4294-8b5c-48e53c7031df

add alert when function and spectral y-units are inconsistent

---

tox.ini

This pull request is to use photutils nightly wheel (https://github.com/astropy/photutils/pull/1834) and also some clean-up to devdeps setup.

TST: photutils nightly wheel, devdeps clean-up

---

jdaviz/configs/default/plugins/plot_options/plot_options.py

This pull request is to address data type error. You can reproduce this error on `main` like this:
1. Install numpy 2.1rc: `pip install numpy --pre -U`
2. Run Cubeviz example notebook.
3. Load the data.
4. Open Plot Options. See traceback in Console Log.

Fix dtype error with numpy 2.1

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/plot_options.py

This pull request removes unnecessary updates to the stretch histogram triggered by callbacks on the zoom-limits when the stretch histogram is not set to be restricted to current zoom-limits.
Fixes #3146

fix unnecessary stretch histogram updates

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/core/events.py
jdaviz/core/marks.py
jdaviz/core/template_mixin.py

This PR improves the messaging from the unit conversion plugin to broadcast changes in selected display unit. Because some plugins are listening for changes to the spectral y axis (either from toggling flux<>sb, changing flux or angle when it is toggled to SB, or changing flux when it is toggled to flux) this is its own message now.
Every time a new selection of 'flux' is made, there are three GlobalDisplayUnitChanged messages broadcasted : 'flux', 'sb', and 'spectral_y'.
While this is not included in this PR, these changes will make it possible for the correct messaging to be broadcasted when a new angle selection is made (always sending a 'sb' message, and if the spectral y axis is in SB also sending a 'spectral_y' message).
Every time there is a toggle between flux<> sb, the …

Update messaging from unit conversion plugin

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue

This pull request is to disallow negative counts conversion factor in Aperture Photometry plugin.

Disallow negative counts conversion factor in Aperture Photometry

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue
jdaviz/core/helpers.py
jdaviz/core/validunits.py
jdaviz/tests/test_app.py
jdaviz/tests/test_utils.py
jdaviz/utils.py

This pull request is to address implementing a solution to handle units that cannot be translated using the MJy <-> MJy / sr custom equivalency (and subsequent surface brightness conversions between these units). The following units are able to be converted between flux units and other flux units, but issues specifically arise in translations and in surface brightness to surface brightness conversions. Custom equivalencies have been added in this PR that enable conversions and translations to solve this issue, and they work in a notebook cell setting. However, attempting to utilize this solution in Cubeviz UI causes tracebacks. It is likely due to the native units from the data collection. The native units will be used for the Spectrum1D object used in `flux_conversion`, and the native …

Untranslatable unit handling

---

CHANGES.rst
jdaviz/components/plugin_color_picker.vue
jdaviz/configs/cubeviz/plugins/slice/slice.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/imviz/plugins/orientation/orientation.vue
jdaviz/core/template_mixin.py

This pull request is a follow-up to #3137 to give the flexibility for inherited plugins (i.e. time selector in lcviz or cube extraction in lcviz/rampviz) to override the plugin key shown in the API hints.  It also makes the following small tweaks:
* fix the styling on a component in the slice plugin
* fix styling for "apply RGB presets" button in plot options
* fix options for "align_by" in orientation plugin to be the same options as the API
* add quotes around the color string in color picker
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not …

API hints tweaks

---

jdaviz/configs/default/plugins/data_quality/tests/test_data_quality.py

Probably caused by pipeline changes we can do nothing about. One of the dangers of remote data tests.

TST: Update remote data result for DQ plugin

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue

This pull request fixes a typo introduced in #3159 causing the spectral extraction UI in cubeviz to fail to render.

fix typo from PR 3159

---

CHANGES.rst
jdaviz/configs/rampviz/plugins/parsers.py
jdaviz/configs/rampviz/plugins/ramp_extraction/ramp_extraction.py
jdaviz/configs/rampviz/tests/test_helper.py
jdaviz/configs/rampviz/tests/test_ramp_extraction.py
jdaviz/configs/rampviz/tests/test_slice.py
jdaviz/conftest.py
notebooks/concepts/RampvizExample.ipynb

Follow up after #3120 adding support for JWST L1 ramps.
The only major difference between JWST ramp files (any instrument) and Roman WFI is that JWST bundles time-series observations with multiple integrations into one 4D array of dimensions (integrations, groups, x-pixel, y-pixel), whereas Roman only ships single integrations in a 3D array.
This PR adds a parser for JWST Level 1 data products as fits files or `Level1bModel` models. By default, rampviz will load the zeroth integration, and specific integrations can be selected with, e.g.:
```
rampviz.load_data(path, integration=3)
```
Since this PR adds support for JWST, without the need for the optional Roman dependencies, the project code coverage test here is more useful than in #3120.
list the proposed change log here for review and …

JWST L1 ramp parser for Rampviz

---

jdaviz/configs/imviz/plugins/coords_info/coords_info.py

Looks like #3139 broke adding moment maps to a viewer, due to the `coords_info` logic. This skips the flux conversion that breaks it in the case of moment-like units (velocity and higher powers of it) by skipping any unit with incompatible physical type.
~Additionally, calculating moment 0 in flux when the cube is in surface brightness seemed to be broken (again?) so I moved the unit conversion to be before the moment calculation, so we can convert, e.g., MJy/sr to MJy and not have to worry about the extra wavelength unit that comes in via the moment calculation.~
~I also took this opportunity to bump the specutils pin and get rid of the handling for the change in 1.16 for the dev tests and such.~

Skip flux conversion for moment maps

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py

Small typo but should still fix it.

BUG: Fix typo on internal method

---

CHANGES.rst
jdaviz/configs/rampviz/plugins/parsers.py
jdaviz/configs/rampviz/tests/test_parser.py
jdaviz/conftest.py

#3148 implemented parsers for JWST ramp cubes. JWST/NIRSpec has two readout modes, and it appears that [the IRS2 readout modes](https://jwst-docs.stsci.edu/jwst-near-infrared-spectrograph/nirspec-instrumentation/nirspec-detectors/nirspec-detector-readout-modes-and-patterns/nirspec-irs2-detector-readout-mode#gsc.tab=0) produce ramp cubes with the order of the x and y axes swapped. This PR identifies that special case and rearranges the axes correctly.
Test this PR with:
```python
from jdaviz import Rampviz
uri = "mast:JWST/product/jw02123001002_0310d_00001_nrs1_uncal.fits"
rampviz = Rampviz()
rampviz.load_data(uri, cache=True)
rampviz.show()
``` …

Fix for NIRSpec IRS2 readout mode

---

CHANGES.rst
jdaviz/configs/default/plugins/viewers.py
jdaviz/configs/rampviz/plugins/ramp_extraction/ramp_extraction.py
jdaviz/configs/rampviz/plugins/tools.py
jdaviz/configs/rampviz/plugins/viewers.py

Three bugs to fix: 
* When updating the selected slice in the integration viewer in Rampviz, the integration viewer's y-limits change twice and the data flash and move around a bit. 
* When a subset is created in the group-viewer, the integration viewer gets a subset profile by default via glue. That profile layer's icon appears in the legend and `layer.visible == True`, even though the subset profile can't be seen in the viewer. Glue ensures that profile viewers create visible subset profiles by default, it's on us to override that behavior, and some minor bits of logic are missing.
* When using the single-pixel ramp-extraction-on-hover tool, integration-viewer limits do not get reset when the preview exceeds the y-limits.
This PR fixes these bugs by: 
* adjusting the logic in …

Rampviz fixes for unexpected viewer limit resets

---

jdaviz/app.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/core/template_mixin.py

This pull request limits the updates to `subset_selected_changed_callback` (originally introduced in #2939) to only trigger for subset update messages corresponding to the currently selected subset (and only when the subset state has been changed, not color, etc) and also minimizes spectral extraction calls when `subset_select.items` are changed to only affect the selected entry.
~Fixes #3164~

improve laggy subset finalization

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue

This changes three things that were requested to be updated:
- update the plugin description to be either config-specific or config-generic
- consider renaming flux_or_sb to spectrum_y_type (or similar) and updating UI language
- determine which cases angle unit should be shown (UI and user API).  Probably can be disabled in anything without an image viewer.
If "Convert the units of displayed physical quantities." doesn't sound good as more generic language to people I can come up with something else.

Unit conversion UI tweaks

---

jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue

This pull request provides the infrastructure for configs (and downstream apps) to dictate which display units should be shown in the plugin, as well as including a time unit (currently unused for all configs, but needed by lcviz).  The individual logic may need to be adjusted as unit conversion is enabled for the remaining configs (I just made a rough guess).  This PR also makes the surface-brightness API access read-only.

per-config display of unit selections

---

CHANGES.rst
jdaviz/configs/specviz/plugins/parsers.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py

This fixes problems on `main` with loading a the spectrum in the SpectrumExample notebook related to the Unit Conversion plugin (or presumably any other spectrum in surface brightness units). Mainly, this sets `spectral_y_type` to the correct selection on loading the first spectrum, and avoids having a blank angle unit selection when triggering `_on_flux_unit_changed`.

Fix empty flux menu in Specviz with spectrum in surface brightness units

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py

This PR changes some of the unit conversion related variable names in aperture photometry to make it clearer that the spectral y axis unit is not being used for the plugin's display unit, but rather the dataset unit type (flux or sb) along with the choice of flux and angle units from the UC plugin for display. This same change needs to be made in moment maps, but since much of the code where these variables are being referenced go away in #3156, that will be addressed there. This also removes a remnant of checking for old specutils version in moment maps which can go away now that the minimum version is 1.16

fix var names in aper phot, remove specutils version check

---

CHANGES.rst
docs/imviz/plugins.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/plugins/catalogs/catalogs.vue
jdaviz/configs/imviz/tests/test_catalogs.py
jdaviz/core/marks.py
jdaviz/core/template_mixin.py

This pull request is to address making the table interactive, mainly adding a zoom feature and additional markers for selected points. 

Make catalog tables interactive

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/default/plugins/model_fitting/initializers.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py

I split this out from #3190 so it can be backported to 3.10. Still need to add a test and move the changelog.
Edit: ready for review. Note that simply adding `filter_non_finite` to the `specutils.fit_lines` call like in the 1D case didn't seem to work, so I masked out the NaN locations instead. Why that didn't work might be worth further investigation in the future.

Fix NaN handling in cube fitting

---

jdaviz/components/tray_plugin.vue

This pull request fixes an inadvertent typo introduced in #3137 that resulted in `.tray-plugin` css styling from being ignored (including hiding the table popout button).

fix tray plugin styling

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/initializers.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py

Opening as draft since I still need to work on the unit conversion part, but I wanted to see the diff and remind myself what I'd changed so far.

Fix cube fitting compatibility with unit conversion

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/model_fitting.py

This pull request includes unit columns by default in the results table in model fitting, which is particularly useful now that switching input units is supported.

show unit cols by default in model fitting results table

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/tests/test_blackbody.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py

This pull request is to fix #3189

Use TRFLSQFitter instead of LevMarLSQFitter

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_parsers.py

This pull request is to address when scientific notation (a scale factor), is included in the native unit of the data file parsed (eg. in a MANGA cube). It is addressed by updating the values of the data to reflect the scale factor, and in the Unit Conversion plugin/app-wide, 'removing' the scale factor from the actual unit. When viewing the BUNIT metadata, the scale factor is still included in the unit. 

add support for scientific notation in unit string

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/mixins.py
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/cubeviz/plugins/slice/slice.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_parsers.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
jdaviz/configs/default/plugins/viewers.py
jdaviz/configs/specviz/plugins/parsers.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz/tests/test_viewers.py
jdaviz/core/events.py
jdaviz/core/template_mixin.py
jdaviz/core/validunits.py
jdaviz/utils.py

This pull request refactors and simplifies the messaging within unit conversion.  ~This currently is branched off of #3156, so should be moved onto main after that is merged.~

refactor unit conversion messaging

---

.github/workflows/changelog_check.yml
.github/workflows/check_milestone.yml
.github/workflows/ci_cron_weekly.yml
.github/workflows/ci_workflows.yml
.github/workflows/codeql-analysis.yml
.github/workflows/open_actions.yml
.github/workflows/predeps_workflows.yml
.github/workflows/publish.yml
.github/workflows/standalone.yml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60) [🐱](https://jira.stsci.edu/browse/JDAT-4821)

MNT: Use hash for Action workflow versions and update if needed

---

CHANGES.rst
jdaviz/configs/imviz/plugins/coords_info/coords_info.py

This pull request fixes the visibility of the mouseover marker in the 1d spectrum viewer during a mouseover in the 1d spectrum viewer.  This was broken by #2830 which now needs to set `coords_status = True` in cases in which the WCS lookup is successful.

fix specviz2d matched mousover marker

---

CHANGES.rst
jdaviz/configs/default/plugins/data_quality/data_quality.py
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/imviz/plugins/parsers.py
jdaviz/configs/rampviz/helper.py
jdaviz/configs/rampviz/plugins/parsers.py
jdaviz/configs/rampviz/plugins/ramp_extraction/ramp_extraction.py
jdaviz/configs/rampviz/plugins/viewers.py
jdaviz/configs/rampviz/tests/test_parser.py
jdaviz/conftest.py
jdaviz/core/tools.py

This PR introduces adaptations to allow Level 2 data products to be loaded into Rampviz, at the same time as Level 1 products.
The demo video below opens L1 and L2 products for the Carina nebula. The L2 product is opened in an image viewer to the right of the usual Rampviz viewers. I've loaded the L2 product with its DQ extension, so you can see where pixels are flagged. I zoom in on a region where pixels are flagged by jump detection (pink DQ overlay), create a subset, and show that the pixels in the subset indeed have a jump.
https://github.com/user-attachments/assets/e037bfc6-f0c8-4b1f-9a0d-91976938bba9
To reproduce locally, run:
```python
from jdaviz import Rampviz
level_2 = 'mast:JWST/product/jw02731001004_02103_00005_nrca3_cal.fits'
level_1 = level_2.replace('_cal', '_uncal') …
```

Level 1 and Level 2 data product support in Rampviz

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/core/template_mixin.py

There was previously an issue where the moment map plugin was using the spectral y axis unit for moment 0 rather than always using a surface brightness unit. This was fixed in #3156. 
This PR applies some of the changes from #3116, which also fixed that issue but based on an outdated main pre many unit conversion changes, so I found it easier to cherry pick some of the code here rather than rebasing that PR.
The display unit now has the spectral unit because specutils is pinned to the version with the fix for MM units. I made some small tweaks including using _get_display_unit rather than grabbing the UC plugin from the MM plugin and accessing display unit there. 
I think sufficient test coverage was added in #3156 so i didn't add the tests from #3116, but i did expand one of the tests to …

add spectral unit to moment map 0 display unit, simplify logic

---

jdaviz/app.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/core/marks.py

This pull request updates the spectral extraction live-preview for any change that affects the y-units of the extracted spectrum or spectral viewer (and also ensures the internal units in the plugin are populated for the warning banner introduced in #3143 which was recently broken).
https://github.com/user-attachments/assets/c4ec1fd9-8cdf-449f-873e-d84b6a8a212a

fix spectral extraction previews on unit change

---

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/core/marks.py
jdaviz/core/template_mixin.py

This pull request implements the ability for the continuum mixin to handle unit conversion within the preview marks themselves, and makes use of that within the moment map plugin, but leaving line analysis to do unit conversion within the plugin since we want to recompute results to expose in the table during a unit conversion change.
See https://github.com/spacetelescope/jdaviz/pull/3211#discussion_r1787796594 

Moment map continuum unit conversion

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_unit_conversion.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/utils.py

This pull request is to unit conversion when equivalency needed breaks contours in cubeviz. Unskips a test added in https://github.com/spacetelescope/jdaviz/pull/3204 .
Probably no need for change log since this is patching unreleased feature, I assume.

Fix "Unit conversion when equivalency needed breaks contours in cubeviz"

---

CHANGES.rst
jdaviz/configs/default/plugins/markers/tests/test_markers_plugin.py
jdaviz/core/marks.py

This pull request is to address updating the spectral density equivalencies to use the original spectral axis so plugin Markers update to the correct position on the spectrum after a unit change. 
Original Behavior:
https://github.com/user-attachments/assets/e1138a05-e7f3-49aa-bb83-6877ca2969dd
Updated Behavior:
https://github.com/user-attachments/assets/00cd6394-4d81-4d66-956d-9e99f26dbe0c

use correct spectral density equivalencies for marker unit changes

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_tools.py
jdaviz/configs/cubeviz/plugins/tools.py
jdaviz/configs/imviz/plugins/tools.py
jdaviz/configs/imviz/tests/test_tools.py
jdaviz/core/tools.py

This pull request fixes matched image box zoom when the matched viewers have different aspect ratios.'
~TODO: this breaks the old tests that expect the same limits to be returned~
**Before**:
https://github.com/user-attachments/assets/edda126e-7adc-4d89-9602-562db23b7df7
**After**:
https://github.com/user-attachments/assets/4f6108b0-b4a3-4de1-ac3b-32e1de9ba3e5

imviz matched zoom: use center & radius instead of corners

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue

This pull request fixes a missing style class added for API hints to the `aperture_method` entry in spectral extraction.

apply api-hints styling to aperture_method in spectral extraction

---

jdaviz/configs/default/plugins/plot_options/plot_options.py

This pull request fixes a bug that only seems to happen in lcviz (perhaps because of the order in which data is added to a new image viewer), which caused plot options to crash when selecting an image layer because `image_color_value` was not yet populated.
Because I have not seen this in imviz, I am marking as no changelog entry needed since it should only affect downstream lcviz.  If anyone can reproduce in imviz, then we should add a changelog entry.

postpone updating stretch hist if image_color_value not yet set

---

CHANGES.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/plugins/footprints/footprints.py

This pull request disables "From File..." options for importing catalogs and footprints from a file in cases where jdaviz is running on an external server.

disable file imports when running on external server

---

docs/_static/jdaviz.css
docs/conf.py
docs/index.rst

This pull request is an alternate fix for the logos based on https://github.com/astropy/astropy/pull/16639
Close #3243

DOC: Fix logos and dark mode

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py

#3088 introduced a scientific validation test for spectral extraction in Cubeviz by comparing an extracted spectrum with the calibration spectrum expectation from CALSPEC, using the science data processinv version 2024_1a. The release of 2024_2b has broken the test, which is likely a result of updates to the MIRI flux calibration.
This PR updates the validation test to use a more liberal tolerance and to tweak the spectral extraction parameters. 

Spectral extraction scientific validation test fix for latest JWST data product release

---

CHANGES.rst
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/tests/test_simple_aper_phot.py

This pull request is to address profile fitting crashing when NaN is within aperture data.

BUG: Fix radial profile fitting when NaN in data

---

jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py
jdaviz/configs/default/plugins/subset_plugin/tests/test_subset_plugin.py

This pull request reverts the combination mode to before the `import_region(region, combination_mode=<list>)` call.

Revert combination mode to before import_region call

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_tools.py
jdaviz/configs/cubeviz/plugins/tools.py
jdaviz/configs/default/plugins/tools.py
jdaviz/configs/default/plugins/viewers.py
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/tests/test_astrowidgets_api.py
jdaviz/configs/imviz/tests/test_tools.py
jdaviz/configs/mosviz/helper.py
jdaviz/configs/mosviz/tests/test_tools.py
jdaviz/core/astrowidgets_api.py
jdaviz/core/tools.py

BUG: Fix spectrum and spaxel resetting X and Y limits.
TST: Add regression test that fails on main without this patch.
FEAT: Add `viewer.get_limits()` method for convenience and refactor some code to use it. Also refactor some code to use existing `viewer.set_limits()` method. Since these are not "public API," there is no need for change log for this part.

BUG: Fix spectrum and spaxel resetting limits; FEAT: Add viewer.get_limits()

---

CHANGES.rst
jdaviz/app.py
jdaviz/components/layer_viewer_icon_stylized.vue
jdaviz/components/plugin_switch.vue
jdaviz/components/subset_icon.vue
jdaviz/components/tooltip.vue
jdaviz/configs/default/plugins/data_menu/data_menu.py
jdaviz/configs/default/plugins/data_menu/data_menu.vue
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue
jdaviz/configs/default/tests/test_data_menu.py
jdaviz/container.vue

This pull request implements the framework for the redesigned data-menu launched from the viewer legend - currently including a list of layers with togglable visibilities.  Until this reaches feature-parity with the existing data menu and can be launched in its place, this will be hidden behind a developer flag to avoid confusion.  To enable for testing (note: both this and the `_obj` will be removed when making the data-menu public):
```
for viewer in viz.viewers.values():
viewer._obj.data_menu._obj.dev_data_menu = True
```
**TODO / follow-ups**:
This checklist is meant to remind the package maintainer(s) who will review this pull request …

Framework for legend data menu

---

CHANGES.rst
jdaviz/core/marks.py

This pull request is to address line lists and unit conversion compatibility. On main, line marks go through conversion machinery and can cause lines to vanish from the spectrum-viewer depending on the original unit and target unit (are not visible even at updated y-range for line after conversion). This PR prevents SpectralLines from y-converting so they maintain their position in the viewer at the rest + redshifted spectral value.

prevent spectral lines from converting y-range

---

CHANGES.rst
jdaviz/app.py
jdaviz/components/data_menu_add_data.vue
jdaviz/components/toolbar_nested.py
jdaviz/configs/cubeviz/plugins/viewers.py
jdaviz/configs/default/plugins/data_menu/data_menu.py
jdaviz/configs/default/plugins/data_menu/data_menu.vue
jdaviz/configs/default/tests/test_data_menu.py
jdaviz/configs/imviz/plugins/viewers.py
jdaviz/configs/mosviz/helper.py
jdaviz/configs/mosviz/plugins/viewers.py
jdaviz/configs/specviz/plugins/viewers.py
jdaviz/core/template_mixin.py

This pull request extends on #3254 by implementing the "+" menu to add data and subsets to the current viewer.  This also exposes `data_menu.create_subset(subset_type)` (to enable the matching subset tool in that viewer's toolbar) and `data_menu.add_data(data_label)` - currently via `data_menu = viz.viewers[viewer_label]._obj.data_menu` (although the necessity for the `_obj` will be removed once the data-menu is ready to be exposed to users.
This PR does include logic so that the listed available data entries _are applicable_ to that specific viewer.
This PR does _not_ include the ability to remove data from the viewer or app in the new data-menu: that will be implemented in #3264.  Until then, remove data from the old data-menu or from the API for testing purposes, or create data in a …

data-menu: add subsets/data

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/core/tests/test_autoconfig.py

Remote data tests are currently failing on a file lookup in MAST. This PR replaces that specific, unresolvable URI to one that works. 
We had commented out a Specviz test, which I've added again, since https://github.com/spacetelescope/jdaviz/pull/2576 was merged. 

Fix URI for autoconfig test for specviz2d, add back specviz test

---

jdaviz/app.py
jdaviz/configs/mosviz/tests/test_parsers.py
jdaviz/tests/test_utils.py

This pull request is to unblock CI for unrelated PRs until someone picks up ticket to fix the test properly.
Close https://github.com/spacetelescope/jdaviz/pull/3275

TST: Skip chronically failing test

---

docs/imviz/import_data.rst

This is a follow-on from #3252 that updates the docs to reflect a more complete version of creating and `NDData` object from a jwst data model.
The `dq` and maybe the `err` parts I think should be generic across jwst instruments, even though the exact interpretation is a bit variable (that is they should all be self-consistent, but different instruments I think use slightly conceptually different uncertainty models).

update datamodels example to include more info

---

docs/conf.py
docs/quickstart.rst

This pull request is to address Cami's desire to see `jdaviz --help` printed in user doc.
Rendered doc: https://jdaviz--3286.org.readthedocs.build/en/3286/quickstart.html#as-a-standalone-application

DOC: Auto-inject CLI help into user doc

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/core/tests/test_autoconfig.py

This pull request is to manually backport https://github.com/spacetelescope/jdaviz/pull/3267 onto v4.0.x

Backport PR #3267: Fix URI for autoconfig test for specviz2d, add back specviz test

---

CHANGES.rst
jdaviz/components/plugin_layer_select.vue
jdaviz/configs/default/plugins/data_menu/data_menu.py
jdaviz/configs/default/plugins/data_menu/data_menu.vue
jdaviz/configs/default/plugins/export/tests/test_export.py
jdaviz/configs/default/plugins/subset_plugin/tests/test_subset_plugin.py
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/core/template_mixin.py

This pull request implements orientation selection (when applicable) in the data menu.
Until enabled, the following is necessary for dev testing:
```
for viewer in imviz.viewers.values():
viewer._obj.data_menu._obj.dev_data_menu = True
```
(Note: icons added to dropdown since screen recording)
https://github.com/user-attachments/assets/c0e13cf2-3859-4bc1-9bff-08d551e61c20

data-menu: orientation

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/initializers.py
jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py

Fixes a traceback that was occurring when adding a Gaussian model component with `Cube Fit` toggled on.

Collapse 3D y before calculating initial model guess for gaussian model

---

jdaviz/configs/cubeviz/plugins/tests/test_parsers.py
jdaviz/utils.py

This pull request is to fix parsing of cube in DN and DN/s units in Cubeviz. This is a follow-up of #3221 that is not yet released, so no need for change log.

BUG: Fix Cubeviz parsing DN and DN/s

---

CHANGES.rst
jdaviz/app.py
jdaviz/app.vue
jdaviz/components/data_menu_add.vue
jdaviz/components/data_menu_remove.vue
jdaviz/components/data_menu_subset_edit.vue
jdaviz/components/hover_api_hint.vue
jdaviz/components/plugin_switch.vue
jdaviz/components/tooltip.vue
jdaviz/components/tray_plugin.vue
jdaviz/configs/default/plugins/data_menu/data_menu.py
jdaviz/configs/default/plugins/data_menu/data_menu.vue
jdaviz/configs/imviz/plugins/orientation/orientation.vue
jdaviz/core/template_mixin.py
jdaviz/core/user_api.py
jdaviz/main_styles.vue

This pull request moves API hint toggles from the plugin to the app-level and implements API hints for the data-menu.
https://github.com/user-attachments/assets/ddf63d27-ef7c-459c-abd0-b893dffdd95b

data-menu: API hints

---

CHANGES.rst
jdaviz/configs/default/plugins/data_menu/data_menu.py
jdaviz/configs/default/plugins/data_menu/data_menu.vue
jdaviz/configs/default/tests/test_data_menu.py
jdaviz/core/template_mixin.py

This pull request implements a `sort_by` option on the `LayerSelect` component, which defaults to the previous behavior of `icon` (order layer was _added_), but also supports `zorder` (shows layers on TOP first).  The `zorder` ordering is then used for the legend, data-menu, ~and plot options tabs~.
~Note that for plot options, it is possible to subscribe to layers from multiple viewers, and they may have different zorder.  In this case, the zorders are parsed and sorted based on the first viewer they are found in according to the selected viewers.~
NOTE: this now defers re-ordering plot options tab since we need to give more thought on how the RGB presets logic should work in this case.
https://github.com/user-attachments/assets/cfd7069a-cfd2-4782-a06d-68409f4f0cdd
list the proposed …

data-menu: enforce layer order

---

CHANGES.rst
jdaviz/app.vue

Since Lab 4.2 cells outside the viewport get the style "display: none" which causes the content to not have height. This causes an error in size calculations of golden layout from which it doesn't recover.
This PR  works around this by not rendering golden layout until its parents have height.

fix: golden layout not rendering when created outside viewport

---

CHANGES.rst
jdaviz/app.vue

Manual Backport: fix: golden layout not rendering when created outside viewport (#3299)

---

CHANGES.rst
jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py
jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py
jdaviz/core/user_api.py

This pull request is to address the request, "File metadata extracted from the API is hard to parse. Maybe a dictionary is better?"
I avoided changing `metadata` itself because that would mean messing with the front-end stuff that already works. Also might be subtly confusing because the same attribute now returns something different. Maybe best to have a clean break using a different attribute name.

Metadata Viewer: API to return dict, not list

---

jdaviz/configs/default/plugins/data_quality/data_quality.vue

This PR fixes a typo introduced in #3268 preventing the DQ plugin from rendering.  #3268 was not backported or released, so this does not need to be backported or have a changelog entry.

fix typo in data_quality vue

---

CHANGES.rst
jdaviz/components/plugin_slider.vue

This pull request ensures sliders in plugins use full-width.  In the footprint plugin, where the slider was not wrapped in a glue sync state, the slider currently did not fill the full-width of the plugin.

Fix full width of plugin slider

---

jdaviz/utils.py
pyproject.toml

This pull request fixes recent upstream changes causing CI/RTD build failures.

Fix CI/RTD failures

---

CHANGES.rst
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/imviz/plugins/orientation/orientation.vue
jdaviz/configs/imviz/tests/test_delete_data.py
jdaviz/configs/imviz/tests/test_footprints.py
jdaviz/configs/imviz/tests/test_orientation.py

This pull request exposes `create_north_up_east_left(...)` and `create_north_up_east_right(...)` methods via the public API of the Orientation plugin, along with API hints.
This also renames `set_on_create` to `set_as_orientation` in these methods, as it sets them whether or not they are created.  This does not however, rename the already public `set_on_create` within `add_orientation(...)`
Docs updates: [Orientation plugin API docs](https://jdaviz--3308.org.readthedocs.build/en/3308/api/jdaviz.configs.imviz.plugins.orientation.orientation.Orientation.html#jdaviz.configs.imviz.plugins.orientation.orientation.Orientation)
API hints:
This …

orientation: expose create_north_up_east_left/right

---

jdaviz/app.py
jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/cubeviz/plugins/tests/test_data_retrieval.py
jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/core/custom_units_and_equivs.py
jdaviz/core/unit_conversion_utils.py

#3221 broke MaNGA data cube loading, because we didn't account for `spaxel` being in the flux units anywhere in our code. I added that to the list of recognized solid angle units in `check_if_unit_is_per_solid_angle`, but this probably needs a little more thought about whether to expose `spaxel` in the unit conversion plugin along with `pix^2`, or whether to always convert `spaxel` to `pix^2` on data load and just have `pix^2` in the unit conversion plugin. @havok2063 @camipacifici any thoughts on those two options?
Note that I milestoned this as 4.1, loading still works in 4.0.x because #3221 was milestoned to 4.1.
Still investigating why the current MaNGA loading test didn't catch this.

Improve spaxel unit handling for cubes

---

CHANGES.rst
jdaviz/core/template_mixin.py

This pull request raises an error when trying to show a widget in popout or sidecar when they are not supported (i.e. in VS Code).  Related to #3251.

raise error for sidecar or popout when not supported

---

jdaviz/core/linelists.py
pyproject.toml

The filtered warning for `mpl-scatter-density` may be unnecessary since the release of v0.8. Trying that out in this PR.
It turns out that there was an in situ `pkg_resources` warning stemming from `linelists.py`, too.
Related PRs:
* https://github.com/glue-viz/glue/pull/2521
* https://github.com/astrofrog/mpl-scatter-density/pull/47
* https://github.com/spacetelescope/lcviz/pull/156
* https://github.com/spacetelescope/jdaviz/pull/3317

Removing filter warning for mpl-scatter-density

---

CHANGES.rst
jdaviz/configs/default/plugins/subset_tools/subset_tools.py
jdaviz/core/template_mixin.py

This pull request delays loading subset layers into viewers during subset tools `import_region` until all regions are loaded into the data collection, improving performance considerably.

subset tools import_region to use batch_load

---

CHANGES.rst
jdaviz/configs/default/plugins/subset_tools/subset_tools.py
jdaviz/configs/default/plugins/subset_tools/subset_tools.vue
jdaviz/configs/imviz/tests/test_subset_centroid.py
jdaviz/tests/test_subsets.py

This pull request exposes `recenter_dataset` and `recenter()` and adds API hints for the subset tools plugin.

Subsets tools API hints

---

jdaviz/core/template_mixin.py

This pull request fixes immediately updating the layer icon style when there is a change to linewidth or colormap from plot options.

data-menu: fix updating linewidth and colormap styling

---

jdaviz/app.py
jdaviz/configs/mosviz/tests/test_parsers.py

See if https://github.com/spacetelescope/gwcs/pull/526 works so we do not have to worry about warning from bounding box downstream anymore in cases we cannot control.
Reverts parts of https://github.com/spacetelescope/jdaviz/pull/3283

Un-ignore GWCS warning because it is no longer necessary

---

.github/workflows/ci_cron_weekly.yml
.github/workflows/ci_workflows.yml
jdaviz/configs/rampviz/plugins/parsers.py
jdaviz/configs/rampviz/plugins/ramp_extraction/ramp_extraction.py
jdaviz/conftest.py
pyproject.toml

Tests that rely on the optional Roman dependencies are currently failing since updates to `roman_datamodels` and `rad` that now save ramps as numpy arrays rather than astropy quantities. I've bumped the pin on rdm, and revised how units are handled for that data model in jdaviz. I've also moved the romandeps cron test into `ci_workflows` under allowed failures, so we'll have faster warning next time we're out of sync.

roman_datamodels compatibility, move `romandeps` test to CI workflows

---

CHANGES.rst
docs/cubeviz/plugins.rst
jdaviz/app.vue
jdaviz/configs/cubeviz/helper.py
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_parsers.py
jdaviz/core/linelists.py
pyproject.toml

Backport PR #3319 on branch v4.0.x (Respect loaded mask cube properly in spectral extraction.)

---

.github/workflows/ci_cron_weekly.yml
.github/workflows/ci_workflows.yml
jdaviz/configs/rampviz/plugins/parsers.py
jdaviz/configs/rampviz/plugins/ramp_extraction/ramp_extraction.py
jdaviz/conftest.py
pyproject.toml

… (#3353)
* rdm compatibility, move romandeps test to CI workflows
* Fix ci_workflows.yml
---------
Co-authored-by: P. L. Lim <2090236+pllim@users.noreply.github.com>
(cherry picked from commit 05e9afb0fdc11d062e52b483b11ee5ac1e8577ec)

Backport PR #3353 on branch v4.0.x (roman_datamodels compatibility, move romandeps test to CI workflows)

---

CHANGES.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/plugins/catalogs/catalogs.vue
jdaviz/configs/imviz/tests/test_catalogs.py

This pull request is to address an edge case when there is only one source in a catalog search from file. It also implements the `max_sources` traitlet for all catalogs. 

catalog search handle from file edge case and implement max sources

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_regions.py
jdaviz/configs/default/plugins/subset_tools/subset_tools.py
jdaviz/configs/default/plugins/subset_tools/tests/test_subset_tools.py
jdaviz/configs/imviz/tests/test_linking.py
jdaviz/configs/imviz/tests/test_parser.py
jdaviz/configs/imviz/tests/test_regions.py
jdaviz/configs/specviz/helper.py
jdaviz/configs/specviz/tests/test_helper.py
jdaviz/core/helpers.py

This PR adds ``get_regions`` to the Subset Tools plugin, and deprecates ``get_interactive_regions`` and ``get_spectral_regions``.

add get_subsets_as_regions method to subset plugin, deprecate get_interactive_regions and get_spectral_regions

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_parsers.py

Updates the value in the test from #3319 to be, I think, correct this time, and adds a simpler test that exposes the problem that I had with that test. I'm out of time to add a changelog, I'll do it tomorrow.

Fix aperture weight mask with loaded mask cube

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_parsers.py

Backport PR #3358 on branch v4.0.x (Fix aperture weight mask with loaded mask cube)

---

jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py

We may want to refactor slightly so that at least one combination always runs, but for now I'm marking the whole thing as slow.

Mark parameterized unit conversion test as slow

---

CHANGES.rst
jdaviz/app.py

As previously noted in the deleted comment, there's no need to process every subset if only one subset was requested. This trims the list down to only the matching subset before going through the loop processing them all.

Improve get_subsets performance for single subset case

---

CHANGES.rst
docs/plugin_api.rst
jdaviz/core/helpers.py
jdaviz/tests/test_user_api.py

This pull request implements and documents `viz.toggle_api_hints()` to allow toggling the presence of API hints from within the notebook.

helper-level method to programmatically toggle API hints

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py
jdaviz/core/tools.py

This pull request is to fix broken pan/zoom on Plot Options histogram.

BUG: Not all viewers have get_limits

---

jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue

This pull request fixes a few minor typos in main but not in the released version.

fix vue typos in specviz2d spectral extraction

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
jdaviz/utils.py

This draft PR resolves:
1. UnitConversionError in Model Fitting plugin, specutils `spec.with_flux_unit` did not have access to `pix2` custom unit equivalencies
To reproduce on main:
```
uri ='https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/IFU_cube_continuum_fit/NGC4151_Hband.fits'
model = cubeviz.plugins['Model Fitting']
model.cube_fit = True
model.create_model_component()
model.calculate_fit()
```
2. TypeError: unsupported operand type(s) for *: 'CompositeUnit' and 'NoneType'. When toggling 'Cube Fit' in Model Fitting plugin, `solid_angle_in_targ` was not being set after `targ_units` was update to include a solid angle unit. Setting 'targ_units' triggered subsequent indirect conversion logic. By setting the `solid_angle_in_targ` we follow the same logic route and …

model fitting: ensure specutils has access to equivs & set targ solid angle

---

jdaviz/core/template_mixin.py

... this time with a comment so it isn't accidentally undone (blaming previous self 🙄 )

fix repr for select component

---

CHANGES.rst
jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py
jdaviz/core/template_mixin.py

Fix a bug that came up when trying to select all layers in plot options when data is float32. The solution is to use the logic in on_glue_value_changed to handle updating mixed state, which takes care of the type issue.
(Need this fix for AAS demo notebook)

Fix type issue in plot options select_all

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/core/freezable_state.py
jdaviz/tests/test_utils.py
jdaviz/utils.py

This pull request implements custom logic to convert (instead of resetting) y-limits on a spectrum when the y display unit is changed.  This does so by sending all 4 corners through the flux/SB conversion logic and ensuring that those bounds remain in view.  As a consequence, multiple unit conversions can result in "zooming out", but never zooming in (i.e. this is not expected to roundtrip, but is supposed to keep any feature in frame).

convert limits on spectrum y-unit change

---

CHANGES.rst
jdaviz/configs/default/plugins/data_menu/data_menu.py
jdaviz/configs/default/tests/test_data_menu.py

This pull request implements logic to ensure a parent data layer is visible when enabling a child data-layer and to hide child layers when disabling the parent data-layer.

data-menu: handle associated data layer logic

---

CHANGES.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/tests/test_catalogs.py

This PR exposes 'zoom_to_selected' in the catalogs plugin, and adds test coverage for this functionality. 
This also fixes an issue where 'zoom_to_selected' was using a fixed default value of 50 pixels around the source(s), which is inappropriate for small images (including when wcs linked and the image is 10x10 pixels). The default is now to use 2% of the total image size around the bounding box containing the selected points, which felt like a good size in my testing. The 'padding' parameter, which refers to the fraction of the image size to use as the zoom level around sources, is now exposed in 'zoom_to_selected' as well so it can be adjusted if needed.

expose zoom_to_selected in catalogs plugin api, fix default zoom level

---

CHANGES.rst
jdaviz/configs/default/plugins/viewers.py
jdaviz/configs/imviz/tests/test_viewers.py

This fixes an issue where back-to-back calls to set_limits and get_limits were producing different results for y limits. For example, 
`viewer.set_limits(x_min=0, x_max=20, y_min=0, y_max=20)`
`limits = viewer.get_limits()`
(0, 20.0, 3.855, 16.145).
For whatever reason, switching the order that ymin and ymax are set fixes this issue. I'm not sure if this entirely fixes the zoom/resize issue noted in #3369, but it resolves this round tripping that should work. There is still a deeper issue going on here.

switch order of setting ymin and ymax

---

.github/workflows/ci_workflows.yml
pyproject.toml
tox.ini

This pull request is to add Python 3.13 job. Probably no need for change log unless we need real code changes here.
After merge: Follow up issue to remove `-dev` tag from Python version spec for 3.13 when stable is available from Actions runner.
Fix #3186

TST: Python 3.13 support

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/parsers.py
jdaviz/configs/cubeviz/plugins/tools.py

This pull request is to fix https://github.com/spacetelescope/jdaviz/issues/3362 .
The fix is so tiny... Do we really need a change log or test here, @rosteen ?

BUG: Also check for inf in spaxel tool

---

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/core/unit_conversion_utils.py

This pull request is to address compatibility with
* https://github.com/astropy/astropy/pull/17586

MNT: Compatibility with astropy v7.1

---

CHANGES.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/tests/test_catalogs.py
jdaviz/core/template_mixin.py

add row select method to Table and table mixin to allow selection by row index, indicies, or slice(s). Also adds 'select all' method.

add row select to plugin table

---

CHANGES.rst
docs/imviz/plugins.rst
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/imviz/tests/test_helper.py
notebooks/ImvizDitheredExample.ipynb

This pull request removes `link_type` and `wcs_use_affine` from the user APIs in the orientation plugin (Imviz) for the 4.2 release (deprecated since 4.0).

orientation: remove deprecated link_type, wcs_use_affine

---

CHANGES.rst
jdaviz/configs/default/plugins/data_menu/data_menu.py
jdaviz/core/template_mixin.py

This pull request fixes tracebacks caused by the new data-menu when renaming a viewer (currently only used by downstream lcviz - this fixes broken tests in https://github.com/spacetelescope/lcviz/pull/158 when run locally).

data-menu: handle viewer rename properly

---

CHANGES.rst
jdaviz/configs/default/plugins/data_menu/data_menu.py
jdaviz/core/template_mixin.py

manual backport of PR 3383

---

CHANGES.rst
jdaviz/app.py
jdaviz/app.vue
jdaviz/core/template_mixin.py
jdaviz/main_styles.vue

This pull request implements plugin-tray filtering of plugins by their exposed methods/attributes.  (Note that this also helps expose to us places where we expose args/kwargs that probably shouldn't be exposed and should work to clean those up [:cat:](https://jira.stsci.edu/browse/JDAT-5070))
https://github.com/user-attachments/assets/f670eeba-10cf-473d-923c-3ff944d6998b
Note that currently this filtering still happens when API hints are off (so "Plot Options" still appears for a search of "RGB"), but that could easily be changed if preferred.
This checklist is meant to remind the package maintainer(s) who will review this pull request of …

UI-searchable API methods/attributes

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/sonify_data/sonify_data.py
jdaviz/configs/cubeviz/plugins/sonify_data/sonify_data.vue

This pull request adds a Refresh button which reruns `sounddevices.query_devices()` and updates the output device dropdown.
Fixes #3334 
Enhancements for the cube sonification plugin. [#3387]

Add refresh button which updates sound device list

---

jdaviz/configs/default/plugins/data_quality/tests/test_data_quality.py

The data label has changed from `(DQ: 1)` to `(DQ: 3)`. Since I don't have an older copy of the MAST image that @bmorris3 used to make that test, I am not sure why. The new label seems in line with existing parser logic in that it uses EXTNUM instead of EXTVER to make the label, so not sure why it was 1 before.
Goal is to fix the test so it does not block unrelated PRs. I am not sure if you want me to refactor the DQ parser.
```
Filename: jw01895001004_07101_00001_nrca3_cal.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
0  PRIMARY       1 PrimaryHDU     347   ()
1  SCI           1 ImageHDU       156   (2048, 2048)   float32
2  ERR           1 ImageHDU        10   (2048, 2048)   float32
3  DQ            1 ImageHDU        11   (2048, 2048)   int32 (rescales to uint32)
4 …
```

TST: Update result for test_data_quality_plugin

---

CHANGES.rst
jdaviz/configs/default/plugins/data_menu/data_menu.vue

This pull request is to address the DataMenu being visible after the app has scrolled out of view.

fix: DataMenu keeps scrolling in view after app is out of view

---

CHANGES.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py

Alternative to https://github.com/spacetelescope/jdaviz/pull/3395
Since we only see in test and no one reported bug yet (outside of workshop), probably no need change log.

BUG: source_id is lowercase in Gaia output (sometimes)

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/mixins.py

TPFs in lcviz should be sliceable by their time axes. Somewhere since jdaviz v3.9, a bug was introduced that causes the step size in the lcviz Time Selector plugin to be fixed to integer values. 
https://github.com/user-attachments/assets/2a0cf55a-29e6-4fac-a007-98b57fbbb335
This PR corrects the slice values for cube axes defined by temporal WCS. Here's a demo after this PR:
https://github.com/user-attachments/assets/c215d30a-3b0f-4724-a369-a413b86f0b60
The failing devdeps tests in this PR should be fixed by #3232.
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. …

Bugfix: lcviz TPFs are sliced by cube index rather than time slice

---

jdaviz/core/template_mixin.py

This pull request fixes a bug in plot options `unmix_state` when the value is being changed by unmixing (which as far as I can tell only happens from calls within the RGB presets and only shows as a bug when the original tab selection is the last tab that is iterated during the RGB presets call and so hard to cover with a regression test).

fix unmix state when changing value

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue

This pull request implements several more generalizations/improvements so that spectral extraction can be inherited downstream (in lcviz in https://github.com/spacetelescope/lcviz/pull/115 and possibly in rampviz in the future).
These are very minor changes - would it be unreasonable to consider this for the next bugfix release?  Shouldn't affect jdaviz configs directly, so probably doesn't need a changelog?

more spectral extraction improvements for downstream use

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/model_fitting.py

Fixes a traceback in model fitting by forcing all items in model_fitting._units to be strings. They were previously a mix of unit/string types.
(Note: The nicer fix would be to standardize the output type from app._get_display_unit - it returns a mix of Unit, string, and None types for now. I went down this path but ran into issues and since this is a small ticket, it will need to be addressed in a follow up. When this is done, we can clean up model fitting and other plugins by removing casting to/from Unit/str since we will always know the return type of _get_display_unit. For now, forcing to string fixes the traceback.)

fix json unit error

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue

This pull request adds the missing UI dropdown for input cube selection in cubeviz's spectral extraction.
Currently milestoning as a bug since the API existed, but we should test to make sure that there aren't unintended consequences since elsewhere we do assume only a single INPUT flux cube (but maybe this is safe because it is guaranteed to be the shape).

UI for dataset-selection in cubeviz spectral extraction

---

docs/dev/release.rst

This pull request is to fix numbering in release steps because auto numbering is messed up by formatting, so just hardcode the numbers. Also remove the "old long way" because no one reads that and probably outdated by now.

DOC: Fix release steps numbering, remove old doc

---

CHANGES.rst
docs/imviz/plugins.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/tests/test_catalogs.py

This pull request is to add support for Catalog Search plugin to import table directly from existing Table/QTable object. To do this, we expose a new public API called `import_catalog`.

FEAT: Catalog Search plugin to support import catalog from Table/QTable object

---

CHANGES.rst
jdaviz/configs/imviz/tests/test_simple_aper_phot.py
jdaviz/core/tests/test_tools.py
jdaviz/tests/test_utils.py
pyproject.toml

photutils is at v2.1 now. By bumping the minversion to 1.12.1, we can simplify some tests.

MNT: Bump photutils minversion to 1.12.1

---

CHANGES.rst
jdaviz/app.py
jdaviz/tests/test_subsets.py

This pull request is to address subset linking in specviz2d [:cat:](https://jira.stsci.edu/browse/JDAT-3508).
**Description:**
This update updates LinkSame to LinkSameWithUnits, and appropriate components depending on the spectrum dimensionality is handled so subsets load within the bounds of both viewers, irregardless of which they were created in, nor if additional data items are added to the data collection (eg. via Spectral Extraction Plugin). 
These updates should also ensure that unit handling for subsets is occurring. Unit changes can be seen in the plugin.
Note:
- If using `specviz2d.app.get_subsets(use_display_units=True)` needs the use_display_units argument. 
**Bug Behavior**:
https://github.com/spacetelescope/jdaviz/assets/42986583/84cd834a-6827-460b-adf0-0751f29930af …

adjusting links to enable pixel, wavelength linking in specviz2d

---

jdaviz/core/template_mixin.py

This pull request is a follow-up of unreleased https://github.com/spacetelescope/jdaviz/pull/3384

Remove signature from wrapper in API hints

---

CHANGES.rst
jdaviz/configs/default/plugins/viewers.py

This pull request is to address hiding spectral subset overlays in Cubeviz image-viewers when the slice tool indicator is within the subset bounds of said subset (in the spectrum-viewer).
https://github.com/user-attachments/assets/8c20e5e1-54bf-4d86-a6c3-d1c53fcb6a3c

set spectral subset visibility to false in cube image viewers

---

.github/workflows/standalone.yml

Looks like the Certification import step got skipped, is this because matrix.os is `macos-14` and we're checking for exactly `macos`?

Debugging Mac standalone again...again...again...(echo...)

---

jdaviz/core/unit_conversion_utils.py

Fix JSON serialization error for edge case when spectral axis is in pix unit.
Because the error happen in front-end, unit test for reported failing case will not fail on non-interactive CI so no test is added with this patch.

BUG: Fix JSON serialization error for edge case when spectral axis is in pix unit

---

jdaviz/core/region_translators.py
jdaviz/core/tests/test_region_translators.py

This pull request is to address compatibility with unreleased photutils 2.2.0 as a result of:
* https://github.com/astropy/photutils/pull/2008

MNT: Compat with photutils 2.2.0

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/subset_tools/subset_tools.py
jdaviz/configs/imviz/tests/test_subset_centroid.py
jdaviz/core/helpers.py
jdaviz/tests/test_subsets.py

This pull request cleans up exposed plugin APIs which are meant for internal use only, including:
* replacing `**kwargs` from `subset_tools.import_region(..., **kwargs)` with explicit `region_format=None`.  If there are other kwargs passed to `load_regions` that we want the user to access, we should explicitly add and document those as well.
* ~remove `update=False` in `subset_tools.set_center(..., update=False)` and hardcode to `update=True`.  **IMPORTANT**: this is technically a change in behavior.  Do we need to deprecate or is a changelog entry in a minor release sufficient?  `set_center` was first made public in 4.1 by #3304.~. (see discussion at https://github.com/spacetelescope/jdaviz/pull/3453#discussion_r1962302548)
* remove `models=None` from …

Cleanup plugin apis

---

CHANGES.rst
jdaviz/components/plugin_table.vue
jdaviz/components/tooltip.vue
jdaviz/configs/default/plugins/virtual_observatory/tests/test_vo_imviz.py
jdaviz/configs/default/plugins/virtual_observatory/vo_plugin.py
jdaviz/configs/default/plugins/virtual_observatory/vo_plugin.vue
jdaviz/configs/imviz/plugins/orientation/orientation.py
pyproject.toml

~NOTE: This PR depends on https://github.com/astropy/pyvo/tree/main until it is released with the changes introduced in https://github.com/astropy/pyvo/pull/594~ PyVO 1.5.3 has been released and the pin updated accordingly
This PR introduces a new plugin to query resources and load data products published by collaborators of the International Virtual Observatory Alliance. This Plugin currently queries resources implementing the original 1.0 version of the Simple Image Access protocol by specifying a source and a waveband and loads the selected products into Imviz. Though currently only implemented into Imviz, I placed this plugin into the `default` config in hopes this plugin can be expanded to also work for Specviz via the Simple Spectrum Access Protocol, and Cubeviz as well. …

Virtual Observatory plugin for Jdaviz

---

CHANGES.rst
jdaviz/configs/default/plugins/virtual_observatory/tests/test_vo_imviz.py
jdaviz/configs/default/plugins/virtual_observatory/vo_plugin.py

This is a small PR after discussing with @kecnry architecting the move of the VO plugin to the new Import Data menu. This PR rolls back the plugin API since the VO tool may move from the plugin tray to the new Import Data menu. It seemed easier to just remove the plugin API rather than publishing it and then having to go through the deprecation process before it moves to its new API location.
This also necessitates changing the tests to use the underlying `plugin._obj` rather than the API. It looks like a lot of changes, but it isn't actually; I'll try to detail them here so we can easy CTRL+F and replace later:
- Convert all `vo_plugin` retrieval from the plugin API to the underlying object `vo_plugin = self.imviz.plugins[vo_plugin_label]` > `vo_plugin = …

Remove VO plugin API and revert tests to underlying object

---

CHANGES.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/tests/test_catalogs.py

This was previously matching the filtered list of N pixel coords in the viewer bounds with the first N skycoords, which led to mismatches between the pixel and sky coords for the results. There's a smarter fix here that involves zipping before filtering both at once rather than doing the check in the loop, this was mostly a quick hack to get the code working properly. If we're worried about performance I can figure out the better way to do this, if not we can merge this for now to fix the bug.

Fix incorrect matching of skycoords with pixel coords in catalog results

---

CHANGES.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/tests/test_catalogs.py

This pull request is to address the bug described in https://github.com/spacetelescope/jdaviz/pull/3429#issuecomment-2660006610 . A more robust solution, as proposed here, is to center and set zoom level, instead of forcing min/max, and let glue viewer decide on the min/max based on aspect ratio etc. at the time of the zoom event. Tests are updated to reflect new behavior.
While this fixes a bug, it changes behavior for single point selected, so probably should not backport.
With this patch:
<table>
<tr>
<th>Full image</th><th>Zoom to selected</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
This …

BUG: Fix Catalog Search zoom to selected for multiple sources

---

CHANGES.rst
docs/cubeviz/import_data.rst
docs/imviz/import_data.rst
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_helper.py
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_unit_conversion.py
jdaviz/configs/cubeviz/plugins/tests/test_regions.py
jdaviz/configs/default/plugins/subset_tools/subset_tools.py
jdaviz/configs/imviz/tests/test_linking.py
jdaviz/configs/imviz/tests/test_parser.py
jdaviz/configs/imviz/tests/test_regions.py
jdaviz/configs/imviz/tests/test_simple_aper_phot.py
jdaviz/core/helpers.py
notebooks/CubevizExample.ipynb
notebooks/ImvizDitheredExample.ipynb
notebooks/ImvizExample.ipynb
notebooks/concepts/imviz_roman_asdf.ipynb

This pull request is to address some of subset API. See https://github.com/spacetelescope/jdaviz/issues/3413
Actions items:

subset_tools.import_region should have max_num_regions=20 as default, also deprecate/remove duplicate functionality

---

CHANGES.rst
docs/imviz/plugins.rst
jdaviz/configs/imviz/helper.py

This pull request is to deprecate `imviz.get_catalog_source_results()` in favor of `imviz.plugins['Catalog Search'].export_table()`. Oddly enough I couldn't find any mention of it in tests and notebooks, so not much else to update.
Meanwhile, `app._catalog_source_table` seems to be used throughout Catalog Search plugin itself internally, so I leave that alone for now.
I also moved 2 change log entries from #3388 that were mistakenly put in Bug Fix section instead of API Change.

Deprecate imviz.get_catalog_source_results()

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/cubeviz/plugins/tests/test_regions.py
jdaviz/configs/default/plugins/subset_tools/subset_tools.py
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/imviz/tests/test_linking.py
jdaviz/configs/imviz/tests/test_regions.py
jdaviz/configs/imviz/tests/test_viewers.py
jdaviz/core/helpers.py
jdaviz/tests/test_subsets.py

This PR adds app.delete_subsets. Calling app.delete_subsets() will delete all subsets in the app. You can also specify which subsets labels to delete - if there are two subsets 'Subset 1' and 'Subset 2', delete_subsets('Subset 1') will delete just the first, and delete_subsets(['Subset 1', 'Subset 2']) will delete both (equivalent to  delete_subsets() in this case).
Orientation.delete_subsets now calls this app level method. I did not deprecate this in the Orientation plugin since the ticket did not say to do so, but what does everyone think.
The _delete_regions and _delete_all_regions methods were removed without deprecation since they were never public, and tests calling these now use app.delete_subsets.
Finally, I considered adding a 'delete_regions' method in Subset tools since thats …

add app level delete_subsets method, remove/replace others

---

.github/workflows/standalone.yml

This should make the CI Mac standalone build finally pass. Opening a PR from the STScI base repository to see if the Mac build will run this way.

Specify port for jdaviz in standalone build CI

---

CHANGES.rst
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py

Replace argmax with nanargmax when estimating location for trace based on the brightest pixel. If there are nans in a column, argmax will choose the first location of a nan for the location of the maximum. This fix combined with the next release of specreduce fixes the issue of the default extraction failing and producing a trace at the bottom of the image that can be seen in the specviz2d example notebook.
I verified the change in the test - one sided was being selected before based on the fact that the trace was at the bottom of the image (see lines 415-421 of spectral_extraction.py). I also removed the line setting the trace pixel, this was done because the initial guess was poor. With this change and the new default trace, it should be two-sided.

ignore nans when finding brightest pixel for initial trace guess

---

CHANGES.rst
jdaviz/core/freezable_state.py

This dramatically speeds up interactive operations (zooming/panning) when visualizing large unlinked datasets. The following example includes a (30000,30000) dataset with 23 subsets after the change:
[Screencast from 2025-03-19 13-33-35.webm](https://github.com/user-attachments/assets/2a04e0a5-f464-4030-85c4-808df9445237)
For comparison, this was before:
[Screencast from 2025-03-19 13-39-53.webm](https://github.com/user-attachments/assets/ce606706-c8f9-4639-a2f6-09e030069a5a)
This might not fix performance issues related to when there are datasets linked via WCS, but this at least fixes the biggest bottleneck for single images.
The fix here is to make sure we don't access all pixel values in order to determine the max pixel values. We can get this simply from the data shape.
list the …

Avoid accessing all pixels in a dataset just to determine pixel limits :zap: 

---

pyproject.toml

follow up to [#3503](https://github.com/spacetelescope/jdaviz/pull/3503), need to remove max pin otherwise dev test is installing 1.4.1. this is why spectral extraction tests were not failing when they should be

remove max pin

---

CHANGES.rst
jdaviz/components/layer_viewer_icon_stylized.vue
jdaviz/components/plugin_layer_select_tabs.vue
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/default/plugins/plot_options/plot_options.vue

This implements an outline highlighting the active layer in the plot options plugin. In this example B is selected, but A is the active layer in the viewer:
Right now this is the light theme orange accent color - it wasn't immediately clear to me how to use the defined `accent` color in `main_styles.vue` such that it would be responsive to light vs dark mode, if anyone can point me to an example of that I could make that change (or figure it out myself tomorrow).

Highlight active layer in Plot Options

---

jdaviz/app.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/core/helpers.py
jdaviz/core/marks.py

This pull request is to address removing Unit Conversion's dependency of the profile-viewer. In the following #3473, an instance of loading 2d spectra with solely an BqplotImageView viewer (with what was formerly known as Specviz2d) is now possible and the expected behavior. With removing the profile-viewer on a Jdaviz instance, unit conversion now must be self-sustaining. 

Remove unit conversion's spectrum viewer dependence

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_regions.py
jdaviz/configs/default/plugins/subset_tools/subset_tools.py
jdaviz/configs/default/plugins/subset_tools/tests/test_subset_tools.py
jdaviz/configs/imviz/tests/test_linking.py

This pull request fixes a bug with SkyRegion objects not working with cube data. The problem was that the `import_region` method was not yet equipped to plot SkyRegion objects onto data with WCS dimensions of 3.

Fix bug with SkyRegion not working with cube data

---

CHANGES.rst
docs/imviz/plugins.rst
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/tests/test_footprints.py
jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py
jdaviz/configs/mosviz/plugins/slit_overlay/tests/test_slit_overlay.py
jdaviz/core/region_translators.py
jdaviz/core/tests/test_region_translators.py

This pull request is to address the python implementation of an s_region STC-S string parser in imviz.
MAST communicates polygonal instrument footprints with “s_region” strings, which are a subset of [STC-S regions](https://www.ivoa.net/documents/STC-S/20130917/WD-STC-S-1.0-20130917.html).
In jdaviz, add a parser to footprint_plugin.import_region to take STC-S strings as input to create and import astropy regions as a Footprint in the Footprints plugin.

implement python s_region parser in imviz

---

jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
pyproject.toml

This pull request is to fix remote data failure. Also ignores a DeprecationWarning I see from solara upstream.
Out of scope: That failure about marks in devdeps.
Normal CI should be green with this PR. devdeps will still fail but with only 1 failure.

TST: Fix remote data, ignore solara DeprecationWarning

---

CHANGES.rst
jdaviz/configs/specviz/tests/test_viewers.py
jdaviz/core/freezable_state.py

This pull request ensure viewer limits will reset when spectral units are converted by overriding glue's `_convert_units_x_limits`.
**Bug Behavior:**
https://github.com/user-attachments/assets/340b3335-4929-4ae2-9052-afa420115185
**Updated Behavior:**
https://github.com/user-attachments/assets/15e1c6b7-389a-4f4c-ad64-50fe76cc1902

override glue's _convert_units_x_limits

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_export_plots.py
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/export/tests/test_export.py
jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py
jdaviz/configs/default/plugins/line_lists/line_lists.py
jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/configs/specviz/specviz.yaml
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/core/template_mixin.py
jdaviz/core/tests/test_template_mixin.py

This pull request sets the default relevance for all specviz + specviz2d plugins so that they only appear when the necessary data/viewers are present.
This also fixes a "bug" where the stretch histogram was showing in the export plugin for configs that do not contain stretch options (could be backported separately, if anyone would prefer).
This attempts to keep behavior unchanged for plugins that used to show a disabled message - we could consider either turning off this logic entirely for configs OR applying relevance to those cases as well - reviewers please let me know what you think.
The only plugins that currently show in the deconfigged app before adding any viewers or data are:
* Subset Tools (could argue this shouldn't show, but we currently don't listen to data or viewers, so …

deconfigged: set_relevant for all plugins

---

CHANGES.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/tests/test_catalogs.py
jdaviz/core/template_mixin.py

This pull request is to not keep internal columns from being exported in Catalog Search plugin.

Catalog Search: Keep original columns from file only

---

CHANGES.rst
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/plugins/catalogs/catalogs.vue
jdaviz/configs/imviz/tests/test_catalogs.py

This PR exposes the user API for the catalog search plugin. You will see in some of the tests that plugin.table._obj is being accessed - these are for table attributes that aren't public, that would belong in a follow up imo.

Expose catalog search api

---

jdaviz/configs/default/plugins/subset_tools/subset_tools.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/core/region_translators.py
jdaviz/core/template_mixin.py

This PR removes the function get_region_from_spatial_subset and replaces it with calls to get_subsets. The previous behavior of returning pixel/sky subsets in imviz based on alignment type, and always pixel regions in cubeviz is maintained.

remove _get_region_from_spatial_subset

---

CHANGES.rst
docs/imviz/displayimages.rst
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/imviz/plugins/parsers.py
jdaviz/configs/imviz/tests/test_astrowidgets_api.py
jdaviz/configs/imviz/tests/test_delete_data.py
jdaviz/configs/imviz/tests/test_linking.py
jdaviz/configs/imviz/tests/test_parser.py
jdaviz/configs/imviz/tests/utils.py
jdaviz/configs/imviz/wcs_utils.py
jdaviz/core/freezable_state.py
jdaviz/utils.py

Since #2179, Imviz displays images in the sky plane without distortion by creating a glue reference data layer that contains only coordinates (no image). The WCS-only layer was has its coordinates defined by a GWCS object. I chose GWCS over FITS WCS because it seemed to me at the time that encoding reference frame rotation in FITS WCS was nontrivial. Since then, I noticed that longitudinal pole rotation is supported by low level WCS.
1. The API for creating low level WCS is very very stable, whereas GWCS is evolving to support Roman. This lowers the risk of imviz maintenance burden on our end.
2. Low level WCS computes transformations in C, which will be as fast or faster than GWCS.
When we think about "linking performance", what we're usually talking about is limiting the number of links …

change imviz reference data coords from GWCS to FITS WCS

---

CHANGES.rst
jdaviz/configs/default/plugins/data_quality/tests/test_data_quality.py
jdaviz/core/tests/test_autoconfig.py
jdaviz/core/tests/test_config_detection.py
jdaviz/tests/test_utils.py
notebooks/CubevizExample.ipynb
notebooks/SpecvizExample.ipynb

jw02732-o004_t004_miri_ch1-shortmediumlong_s3d.fits > jw02732-o004_t004_miri_ch1-short_s3d.fits 
jw02732-o004_t004_miri_ch1-shortmediumlong_s3d.fits > jw02732-o004_t004_miri_ch1-short_s3d.fits
also fixes an issue with accessing by data label in the cubeviz notebook, that needs to be addressed further (see JDAT-5293)

fix remote data failures

---

CHANGES.rst
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py

In 4.2.1, deleting a 2d spectrum from the entire app results in a traceback.  This was inadvertently addressed in main via in #3473, so this PR just backports the relevant 2 lines necessary, but gives a separate changelog.

backport: fix deleting 2d spectrum from specviz2d

---

CHANGES.rst
jdaviz/components/toolbar_nested.py
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/tests/test_footprints.py
jdaviz/core/events.py
jdaviz/core/tools.py

This PR is a temporary solution for controlling the visibility of the FootprintSelect tool. The long-term idea is to have a shared selection tool that can handle different workflows across plugins, depending on what's active.
Until we have that framework in place, this tool will only show up when there are overlay footprints on the image viewer. This helps keep the toolbar cleaner and avoids showing tools that aren’t useful in the current context.
https://github.com/user-attachments/assets/2ab0b96c-ab0b-4b35-af72-72cf66189d68
This checklist is meant to remind the package maintainer(s) who will review this pull request …

Show FootprintSelect tool only when overlays exist

---

CHANGES.rst
jdaviz/app.py
jdaviz/app.vue
jdaviz/core/helpers.py
jdaviz/core/loaders/importers/importer.py
jdaviz/core/loaders/importers/spectrum2d/spectrum2d.py
jdaviz/core/loaders/parsers/fits.py
jdaviz/core/template_mixin.py
jdaviz/core/user_api.py

This pull request implements additional flexibility into the loaders framework that is necessary for downstream use by lcviz via https://github.com/spacetelescope/lcviz/pull/187, including:
* failing gracefully if standardizing metadata fails
* enable lcviz (alongside "deconfigged", "specviz", and "specviz2d") to use loaders by default
* allow lcviz to use fits parser (needed for DVT importer)
* allow importers to provide list of viewer classes to ignore when attempting to load data - allowing them to give a different viewer (to potentially create) as priority over other viewers that might support loading the data.  For lcviz, TPF data _can_ be loaded into the light curve viewer, but should not be by default, and instead we want the importer to automatically create an image/cube viewer if …

loaders: lcviz support

---

CHANGES.rst
jdaviz/configs/default/plugins/markers/markers.py
jdaviz/configs/imviz/plugins/coords_info/coords_info.py
jdaviz/configs/imviz/plugins/viewers.py

Follow up to #3483 to address comments by @pllim in https://github.com/spacetelescope/jdaviz/pull/3483#pullrequestreview-2730199866
Closes #3534
This PR enables mouseover world coordinate info in imviz on images with GWCS, even outside the bounding box, when linked by WCS. If the cursor is outside of the bounding box for the selected image layer, the coord info is taken from the reference data layer, which will be defined with FITS WCS as of #3483. No pixel coordinates are shown if the cursor is outside of the bounding box for an image with GWCS.
In the image below, the cursor is where the red "X" sits, which is on the top image layer:
When the cursor is outside the bounds of the top image layer, the world coordinates are shown in gray, without pixel info:
The same is true if you hover …

for images with GWCS, show world coords on mouseover outside of bounding box using refdata 

---

CHANGES.rst
jdaviz/app.py
jdaviz/configs/default/plugins/subset_tools/subset_tools.py
jdaviz/configs/default/plugins/subset_tools/tests/test_subset_tools.py
jdaviz/tests/test_subsets.py

This PR fixes a bug for composite subsets applied with remove/andnot when wcs linked, which previously were not returning the sky region through app.get_subsets or subset_tools.get_regions. Unskipped a test already written for this case, and modified a few existing tests to also test returning sky regions. (as a bonus I also added valid combination modes to the docstring of import_region, because i noticed this was unclear while i was investigating this bug)

fix andNot subset bug

---

jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py

There are several test failures in spectral extraction that this PR fixes. The first was a result of 2d/1d viewer marks accidentally being added to both viewers. There were a few failures resulting from new syntax to access to marks attributes that changed when PluginMarkCollection was implemented.

fix test failures in spectral extraction

---

jdaviz/core/template_mixin.py

Reverts spacetelescope/jdaviz#3562
Looks like the logging issues were from upstream: https://github.com/spacetelescope/roman_datamodels/pull/506

Revert "temp fix: auto_label python 3.11"

---

jdaviz/__init__.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/specviz2d/tests/test_parsers.py
jdaviz/core/loaders/importers/spectrum2d/spectrum2d.py
jdaviz/core/loaders/resolvers/resolver.py
jdaviz/core/loaders/resolvers/url/url.py
jdaviz/core/template_mixin.py

This PR allows the spectrum 2d importer to accept `mast:HLSP/jades/dr3/goods-n/spectra/clear-prism/goods-n-mediumhst/hlsp_jades_jwst_nirspec_goods-n-mediumhst-00000804_clear-prism_v1.0_s2d.fits` as a valid input (despite not matching the other checks) and ensures future coverage with a regression test.
In doing so, this PR also (reviewers: feel free to request these in separate PRs if you'd rather, they are just small things I ran into while fixing this that helped track down the cause/solution):
* implements a few additional debugging capabilities
* strips any whitespaces from an input URL
* exposes top-level access to `get_data`
* allows `DatasetSelect` to define a default `cls` to pass to internal `get_data` calls, which then fixes support for loading these same data files into the …

loader support for HLSP 2D spectrum

---

CHANGES.rst
jdaviz/app.py
jdaviz/app.vue

Manual backport of #3551 (changelog and one-line conflict in app.py)

Manual backport of PR #3551

---

CHANGES.rst
jdaviz/configs/imviz/tests/test_astrowidgets_api.py
jdaviz/core/astrowidgets_api.py

This pull request is to address when data's GWCS uses Lon/Lat. A condition existed for adding markers in Imviz that was written before the Orientation plugin was implemented. This PR adjusts this condition to be more accepting when Lat/Lon are in the component ids of the original data/data entry created on orientation change for catalog marks. 

adjust component_id condition for catalog markers

---

CHANGES.rst
jdaviz/core/loaders/resolvers/resolver.py
jdaviz/core/loaders/test_loaders.py

This pull request improves the error when passing a URL to `.load(...)` which does not result in any object passed to the parsers.  This also skip attempting to the the "URL drop" resolver when called `.load(...)` (but is still available from `.loaders` and the UI)
For example, `jd.load('mast:invalid')` now gives:
```
ValueError: ('no valid loaders found for input, tried', {'file': 'not valid', 'url': "resolver exception: Failed query for URI 'mast:invalid' at '[https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:invalid':\n\nHTTPError](https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:invalid%27:\n\nHTTPError): 400 Client Error: Bad Request for url: https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:invalid", 'object': 'not valid'})
```
instead of:
```
ValueError: ('no valid …
```

loaders: improved URL resolver error

---

CHANGES.rst
jdaviz/core/loaders/resolvers/resolver.py
jdaviz/core/loaders/test_loaders.py

Manual backport of #3580 (conflicts in changelog and `resolver.py`)

Manual backport of PR 3580

---

notebooks/CubevizExample.ipynb
notebooks/SpecvizExample.ipynb

I missed these when I updated the links in the remote data tests.

Update data URI in Cubeviz and Specviz example notebooks

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
jdaviz/configs/imviz/tests/test_simple_aper_phot.py

Exposes the Aperture Photometry public API. Updates tests and class docstring accordingly. There are no calls to aperture photometry in example notebooks, so no updates are needed there. Added API hints.

expose aperture photometry api

---

CHANGES.rst
jdaviz/configs/default/plugins/viewers.py

While debugging cubeviz performance issues, I noticed that sometimes there are ciruclar calls to _on_layers_update - that is, if an update to any of the layers is made inside the method it will then call _on_layers_update again.
Avoiding this speeds things up by a factor of 2x when 10 subsets are present.

Avoid circular calls to _on_layers_update

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_regions.py
jdaviz/configs/cubeviz/plugins/viewers.py

While I don't understand the motivations behind this, it seems the cubeviz profile viewer doesn't actually use glue subsets and instead uses extracted datasets and pretends they are subsets. However, because of the way glue works, all subsets that are defined automatically get added to all datasets, and if a dataset is in a viewer, subsets will get added automatically. This means that if one had a cube loaded in cubeviz and had extracted say 10 subsets, there would be 11 datasets in the cubeviz profile viewer plus 110 subsets. The subsets were all set to be not visible, but having them in the viewer still slows things down a lot as they still all have a layer artist and state instantiated in case the visibility changes.
The simple fix is to simply not accept any subsets in the cubeviz …

Don't add actual subsets to CubevizProfileView

---

CHANGES.rst
jdaviz/configs/imviz/wcs_utils.py

This fixes a corner case in ``compute_scale`` when the fiducial coordinates provided are outside of the bounding box.
This is needed if the bounding box on data is not reset, and in order to be compatible with https://github.com/spacetelescope/gwcs/pull/498
cc @bmorris3 

Fix compute_scale when fiducial coordinates are outside bounding box

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/sonify_data/sonify_data.py

Manual Backport of #3647 
* add successful sonified data snackbar message
* update change log, styling
* use results label in messasge
(cherry picked from commit 8973df4b47bf948ebe6075ab4f0f08623269e445)

add successful sonified data snackbar message (#3647)

---

CHANGES.rst
jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py
jdaviz/configs/imviz/tests/test_line_profile_xy.py

This PR fixes an issue when line profiles in imviz when WCS linked, when the zoom limits fall outside of the gwcs bounding box, and adds a test for this case.
Fixes #3641

fix get_zoom_limits when wcs linked and out of image bounds

---

CHANGES.rst
jdaviz/configs/imviz/tests/test_wcs_utils.py
jdaviz/configs/imviz/wcs_utils.py

This resolves an issue in which computing the inverse of a WCS (which is done in wcs.in_image) requires removing input units if the forward transform does not use units.

fix gwcs units issue

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/sonify_data/sonify_data.py

* Added an observer to avoid a vue error (that checks for an existing label) since relabeling cannot be done 'simultaneously' with the sonification being added to the viewer. If the relabeling is done after sonification, the vue error disappears but this is not ideal.
* If the label is updated just before sonificiation (instead of with the observer), then there is a risk of confusing the user.
This pull request is to address updating the default output label provided the user upon sonification.
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not …

Auto-update default sonification label

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
jdaviz/core/template_mixin.py

This pull request is to address a bug in deconfigged model fitting where the plugin attempted to access a spectral subset, but was unable to.

fix deconf model fitting when spectral subset is referenced

---

CHANGES.rst
jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/export/export.vue
jdaviz/configs/default/plugins/export/tests/test_export.py

This pull request is to address API behavior that raised an error message and
automatically reverted bad subset formats to an allowed default format. 
* In the UI, a vue message is displayed while also raising an error (necessary for users
working solely in code). 
* The export button is also now disabled when a bad format
is selected.
Fixes [JDAT-5374](https://jira.stsci.edu/browse/JDAT-5374)

Disable subset export formats

---

jdaviz/configs/default/plugins/model_fitting/fitting_backend.py

This is no longer used anywhere, I assume because of changes with unit handling. Just a little code cleanup.

Remove unused function from model fitting

---

CHANGES.rst
docs/cubeviz/export_data.rst
docs/cubeviz/plugins.rst
docs/specviz2d/plugins.rst
jdaviz/app.py
jdaviz/configs/cubeviz/cubeviz.yaml
jdaviz/configs/cubeviz/helper.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_parsers.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/specviz2d/specviz2d.yaml
jdaviz/configs/specviz2d/tests/test_parsers.py
jdaviz/core/helpers.py
jdaviz/core/loaders/importers/spectrum2d/spectrum2d.py
jdaviz/core/loaders/test_loaders.py
jdaviz/core/template_mixin.py
jdaviz/tests/test_app.py
notebooks/Specviz2dExample.ipynb

To allow the deconfigged app to start using the new names without conflict, cubeviz Spectral Extraction is now 'Spectral Extraction 3D', and specviz2d Spectral Extraction is now 'Spectral Extraction 2D'. Access by the former name is still possible for now, with a deprecation message. Docs and notebooks updated.

rename and deprecate Spectral Extraction plugins in specviz2d and cubeviz

---

.github/workflows/cache-download.yml
.github/workflows/ci_workflows.yml
.github/workflows/publish.yml
jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/cubeviz/plugins/tests/test_export_plots.py
jdaviz/configs/default/plugins/data_quality/tests/test_data_quality.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
jdaviz/configs/specviz2d/tests/test_parsers.py
jdaviz/conftest.py
jdaviz/core/loaders/test_loaders.py
jdaviz/core/tests/test_autoconfig.py
jdaviz/core/tests/test_config_detection.py
jdaviz/tests/test_utils.py
jdaviz/utils.py

This PR updates the CI workflow to make use of the caches implemented in #3689 by moving the cache to the top-level directory of the tox working directory, removing references to hardcoded local paths from the tests, and having tests call `cached_uri` to pass just the filename to `load`/`load_data` if it is found in the cache in the working directory and otherwise pass through the full URI.  This PR also fixes the weekly scheduled run in #3689 to default to the same set of URIs as when manually triggered.
Before #3689, remote/slow tests often took 2 hours and still failed due to timeouts.
Now they take ~45 mins, including with slow tests enabled.
Note that this PR does skip one remote test which is now failing - it likely slipped through the cracks among the remote data failures so should …

TST: CI updates to use cache

---

CHANGES.rst
jdaviz/configs/default/plugins/data_menu/data_menu.vue

This pull request fixes the API hint in viewer data-menus to use the viewer reference instead of viewer ID.

fix API hint in data-menu to access viewer

---

CHANGES.rst
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py

This fixes a bug when importing array traces, which must go through loaders instead of spectral_extraction.import_trace. 
The issue is related to unit conversion, in the method that handles when data is added to the viewer. A quick fix for this is to just skip this when the data being added is a trace, because the defaults and dropdown items should be set when non-trace data is added to the viewer. I think that refactoring this code in Unit Conversion at some point is necessary. I started to do that for this ticket on another branch but decided to just get in the quick fix for now.

Fix importing array trace

---

CHANGES.rst
jdaviz/configs/default/plugins/data_menu/data_menu.vue

This PR is a manual backport of PR #3695 (conflicts with `config` vs `api_hints_obj` and sonification added to the visibility switch addressed)

Manual backport of PR 3695

---

.github/workflows/ci_workflows.yml

This PR implements CI-workflow support for a `continue-on-error` PR label which disables stopping workflows when another fails.  This is useful if you want to run CI on devdeps or remote data while other workflows have known failures, etc.
This can be seen in action in #3698 (I'll remove that commit from there if/when this is merged).

continue-on-error PR label support

---

CHANGES.rst
jdaviz/configs/imviz/helper.py
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/imviz/plugins/orientation/orientation.vue
jdaviz/configs/imviz/plugins/parsers.py
jdaviz/configs/imviz/tests/test_parser.py
jdaviz/core/helpers.py
jdaviz/core/loaders/importers/image/image.py
jdaviz/core/loaders/importers/image/image.vue
jdaviz/core/loaders/test_loaders.py
jdaviz/utils.py

This PR removes the toggle to enable FITS SIP approximation from the Orientation plugin and adds it to the image loader. 
To use the gwcs_to_fits_sip option from the API, 'gwcs_to_fits_sip' is now a keyword argument in imviz.load_data (previously it was advertised in the docstring of load_data, but obtained from kwargs). Within load_data it as added to kwargs to pass to the parser.
I did not deprecate this in the Orientation plugin because it was not in 4.3.2.
I also fixed a few instances where _roman_asdf_2d_to_glue_data was being called but not being passed the gwcs_to_fits_sip argument (I'm not sure this was intentional in the first place, if it was I will revert this change).

add gwcs sip switch to image loader, remove from orientation plugin

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/tests/test_export_plots.py
jdaviz/configs/default/plugins/export/export.py

Fixes getting an incorrect value for the default slice maximum as well as a bug where the movie was always starting from the current slice rather than the specified slice and returning to an incorrect slice after the movie.

Fix export movie in cubeviz

---

jdaviz/configs/specviz2d/tests/test_parsers.py

This pull request adds test coverage to ensure that the extraction of a 2d spectrum in pixel space is successful.

Test coverage for 2d spectral extraction of uncal spectrum

---

CHANGES.rst
jdaviz/configs/imviz/helper.py
jdaviz/configs/imviz/plugins/orientation/orientation.py
notebooks/ImvizExample.ipynb
notebooks/Specviz2dExample.ipynb
notebooks/SpecvizExample.ipynb

This pull request enables user-access to `imviz.load` and deprecates `imviz.load_data` to match what has been done for specviz and specviz 2d now that `load_data` relies entirely on `load` in #3662.

enable imviz.load, deprecate load_data

---

jdaviz/configs/default/plugins/export/export.py
jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py
jdaviz/configs/default/plugins/line_lists/line_lists.py
jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/plot_options/plot_options.py
jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
jdaviz/configs/imviz/plugins/catalogs/catalogs.py
jdaviz/configs/imviz/plugins/compass/compass.py
jdaviz/configs/imviz/plugins/footprints/footprints.py
jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
jdaviz/conftest.py
jdaviz/core/template_mixin.py
jdaviz/core/tests/test_template_mixin.py

This pull request is to address the use of a repeated structure, `set_relevant`, in plugins. The code to do so has been generalized and is now housed in `template_mixins.py`. Those that couldn't be neatly generalized were left in. 

Add relevancy check code to PluginMixin

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py

Fixes an issue where model components created in model fitting were not correctly using the spectral y unit when cube fit was not selected. 
This also fixes an issue where temporarily on load the unit conversion spectral_y_unit traitlet and the real spectrum y axis units are temporarily out of sync when data is being loaded. this was preventing reliable access to the spectrum y axis unit through the unit conversion plugin.

use spectral y unit for non cube fit model fitting component  

---

CHANGES.rst
jdaviz/configs/default/plugins/data_menu/data_menu.py
jdaviz/configs/default/plugins/subset_tools/tests/test_subset_tools.py
jdaviz/configs/default/plugins/viewers.py
jdaviz/core/template_mixin.py

This pull request modifies existing glue-validator logic to resolve subset visibility issues in spectrum-viewer data menu, while maintaining the same plot option functionality.
https://github.com/user-attachments/assets/ea97d7e4-5d16-4445-b9af-0fe2cbcc272d

re-enabling spectral subset visibility from data menu

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py

This pull request is to address restricting the value of polynomial order in model fitting to >= 0 to avoid a traceback for negative numbers. 0 and 1 are redundant with constant and linear but for convenience, we (currently) allow those values.

Forbid polynomial order < 0

---

jdaviz/core/tests/test_template_mixin.py
jdaviz/tests/test_user_api.py
jdaviz/tests/test_utils.py
jdaviz/utils.py

This pull request is to address a bug in wildcard matching in which '?' and other wildcards weren't checked for
and therefore errored out. I have since realized an issue without our implementation which is that brackets are
used as UNIX wildcards but we also use brackets to denote image extension. I have therefore removed the ability
for our code to check for brackets, escaping any brackets on the premise that they're meant for image extensions. 
I have also added some tests and updated the old tests to be a bit more comprehensive. 
This checklist is meant to remind the package maintainer(s) who will review this pull …

Fix wildcard bug and update test

---

CHANGES.rst
jdaviz/core/loaders/importers/importer.py
jdaviz/core/template_mixin.py
jdaviz/core/user_api.py
jdaviz/tests/test_user_api.py

This pull request adds user API convenience setting to the `ViewerSelectCreateNew` component introduced in #3739 (not yet released).  The main motivation for this is to allow access via the kwarg from `.load()`, for example: `jd.load(..., viewer=[])` to be equivalent to the previous `show_in_viewer=False` but also `jd.load(..., viewer='my-new-viewer')` to create a new viewer.  See added test coverage for details.
This also fixes the case where the import button was disabled when a viewer already existed as it was considering the empty `new_label` as invalid even if `create_new` was off.
This checklist is meant to remind the package …

User API tweaks for viewer select create new

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py

Before this PR, if the mask was None as returned by the ``NDData``'s ``.mask`` attribute, ``np.logical_or`` was returning object arrays:
```
In [2]: np.logical_or(None, np.array([1, 0, 1], dtype=bool))
Out[2]: array([True, False, True], dtype=object)
```
Object arrays are very memory and CPU inefficient. This PR avoids this by only doing a logical OR if the original mask is not None. This speeds up the initial loading of large cubes into cubeviz by a factor of 3x on my machine (I tested this for a 3.4GB cube).
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This …

Avoid making object arrays for mask in cubeviz to speed up loading large cubes

---

CHANGES.rst
jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py

This improves the memory usage of cubeviz a bit when using large cubes. Before this change, the casting to float would cause an array to be created that would be as big as the original data, but in fact this casting is unecessary, numpy deals fine with it as a boolean even when used in e.g. multiplications. This shaved off 10-20% of memory usage in my case.

Avoid unecessary float conversion in mask

---

CHANGES.rst
jdaviz/configs/specviz/tests/test_helper.py
jdaviz/core/helpers.py
jdaviz/core/loaders/importers/importer.py
jdaviz/core/loaders/importers/spectrum_list/spectrum_list.py
jdaviz/core/loaders/importers/spectrum_list/test_spectrum_list.py
jdaviz/core/template_mixin.py
jdaviz/tests/test_user_api.py
jdaviz/tests/test_utils.py

Previously, the spectrum list loader would default to using no selection to allow the user to 
choose the sources they wished to import. This led to scenarios where the viewer would be blank
and this was deemed confusing. We now default to loading in the first source and notify the user
via snackbar *and* warning (just in case they don't have the viewer open) that we will be doing so
and advise on how to load more. 

Spectrum list default to using first source

---

CHANGES.rst
jdaviz/configs/default/plugins/model_fitting/model_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py

This PR makes a few changes to improve how nonfinite data in flux is handled by the model fitting plugin, and adds test coverage for a simple case of a flux array with NaNs as well as a partially overlapping subset, which was a case mentioned in the ticket.

Fix handling of nonfinite data in model fitting

---

CHANGES.rst
jdaviz/core/loaders/importers/spectrum2d/spectrum2d.py
jdaviz/core/loaders/tests/test_loaders.py

This catches the case where the FITS WCS has a `spectral` attribute, but it's empty, as is the case for the new JWST WFSS* BSUB** files. We don't actually handle real WFSS spectral extraction, this just enables a simple preview in pixel space.
* wide field slitless spectroscopy
**  "background subtracted", this is an intermediate pipeline step that is being made available

Allow loading new BSUB file in Specviz2D

---

jdaviz/app.py
jdaviz/configs/imviz/plugins/orientation/orientation.py
jdaviz/configs/imviz/tests/test_viewers.py
jdaviz/conftest.py

This PR implements linking for source catalogs when loaded into an image viewer, when WCS linked (because source catalogs must have RA and Dec only, this will change once pixel coordinate columns are supported). The catalog is linked to the orientation layer via Component Links because a 2D WCS can not be assigned directly to the glue data table object.
This PR changes a test fixture as well to have better source positions, and modifies the test that uses it to not use manual linking anymore and now loads the catalog into the viewer when it is initially loaded into the data collection, rather than waiting for manual links to be set up and then adding it from the data menu.

Automatic (wcs) linking for source catalogs
