spacetelescope/jdaviz

examples/cubeviz-example.ipynb
=> cleanup cubeviz notebook

examples/cubeviz-example.ipynb
This is a pretty simple thing that just updates the cubeviz example to auto-download (with a pretty progress bar if `tqdm` is installed...) the manga example dataset.
=> add incantation to auto-download the data cube

.gitignore, setup.cfg, web/package.json, web/yarn.lock
Example notebooks are now compatible and runnable with latest package releases.
=> Update installation dependencies

README.rst, jdaviz/cli.py, jdaviz/configs/cubeviz/cubeviz.ipynb, jdaviz/configs/default/default.ipynb, setup.cfg
With this, we can do:
```
jdaviz your_favorite_fits_file.fits
```
and it will start up voila with that data pre-loaded. We can then do:
```
jdaviz your_favorite_fits_file.fits --layout=cubeviz
```
to load a non-default layout. It would be easy to add other commands, e.g. cubeviz, that default to the cubeviz layout.
=> Added jdaviz command-line tool

jdaviz/cli.py
This is a workaround for https://github.com/glue-viz/bqplot-image-gl/issues/20 which I haven't been able to fix yet.
=> Set enable_nbextensions to True for Voila

jdaviz/configs/specviz/specviz.yaml
Tiny change, does what the title says
=> Updated specviz config file to include tray plugins

README.rst, docs/index.rst
Addresses https://github.com/spacetelescope/jdaviz/issues/75
=> Add a bit more detail in intro docs

jdaviz/app.vue, jdaviz/configs/default/plugins/collapse/collapse.vue, jdaviz/configs/default/plugins/data_tools/data_tools.vue, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue
Resolves #147 and #136. Uses the theming setup in Vuetify to apply a consistent color scheme to the application.
=> Implement default vuetify color theme

jdaviz/app.py
Fixes an issue introduced in the follow-up commits in #159.
=> Fix region extraction

README.rst
Added language to the README making it clear that the project is being actively developed
=> Updated README with expanded introductory section

jdaviz/app.py, jdaviz/configs/specviz/helper.py, notebooks/Minimal Specviz.ipynb
Includes example of how to retrieve spectral region objects from subsets. Depends on #161.
=> Specviz minimal notebook

jdaviz/container.vue
Resolves #143.
Closed:
Opened:
=> Update viewer toolbar icons

.gitignore, docs/dev/infrastructure.rst
These docs are a starting point describing the Jdaviz theory (as I understand it) regarding regions, subsets, etc. This started with a conversation I had with @eteq when introducing the specviz helper methods `get_spectra` along with @nmearl's `get_spectral_regions`. This is meant to serve as the beginning of a longer documentation discussion about these points (i.e. what is a spectral region, what is a subset, what are we abstracting and what are we presenting?)
=> Jdaviz Subset Theory Docs

README.rst
Updates the README file to also include:
=> Add badges to repo landing page

jdaviz/configs/cubeviz/cubeviz.yaml, jdaviz/configs/cubeviz/plugins/__init__.py, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, notebooks/Example.ipynb
Still in progress, but creating the draft PR to demo the SubsetCreateMessage subscription bug. To see that behavior, uncomment lines 41 and 42 of moment_maps.py.
=> Implement moment map plugin

docs/installation.rst
This PR updates the `jdaviz` python package installation documentation and expands the section on running jdaviz.
=> Installation Documentation

jdaviz/app.py, jdaviz/app.vue, jdaviz/container.vue
This is working for the spectrum viewer, but I'm creating the PR as draft for now because the image viewers results in only the axes showing up in the saved images. I'm working on coming up with a fix for that.
=> Save viewer figure to PNG or SVG

jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, notebooks/concepts/Specviz Unit Conversion.ipynb
=> Specviz uc bug fix

jdaviz/configs/default/plugins/model_fitting/model_fitting.py
Now actually fixes the specified parameters when model fitting.
=> Fix "fixed" parameter option in model fitting

jdaviz/configs/specviz/plugins/viewers.py, notebooks/Minimal Specviz.ipynb
This is blocked by glue-viz/glue-astronomy#19. 
The Specviz notebook exercises the functionality.
=> Add plotting of uncertainties and masks

jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/collapse/tests/test_collapse.py
=> Add missing stat (Sum) to collapse plugin

docs/index.rst, docs/known_bugs.rst
This replaces already approved PR #291 with a clean (I hope) version that should build clean.
=> Add known bugs docs

docs/installation.rst
Minor update to the install instructions to clarify what's github vs release.
=> update install instructions to reflect released version

jdaviz/configs/default/plugins/line_lists/line_list_mixin.py, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/specviz/plugins/viewers.py
Fixes a couple bugs with loading preset line lists from the notebook. I'm hoping to have this included in 1.0.2
=> Linelist bugfix

jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
Leaving as a draft for now since I'm still trying to fix the uncertainty conversion going between wavelength and frequency space.
=> Fix error with variance uncertainties, fix looping bug on initial conversion

docs/known_bugs.rst
This adds #305 to the list of known issues
=> add mention of vispy install issue

docs/dev/release.rst
=> MNT: Replace pep517 with python-build

jdaviz/configs/default/plugins/model_fitting/fitting_backend.py
=> Remove extra unit multiplication in fitting backend

docs/specviz/notebook.rst
This PR includes some small documentation detailing how to use SpecViz in a notebook. Most of the API calls are included with the rest of the documentation, so this is comparatively short. I've just included how to extract the data out of specviz, which is the only notebook *only* feature that I'm aware of that wouldn't be documented elsewhere in the other feature-specific documentation.
=> Specviz Notebook Documentation

docs/cubeviz/displaycubes.rst, docs/cubeviz/displayspectra.rst, docs/mosviz/displayspectra.rst, docs/specviz/displaying.rst
Hopefully this will all be replaced soon, but in case a user sees it in the meantime this text is a little better.
=> Change the placeholder text to be more user-oriented.

README.rst
I removed the warning about being unstable since we released 1.0. 
I also reworded the second paragraph of the intro, I'm not attached to that update so feel free to reject that change in favor of the original.
=> Remove pre-1.0 wording, rephrase part of intro

docs/cubeviz/displayspectra.rst
Added documentation to Cubeviz:Displaying Spectra
=> Updated Cubeviz Displaying Spectra

.travis.yml
Fixes the currently failing windows travis job.
ref: https://jira.stsci.edu/browse/JDAT-1053
=> Use choco to install windows on Travis CI

docs/cubeviz/displaycubes.rst
=> Fill in Cubeviz Pan/Zoom and Spectral Region sections

share/jupyter/nbconvert/templates/jdaviz-default/ansi.js, share/jupyter/nbconvert/templates/jdaviz-default/app.html, share/jupyter/nbconvert/templates/jdaviz-default/index.html.j2, share/jupyter/nbconvert/templates/jdaviz-default/util.js, share/jupyter/voila/templates/jdaviz-default/index.html.j2
Add ?debug to the URL to enable this feature. A bug icon will
appear in the bottom right-hand corner when an error occurs or
when there is output to stdout or stderr. Clicking the icon opens
the log.
=> feat: show errors, stdout and stderr in the frontend

.bandit.yaml, .github/workflows/ci_workflows.yml, .readthedocs.yml, docs/conf.py, jdaviz/app.py, setup.cfg, tox.ini
~If you enable PR builder for RTD, we can test this. Otherwise, we won't know till merge.~
PR builder enabled -- See status check below.
Also removing `build_docs` from CI because it is not necessary once RTD PR builder is enabled.
=> DOC: Update RTD config

jdaviz/configs/specviz/helper.py
=> Fix specviz autoscale_x method with redshift

.github/workflows/ci_workflows.yml, README.rst, docs/conf.py, docs/dev/release.rst, notebooks/concepts/Mosviz concept notebook.ipynb
To go with the default branch name change that just happened.
=> MNT: Rename master to main

setup.cfg
Title is self explanatory. This would unblock #355, which has been languishing in review for a while.
=> Pin to development version of specutils until specutils 1.2 release

docs/dev/release.rst, tox.ini
You appear to be using GitHub Actions.
=> MNT: Remove remaining references to Travis CI

jdaviz/configs/specviz/helper.py
Fixes #454 (assuming the POs agree with my assumptions there).
=> Fix handling of redshift setting in output of specviz.get_spectra

docs/dev/release.rst
=> DOC: Fix broken link

setup.cfg
Erik released specutils two days ago.
=> MNT: Pin specutils to stable minversion

docs/cubeviz/notebook.rst
=> Add cubeviz docs for exporting data

docs/mosviz/notebook.rst
Resolves #466 
Relies on #481 and #468 being merged.
=> Add docs for mosviz data exporting

docs/cubeviz/plugins.rst, docs/specviz/plugins.rst
=> Add docs for model extraction

CHANGES.rst, setup.cfg
Updated the changelog, reserving the right to make other updates here if needed.
=> Book keeping for 1.1 release

docs/known_bugs.rst
Document the bug mentioned in #490
=> Add scikit issue to known bugs docs

docs/cubeviz/displayspectra.rst, docs/mosviz/displayspectra.rst
I think it makes sense to put this information in this location, but I'm open to other suggestions.
=> Add documentation of Specviz property in Cubeviz/Mosviz

setup.cfg
=> MNT: Minversion of glupyter is now 0.3

setup.cfg
Fixes https://github.com/spacetelescope/jdaviz/issues/534
=> Specify minimum bqplot version to include pan/zoom fix

.github/workflows/ci_workflows.yml, tox.ini
This was part of #476 that specifically deals with expanding the dev version of packages that we test with. Should also test for PRs.
=> TST: Add more deps to devdeps, and devdeps to PR

jdaviz/configs/default/plugins/collapse/collapse.vue
=> Fix field label typo in Collapse plugin

tox.ini
See if adding this line fixes coverage report.
=> TST: Generate coverage in tox

jdaviz/cli.py, share/jupyter/nbconvert/templates/jdaviz-default/app.html, share/jupyter/nbconvert/templates/jdaviz-default/index.html.j2
Fixes the dark mode not being activated in #669.
Fix #415
=> feat: support Voila dark theme (--theme=dark)

notebooks/MosvizExample.ipynb
I find the existing example notebook hard to understand or use, so I tried to clean it up here for my own sanity in case I have to use it again for review in the future.
=> DOC: Clean up Mosviz example notebook

setup.cfg
=> MNT: Change jwst maxversion to minversion

jdaviz/configs/specviz/plugins/redshift_slider/tests/test_redshift_slider.py
Add some tests for a particular part of the redshift slider.
=> Add tests for the redshift slider

jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, notebooks/ImvizExample.ipynb
Follow up of #687 
Fix #705 
Similar to astropy/astrowidgets#140 but we don't have to deprecate anything here because Imviz is not yet released.
=> Imviz: Replace offset_to with offset_by

jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
I think there is a missing `</v-row>`.
=> BUG: unclosed v-row

notebooks/MosvizExample.ipynb
Add some brief comments about how to add cutouts to mosviz if they exist in a "cutouts" directory.
=> Add information about adding cutouts in notebook

jdaviz/configs/imviz/plugins/tools.py
Based on Imviz Hack Hour feedback. This goes with glue-viz/glue-jupyter#245
=> Clarify tooltip for WCS panzoom tool

jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py
Fix #704 .
I realize that I need this fix to profile for #564 , so quick turnaround to get this merged would make my life easier. Thanks!
=> BUG: Fix Imviz center/offset bounds check

.github/PULL_REQUEST_TEMPLATE.md
Modeled after https://github.com/astropy/astropy/blob/main/.github/PULL_REQUEST_TEMPLATE.md but points to https://github.com/spacetelescope/style-guides instead of Astropy standards.
My first draft is only best guess based on my short time in Indigo. Feel free to suggest changes. Thanks!
=> MNT: Add PR review check list

jdaviz/app.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/mosviz/tests/test_helper.py, notebooks/MosvizExample.ipynb
Enables users to input a single image filename string (and optionally a single associated label) to the Mosviz `load_data()` method that will be associated with all spectra in a list of input spectra. Also sets a couple currently-unused attributes (e.g. `_shared_image` in the table viewer) that will be useful later for addressing #739. Can be tested with the updated MosvizExample notebook, which now passes in the single cutout image instead of duplicating it into a list in the notebook before calling `load_data`.
Closes #740 
=> Enable multiple spectra to share the same image without data duplication

.github/CODEOWNERS
This pull request is to add new devs to the code owners listing.
=> MNT: Update code owners list

jdaviz/configs/imviz/plugins/tools.py
Trivial change to add information to a tool hover text, to clarify what it actually does.
=> Clarify Imviz tooltip

jdaviz/configs/imviz/plugins/tools.py
This pull request is to change contrast/bias mouse event math to use display coordinates/dimensions instead of data. This new math is resistant to zooming in/out of the data, and purely relies on position of mouse on the available display.
Fixes #774 
Follow-up of #553 and #516 .
=> BUG: Fix Imviz contrast/bias math

jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/tests/test_parser.py
This pull request is to still show the data but without sky coordinates when Glue fails to understand a particular GWCS. In this case, an uncalibrated grism image.
=> Imviz: Do not crash on bad GWCS

jdaviz/configs/imviz/plugins/viewers.py
This also removes the border from the exported image.
Fixes #793
=> fix: remove border around imviz image

jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/configs/imviz/tests/utils.py, notebooks/ImvizExample.ipynb
This pull request is to implement these astrowidgets API:
* Fix #716 
* Fix #717 
* Fix #718
xref #632 
=> Imviz astrowidgets API MVP triple-play: stretch, cuts, colormap

jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py
This pull request is to clarify the non-zero option of `share_image` for other developers.
Fixes #772
Direct follow-up of #757
=> DOC: Clarify share_image in Mosviz parser

docs/installation.rst, docs/known_bugs.rst
Update known issues and better organize the page. Also link to it from installation doc.
Fixes https://jira.stsci.edu/browse/JDAT-1662
Rendered doc preview at https://jdaviz--780.org.readthedocs.build/en/780/index.html
=> DOC: Update known issues, etc

notebooks/concepts/generate_mosviz_photometry.ipynb
I made some updates to the synthetic image creation notebook after a presentation. It no longer requires VPN access and the paths should work on Windows systems now.
=> Updated synthetic image creation notebook

jdaviz/configs/mosviz/helper.py, notebooks/MosvizNIRISSExample.ipynb
This pull request fixes some bugs that appeared after all of today's merges. There is still one bug that @rosteen may need to take a look at (feel free to commit to this PR) where the images do not appear in `MosvizExample.ipynb` when selecting new rows.
=> Mosviz hotfix

jdaviz/app.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/mosviz/tests/test_helper.py
This pull request is to clear Application's dirty state when data loading fails.
The original fix was at #830 and only for Mosviz but @havok2063 said it might be beneficial to just do this for all the viz.
Fixes #364
=> BUG: Clean app state after crash (Mosviz)

jdaviz/app.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py
Don't overwhelm users with a million success messages (e.g. for every 1D/2D spectrum and image in Mosviz). @pllim I tried not to touch the image parser in Mosviz for now pending #783  😁.
Fixes #714 .
=> Reduce amount of success messages sent to users

jdaviz/configs/specviz/plugins/parsers.py, jdaviz/configs/specviz/tests/test_helper.py
Intended to address #822. Depends on https://github.com/astropy/specutils/pull/856 for loading the most recent JWST multi-extension data files. I tested with the following files from @havok2063's folder:
- jw00721-o023_t008_nircam_f444w-grismr-subgrism256_x1dints.fits
- jw00787-o014_s00033_niriss_f150w-gr150c-gr150r_x1d.fits
- jw00787-o014_s00015_niriss_f150w-gr150c-gr150r_c1d.fits
I'm also planning to add batch linking a la Mosviz now that #762 is merged.
=> Update specviz parser to handle SpectrumList input

notebooks/concepts/imviz_color_display.ipynb
This pull request is to add a proof-of-concept notebook detailing how to generate a color display in Imviz given a RGB input (e.g., JPEG). This notebook is by no means ready for end-users as it contains too many calls into the underlying objects. However, it can be used as a reference if we want to pursue color display feature in the future.
Input file: 
Screenshot of Imviz from this patch:
=> POC: Imviz with RGB color display

docs/cubeviz/import_data.rst, docs/cubeviz/notebook.rst, docs/index.rst, docs/notebook/export_data.rst, docs/notebook/import_data.rst, docs/notebook/index.rst, docs/notebook/save_state.rst, docs/specviz/notebook.rst, docs/specviz/plugins.rst
New documentation specific to working in a Notebook.  I wanted to pull out a lot of information that is currently buried or non-existent into one place.  That means there is a little redundancy.  I don't mind that for the time being.  If these changes look correct, we can worry about how to consolidate all the information and potentially reorganize in the future.
EDIT: Rendered doc at https://jdaviz--832.org.readthedocs.build/en/832/index.html
EDIT: Fix #839
=> notebook related documentation

jdaviz/configs/default/plugins/collapse/collapse.vue
=> Fix label on field in collapse plugin

CHANGES.rst
This pull request is to prepare the change log for next release by doing the following:
* Fix existing formatting.
* Fix year typo of last release.
* Propose major version bump in accordance to https://semver.org/ (negotiable).
* Since we have not been updating it, I added vague entries for this next release. Though going forward, we need to be stricter about making sure PR authors add change log in their PRs (if applicable).
=> DOC: Preparing change log for next release

jdaviz/configs/imviz/helper.py
This pull request is to clarify success message, as @PatrickOgle suggested during review of #735 .
=> Imviz: Clarify relinking success message

jdaviz/configs/mosviz/mosviz.yaml
This pull request fixes the height of Mosviz in the notebook so that the bottom part of the UI (that changes the page) can be accessed.
=> Fix mosviz notebook height

docs/dev/release.rst
This pull request is to make release more exciting, for better or worse. This is a direct follow-up of #469 .
=> DOC: Release doc for the adventurous

jdaviz/core/events.py
It appears these message classes are not used anywhere in the code.
Discovered in #872.
=> Remove unused message classes

notebooks/ImvizExample.ipynb, notebooks/concepts/Cube_fit.ipynb, notebooks/concepts/Data interactions through CubeViz.ipynb, notebooks/concepts/Example cubeviz spectral and spatial interactions.ipynb, notebooks/concepts/Example_fitting.ipynb, notebooks/concepts/Specviz from splot concept notebook.ipynb, notebooks/concepts/concept_programmatic_viewers_from_blank_default.ipynb
=> Fix typos in notebooks

docs/imviz/notebook.rst, docs/reference/api.rst, jdaviz/app.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/imviz.yaml, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/test_regions.py, jdaviz/configs/imviz/tests/utils.py, jdaviz/core/astrowidgets_api.py, jdaviz/tests/test_viewer_ids.py, notebooks/ImvizExample.ipynb, notebooks/concepts/imviz_color_display.ipynb
This pull request is to refactor astrowidgets API to:
* fix #741
* fix #754 
TODO:
=> Refactor astrowidgets API

jdaviz/app.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/specviz/helper.py
This pull request is to use absolute import. There is no need for relative import as we no longer have to worry about Python 2.
I left the init files alone. The imports in tests are being handled at #876 .
=> MNT: Use absolute import

jdaviz/configs/mosviz/mosviz.yaml
Remove the Unit Conversion plugin from Mosviz until we figure out some Mosviz-specific implementation details. Se #884 for details of the followup work.
=> Remove unit conversion plugin from Mosviz for now

jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_data_retrieval.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/default/plugins/collapse/tests/test_collapse.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/tests/test_helper.py, jdaviz/configs/specviz/plugins/redshift_slider/tests/test_redshift_slider.py, jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py, jdaviz/configs/specviz/tests/test_helper.py, setup.cfg
This pull request is to be more explicit in test warnings handling. Any unhandled warning will now fail the CI. This will prevent us from not catching new warnings until it is too late.
Out of scope: *Fixing* existing warnings. In the future, if you want to really dig at why that warning happens, remove it from the ignore list in `setup.cfg`.
Fixes #478 
=> TST: Be more explicit in ignoring pytest warnings

docs/mosviz/plugins.rst
=> Remove defunct section from Mosviz docs, clean up spacing

CHANGES.rst, MANIFEST.in, docs/conf.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/imviz/tests/test_regions.py, setup.cfg
This pull request is to:
* Move regions and scikit-image to required dependencies.
* Finalize change log for the release.
* Minor doc improvements.
=> MNT: 2.0 release prep

.github/CODEOWNERS
This pull request is to add @kecnry to codeowners list so he gets pinged for PR reviews.
=> MNT: Add Kyle to codeowners

docs/dev/links.rst, docs/dev/release.rst, docs/dev/ui_description.rst
This pull request is to fix the linkcheck cron job that has been failing at https://github.com/spacetelescope/jdaviz/actions/workflows/ci_cron_weekly.yml . I have no idea who has been getting/ignoring those email notifications. This patch makes it pass locally, but we'll find out for sure next scheduled run.
=> DOC: Fix linkcheck

README.rst, docs/dev/release.rst
This pull request is to add links to Zenodo DOI that is now available since jdaviz 2.0 release.
https://zenodo.org/badge/latestdoi/185452341
Fixes #732
=> DOC: Add Zenodo DOI

CHANGES.rst, docs/dev/release.rst
This pull request is to introduce new way to organizing the change log going forward. This is modeled after [astropy change log](https://raw.githubusercontent.com/astropy/astropy/main/CHANGES.rst). While `astropy` uses `towncrier` now, the rendered change log still remains the same. I don't think we need `towncrier` (yet), so we can write the change log by hand.
If you want to enforce a check, we can also try deploying [action-check_astropy_changelog](https://github.com/pllim/action-check_astropy_changelog) here, but that requires consistent usage of PR milestone, which we are currently not doing.
Pro: Saner change log at release time. Release manager cries less.
Con: One more thing for PR reviewer to check at the PR stage.
This checklist is meant to remind the package maintainer(s) who …
=> DOC: New change log format

CHANGES.rst, jdaviz/app.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/imviz.yaml, jdaviz/configs/imviz/tests/test_viewers.py, notebooks/ImvizExample.ipynb
This pull request is to implement feature request to be able to programmatically create image viewers in Imviz. While I am at it, might as well have API to destroy the created viewers, so there is balance in the world.
Fixes #882 
=> Imviz: API to create and destroy viewers

CHANGES.rst, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_regions.py
This pull request is to better handle unsupported shapes in `imviz.get_interactive_regions()`.
Out of scope: Actually support the weird shapes. For that, see glue-viz/glue-astronomy#49 (for annulus).
Fix #898 
=> Imviz: get_interactive_regions() to handle weird shapes better

CHANGES.rst, docs/reference/api.rst, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/imviz.yaml, jdaviz/configs/imviz/plugins/__init__.py, jdaviz/configs/imviz/plugins/links_control/__init__.py, jdaviz/configs/imviz/plugins/links_control/links_control.py, jdaviz/configs/imviz/plugins/links_control/links_control.vue, jdaviz/configs/imviz/plugins/parsers.py
I thought it would be nice to have *something* for the upcoming demo using "standalone app" even though we might change up the GUI later.
~Currently there is an error I don't understand. Maybe someone with JS experience can help me.~ (Doh, typo fixed.)
Fix #833
=> Plugin to control Imviz linking

CHANGES.rst, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/specviz2d/plugins/parsers.py, notebooks/Specviz2dExample.ipynb
As said in the title. Loads data if "WAVEND" and "WAVESTART" header extensions are not present by using pixel values. There is a more accurate solution that @havok2063 mentioned [here](https://github.com/spacetelescope/jdaviz/issues/532#issuecomment-830210418) but that requires using `jwst` as a dependency, which might require some discussion.
Fixes #532 
=> Add specviz2d example notebook and load miri s2d files

jdaviz/components/tooltip.vue, jdaviz/configs/imviz/plugins/image_viewer_creator/image_viewer_creator.vue
This pull request fixes the vertical positioning of the new image viewer button in Imviz and adds a tooltip (text not yet reviewed - feel free to suggest changes).
Fixes #941 (note that the plugin icon on the right was fixed in #940 when changed to hamburger)
=> fix layout and add tooltip to new image viewer button

setup.cfg
I didn't really want to claim this, but I figure we should have this email set to someone who still works here.
=> Update email in setup.cfg

jdaviz/app.py, jdaviz/app.vue, jdaviz/components/play_pause_widget.vue, jdaviz/components/tooltip.vue, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/mosviz/tests/test_helper.py, jdaviz/container.vue
This pull request implements an API for select_row/next_row/previous_row on the table-viewer as well as up and down arrows and a play/pause button in the table toolbar.  ~~The UI/UX is not yet reviewed/finalized, but currently looks like:~~
**Paused**:
**Playing**:
with the following alternative to consider for the "active" play state:
Changing the delay time (in seconds) while playing immediately updates on the next iteration (although the change using the up/down buttons in the number select is not applied until clicking away - this is a vue internal design and does allow scrolling without a ton of internal updates).
Before ready for review:
Future Considerations:
* Do we want to keep the arrow buttons? 
* Do we want to continue to pursue keyboard-bindings?
This checklist is meant to …
=> Mosviz: table row select/scroll

jdaviz/app.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/specviz/helper.py, jdaviz/configs/specviz/tests/test_helper.py
This pull request is to address the problem where running `viz.get_spectral_regions()` when there are noncontiguous subset regions fails. Regions within a subset are now returned and renamed "Subset 1_5306" where 5306 is the starting value of that particular region of the subset.
Fixes #356 
=> Fix error for noncontiguous subset regions

setup.cfg
=> Bump specutils pin to new release

jdaviz/app.vue, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/mosviz.yaml, jdaviz/configs/mosviz/plugins/__init__.py, jdaviz/configs/mosviz/plugins/row_lock/row_lock.py, jdaviz/configs/mosviz/plugins/row_lock/row_lock.vue, jdaviz/core/events.py
This pull request refactors the work in #918 to be in a plugin in order to:
* remove logic from app.vue and place in individual files instead,
* allow enabling/disabling the lock button as well as defining its position in the toolbar from the yaml config file,
* remove the need to store the locked state in a nested dictionary which is difficult to mutate.  The button now communicates with the mosviz helper through a Message event.
This is necessary now in order to properly position the redshift slider on the same toolbar without major alignment issues, but is also just a cleaner implementation for future maintenance, etc.
=> refactor mosviz row lock to be plugin

jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/tests/test_source_identifier_extract.py, jdaviz/configs/mosviz/tests/test_source_name_extract.py
This PR addresses the original request of updating our Mosviz Generic Metadata parser to attempt to use the SOURCEID header value, with the additional stretch goal of unifying the NIRISS Source Name extraction logic with the generic parser's
=> Mos: Genercize SourceID logic

docs/notebook/import_data.rst
This pull request adds documentation on how to import custom line lists using an Astropy QTable
=> Add Custom Line List Import API Docs

CHANGES.rst, jdaviz/configs/specviz/plugins/viewers.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/core/helpers.py
This pull request sets the default thickness for new subsets ~(currently from the **xrange tool ONLY**)~ to be 3px so they are more visible.
**BEFORE:**
**AFTER:**
**TODO**:
=> spectrum-viewer: override default thickness for new subset

setup.cfg
=> Revert to release version of glue-astronomy to make PyPi happy

CHANGES.rst
Last release step.
Edit: The most boring possible option for #1000
=> Put changelog back in unreleased state

docs/dev/release.rst
This pull request is to add milestone bookkeeping to release procedures, as requested by @rosteen .
=> DOC: Add milestone bookkeeping

jdaviz/app.vue, jdaviz/configs/default/plugins/data_tools/data_tools.vue
This pull request updates the colors of the app-wide toolbar and import button (in consultation with Jenn) so that the import button no longer has the same color as the active state of buttons (orange).
**BEFORE**
**AFTER**
=> update colors of top toolbar and import button

CHANGES.rst
A small release with some improvements in case we end up doing a AAS demo/workshop virtually.
=> Prep changelog for 2.2.0 release

jdaviz/configs/imviz/tests/test_parser.py, jdaviz/conftest.py, setup.cfg
This pull request is to remove soon to be deprecated code; also see astropy/astropy#12633 .
=> MNT: Do not use enable_deprecations_as_exceptions, fix CI

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
This pull request ensures that model names are valid and will not cause issues within the equations (by containing operators, etc).  This is done in python by validating and raising an error, and in JS by stripping non-valid characters when the element loses focus (tab or clicking away).  Alternatively, this could be done with rules (showing red text for an invalid entry), but that would require intervention by the user (but also gives a chance to explain the reason).
**NOTE**: failing CI seems unrelated but probably should be fixed before merge.
https://user-images.githubusercontent.com/877591/147768549-ba0bfd01-6cd6-4a15-ac2f-58e94c527300.mov
Fixes #1002
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This …
=> Model component name sanitization/validation

docs/index.rst
This PR adds `Imviz` to the main docs page and also adds reference links to the configs.
=> Add Imviz description to main docs page

CHANGES.rst, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/tests/test_viewers.py
This pull request is to let `mastviz` use Imviz.
Fixes #1037
=> BUG: Let mastviz use Imviz

CHANGES.rst, jdaviz/configs/specviz/specviz.ipynb
This pull request fixes the corrupted specviz notebook (introduced in #913).
Fixes #1043 
=> Fix voila specviz launch notebook

jdaviz/configs/mosviz/helper.py, jdaviz/configs/specviz2d/helper.py
This pull request updates the docstring for mosviz and specviz2d `load_data` methods to be consistent with the current state of the API.
=> update load_data docstring for mosviz/specviz2d

setup.cfg
This pull request is to officially acknowledge matplotlib as a required dependency. It has been since #183 .
https://github.com/spacetelescope/jdaviz/blob/85614cdabd33427b34844f864a8ba5b56be06649/jdaviz/configs/specviz/plugins/viewers.py#L15
=> MNT: Officially list matplotlib as dependency

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/app.py, jdaviz/configs/imviz/imviz.yaml, jdaviz/configs/imviz/plugins/__init__.py, jdaviz/configs/imviz/plugins/compass/__init__.py, jdaviz/configs/imviz/plugins/compass/compass.py, jdaviz/configs/imviz/plugins/compass/compass.vue, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_wcs_utils.py, jdaviz/configs/imviz/wcs_utils.py, jdaviz/core/events.py, licenses/GINGA_LICENSE.txt, notebooks/ImvizExample.ipynb, notebooks/concepts/imviz_compass_mpl.ipynb
This pull request is to implement a compass for Imviz.
Basically, the viewer needs a way to access `imviz.app` instance so it can grab the Compass plugin instance. Until these PRs are accepted and we update the `setup.cfg` pins, CI will fail (it passed locally with these two branches installed).
* #1051 
* #1054 
**or**
* ~Maybe wait for [tool registry for viewers](https://jira.stsci.edu/browse/JDAT-2015)?~
- ???
- Profit!!!
[🐱](https://jira.stsci.edu/browse/JDAT-1982)
=> Imviz compass

jdaviz/app.vue
See: https://github.com/jupyter-widgets/ipywidgets/issues/2499
Alternative to #1071, but more generic. This also replaces:
ea276722263d6e84e8b154729b1ec33bd593695d
Fixes #1067 #1008 (copied from  #1071)
=> fix: workaround for wrong CSS in lab

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/line_lists.vue, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, jdaviz/core/validunits.py
This pull implements a dropdown with choices for the units of custom lines in the line list plugin, making use of shared code with the unit conversion plugin (moving some of the code from that class into `jdaviz.core`.
* defaults to the units in the viewer
* excludes units that no one would ever want to use for the spectral axis (light years, AU, etc)
=> Line List Plugin: unit choices for custom lines

jdaviz/app.vue, setup.cfg
Bump bqplot minversion to 0.12.33 to get:
* bqplot/bqplot#1465
=> MNT: Bump bqplot minversion to 0.12.33

jdaviz/app.py, jdaviz/tests/test_app.py, jdaviz/tests/test_viewer_ids.py
This pull request is to formally implement the `app.get_tray_item_from_name()` documented in #1065 , as @kecnry suggested. This method should only be used for developers, so I don't think we need a user-facing changelog.
=> Add app.get_tray_item_from_name() method for developers

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_lists.py
This pull request is to address bug mentioned in https://github.com/spacetelescope/jdaviz/pull/1073#issuecomment-1039163982 . I don't see any existing test for custom line that I can just attach a test to, so maybe this screenshot is enough?
[🐱](https://jira.stsci.edu/browse/JDAT-2103)
=> BUG: Allow custom line list in Hz

setup.cfg
This pull request is to unpin maxversion of `idna`. Pinning maxversion is never a good idea and maybe it is not even a problem anymore.
Fixes #1075 
=> MNT: Unpin maxversion of idna

CHANGES.rst, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
This pull request is to pull out the moment fix from #1040 into its own PR.
=> BUG: Fix transposed moment result

setup.cfg
until we can figure out #1117
I might just YOLO this one so it does not block unrelated PRs.
=> MNT: Pin maxversion of glue-jupyter

notebooks/concepts/pypi_metrics.ipynb
This notebook allows us to us the `pypistats` api to track metrics of jdaviz downloads, including date of download, python version, and operating system.
Box link for jdaviz metrics: https://stsci.app.box.com/folder/157063321174
=> Add concept notebook to track jdaviz pypi metrics

jdaviz/configs/imviz/plugins/parsers.py
This pull request is to address a small oversight from #1056 .
=> MNT: Remove unused code from Imviz parser

jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
This pull request is to fix a documentation bug for Imviz simple aperture photometry plugin. I thought it would use Sphinx ref name but turns out it parses from the actual section text.
https://jdaviz.readthedocs.io/en/latest/imviz/plugins.html#simple-aperture-photometry
=> Fix simple aperture photometry j-docs-link URL

jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
This pull request is to address the fact that the color of plot points confuses users who expect the color to correlate to the color of the subset they are representing. This PR changes the color to magenta, which works well in light and dark mode.
Fixes #1131 
=> Change simple photometry plot color to magenta

setup.cfg
This pull request fixes the issue in https://github.com/spacetelescope/jdaviz/pull/1013#issuecomment-1021350256 by bumping the bqplot version to include https://github.com/glue-viz/bqplot-image-gl/pull/86.
=> bump bqplot version to fix slice indicator drag event

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_list_mixin.py, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py, jdaviz/configs/specviz/plugins/viewers.py
This pull request removes support for setting per-line or per-linelist redshifts.  Redshifts are currently only supported app-wide.
=> Disable support for per-line/list redshift

docs/mosviz/redshift.rst, notebooks/MosvizNIRISSExample.ipynb
This pull request adds mosviz table/redshift manipulation to the `MosvizNIRISSExample.ipynb` notebook along with a pointer in `mosviz/redshift.rst`.
=> DOCS: mosviz table/redshift manipulation

tox.ini
development branch for now until we can use its master branch again.
This pull request is to temporarily test against bqplot 0.12.x development branch because we cannot test against its master branch yet. 
xref: https://github.com/spacetelescope/jdaviz/issues/955#issuecomment-1068138662
=> TST: Test against bqplot 0.12.x

notebooks/CubevizExample.ipynb
Just a simple `Mosviz -> Cubeviz` typo fix in the notebook narrative. Should be uncontroversial.
=> Cubeviz: Fix notebook typo

.github/PULL_REQUEST_TEMPLATE.md
Just a small update to the pull request template, since we are using milestones more generally now.
=> Update pull request checklist entry

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/app.py, jdaviz/configs/default/plugins/viewers.py, jdaviz/configs/imviz/imviz.yaml, jdaviz/configs/imviz/plugins/__init__.py, jdaviz/configs/imviz/plugins/line_profile_xy/__init__.py, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.vue, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_line_profile_xy.py, notebooks/concepts/imviz_line_profiles.ipynb
User wants to see line plots across X and Y in Imviz. This is a proof-of-concept using key binding and existing plugin machinery.
=> Imviz line profile plots

setup.cfg
Workaround voila-dashboards/voila#1126 so our CI can run.
=> MNT: Pin maxversion of Jinja2 until voila catches up

setup.cfg
Maybe it is the package data?
Fixes #1196 
=> MNT: Fix package data definition

MANIFEST.in, setup.cfg
This pull request is to clean up manifest for packaging. I need to check that the sdist and wheel generated from this actually works.
=> MNT: Clean package manifest

CHANGES.rst, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/tests/test_helper.py
=> Split out subset update handling in line analysis

.github/CODEOWNERS
This pull request is to remove Ivo from code owners listing since he is done with this project.
🌴 😎 🍹 
=> MNT: Update code owners

CHANGES.rst, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py
This pull request exposes uncertainties (where available) in the line analysis plugin (centroid will require https://github.com/astropy/specutils/pull/938, line flux already exists, but is hidden if nan/inf).
=> line-analysis: expose uncertainties when provided

CHANGES.rst, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue
This pull request fixes the logic for the visibility of the switch and dropdown options for plotting the output from gaussian smooth depending on whether its spectral or spatial.
Fixes #1215
=> fix gaussian smooth "plot in viewer" visibility logic

jdaviz/cli.py
I accidentally removed `\f` back in #856 because I didn't know `click` relies on it to truncate text to show in `--help`.
=> BUG: Fix --help text

setup.cfg
This pull request ignores the imageio deprecation warning:
```
DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning dissapear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
```
=> pytest ignore imageio deprecation warning

CHANGES.rst, jdaviz/app.py, jdaviz/app.vue, jdaviz/components/tooltip.vue
This pull request adds a button in the app-level toolbar to open the docs in a new browser tab for the current config.
TODO before ready to review:
=> docs help button in toolbar

README.rst, docs/index.rst, docs/quickstart.rst, docs/sample_notebooks.rst
=> new docs readme, quickstart, sample_notebook

docs/sample_notebooks.rst
This pull request fixes the mis-aligned indentation in the "sample notebooks" page in the docs introduced in #1231.
=> DOC: minor formatting tweak to sample notebooks

docs/quickstart.rst
This pull request links to the same MaNGA data cube in the quickstart as in the cubeviz example notebook.  The previous one lacks uncertainty or mask data in the viewers.
=> DOC: quickstart data cube

docs/cubeviz/import_data.rst
This pull request is to add a section to readthedocs explaining to users how to create a Spectrum1d cube from scratch and then add it to cubeviz from within a jupyter notebook instance.
=> Add section to docs for creating data for cubeviz

CHANGES.rst, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py
This pull request converts the output quantities from line analysis so that it:
* combines all length units by converting all to the first found length unit with a power of 1
* strips any constants in the unit into the value
Before and after screenshots:
<div>
</div>
=> line analysis: coerce units in results

jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
This pull request aims to help guide the user to creating model components before attempting to fit the model.  It does so by:
* hiding the rest of plugin until/unless model components exist.  This should help make it clear to the user that components must be added before progressing further.
* showing an invalid message in the equation input and deactivating the "fit" button if the equation is empty.
=> model fitting: require model components to be created

CHANGES.rst
=> Preparing release 2.5.0

docs/dev/index.rst, docs/dev/ui_plugin_components.rst, jdaviz/core/template_mixin.py
This pull request adds developer docs for plugin components.
=> DOC: developer docs for plugin components

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py, jdaviz/configs/imviz/tests/test_simple_aper_phot.py, jdaviz/utils.py
This pull request is to implement annulus background calculation for Simple Aperture Photometry plugin.
| Manual | Annulus | Subset |
| --- | --- | --- |
| ![Screenshot 2022-03-31 170632](https://user-images.githubusercontent.com/2090236/161151947-2981b428-b0d2-4a9f-8b93-d342c6d391bb.png) | ![Screenshot 2022-03-31 170557](https://user-images.githubusercontent.com/2090236/161151945-04ac80a3-8bd3-49b1-b134-abb4ee83d6d6.png) | ![Screenshot 2022-03-31 170651](https://user-images.githubusercontent.com/2090236/161151948-ebd7da01-606a-4541-8903-6090fdd86757.png) |
Also see #1050
=> Imviz: Annulus background for photometry

jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py
This pull request is to add unit test coverage of the line analysis plugin.
Close #1279
=> Line analysis tests

jdaviz/app.vue
This pull request attempts to address feedback from users that did not realize that the hamburger button in the top right controlled the plugin sidebar by visually tying the sidebar (once opened from a "plot options" button in a viewer toolbar or if we have it opened on load by default in the future) to the button.  This also removes white border between toolbar and content and adds a slight margin to toolbar so they align
**Before**
**After**
=> tie sidebar to orange hamburger button

setup.cfg
Fixes not being able to toggle the visibility of layers in the spectrum viewer.
=> Bump bqplot-image-gl version to get bug fixes

docs/cubeviz/import_data.rst
This pull request clarifies what WCS information needs to be present in order for data to be loaded into cubeviz.
=> Add WCS information to cubeviz docs

docs/installation.rst
This pull request mentions our python requirement and that pip may not find jdaviz if using an older version of python.  It also _suggests_ using a virtual or conda environment (but doesn't provide step-by-step instructions since users may have preferences).
=> DOC: python requirements in install instructions

jdaviz/app.vue, jdaviz/configs/default/plugins/line_lists/line_lists.vue, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue
This pull request improves theming in dark mode for the line selection icons in line lists and line analysis plugins.
Before and after screenshots:
<div>
</div>
<div>
</div>
<div>
</div>
=> line selection: improve dark theme support

docs/cubeviz/plugins.rst, docs/specviz/plugins.rst
This pull request updates the model fitting plugin in the docs to fix a broken link and to update the text for recent UI updates to the plugin (changed names of buttons, labels, etc).
=> DOC: model fitting updates

.github/workflows/ci_cron_weekly.yml, .github/workflows/ci_workflows.yml, .github/workflows/codeql-analysis.yml, .github/workflows/open_actions.yml, .github/workflows/publish.yml
This pull request is to bump GitHub Actions workflow versions, where applicable.
=> TST: Update workflow versions

.github/workflows/changelog_check.yml, .github/workflows/ci_workflows.yml, .github/workflows/publish.yml
This pull request adds the ability for GitHub Actions to cancel duplicate CI builds.
=> TST: Cancel duplicate CI builds

docs/conf.py, docs/cubeviz/index.rst, docs/imviz/index.rst, docs/mosviz/index.rst, docs/quickstart.rst, docs/sample_notebooks.rst, docs/specviz/index.rst
This pull request adds support in our sphinx build to point to release-versioned GH notebooks, and links to the example notebooks for each of the respective viztools in a new quickstart section (along with a link to download the sample data and a snippet of how to launch in the standalone voila app).
=> DOC: release-versioned links to GH notebooks

setup.cfg
The 1.4.8 release of `bqplot-image-gl` is broken, let's not use it for now 😅 
Close #1309
=> Pin to last working version of bqplot-image-gl

setup.cfg
This pull request is to bump minversion of `bqplot-image-gl` to 1.4.9 so we pick up upstream fixes.
Close #1177 
=> MNT: Bump minversion of bqplot-image-gl

.readthedocs.yml
RTD has changed their way to specify Python version. We are using the same thing in `astropy`, so should be uncontroversial.
=> DOC: Update RTD env

jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
This pull request increases test coverage of the model fit plugin. Looks like we already have tests for the actual fitting itself, so this PR mainly addressed the functionality of the plugin itself (selecting model parameters, adding models, etc.)
I was able to get the plugin to 80% coverage (as per our goal); there were a few more tests I wish I had the time to write, but due to interrupts this sprint, I couldn't find that time...
=> Improve test coverage of model fit plugin

setup.cfg
This pull request is to change how we ignore the imageio warning. The way we ignore stopped working after [imageio v2.19.2](https://github.com/imageio/imageio/releases/tag/v2.19.2) release last night.
Eventually, this will be undone by #1254 . Also see #1248 .
=> TST: Ignore same imageio warning in a different way

setup.cfg
This pull request is to bump minversion of voila to include voila-dashboards/voila#1127 so we can undo #1193 .
Fixes #1194
=> MNT: Bump voila minversion

tox.ini
This pull request is in response to https://github.com/nedbat/coveragepy/issues/1310#issuecomment-1027521713 and a follow-up of #1052 .
Update: It works but only have one run. Some people reported transient timeouts upstream, so we should wait and see.
=> TST: Unpin coverage and see if 6.4 works

docs/imviz/import_data.rst
This pull request is to clarify datamodels support in Imviz.
Dev job is going to fail and it is unrelated to this PR.
Fixes #1348 
=> DOC: Of Imviz and datamodels

jdaviz/configs/cubeviz/plugins/tools.py
This pull request is to follow-up on https://github.com/spacetelescope/jdaviz/pull/1317#discussion_r883790064 . It is an unreleased feature, so no need for change log; also no changes that user can see.
I thought we need to add a new option to `add_data` but turns out the option is already there. Also, a tiny refactoring to update the metadata all at once.
=> Cubeviz: Use add_data API for spaxel spectrum

jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, setup.cfg
This pull request is in response to https://github.com/astropy/specutils/pull/946 .
Fixes #1338 
=> MNT: Future-proof spectrum redshift setter

docs/cubeviz/index.rst, docs/imviz/index.rst, docs/mosviz/index.rst, docs/specviz/index.rst
This PR adds animated gifs to the documentation landing pages of each of the configurations (no Specviz2D, since there's no docs for that). These are the same videos I'm using as part of my AAS poster. I prioritized quality over space to get them looking crisp and clear (I did have to spend some time manually editing my Imviz gif to fit it under the 100MB space limit for GitHub.
=> Add landing gifs to each tool docs

CHANGES.rst, jdaviz/components/viewer_data_select.vue, jdaviz/components/viewer_data_select_item.vue
This pull request:
* increase width of viewer data menu to fit default JWST labels (350px -> 430px)
* truncate (with ellipsis) any labels that are still too long, with priority for extensions at end of label
* menu width and `calc(100% - 80px)` for span width might need to be updated if any additional icons (besides the check and delete button) are added in the future.
* updates text in header to fit in single line
Fixes #1381
=> improve data menu for long labels

jdaviz/configs/imviz/tests/test_parser.py
This pull request is to update test results for HST/DRZ parser because the file changed upstream in MAST (some new drizzlepac deployed or something). Without this patch, all unrelated PRs will start failing.
=> TST: Update test results for HST/DRZ parser

jdaviz/configs/default/plugins/line_lists/line_lists.vue
This pull request is to see where we can move the success message from Line Lists to somewhere more permanent that user cannot miss because it contains instructions of what to do next.
Unblocks:
* #1368 
=> Line Lists: Success message in plugin

conftest.py, jdaviz/cli.py, jdaviz/conftest.py, setup.cfg
This pull request is to remove our dependency of `click`, as stated in https://github.com/spacetelescope/jdaviz/pull/1372#issuecomment-1150513370 . User should notice no difference, so I don't think this needs a change log. Also see https://docs.python.org/3/library/argparse.html
Please try out the different CLI options in case I missed something.
p.s. I think it might be slightly faster without click but you should double check in case I am hallucinating.
=> CLI: Replace click with argparse

CHANGES.rst, docs/specviz/plugins.rst, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue, jdaviz/tests/test_subsets.py
Fixes #1329 by properly retrieving and displaying subset information for subsets composed of multiple regions. Opening as draft since I have the backend (mostly) working, but the UI side needs work still. I think the only case this doesn't currently work for is if you remove a region from the subset - I just need to figure out the difference in the Glue nesting in that case.
=> Display compound subset info in subset plugin

notebooks/concepts/imviz_custom_colormap.ipynb
This pull request is to show power-user how to add their own custom colormap to image viewer. This also shows you how #1407 works.
=> Concept notebook to show custom colormap

docs/installation.rst
This pull request is to improve installation instructions, as requested by Ricky. The motivation is to have less help calls.
I wrote down what I do. But I know different devs do things differently, so suggestions welcome.
=> DOC: Improve install instructions

docs/imviz/import_data.rst
This pull request is to encourage users to filter a large catalog first before adding it as markers.
Fixes #1411 
=> DOC: Filter markers for large catalogs

jdaviz/tests/test_show.py
Enhances one of the display tests from #965 to check for the explicit error, rather than the outer, generic, chained, user-friendly error
=> Update Chained Exception test from #965

jdaviz/app.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py
Using model fitting in mosviz does not link the model to the spectrum 1d reference data. This line explicitly calls the linking method and links the reference data to the model.
EDIT: This PR was updating to fix all mosviz plugin linking.
=> Fix plugin linking in mosviz

CHANGES.rst, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/tests/test_tools.py, jdaviz/configs/cubeviz/plugins/viewers.py
Fixes https://github.com/spacetelescope/jdaviz/issues/1469
=> Fix Cubeviz coordinates info display when Subset exists

jdaviz/components/tray_plugin.vue, jdaviz/container.vue
This pull request explicitly sets a few css styles that are otherwise overridden in the MAST embedded version of jdaviz, and will hopefully make the app look more consistent between the notebook and web versions.
=> in-line styling to avoid conflicts when embedding

docs/index.rst
This pull request is to tell users where to download documentation for offline use because it is no longer shipped with package releases as of v2.7 onwards.
This is a follow-up of #1464 .
=> DOC: Note about offline docs

docs/known_bugs.rst
=> Add note about known tornado ioloop bug

CHANGES.rst, jdaviz/app.py, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
This pull request is to try to fix an upstream bug where the wavelength units are set to meters instead of what is in the `CUNIT3` value.
Patch for https://github.com/astropy/astropy/issues/3658
Fix #1025
Fix #840
=> Use CUNIT3 units by default

README.rst, docs/index.rst
I added the Zenodo link to the documentation's index page. Would we like it in the README, too?
=> Attempted first draft of citation instructions

CHANGES.rst, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_linking.py, notebooks/concepts/imviz_load_fits_hdu.ipynb
This pull request is to make sure coordinates info panel does not crash when multiple extensions are loaded. The reference data has a valid WCS but another extension has a non-celestial (dummy) WCS.
Fixes #1497
=> Fix coordinates panel bug for Imviz

CHANGES.rst
Prepping for v2.8.0 release, mainly want to see release/build CI job pass.
=> Update changelog for 2.8.0 release

CHANGES.rst, docs/display.rst, jdaviz/core/helpers.py, setup.cfg
@mariobuikhuizen implemented the necessary methods to implement our missing show location options; this PR updates our required ipypopout version to 0.0.10 and implements our missing popout locations. Thanks @mariobuikhuizen !!!
Depends on:
* https://github.com/spacetelescope/jdaviz/pull/1481
=> Implement popout location in show()

docs/sample_notebooks.rst
The "Sample JDAT Notebooks" link broke, so I changed it to one that I assume points to the same information.
=> Updated broken sample notebook link

docs/dev/ui_style_guide.rst
My main intent was to change "jutify" to "justify." The other diffs just strip trailing spaces.
=> Fixed typo in boilerplate code

jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/mosviz/plugins/parsers.py
This pull request fixes recent codestyle errors introduced by a new release of flake.
=> codestyle changes to appease flake

docs/cubeviz/export_data.rst
This pull request is to add more examples of data retrieval from Cubeviz, specifically subsets.
=> Update cubeviz docs with subset retrieval examples

CHANGES.rst, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue, setup.cfg
This pull request re-enables the popout button in the subset plugin (temporarily disabled in #1427)
Fixes #1567
=> re-enable subset plugin popout button

setup.cfg
This pull request is to unpin jsonschema because asdf released with the pin upstream.
Reverts #1573 
Fixes #1575 
=> MNT: Unpin jsonschema

.github/labeler.yml
We forgot to update auto-labeler rules.
=> MNT: Label specviz2d correctly on GitHub

CHANGES.rst, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/tests/test_helper.py
This pull request exposes `specviz2d.specviz` to match `cubeviz.specviz` and `mosviz.specviz`.
Needed for upcoming specviz2d docs PR (docs not included as part of this PR since the docs for all of specviz need to be populated).
=> specviz2d: expose specviz helper

CHANGES.rst, jdaviz/cli.py, jdaviz/configs/specviz2d/specviz2d.ipynb
This pull request adds basic (2d spectrum only) CLI support for specviz2d.  Support for passing a 1D spectrum filename may require refactoring (either a more advanced parser or an additional CLI argument only used for specviz2d) [:cat:](https://jira.stsci.edu/browse/JDAT-2686) - filed as #1578 for future work.
Needed for upcoming specviz2d docs PR (docs not included as part of this PR since the docs for all of specviz need to be populated).
As far as I know, we don't have any way to include the CLI in the CI tests, so 0% coverage is expected.
=> specviz2d: cli support (2d spectrum only)

conftest.py, docs/conf.py, docs/specviz2d/displaying.rst, docs/specviz2d/export_data.rst, docs/specviz2d/import_data.rst, docs/specviz2d/index.rst, docs/specviz2d/plugins.rst, jdaviz/conftest.py
This pull request adds basic fundamental docs to specviz2d.
[Rendered specviz2d docs](https://jdaviz--1580.org.readthedocs.build/en/1580/specviz2d/index.html)
Once merged:
=> DOC: Specviz 2d basic docs structure

setup.cfg, tox.ini
This pull request is to workaround #1585 so it does not block unrelated PRs.
Also add specreduce to devdeps job so we know any future breakage before it is too late (hopefully).
=> MNT: Do not use specreduce v1.1.0, add specreduce to devdeps job

CHANGES.rst, docs/cubeviz/displaycubes.rst, docs/cubeviz/export_data.rst, docs/cubeviz/import_data.rst, docs/imviz/displayimages.rst, docs/imviz/import_data.rst, jdaviz/app.py, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_regions.py, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_regions.py, jdaviz/conftest.py, jdaviz/core/helpers.py, notebooks/CubevizExample.ipynb, notebooks/ImvizExample.ipynb
This pull request is to enable DS9 region support in Cubeviz and also enables ellipse drawing.
Fixes #1432 
- Sky region support in Cubeviz is blocked by https://github.com/glue-viz/glue-astronomy/issues/75
- Is MaskedSubset breaking spectrum collapse? Yes, so we just disable that for Cubeviz.
=> Cubeviz: DS9 regions and ellipse draw tool

jdaviz/configs/mosviz/helper.py, jdaviz/configs/specviz/helper.py
This pull request is to clarify the entity that is `apply_slider_redshift`.
Fixes #1584
=> Clarify redshift warning verbiage

CHANGES.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, setup.cfg
This pull request extends on #1514 to add support for `peak_method` from https://github.com/astropy/specreduce/pull/115.  
Note that the auto/kosmos trace still often results in an error when actually extracting the spectrum (known bug in specreduce), so this review/PR should be isolated to seeing how the trace itself reacts to changes to the peak method when trace type is set to "Auto".
=> spectral-extraction: support for peak_method in auto/kosmos trace

docs/imviz/export_data.rst, docs/imviz/import_data.rst
I didn't get a chance to submit a review to #1444 before it was merged and remembered I had some fixes and suggestions that I wanted to get considered. The edits in this pull request are more unequivocal, and I'll open another one after this where the suggestions are more matters of opinion.
=> Fixed typos in docs

CHANGES.rst, docs/cubeviz/displaycubes.rst, jdaviz/configs/cubeviz/plugins/tests/test_tools.py, jdaviz/configs/cubeviz/plugins/tools.py, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_tools.py
This pull request is to add linked pan/zoom and linked box zoom to Cubeviz. No one asks for it but I always want it when I test Cubeviz, so here it is. ~This is interactive tool, so I didn't add any tests.~
=> Add linked pan/zoom and linked box zoom to Cubeviz

.github/ISSUE_TEMPLATE/bug-report--cubeviz.md, .github/ISSUE_TEMPLATE/bug-report--imviz.md, .github/ISSUE_TEMPLATE/bug-report--specviz.md, .github/ISSUE_TEMPLATE/bug-report--specviz2d.md, .github/ISSUE_TEMPLATE/feature--cubeviz.md, .github/ISSUE_TEMPLATE/feature--imviz.md, .github/ISSUE_TEMPLATE/feature--mosviz.md, .github/ISSUE_TEMPLATE/feature--specviz.md, .github/ISSUE_TEMPLATE/feature--specviz2d.md
This pull request is to:
* Update dependencies listing in existing vizes.
* Add templates for Specviz2D.
Out of scope here because it needs upstream fix:
* #1605 
=> Update GitHub templates

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/links_control/links_control.py, jdaviz/configs/imviz/plugins/links_control/links_control.vue, jdaviz/configs/imviz/tests/test_links_control.py, jdaviz/core/events.py
This pull request removes the link button in the link controls plugin and instead updates the link state in real-time, with a progress spinner to communicate when linking is in progress.  To avoid concerns of the expensive WCS linking without the fast approximation, fast approximation defaults to True whenever the WCS method is changed to pixel (so that it will already be on fast for the next time it's changed to WCS).
https://user-images.githubusercontent.com/877591/186757516-08eff9bd-323d-4ec4-a170-702fcfb2b554.mov
the plugin state also listens to changes from the API:
https://user-images.githubusercontent.com/877591/186967307-155ee181-5283-46b1-8f99-958dca34f91f.mov …
=> live-updating linking with progress spinner

.github/workflows/ci_cron_weekly.yml, .github/workflows/ci_workflows.yml, .github/workflows/publish.yml
This pull request is to use newest setup python Action.
=> MNT: Upgrade actions/setup-python to v4

jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/tests/test_lineflux.py
There was an unforeseen clash between #1583 and #1564, where a known astropy units warning introduced in #1564 was popping up in #1583's test. I copied over the warnings ignore, and also matched them so that the warnings ignore is more specific
=> Catch known test warning

docs/cubeviz/displaycubes.rst, docs/cubeviz/import_data.rst, docs/imviz/displayimages.rst, docs/imviz/import_data.rst, docs/imviz/plugins.rst, docs/mosviz/index.rst, docs/save_state.rst, docs/specviz/import_data.rst, docs/specviz/index.rst, docs/specviz/plugins.rst, docs/specviz2d/import_data.rst
I didn't get a chance to submit a review to #1444 before it was merged and remembered I had some fixes and suggestions that I wanted to get considered. The issues addressed in this pull request are less cut-and-dry than in #1602, but I'm happy to talk through any differing opinions.
=> Attempted to improve clarity across docs

CHANGES.rst, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py
This pull request extends on #1401 and provides user-API access to the moment maps plugin.
[Plugin User API docs](https://jdaviz--1642.org.readthedocs.build/en/1642/api/jdaviz.configs.cubeviz.plugins.moment_maps.moment_maps.MomentMap.html#jdaviz.configs.cubeviz.plugins.moment_maps.moment_maps.MomentMap)
**TODO**:
=> user API for moment maps plugin

CHANGES.rst, jdaviz/configs/imviz/plugins/compass/compass.py, jdaviz/configs/imviz/plugins/compass/tests/test_compass.py, jdaviz/configs/imviz/tests/test_helper.py, jdaviz/core/user_api.py
This pull request extends on #1401 and provides user-API access to the compass plugin.
[Plugin User API docs](https://jdaviz--1643.org.readthedocs.build/en/1643/api/jdaviz.configs.imviz.plugins.compass.compass.Compass.html#jdaviz.configs.imviz.plugins.compass.compass.Compass)
**TODO**:
=> user API for compass plugin

.github/PULL_REQUEST_TEMPLATE.md
This pull request is to clarify change log policy on the PR template, as discussed at tag-up today.
=> DEV: Clarify change log policy

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/line_lists.vue, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py, jdaviz/core/linelists.py, jdaviz/data/linelists/linelist_metadata.json
This PR is intended to display the available line list medium information, if it is provided in the metadata. If not, it defaults to "Unknown". I tried to make the information unobtrusive and non-controversial as possible, but I'll still ping @Jenneh to see if there are any UI considerations.
I also went through and added the medium information provided by @rosteen in #1517, as well as the information provided on the links. A surprising number of reference links were either dead links or not accessible to the public, which is slightly concerning... Continued in #1656 
Fixes #1517 
=> Line List: Display medium information from metadata

jdaviz/app.vue
The classList should only be used when the target element is found.
Addresses one console error of #1367
=> fix: invoking classList on null

setup.cfg
so image display resize properly when tray is opened or closed.
This pull request is to bump minversion of bqplot as recommended by @maartenbreddels at https://github.com/spacetelescope/jdaviz/issues/1604#issuecomment-1252112678 .
Close #1604 
=> MNT: Bump bqplot minversion

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py, jdaviz/core/template_mixin.py, jdaviz/core/user_api.py
This pull request extends on #1401 and provides user-API access to the plot options plugin.
[Plugin User API docs](https://jdaviz--1637.org.readthedocs.build/en/1637/api/jdaviz.configs.default.plugins.plot_options.plot_options.PlotOptions.html#jdaviz.configs.default.plugins.plot_options.plot_options.PlotOptions)
**TODO**:
=> user API for plot options

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py, jdaviz/core/template_mixin.py, jdaviz/core/user_api.py
This pull request extends on #1401 and provides user-API access to the model fitting plugin.
[Plugin User API docs](https://jdaviz--1658.org.readthedocs.build/en/1658/api/jdaviz.configs.default.plugins.model_fitting.model_fitting.ModelFitting.html#jdaviz.configs.default.plugins.model_fitting.model_fitting.ModelFitting)
**TODO**:
=> user API for model fitting plugin

CHANGES.rst, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
This PR adds a visual prompt to the user when overwriting an existing file on disk. It allows the user to cancel or continue and overwrite the file.
I believe there are multiple places where we write digital artifacts for the user; this PR can be the basis for a reusable mixin later down the line
https://user-images.githubusercontent.com/25206008/192894471-2c1c755c-732b-4f5f-b13f-3db3ab021975.mp4
=> Add Overwrite Warning to Moment Map Plugin

CHANGES.rst, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py
This pull request is a direct follow-up of https://github.com/spacetelescope/jdaviz/pull/1683 that was just merged because I did not post a review in time.
=> Follow up of PR 1683

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py
This pull request removes the model equation validation error for model equations over a length of 20 characters.  This was original implemented [as an example for the hook up for validating the model equation](https://github.com/spacetelescope/jdaviz/commit/ae6990b97fbc96af5671eb875e9aefdf1162bdab#diff-f8d8ca5f492ba5b9a6662f90b39d7e11ccff5ee72bce742257a154c13e540744R85-R88), but shouldn't actually be a restriction.
=> remove validation for model equation length

CHANGES.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
This pull request extends on #1401 and provides user-API access to the spectral extraction plugin.
[Plugin User API docs](https://jdaviz--1639.org.readthedocs.build/en/1639/api/jdaviz.configs.specviz2d.plugins.spectral_extraction.spectral_extraction.SpectralExtraction.html#jdaviz.configs.specviz2d.plugins.spectral_extraction.spectral_extraction.SpectralExtraction)
**TODO**:
=> user API for spectral extraction

CHANGES.rst
This pull request is to fix change log for https://github.com/spacetelescope/jdaviz/pull/1638
=> Fix changelog for PR 1638

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
This pull request is to fix #1686 . 
=> BUG: Fix model fitting crashing when param is fixed

CHANGES.rst, jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/collapse/collapse.vue
This pull request renames `collapse_plugin.method` to `collapse_plugin.function` to be consistent with `plot_options.collapse_function`.  `collapse_plugin.method` was first made available in the user API in #1641, but has not yet been included in a release, so this change does not need to be considered breaking as long as it is merged before the next release
=> collapse plugin: rename "method" to "function"

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py, jdaviz/core/template_mixin.py
This pull request fixes the `plugin_select.select_default()` behavior to reset the value to the default even if the current value is valid.  Internal calls to `_apply_default_selection` automatically return without changing the value if the current value is valid, but manual calls to `select_default` (by the user) are expected to change the current selection even if it is valid.
=> plugin select: fix select_default behavior

.github/CODEOWNERS
=> Add Brett to list of code owners

CHANGES.rst, jdaviz/app.vue
This pull request fixes the padding in the logger overlay (introduced in #1352) to account for the increased size in the main app toolbar in specviz2d (changed when adding the mouseover information in #1608).
Before:
After:
=> fix padding in logger overlay for non-dense top bar

jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
This pull request is to skip test with data now missing on MAST. Possible outcomes:
* If MAST restores the file, we can close this PR without merge.
* If someone can find a replacement dataset (@kecnry ?), then we can replace it instead of skipping the test.
* We can merge this PR as-is to skip it and open follow-up issue to investigate more.
=> TST: Skip test with missing file

CHANGES.rst, jdaviz/configs/imviz/plugins/compass/compass.py, jdaviz/configs/imviz/tests/test_tools.py
This pull request is to work around #1730 .
~I don't know how to write a test for this one. Ideas welcome, otherwise maybe we can skip testing this one?~
=> BUG: Fix crashing in Compass when data is loaded while it is open

.github/workflows/ci_workflows.yml, jdaviz/configs/specviz/tests/test_helper.py
This pull request updates the dev dependency test to make use of remote data and updates a test to account for recent changes introduced in specutils 1.9 by https://github.com/astropy/specutils/pull/982
=> TST: remote data in dev deps test

docs/cubeviz/displaycubes.rst, docs/cubeviz/import_data.rst
This was originally in #1698 but it is really its own patch because it is some documentation inconsistency I noticed while working on something unrelated.
Even though this fixes wrong doc in released software, our default RTD is "latest," so I don't see any burning need to backport. But if you want to switch the default to "stable" then we might have to change the milestone.
=> DOC: Improve and fix Cubeviz docs for displaycubes and import_data

CHANGES.rst, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_data_retrieval.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue, jdaviz/core/validunits.py, notebooks/concepts/cubeviz_wfc3ir_ramp.ipynb
This pull request was in #1698 but is has nothing to do with loading GIF or plain cube. This is more like a pre-requisite to make it possible because it fixes existing bugs related to that feature, so I turned this into a separate PR.
Screenshot from the WFC3/IR concept notebook:
=> BUG: Better Cubeviz support for Spectrum1D without WCS

notebooks/concepts/imviz_load_3d_slices.ipynb
I didn't realize some frames come back as 3D in itself (RGB). We would want to convert those to gray first before displaying.
=> BUG: Fix baby shark loading in Imviz concept notebook for image slices

.github/PULL_REQUEST_TEMPLATE.md
This pull request is to update the PR checklist to account for extra stuff necessary to support branched release model.
=> Update PR template to account for new branched release model

docs/installation.rst
This PR migrates some documentation I wrote in https://github.com/spacetelescope/jdaviz/discussions/926 to our actual docs section. Directs windows users to install the C++ compilers necessary for our dependencies that aren't included by default
=> DOC: Add instructions to install build tools for Windows

CHANGES.rst
Because there will not be 3.0.3 release -- cc @rosteen 
=> Move 3.0.3 stuff to 3.1 section

docs/dev/release.rst
While doing the release today I realized I had missed a couple things in the last docs update. This adds some details that will be useful if anyone else does a release.
=> Update release instructions with more details

jdaviz/configs/imviz/plugins/viewers.py
The function was moved a long time ago but I must have forgotten to update this import.
=> MNT: Import data_has_valid_wcs from the correct place

CHANGES.rst, jdaviz/app.vue, jdaviz/configs/specviz/plugins/viewers.py, jdaviz/configs/specviz/specviz.yaml, jdaviz/configs/specviz/tests/test_helper.py
This pull request is to add coordinates info panel for spectrum viewer. The first pass hacks the image pixel display to display flux and wavelength values under the cursor. Not the prettiest but it works.
I didn't want to overcomplicate things by extracting the data just to grab unit strings. To do that at every mousemove event is expensive. People can already see the unit on the axes.
I know what Kyle is going to say but it is not easy to generalize this thing for all the viewers. 😬 
Address part of #567 (except not saving anything on click)
This checklist is meant to remind the package maintainer(s) who will review this pull request of …
=> Spectrum coordinates info panel

CHANGES.rst, jdaviz/core/tests/test_tools.py, jdaviz/core/tools.py
This pull request is to address box zoom not respecting the aspect ratio of the viewer. You can see the associated issue for the original behavior, here is how it is in this PR:
https://user-images.githubusercontent.com/7179333/195392524-2db4eb6f-1bf4-4420-b53f-974510f3f147.mov
Fixes #1678 
=> Fix box zoom

CHANGES.rst, jdaviz/app.py, jdaviz/configs/mosviz/plugins/viewers.py
This pull request is to remove MosvizProfileView that is not used anywhere.
=> MNT: Remove unused MosvizProfileView

jdaviz/core/helpers.py
=> Update this docstring to be accurate

CHANGES.rst, jdaviz/app.vue, jdaviz/configs/mosviz/mosviz.yaml, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/mosviz/tests/test_data_loading.py
This pull request is to enable coordinates display panel for image and 2D spectrum viewers in Mosviz.
I am not familiar with all the different data Mosviz is supposed to be able to load, so Mosviz experts should play with this.
Goes with:
* #1759 
Mousing over the image:
Mousing over the 2D spectrum:
Mousing over the 1D spectrum. There is no data icon label (B) because Kyle said it is cursor position, not actual data:
=> Mosviz coordinates display panel for image and 2d spectrum viewers

docs/imviz/export_data.rst, docs/imviz/plugins.rst
DOC: Clarify the role of centroid in aperture photometry plugin.
BUG: Fix typo in doc ref.
Just affects the docs, so no need to backport.
=> DOC: Clarify the role of centroid in aperture photometry plugin

CHANGES.rst, docs/cubeviz/import_data.rst, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, notebooks/concepts/cubeviz_ndarray_gif.ipynb
This pull request is to wrap up #1698 but that one got split up into smaller PRs and now has too much conflicts so I opened this PR instead.
Out of scope: https://github.com/spacetelescope/jdaviz/issues/1697
Earlier more ambitious attempts: https://github.com/spacetelescope/jdaviz/pull/1040 and #1698 
=> Cubeviz to support plain Numpy cube and GIF

jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue
I'm working on some improvements/docs on the spectral extraction plugin, and came across a few possible improvements to the hints in the plugin. 
To consider: the underlying data have dispersion along columns, but we take the transpose of the data for the spectrum-2d viewer, so columns are displayed as rows. I have used the word "row" in the hints so that it matches what the user sees.
=> better hints for spectral extraction

docs/specviz2d/plugins.rst
A workflow was added in #1556 to generate traces for spectral extractions based on existing traces. This PR adds to the narrative docs to explain the workflow.
[🐱](https://jira.stsci.edu/browse/JDAT-2724)
=> DOC: describe workflow for spatially-offset traces 

tox.ini
Fix Jupyter DeprecationWarning about migrating its paths to use standard platformdirs.
Fixes #1830 
=> TST: Fix Jupyter DeprecationWarning

CHANGES.rst
Switched the changelog entry to 3.2 for #1836 after a failed backport: https://github.com/spacetelescope/jdaviz/pull/1836#issuecomment-1313975699
=> Move changelog for failed backport 1836

CHANGES.rst, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/tests/test_data_loading.py
* Allow mosviz load_data to load only 1d or 2d spectra
* Add tests
* Only link table data if more than just 1d or 2d spectra is loaded
* Update change log
* Add options for 1d and image or 2d and image
(cherry picked from commit 9a1d4145f84666479eef59ce5d97430ba6e0d8bc)
This pull request is to manually backport #1833 to v3.1.x branch.
=> Manual backport of PR 1833 to v3.1.x (Allow mosviz load_data to load only 1d or 2d spectra)

docs/dev/release.rst
This pull request is to add manual backport instructions because the autobackport bot is misbehaving and not giving out the instructions anymore and I don't know when that is going to be fixed.
Since @javerbukh just did a manual backport, he should see if this comes close to what he actually did. This is what I do personally but everyone is different.
https://jdaviz--1845.org.readthedocs.build/en/1845/dev/release.html#manual-backport
=> DOC: Manual backport instructions

CHANGES.rst, docs/cubeviz/plugins.rst, jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/configs/cubeviz/plugins/slice/slice.vue, jdaviz/configs/cubeviz/plugins/slice/tests/test_slice.py, notebooks/concepts/cubeviz_ndarray_gif.ipynb
This pull request is an attempt to see if we can have things like "next", "play", "stop" for Cubeviz slice plugin.
Slightly outdated UI in dark mode:
Demo video (YouTube): https://www.youtube.com/watch?v=RwiZ419eecc&list=PLTBpUCKusTg0MESZVWRQRHrw5ciKv87_Q&index=7
=> Cubeviz autoplay

CHANGES.rst
=> Back to development: v3.1.2

setup.cfg
Would resolve #1863 by reverting #1861.
=> Revert "DOC: Pin setuptools"

docs/specviz/displaying.rst
This pull request is to update Specviz Plot Options documentation and also show user how to show uncertainties via API.
Fixes #847
=> DOC: Update Specviz Plot Options documentation

CHANGES.rst
Backport failed for #1887. This PR moves the changelog entry to the main 3.2 release
=> Move changelog entry for failed backport #1887

tox.ini
This pull request updates our passenv to be compatible with tox 4.0.6+
=> MNT: comma separated passenv to be compatible with tox requirements

CHANGES.rst, jdaviz/app.py, jdaviz/app.vue, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/test_tools.py, jdaviz/core/freezable_state.py
This pull request overrides the behavior in glue for `viewer.state.reset_limits()` (and therefore the zoom "home" button) to account for the limits of all *visible* layers.
**Previous behavior**:
https://user-images.githubusercontent.com/877591/206013547-a52a5c67-307d-40ac-b1da-e12d00aa03c7.mov
https://user-images.githubusercontent.com/877591/206261204-128c8dd7-bba3-48a3-a3ae-55e7457a8d46.mov
**New behavior**:
https://user-images.githubusercontent.com/877591/206013382-817561e2-c1fc-40de-a90e-f0986ee7f0a5.mov
https://user-images.githubusercontent.com/877591/206261235-ba632f57-90a5-42ee-97f9-eb8f91d233c7.mov
**TODO**:
This checklist is meant …
=> Account for all layers in reset limits/zoom home

docs/specviz/plugins.rst
This pull request removes a line in the docs that probably should have been removed in #1134.
=> remove line from code snippet suggesting we support per-line redshift

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
As the title says, manual backport of #1880 .
=> Manual backport of pr 1880 on v3.1.x

setup.cfg
See #1925 for discussion. The newest release of asdf is available (2.14.3 on [GH](https://github.com/asdf-format/asdf/releases/tag/2.14.3) and [PyPI](https://pypi.org/project/asdf/2.14.3/)), so I bumped the pin here.
Closes #1925.
=> Minversion pin for asdf

jdaviz/configs/imviz/plugins/parsers.py
This is a quick follow-up of #1908 . Somehow missed this in the initial review.
=> Remove redundant if statement introduced in PR 1908

jdaviz/configs/imviz/plugins/viewers.py
As far as we are concerned `pixel_to_pixel` from `astropy.wcs.utils` is interchangeable with the code it is replacing.
https://github.com/astropy/astropy/blob/87963074a50b14626fbd825536f384a6e96835af/astropy/wcs/utils.py#L803
Pro: We are using "blessed" functionality from astropy core lib.
Con: I am not sure if this is worth it. The astropy function has extra processing that we don't really need. If not worth it, we should just close without merging.
Why this PR? Because I didn't know this function existed until Tom R pointed it out today. …
=> Use pixel_to_pixel in _get_real_xy method

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py
This pull request fixes fitting a 1d spectrum of a spatial subset in cubeviz, temporarily broken by #1947 and reported by @rosteen in https://github.com/spacetelescope/jdaviz/pull/1952#issuecomment-1368092168
Since #1947 has not made a release, I am just appending this PR to the relevant part of that changelog entry.
=> fix 1d spectrum fitting for spatial-subset in cubeviz

CHANGES.rst, docs/specviz/plugins.rst, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue
This pull request is to temporarily disable Unit Conversion plugin until it can be refactored, which is tracked separately.
=> Disable Unit Conversion plugin for now

CHANGES.rst, jdaviz/app.vue
This pull request points the help button in the app toolbar to the specviz2d-specific page in the docs for specviz2d (instead of the main landing page)
=> enable link to specviz2d docs

CHANGES.rst
Cleanup from #1992 and reintroduce the missing entry from #1958 
=> Move mosviz changelog entries to 3.3

CHANGES.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
This pull request adds the missing `aperture_sum_mag` column to the UI table within aperture photometry.
=> add aperture_sum_mag to aperture table cols

docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/catalogs/catalogs.py, jdaviz/configs/imviz/tests/test_catalogs.py, setup.cfg, tox.ini
This pull request is to work around https://github.com/astropy/astroquery/issues/2673 but maybe we want it to see for a few days in case it is fixed upstream, then we do not need this patch.
Or if we need the CI to be green sooner, we can also merge this and then revert later. 🤷 
Also have to handle https://github.com/glue-viz/bqplot-image-gl/issues/99 so we can get the dev/remote-data job green, which was the purpose of this PR. But if we don't need this PR, I can take this part out too.
Also have to ignore a deprecation warning related to #1980 .
This checklist is meant to remind the package maintainer(s) who will review this pull request …
=> Catalogs: Use SDSS DR 16, fix other dev failures

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/conftest.py
=> Manual Backport PR #2023 on branch v3.3.x (Fix 2D smooth visibility bug by utilizing SpectralExtraction linking logic)

setup.cfg
This pull request is to ignore asdf warning from dev version of specutils. The warning is not related to Jdaviz.
Maybe related:
* https://github.com/astropy/specutils/issues/1011
=> TST: Ignore asdf_extensions deprecation warning from specutils

CHANGES.rst, jdaviz/configs/default/plugins/export_plot/export_plot.py
This pull request exposes the ``viewer`` dropdown in the user API for the export plot plugin
=> expose viewer dropdown in export plot user API

docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/catalogs/catalogs.py
Use SDSS DR17 again now that server error is fixed upstream.
This reverts some stuff from #2021.
Fix #2030
=> Catalogs: Use SDSS DR17 again

setup.cfg
This pull request is to un-ignore numpy warnings in test suite.
Fixes #1878 
=> TST: Un-ignore Numpy warnings

jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/models/physical_models.py
This pull request is to address upstream changes made by https://github.com/astropy/astropy/pull/14439 so our dev job passes again.
Fix #2076 
Blocked by:
* #2052
=> TST: Unit str compatibility with astropy 5.3

.github/workflows/ci_workflows.yml, jdaviz/configs/imviz/tests/test_catalogs.py
This pull request is to abuse the `slow` tag that comes with `pytest-astropy` for this purpose.
Fixes #2083
=> Only run test_plugin_image_with_result in dev job

jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
This pull request is to update new results affected by astropy/astropy#14519 now that uncertainties are propagated.
Fixes #2086
=> TST: Update expected answer from astropy PR 14519

jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py
This pull request is to remove redundant code in Line Profile plugin. It seems like figures are being cleared twice in a row. The second call basically does nothing but also unnecessary.
Fixes #2096
=> Line Profile: Remove redundant code

LICENSE.rst, tox.ini
This pull request is to fix #2118 
=> TST: Fix devdeps failures

CHANGES.rst, jdaviz/configs/default/plugins/data_tools/data_tools.py, jdaviz/configs/default/plugins/data_tools/file_chooser.py
This pull request is to fix `DataTools` logic so it does not crash when `file_path` is `None`.
I did not add test because I don't know how exactly it was triggered by the user.
=> BUG: Fix DataTools logic

.github/CODEOWNERS
This pull request adds @cshanahan1 to codeowners.
=> add cshanahan1 to codeowners

docs/dev/release.rst
This pull request is to update release procedures so people get the correct dev tag on dev installs. This is needed because setuptools-scm cannot pick up stable tags from release branches. This is similar to what `astropy` does: https://docs.astropy.org/en/latest/development/releasing.html#start-of-a-new-release-cycle-feature-freeze-and-branching
I fixed the v3.4.dev tag but we have to remember going forward.
=> DOC: Add dev tag to release procedures

tox.ini
This pull request is to fix #2031 now that https://github.com/glue-viz/bqplot-image-gl/issues/99 is resolved.
xref #2021
=> TST: Re-enable dev testing for bqplot-image-gl

README.rst, docs/index.rst
=> Add links to the JWebbinar notebooks and videos to the docs

setup.cfg
This pull request is to fix CI.
=> IPython 8.13+ is Python 3.9 only

pyproject.toml
This pull request is to fix CI. Suspect is https://github.com/glue-viz/glue/pull/2394 that is part of glue-core v.1.10.0 released last night.
Maybe @kecnry can unpin over at his unit conversion branch.
=> Pin maxversion of glue-core

setup.cfg
This pull request applies the same max-pin of glue as in #2180 but to `setup.cfg` in `3.4.x` in place of `pyproject.toml` in `main`.
=> manual backport of PR #2180

CHANGES.rst, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue, jdaviz/configs/default/plugins/subset_plugin/tests/test_subset_plugin.py, jdaviz/tests/test_subsets.py
This pull request is to implement `app.get_subsets()` in the Subset Plugin. Still to do:
Video showing repeated plugin refreshing when trying to sync (the UI moving with the plugin tray did not appear in the recording for some reason):
https://user-images.githubusercontent.com/7179333/233375541-9b949f44-6178-42c4-abda-75fb2e7dd4d6.mov
Fixes #2068 
=> Subset Plugin updated to use get_subsets method

jdaviz/app.py, jdaviz/components/viewer_data_select.vue, jdaviz/container.vue, jdaviz/core/template_mixin.py
This pull request implements a few minor quality-of-life tweaks and generalizations that will be useful for using jdaviz as a dependency for downstream packages (such as lcviz).  This PR includes:
* generalizing handling of viewer labels and supporting non-title-case for some words (currently "vs")
* generalizing `App._on_new_viewer` to work outside imviz
* improving the styling for the `SelectPluginComponent` repr
None of these changes should noticeably affect users of jdaviz.
=> lcviz quality of life tweaks

jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, setup.cfg
This pull request is a manual backport of #2196 to unpin max glue in the bugfix branch and skip a test that is failing to get the URL from MAST (see #2197)
=> unpin max glue

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/core/template_mixin.py
This pull request adds hooks to glue state entries for scatter viewers and layers.  These currently are not used by jdaviz, but may in the future, and are not easy to implement downstream separately.  Because they are not used in any of the configs here, it is difficult to get coverage for the non-covered lines, but suggestions are welcomed!
NOTE: some attribute names may change if/when plotting lines in scatter viewers is exposed by glue-jupyter.
=> plot options support for scatter viewers/layers

jdaviz/configs/default/plugins/markers/markers.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/core/template_mixin.py
This pull request generalizes some of the markers/coords_info code so that it can more easily be adapted downstream (in `lcviz`).  No user-facing API or behavior changes are expected.
=> generalize markers code for future downstream use

docs/cubeviz/export_data.rst, docs/specviz/export_data.rst, jdaviz/configs/cubeviz/helper.py, notebooks/SpecvizExample.ipynb
This pull request is to address references to `subset_to_apply` when called with `get_data` in the documentation.
=> Replace subset_to_apply in docs where possible

jdaviz/configs/default/plugins/viewers.py
This pull request generalizes the logic for "native" vs "custom" marks so downstream apps can override their definitions as necessary.  This should not affect jdaviz or the user in any way.
=> allow downstream apps to set what classes are considered native marks

jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue
This pull request attempts to make the subset plugin UI easier to understand when using composite subsets.
Before:
After:
=> Update subset plugin UI

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue, jdaviz/tests/test_subsets.py
Add simplify button to subset plugin
This pull request is to add a simplify subset button to the Subset Plugin UI to convert a composite spectral subset consisting of And, AndNot, Or, Replace, and Xor into one consisting of just Range and Or state objects.
Fixes #2210 
=> Add app method to simplify spectral subset

jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue
This pull request implements a fallback in the subset plugin UI that attempts to display the subset parameters with units (as of #2127) when those units are not available (as in imviz currently).  Since this has not been released yet, it should not require a change log entry.
Fixes #2251
=> subset plugin: fallback if unit cannot be found

tox.ini
Re-adds stdatamodels to devdeps testing.
The backwards compatibity issue: https://github.com/spacetelescope/stdatamodels/issues/159
appears to have been fixed in: https://github.com/spacetelescope/stdatamodels/pull/161
Fixes #2165 
=> re-add stdatamodels to devdeps

.mailmap
This pull request is to add `.mailmap` so `git shortlog -es` gives sane listing. Currently the same person is listed multiple times, so if you are one of these people, git thinks your precious contributions are from multiple clones of yourselves.
Except for Brett Graham, he is fine, but just "Brett" is confusing because we have so many Bretts now.
Also see https://git-scm.com/docs/gitmailmap
Out of scope: It does seem weird that some of the past devs have less number of total commits than I would expect, but `git` does its own math, so you just have to trust it.
This checklist is meant to remind the package maintainer(s) who will review this …
=> MNT: Add .mailmap

pyproject.toml
This pull request is to ignore deprecation warning from `asteval` that we can do nothing about. Already reported to For example https://github.com/newville/asteval/issues/120 .
I will just YOLO-merge this when devdeps job passes and CI is green. I cannot stand the red X anymore.
=> TST: Ignore DeprecationWarning from asteval

docs/dev/ui_style_guide.rst, jdaviz/components/plugin_add_results.vue, jdaviz/configs/default/plugins/export_plot/export_plot.vue, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue
This pull request resolves some inconsistencies in styling between plugins and updates the dev style guide accordingly.  The only visual changes are to a few of the expansion panels in specviz2d's spectral extraction, the styling of the buttons in the export plot plugin, and the ordering of the stop and create movie buttons from #2264.
=> update style guide for consistency between plugins

CHANGES.rst, jdaviz/components/viewer_data_select.vue
When switching to single select from multi select, the data menu will now default to the "first" data entry and de-toggle the other data elements
=> Single select replaces other selected items in multi select

docs/index_using_jdaviz.rst, docs/quickstart.rst
@camipacifici noticed that this file was missing and contained valuable information so we are adding it back.
=> Re-upload quickstart file

CHANGES.rst
This pull request is to add a change log for PR #2309 
=> Add changelog for 2309

CHANGES.rst, CITATION.cff
This pull request is to release v3.6.0 of jdaviz.
=> Preparing release v3.6.0

CHANGES.rst
This pull request is to set up jdaviz for the next release cycle.
=> Back to development: 3.7.dev

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py, jdaviz/core/template_mixin.py
This pull request migrates the stretch histogram in plot options to make use of the plugin plot subcomponent introduced in #2254.
=> migrate stretch histogram to use plot plugin-subcomponent

jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py, jdaviz/core/tests/test_autoconfig.py
Fix recent codestyle failures for
```
E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
```
=> fix codestyle failures

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/imviz/plugins/compass/compass.py
This PR is a manual backport of #2326
=> manual backport of 2326

CHANGES.rst, jdaviz/configs/cubeviz/plugins/tests/test_tools.py, jdaviz/configs/cubeviz/plugins/tools.py, jdaviz/configs/cubeviz/plugins/viewers.py
This pull request fixes the cubeviz pan zoom match tool (previously there was a bug where it would attempt to update the limits on the spectrum viewer) and also clean up both the matched pan zoom and box zoom to make use of #2343, assume pixel-linking, and skip syncing reference data.
=> update cubeviz matched zoom tools

jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/tests/test_helper.py, jdaviz/conftest.py, jdaviz/core/astrowidgets_api.py, jdaviz/utils.py, tox.ini
This pull request is to follow advice at https://github.com/astropy/astropy/issues/15146#issuecomment-1669517226 so we get latest astropy dev wheel. Currently, we're pulling in an outdated one because it didn't know how to handle the new astropy-iers-data that astropy dev now requires.
Blocked by:
* https://github.com/scipy/scipy/issues/19046
=> TST: Pick up astropy-dev from index URL to get latest dev wheel

jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/viewers.py, jdaviz/core/astrowidgets_api.py, jdaviz/utils.py
This pull request is to manually backport #2336 
=> Backport PR 2336 to v3.6.x (MNT: glue-jupyter compatibility for import)

jdaviz/configs/mosviz/tests/test_helper.py, tox.ini
and unskip mosviz csv job
This pull request is to use pandas dev in devdeps stack.
Fixes #2364
=> TST: Use pandas-dev in devdeps

docs/conf.py, docs/dev/ui_description.rst, docs/imviz/import_data.rst
This pull request is to get us out of a *sticky* situation.
Close #2380
=> DOC: Update glue-core intersphinx

.github/CODEOWNERS
This pull request is to upkeep with staff changes.
=> MNT: Remove Duy from codeowners

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue
This pull request implements a dynamic step size for vmin/vmax (for the stretch histogram in plot options).  The value is updated based on the limits of the histogram itself (updating every time the histogram range changes) and to increment approximately 1% of that range.
=> stretch histogram vmin/vmax dynamic step size

jdaviz/app.py, jdaviz/app.vue, jdaviz/cli.py
This pull request moves the logic for setting the link to read-the-docs from the vue template into `app.py` so that downstream apps can override and provide their own custom link without having to override the entire app template.
This is then used in lcviz in https://github.com/spacetelescope/lcviz/pull/40
=> allow downstream apps to set links to docs

.readthedocs.yaml
This pull request is to fix RTD build. Just need RTD to pass.
=> RTD: No more system_packages

CHANGES.rst, jdaviz/app.vue
In Notebook 7, the application currently displays only the header. For notebooks, the application content is assigned a fixed height. To accommodate Notebook 7, adjustments need to be made in how the app detects whether it's running within a notebook environment.
=> fix: support for notebook 7

jdaviz/core/user_api.py
This pull request prevents accidentally overwriting a plugin user-API method.  For example:
```
fp = imviz.plugins['Footprints']
fp.add_overlay = 'blah'
```
where `add_overlay` is actually a method, then breaks the user-API object moving forward (and could potentially break internal calls).  This now raises an error and points to `help(add_overlay)` for input arguments to the method.
=> prevent overwriting user-API methods

tox.ini
This pull request is to also pull in scikit-image dev to get rid of incompatibility with numpy. This will hopefully make devdeps job green again.
=> TST: Also pull in scikit-image dev

.github/workflows/ci_cron_weekly.yml, .github/workflows/ci_workflows.yml, .github/workflows/codeql-analysis.yml, .github/workflows/predeps_workflows.yml, .github/workflows/publish.yml, .github/workflows/standalone.yml
This pull request is to do something that Dependabot should have done here but didn't.
Fix #2436 
=> MNT: Bump actions/checkout to v4

jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/configs/mosviz/tests/test_parsers.py
This pull request is to ignore ASDF warning about gwcs-1.0.0 schema because gwcs dev and/or asdf-wcs-schemas 0.2.0 triggers the warning because the schema is no longer supported.
See https://github.com/spacetelescope/jdaviz/issues/2446#issuecomment-1716474563
Fixes #2446
=> TST: Ignore ASDF warning about gwcs-1.0.0 schema

jdaviz/app.py, jdaviz/components/viewer_data_select.vue
This pull request adds temporary logic to the data menu to control per-viewer visibility of data menus in lcviz.  See https://github.com/spacetelescope/lcviz/pull/28.
We can either merge this temporarily and later generalize the code to allow better filtering access to individual (including downstream) configs, or we can leave this in draft and just deal with the extra entries in lcviz until that larger refactoring can be completed.
This should not affect any configs in jdaviz directly, and therefore has no changelog entry. …
=> visibility logic for lcviz data entries

tox.ini
This pull request is to force numpy-dev in devdeps even if matplotlib downgrades it via contourpy.
Fixes #2470
=> TST: Force numpy-dev in devdeps

CHANGES.rst
(just fixing an indentation error, i cant push directly to the branch)
=> Preparing release v3.7.0

CHANGES.rst, CITATION.cff
updating change log / citation after 3.7
=> Update for 3.7.x

CHANGES.rst, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/tests/test_subsets.py
This PR adds a circular annulus subset option to the toolbar.
=> added circular annulus subset to cubviz toolbar

tox.ini
This pull request is to use nightly wheel from matplotlib for our devdeps job. 
=> TST: Use mpldev for devdeps

.github/ISSUE_TEMPLATE/bug_report.yaml, conftest.py, jdaviz/conftest.py
This pull request is to add `ipypopout` version reporting in test header and bug report template now that `ipypopout.__version__` is possible.
Fixes #1605
=> DOC: Add ipypopout version reporting

jdaviz/components/play_pause_widget.vue, jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/configs/cubeviz/plugins/slice/slice.vue, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue, jdaviz/configs/default/plugins/line_lists/line_lists.vue, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.vue, jdaviz/configs/imviz/tests/test_line_profile_xy.py
This pull request audits and updates all the existing plugins for consistent usage of traitlets (Int, Float and IntHandleEmpty, FloatHandleEmpty when tied to a UI-element) and UI inputs (`type="number" v-model.number="traitlet"`).  This should not affect users in any significant way (except perhaps that in line profile, the pixel position is now displayed as rounded rather than as a full floating point number).
=> consistent use of float/int traitlets in plugins

jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/viewers.py, jdaviz/utils.py
This pull request is to remove `GLUE_JUPYTER_LT_0_18` because it is no longer necessary.
https://github.com/spacetelescope/jdaviz/blob/75f33004d2210e3e5b627bf3105eeceb1c7f0f4b/pyproject.toml#L16
Fixes #2519 
=> MNT: Removed GLUE_JUPYTER_LT_0_18

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue
This pull request adds support in the plot options plugin for lines in scatter viewers (introduced in https://github.com/glue-viz/glue-jupyter/pull/398).
~This is blocked until glue-jupyter with the PR above is released and pinned here (or we could add additional logic to handle both before and after that PR).~
=> plot options support for line in scatter viewer

jdaviz/core/tools.py, jdaviz/data/icons/stretch_bounds.svg
Simple enough! Thanks to @Jenneh .
=> Adding icon for stretch bounds tool

CHANGES.rst, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/configs/mosviz/tests/test_data_loading.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/configs/specviz2d/tests/test_parsers.py, jdaviz/core/marks.py
This pull request creates matched/linked mouseover markers between the 1d and 2d spectrum viewers in both specviz2d and mosviz, with the aim to make the possible non-linear mapping between the two viewers more obvious and intuitive feeling to users.  This also adds the corresponding wavelength in the mouseover coordinates info (in the top app bar) when mousing over the 2d spectrum viewer.
https://github.com/spacetelescope/jdaviz/assets/877591/ba8f6663-d393-434c-b675-df61c231f911
=> specviz2d/mosviz: matched mouseover markers

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py
This pull request is to get CI green again.
Fixes #2590
=> Compat with glue-core 1.17

.github/workflows/ci_cron_weekly.yml, .github/workflows/ci_workflows.yml, .github/workflows/predeps_workflows.yml, .github/workflows/publish.yml, .github/workflows/standalone.yml
Just normal maintenance. Should get dependabot set up so we don't have to do this manually in the future.
=> MNT: Use setup-python v5 in Actions

.github/dependabot.yml
So PR like #2613 can be automated in the future. This config is copied over from `astropy`. No need for backport.
=> DEV: Dependabot for Actions auto-update

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue
=> Manual Backport PR #2606 on branch v3.8.x (stretch histogram: handle mixed state)

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py, jdaviz/core/template_mixin.py
This pull request extends on #2606 to support the interactive splines introduced in #2545.  Its a separate PR as #2606 was milestones for a bugfix release that does not include #2545.
https://github.com/spacetelescope/jdaviz/assets/877591/828ee4e3-a9ac-43da-ae28-c45319b55142
=> handle mixed state for stretch params (knots)

jdaviz/app.vue
This pull request is a manual backport of PR #2625 (css has since been moved from `app.vue` to `main_styles.vue`).
=> always hide button to close group of tabs

CHANGES.rst, jdaviz/configs/default/plugins/viewers.py, jdaviz/core/helpers.py, jdaviz/core/user_api.py, jdaviz/tests/test_user_api.py
This pull request fixes the keys in `imviz.viewers` for additional viewers to fallback on the id when reference does not exist so the keys are not `None`, but rather `imviz-2`, etc.  
=> helper.viewers dict to better generalize reference vs id

docs/dev/release.rst
I noticed outdated text while doing v3.8.1 release:
* `astroconda` is not a thing anymore.
* Looks like now we release via GitHub UI, not pushing a tag manually, so the "check Release" text makes no sense.
This is the same as #2634 except I needed to fix the labeler workflow on `main` and then re-open this PR as new so the labeler would be happy. My bad.
=> DOC: Update release instructions

jdaviz/core/template_mixin.py
This pull request allows setting validation rules for any EditableSelect component.  https://github.com/spacetelescope/lcviz/pull/78 will use and add test coverage for this case.
=> allow validation rules for EditableSelect

jdaviz/core/helpers.py, notebooks/ImvizDitheredExample.ipynb
This pull request is to stop advertising that you can load boolean mask to make cute Space Invaders, as requested by @kecnry and @camipacifici .
Related issues:
* https://github.com/spacetelescope/jdaviz/issues/2638
* https://github.com/glue-viz/glue/issues/2474
=> DOC: Hide boolean mask support in load_regions

jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
This pull request removes a redundant nested instance of parsing the aperture photometry results (probably a botched rebase at some point).
This should not affect behavior (although will likely be more performant 🤞 )
=> aper phot: remove redundant nested table parsing

jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
This pull request is just minor clean-ups to `test_fitting` module that I did while looking to building a test case for #2682 . That PR is currently stuck but this clean-up should be uncontroversial, so I will just merge when CI passes.
In general, we should only ignore warnings on the lines we expect those warnings. Blind ignore on the entire test function, while convenient, is not a good habit. Also I think there is a small typo in the test (didn't really affect the test but also didn't do anything useful with the typo). …
=> TST: Minor clean-up of test_fitting

CHANGES.rst
This pull request updates the changelog to remilestone PR #2697  (since the text that is updated is not present in 3.8.x).
=> re-milestone PR 2697

docs/dev/ui_style_guide.rst, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue, jdaviz/configs/cubeviz/plugins/slice/slice.vue, jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/configs/default/plugins/collapse/collapse.vue, jdaviz/configs/default/plugins/export_plot/export_plot.vue, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue, jdaviz/configs/default/plugins/line_lists/line_lists.vue, jdaviz/configs/default/plugins/markers/markers.vue, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.vue, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/plugins/catalogs/catalogs.vue, jdaviz/configs/imviz/plugins/compass/compass.vue, jdaviz/configs/imviz/plugins/footprints/footprints.vue, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.vue, jdaviz/configs/imviz/plugins/orientation/orientation.vue, jdaviz/configs/imviz/plugins/rotate_canvas/rotate_canvas.vue, jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.vue, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/core/template_mixin.py
This pull request allows overriding the plugin description text in the plugin's python class, so that there can easily be per-config overrides as well as support for downstream apps to set custom text.
This was split out of #2706 to be applied to all plugins as well as the style guide.
=> allow downstream apps or config-specific override to docs description

.github/workflows/check_milestone.yml
This pull request is to backport milestone check directly to v3.8.x since it refuses to pass for #2728 .
=> Backport milestone check workflow

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_list_mixin.py, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py, jdaviz/configs/specviz/plugins/viewers.py
This pull request is to address PR 2726, in the link below:
https://github.com/spacetelescope/jdaviz/pull/2726
=> Backport PR #2726 on branch v3.8.x (loading line lists at redshifted wavelength)

jdaviz/configs/imviz/plugins/catalogs/catalogs.py, jdaviz/configs/imviz/tests/test_catalogs.py
Catalogs test was failing but I don't know why because it passes locally. Should bubble up the exception next time.
Example failing log: https://github.com/spacetelescope/jdaviz/actions/runs/8157866577/job/22298471598
=> TST: Catalogs failure to bubble up when fails

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue, jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/configs/default/plugins/collapse/collapse.vue
Save as FITS was not available through the API, so I think this is all that's needed.
=> Add deprecation warning in UI for moment map export

jdaviz/configs/default/plugins/export/export.py, jdaviz/configs/default/plugins/export/export.vue, jdaviz/configs/default/plugins/export/tests/test_export.py, jdaviz/conftest.py
This pull request is to emit warning when user is about to overwrite an existing file in export plugin. However, I was also given the understanding that this functionality would be replace by Solara in the future anyway, as not to make it too fancy.
Also see:
* https://github.com/spacetelescope/jdaviz/pull/2755#pullrequestreview-1946978522
* https://github.com/spacetelescope/jdaviz/pull/2760
=> export plugin: warning before overwriting files

CHANGES.rst
=> adding 3.10 to change log

docs/specviz2d/import_data.rst, docs/specviz2d/index.rst, docs/specviz2d/plugins.rst
Updates to the docs for specviz2d. Need to check if the gif is too slow or ok when it renders.
=> Docs specviz2d

CHANGES.rst, jdaviz/configs/imviz/plugins/orientation/orientation.py, jdaviz/configs/imviz/tests/test_orientation.py, jdaviz/core/freezable_state.py
Forgot to add backport label to original PR. #2789
=> Backport PR 2789 to v3.9.x (Orientation with empty viewer)

CHANGES.rst, jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
This pull request sends any exceptions in spectral extraction to the snackbar.  We should still aim to *prevent* errors by disabling the button, whenever possible, but this can catch any remaining exceptions instead of burying them.
=> cubeviz spectral extraction: send exceptions to snackbar

CHANGES.rst, jdaviz/app.py, pyproject.toml
=> backport of #2820

CHANGES.rst, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/default/plugins/viewers.py, jdaviz/configs/imviz/helper.py
This is a manual backport of #2818 (conflicts with DQ plugin additions on main that are not in 3.9.x).
=> backport of #2818

CHANGES.rst, jdaviz/configs/cubeviz/plugins/tests/test_export_plots.py, jdaviz/configs/default/plugins/export/export.py, jdaviz/configs/default/plugins/export/export.vue, jdaviz/configs/default/plugins/export/tests/test_export.py, jdaviz/core/template_mixin.py
This pull request uses the existing `AutoTextField` component for the filename entry in the export plugin.
=> export plugin: auto filename

.github/workflows/standalone.yml
It was just released to address Apple-Actions/import-codesign-certs#57
Not sure how to test this. @rosteen ?
=> BLD: Upgrade import-codesign-certs to v3

jdaviz/app.py, jdaviz/app.vue, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.vue
This pull request hides the toolbar buttons (except for the sidebar hamburger button) during active mouseover to avoid conflict between the mouseover information and the buttons on narrow screens.  This also improves the styling and layout of the mouseover information to avoid displacement in the layer icon when entering/leaving mouseover.
https://github.com/spacetelescope/jdaviz/assets/877591/938e637a-2e0f-4266-8ba7-72afe620446d
=> App toolbar buttons dodge mouseover info

jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/default/plugins/viewers.py, jdaviz/core/template_mixin.py
This pull request further generalizes the viewer slices logic (used for the slice plugin) to be less spectral-axis specific.  This is not expected to have any behavior consequences in jdaviz, but fixes support for slicing in lcviz (and other future downstream uses).
Closes #2253
=> Generalize viewer slices logic

jdaviz/configs/default/plugins/plot_options/plot_options.vue
This pull request makes some style tweaks on top of #2894 based on feedback from @Jenneh
**Before**:
**After**:
=> small style tweaks to color mode dropdown

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_aperphot.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/tests/test_simple_aper_phot.py, jdaviz/core/tests/test_tools.py, jdaviz/tests/test_utils.py
This pull request is to manually backport #2905 but only photutils changes are relevant here.
No need for review. I will merge if devdeps indeed turns green.
=> Manual backport of PR 2905 to v3.10.x (Fix devdeps)

CHANGES.rst, CITATION.cff
Prep for release of bugfix v3.10.2.
=> Preparing release v3.10.2

CHANGES.rst
Replaces https://github.com/spacetelescope/jdaviz/pull/2919. 
=> Changelog update for dev on v3.10.3

.github/workflows/standalone.yml
=> Add scipy subdirectory to dylib deletion

.github/workflows/standalone.yml
Backport OSX standalone changes for https://github.com/spacetelescope/jdaviz/pull/2927
=> BLD: Backport OSX standalone changes

.github/workflows/standalone.yml
I missed that this is different from the rest.
=> Fix path in previous build fix

jdaviz/configs/imviz/tests/test_catalogs.py, standalone/jdaviz-cli-entrypoint.py
=> Backport PR #2944 on branch v3.10.x (fix: make standalone work with matplotlib >= 3.9.0)

.github/workflows/standalone.yml
I guess I did not consistently backport the workflow stuff. Need this to backport #2946
=> Sync standalone.yml with main

jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/default/plugins/subset_plugin/tests/test_subset_plugin.py
This pull request is to create a private method for import spectral region objects into the spectrum viewer. This method will be called in the general `import_region`  method which will be implemented in the subset plugin soon.
=> Create private method for importing spectral region objects

CHANGES.rst, CITATION.cff
=> Preparing release v3.10.3

CHANGES.rst
Date for v3.10.3, empty section for v3.10.4.
=> Changelog update for release of v3.10.3

jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py, jdaviz/models/physical_models.py
This pull request is to exorcise a small technical debt.
=> MNT: Remove unused astropy version check, update doctest

CHANGES.rst
I should really stop doing this 😅.
=> Remilestone 3133 to 4.0

jdaviz/configs/cubeviz/plugins/spectral_extraction/spectral_extraction.py
This pull request is to remove snackbar message because it is spamming the app, as originally discussed in #3118 .
=> BUG: Remove spammy snackbar message

docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.vue
This pull request fixes some outdates/broken links from the app to the docs.
=> update docs links

docs/conf.py, docs/imviz/import_data.rst, docs/index.rst, docs/installation.rst, docs/rampviz/import_data.rst, docs/rampviz/index.rst, docs/rampviz/plugins.rst
Add note in the docs that Rampviz is in development, remove/replace placeholder (Cubeviz) logo used in places for Rampviz, add a subsection in the installation instructions for optional Roman dep installs, add links to the new optional deps subsection in the Imviz and Rampviz import data docs.
=> Rampviz docs update

jdaviz/app.py, jdaviz/configs/default/plugins/data_menu/__init__.py, jdaviz/configs/default/plugins/data_menu/data_menu.py, jdaviz/configs/default/plugins/data_menu/data_menu.vue, jdaviz/configs/default/plugins/viewers.py, jdaviz/container.vue, jdaviz/core/events.py, jdaviz/core/template_mixin.py
This pull request builds the infrastructure for the currrent viewer legend (which will eventually become the new data menu) to eventually be accessible via `viewer.data_menu` using the same framework as the sidebar plugins (with user-APIs and a direct connection between the python and vue template, rather than relying on the `viewer_item` defined in `app.py`).
=> data menu infrastructure

jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/configs/specviz/tests/test_viewers.py, jdaviz/core/template_mixin.py
This pull request is an alternative to https://github.com/spacetelescope/jdaviz/pull/3168 . This patch avoid actually converting the spectrum. And it also avoids adding yet another listener (fear of further performance impact). It targets only where this particular bug is happening in the `add_results_to_plugin` method.
Close https://github.com/spacetelescope/jdaviz/pull/3168
=> BUG: Fix spectral extraction in the presence of unit conversion (no actual conversion, no new callback)

jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
Trivial, changed a traitlet name in the vue file to fix aperture phot UI.
=> updated vue file

pyproject.toml
This pull request fixes popout support after solara replaced voila in #2909.  Note that solara (and possibly ipypopout) must be installed in the environment running jupyter for popouts to work (not only the notebook kernel environment).
For MAST that is using voila to run jdaviz, ipypopout _should_ still function without solara installed.
=> Fix popouts without voila

CHANGES.rst, notebooks/concepts/imviz_roman_asdf.ipynb
Updating the example files in the `imviz_roman_asdf.ipynb` concept notebook. I've also added an `assert` for the `rad`/`roman_datamodels` versions to catch mismatches between dependencies and the example data. cc @PaulHuwe
Fixes #3344
=> Example Roman L2 notebook update since B16

jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue
trivial, just a missing quote that i noticed while reviewing another PR
=> spectral extraction api hint

jdaviz/components/plugin_dataset_select.vue
This pull request fixes a typo that prevented the dataset dropdown from appearing in plugins.  This was introduced by #3281 and so never appeared in a release.
=> fix typo in plugin-dataset-select preventing showing dropdown

.github/workflows/standalone.yml
=> Debug standalone build for MacOS

jdaviz/configs/default/tests/test_data_menu.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/core/tests/test_config_detection.py, jdaviz/tests/test_utils.py, notebooks/Specviz2dExample.ipynb
This pull request is to unskip a test skipped in https://github.com/spacetelescope/jdaviz/pull/3283 and replace broken Specviz2d example notebook. Also fix #2197
The new data, even though looking good visually, does not play nice with default spectral extraction, so I added a section in example notebook to re-extract, so it would look like this:
Fixing spectral extraction default setting is out of scope here.
=> Replace broken specviz2d data in test and notebook

jdaviz/configs/default/tests/test_data_menu.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/core/tests/test_data_menu.py, jdaviz/tests/test_utils.py, notebooks/Specviz2dExample.ipynb, tox.ini
This pull request is to manually backport #3431
=> Backport PR #3431 on branch v4.1.x (Replace broken specviz2d data in test and notebook)

CHANGES.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue
This pull request adds a missing user API entry for `export_bg_spectrum()` in spectral extraction in specviz 2d and updates the API hint to match.
=> add missing exposed export_bg_spectrum and API hint

CHANGES.rst, jdaviz/configs/imviz/plugins/catalogs/catalogs.py, jdaviz/configs/imviz/tests/test_catalogs.py
=> Backport PR #3464 on branch v4.1.x (Fix incorrect matching of skycoords with pixel coords in catalog results)"

CHANGES.rst, jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
This pull request improves the logic for determining the default trace location in specviz2d's spectral extraction by ignoring columns (along the spectral axis) where the median flux is at or below zero or nans (which was previously artificially "pulling" down the estimated trace location).
=> spectral extraction: improve default guess for trace location

CHANGES.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
=> Manual backport of #3475

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/default/plugins/subset_tools/subset_tools.py, jdaviz/configs/default/plugins/subset_tools/subset_tools.vue, jdaviz/configs/default/plugins/subset_tools/tests/test_subset_tools.py
Opening as draft since I'm not sure if I'm happy with this implementation yet. I also still need to handle the special case of changing center of annulus properly and then deprecate `set_center`.
=> Add Subset Tools API method to update subset

.github/workflows/standalone.yml
This will only run on main, just have to merge and see if it works 😬
=> Add scipy file removal to macos step

.github/workflows/standalone.yml
=> Install qt for mac standalone

tox.ini
add specreduce to dev test (will pass after https://github.com/astropy/specreduce/pull/256)
=> add specreduce to dev test

CHANGES.rst, jdaviz/components/plugin_table.vue, jdaviz/core/template_mixin.py
A quick PR to expose the `single_select` attribute on the Table Mixin. Included this in the block with the warning that it isn't tested, similar to #2856. Will add changelog once a number is assigned
=> Expose Table Mixin Single Select

.github/workflows/standalone.yml
Simple enough. Can't test in CI.
=> Unpin max pyinstaller

.github/workflows/ci_workflows.yml, .github/workflows/predeps_workflows.yml, .github/workflows/publish.yml, CHANGES.rst, docs/imviz/plugins.rst, docs/index.rst, docs/installation.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/tests/test_simple_aper_phot.py, jdaviz/core/region_translators.py, jdaviz/core/tests/test_region_translators.py, pyproject.toml
This pull request is to use photutils for radial profile and curve of growth calculations. 
* Radial profile calculation now deviates from imexam algorithm.
* Curve of growth always uses circular aperture behind the scenes now, regardless of selected Subset shape.
* Raw radial profile requires bump to `photutils>=2.2`.
* Bump to `photutils>=2.2` requires Python 3.11 or later.
References:
* https://photutils.readthedocs.io/en/stable/api/photutils.profiles.RadialProfile.html
* https://gist.github.com/larrybradley/308dda15f7ed3c5bebb7d47830a410af
**After merge:** Repo admin need to update branch protection rules for Windows job.
This checklist …
=> RFC: Radial profile and CoG using photutils.profiles

CHANGES.rst, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/tests/test_utils.py, jdaviz/utils.py, pyproject.toml
This pull request enhances data loading capabilities by adding support for loading FITS files from S3.
=> Load data via s3 uri

jdaviz/configs/default/plugins/data_menu/data_menu.vue, jdaviz/configs/default/plugins/markers/markers.py, jdaviz/configs/default/plugins/subset_tools/subset_tools.py, jdaviz/configs/imviz/helper.py, jdaviz/core/astrowidgets_api.py, jdaviz/core/helpers.py
This pull request updates UI elements, API docs, error messages from the previous "linked" terminology to "aligned".
=> update linked -> aligned

CHANGES.rst, jdaviz/configs/imviz/plugins/footprints/footprints.py, jdaviz/core/marks.py
This PR visually highlights the selected footprint overlay by increasing its stroke width. This helps users easily distinguish the currently selected region in the viewer.
https://github.com/user-attachments/assets/3c145b16-7269-42e9-ab92-865a9aed7af3
=> Make selected footprint overlays more visible

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/cubeviz/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/configs/cubeviz/plugins/tests/test_regions.py, jdaviz/configs/default/plugins/export/tests/test_export.py, jdaviz/configs/default/plugins/subset_tools/subset_tools.py, jdaviz/configs/default/plugins/subset_tools/tests/test_subset_tools.py, jdaviz/configs/imviz/tests/test_regions.py, jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py, jdaviz/tests/test_subsets.py
This pull request changes the default behavior of `viz.plugins['Subset Tools'].import_region()` to create a new region unless `combination_mode='replace'`.
- Change behavior of `import_region` method to default to creating a new subset when run. Also allow editing a subset using the `edit_subset` argument.
=> Switch default import_region behavior to create a new subset

CHANGES.rst, jdaviz/configs/imviz/plugins/footprints/footprints.py, jdaviz/core/marks.py
This PR addresses a [comment](https://github.com/spacetelescope/jdaviz/pull/3546#discussion_r2049438487) left on [PR#3546](https://github.com/spacetelescope/jdaviz/pull/3546) regarding reformatting of the logic included to make selected footprint overlays more visible. 
The same tests were performed to ensure that the functionality of the changes remains correct
https://github.com/user-attachments/assets/5ae10925-6e27-444d-a1d7-fa916fa6a3bb
=> Reformat PR#3546

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/data_menu/data_menu.py, jdaviz/configs/imviz/tests/test_viewers.py
This pull request fixes the traceback caused when switching alignment on a second imviz viewer.  See regression tests on how to reproduce on main.
=> Imviz mult viewer wcs link

jdaviz/core/template_mixin.py
=> temp fix: auto_label python 3.11

CHANGES.rst, jdaviz/components/plugin_table.vue, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/tests/test_lineflux.py
This pull request implements a results table for line analysis and implements a button to both expose current results and add to the table (behavior change: the current results table used to update to the change in any input, now the continuum previews update, but require clicking the button in order to view the results and add to the table.  Note that the old API for `get_results` still exists and calculates and returns the current results, with an optional kwarg to control whether they are appended to the table or not).
https://github.com/user-attachments/assets/3291bdbb-bf4b-4428-8b72-d3e348a80177 …
=> Line analysis results table

docs/cubeviz/export_data.rst
I searched if this was already being updated in some PR as part of the subset api work, but I did not find anything. Apologies if I missed it. Here I update the calls to get subsets and aperture photometry.
=> Docs: update export stuff to go through plugin for cubeviz

CHANGES.rst, jdaviz/configs/mosviz/helper.py
=> Fix exception on Mosviz s2d

CHANGES.rst, jdaviz/configs/mosviz/helper.py
=> Auto backport of pr 3570 on v4.2.x

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/subset_tools/subset_tools.py, jdaviz/configs/default/plugins/subset_tools/tests/test_subset_tools.py, jdaviz/tests/test_subsets.py
(cherry picked from commit 73867767fabb29848a2a8334959972519880aaa2)
=> fix andNot subset bug (#3547)

jdaviz/app.py
This has been annoying me for a while. Any objections to just suppressing it?
=> Suppress this annoying repeated warning app-wide

CHANGES.rst, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/core/astrowidgets_api.py
=> Manual backport of PR 3576

CHANGES.rst, CITATION.cff
updated change log for main branch, post 4.2.2 release
=> back to development, 4.2.dev

CHANGES.rst, jdaviz/components/loader.vue, jdaviz/core/loaders/resolvers/file/file.vue, jdaviz/core/loaders/resolvers/resolver.py
=> Auto backport of pr 3593 on v4.2.x

.github/workflows/ci_workflows.yml, jdaviz/configs/specviz2d/tests/test_parsers.py, jdaviz/core/loaders/resolvers/resolver.py
Opening as draft, as I want to see the CI run on this but I'd like to generalize this for all the tests. Not sure if it works to put it in conftest.py or not.
=> Tweaks to help debug failed remote data jobs

.github/CODEOWNERS
=> Add Matthew Portman to codeowners

jdaviz/configs/default/plugins/data_quality/tests/test_data_quality.py, jdaviz/core/tests/test_autoconfig.py, jdaviz/core/tests/test_config_detection.py, jdaviz/tests/test_utils.py
Reprocessing changed these filenames again...
=> Update MIRI filenames for test data

CHANGES.rst, jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/collapse/tests/test_collapse.py
This pull request is to address backport issue.   Manual backport of #3604 
=> Backport PR #3604 on branch v4.2.x (Catch vue_collapse exception and broadcast snackbar message, added test)

docs/conf.py
Link to the specutils 1.20.3 docs until my 2.0 compatibility PR is merged.
=> Link to specutils 1.20.3 docs

tox.ini
Adds echo to the list of dependencies we include in ``-devdeps``
=> Include echo in developer dependencies

CHANGES.rst, jdaviz/components/plugin_editable_select.vue
This pull request fixes a bug inadvertently introduced in #3623 that results in editable select components from not showing in the UI
=> fix bug hiding editable select UI

CHANGES.rst, jdaviz/configs/cubeviz/plugins/sonify_data/sonify_data.py
This pull request adds a snackbar message when sonification of a data cube completes.
=> add successful sonified data snackbar message

jdaviz/core/loaders/resolvers/resolver.py
This pull request implements a `resolver.defer_update_format_items()` context manager to delay calling the resolver during `Resolver.from_input(...)` until all traitlets are set.  This improves performance but also prevents cases where URL could in theory download multiple times, needlessly.
=> loaders: defer calling resolver while initializing kwargs

jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/wcs_utils.py, jdaviz/configs/specviz2d/tests/test_parsers.py, jdaviz/core/loaders/importers/__init__.py, jdaviz/core/loaders/importers/image/__init__.py, jdaviz/core/loaders/importers/image/image.py, jdaviz/core/loaders/importers/image/image.vue, jdaviz/core/loaders/importers/importer.py, jdaviz/core/loaders/parsers/__init__.py, jdaviz/core/loaders/parsers/asdf.py, jdaviz/core/loaders/test_loaders.py, jdaviz/core/viewer_creators/test_viewer_creators.py
This pull request moves data importing in Imviz to the new loaders infrastructure.
=> Enable imviz loaders

.github/workflows/ci_workflows.yml
We have been receiving the following [code coverage errors](https://app.codecov.io/gh/spacetelescope/jdaviz/commit/f0a29c60992df9cd5a790cfc6ffa01d2cb7d2882)
> Unusable report due to issues such as source code unavailability, path mismatch, empty report, or incorrect data format. Please visit our [troubleshooting document](https://docs.codecov.com/docs/error-reference#unusable-reports)
for assistance.
After investigation, it seems to be related to the following bug in codecov:
- https://github.com/codecov/codecov-action/issues/1801
An effective workaround was identified by adding a checkout step to the job that uploads the coverage report to CodeCov.
- https://github.com/inclusive-design/idrc-cms-authenticator/pull/137
list the proposed change log here for review and add to `CHANGES.rst` …
=> [bug] address codecov upload issue

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/markers/markers.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/catalogs/catalogs.py, jdaviz/configs/imviz/plugins/compass/compass.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/configs/imviz/plugins/footprints/footprints.py, jdaviz/configs/imviz/plugins/footprints/footprints.vue, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py, jdaviz/configs/imviz/tests/utils.py, jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue, jdaviz/conftest.py, jdaviz/core/helpers.py, jdaviz/core/loaders/importers/image/image.py, jdaviz/core/loaders/importers/importer.py, jdaviz/core/template_mixin.py, jdaviz/core/viewer_creators/__init__.py, jdaviz/core/viewer_creators/image/image.py, jdaviz/core/viewer_creators/test_viewer_creators.py
This pull request:
* brings context-aware imviz plugins (with the exception of the orientation plugin) to the deconfigged app
* adds unit conversion support for image data/viewers.  
* adds image viewer support to the viewer creator
This intentionally does not yet:
* add support for the orientation plugin: rotation, sky linking, etc.
* ensure support for mixed-workflows between spectra and images (loading a spectrum after loading an image will almost definitely result in a traceback)
* support multiple images (requires general linking support)
```
import jdaviz as jd
jd.load('mast:JWST/product/jw02727-o002_t062_nircam_clear-f090w_i2d.fits')
jd.show()
```
https://github.com/user-attachments/assets/1f8500ee-e0cc-4c39-8d1d-10af500c5b80 …
=> Deconfigged: imviz plugins

jdaviz/app.py, jdaviz/app.vue, jdaviz/container.vue, jdaviz/core/template_mixin.py
This pull request fixes an unreleased bug found in #3577 (see https://github.com/spacetelescope/jdaviz/pull/3577#issuecomment-2901675699) related to the viewer layout breaking after removing a viewer in a row.
=> Fix viewer layout after removing row

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/default/plugins/markers/markers.py, jdaviz/configs/default/plugins/markers/markers.vue, jdaviz/configs/imviz/tests/test_orientation.py, jdaviz/core/marks.py
=> Started work on Distance Tool

docs/cubeviz/displaycubes.rst, docs/cubeviz/export_data.rst, docs/cubeviz/plugins.rst, docs/dev/infrastructure.rst, docs/dev/links.rst, docs/dev/release.rst, docs/dev/specviz_selection.rst, docs/dev/ui_description.rst, docs/dev/ui_plugin_components.rst, docs/dev/ui_style_guide.rst, docs/dev/win_dev.rst, docs/imviz/displayimages.rst, docs/imviz/export_data.rst, docs/imviz/import_data.rst, docs/imviz/plugins.rst, docs/index.rst, docs/index_jwst_modes.rst, docs/mosviz/displayspectra.rst, docs/mosviz/plugins.rst, docs/rampviz/plugins.rst, docs/specviz/displaying.rst, docs/specviz/plugins.rst, docs/specviz2d/plugins.rst, docs/video_tutorials.rst, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py
This pull request is to address updates/revisions to the dev portion of the documentation.
I have additionally updated labels in the rest of the docs (notably for Imviz) to be more consistent,
i.e. dashes instead of underscores for page labels. Using the powers of grep, I believe I caught them 
all but it's possible that I may have a missed a few.
=> Read dev docs

CHANGES.rst, jdaviz/configs/default/plugins/markers/markers.py, jdaviz/configs/default/plugins/markers/tests/test_markers_plugin.py, jdaviz/core/marks.py, pyproject.toml
This PR enhances the distance measurement tool in the Markers plugin.
Key updates include a real-time preview line that follows the cursor and new support for measuring Δx and Δy in profile viewers (e.g., in Specviz and Cubeviz). This provides immediate visual feedback and extends the tool's functionality across different Jdaviz configurations.
=> Expand Distance Tool

CHANGES.rst, jdaviz/configs/default/plugins/markers/markers.py, jdaviz/configs/default/plugins/markers/tests/test_markers_plugin.py, jdaviz/core/marks.py
I was going to revamp the `DistanceMeasurement` class a bit more to have it subclass from `PluginLine` directly, but this ended up being the simplest fix for the unit change problem.
=> Update distance measurement marks on unit change

CHANGES.rst, docs/specviz/plugins.rst, jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
This pull request adds the ability to select a different fitter for model fitting and adjust the parameters for it accordingly.
=> Expose fitters in Model Fitting

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
=> Backport of PR 3741: Forbid polynomial order < 0 (#3741)

jdaviz/configs/default/plugins/virtual_observatory/tests/test_vo_imviz.py
This pull request temporarily skips a failing VO test that we've been ignoring for a while so that coverage can succeed and unblock PRs.  A ticket has been created to investigate/fix the test.
=> skip failing VO test

CHANGES.rst, jdaviz/app.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/configs/specviz2d/tests/test_parsers.py, jdaviz/core/loaders/tests/test_loaders.py, jdaviz/tests/test_subsets.py
This pull request fixes a bug where subsets created in the 2d viewer of specviz2d were not linking correctly with the 1d viewer. It adds links for this particular case and updates test coverage for this bug (which now uses remote data and does indeed fail on main).
=> add specific links for specviz2d subsets, update test coverage
