jdaviz/mast/mast_index.html
This PR creates a basic MAST index html page.  This page contains some basic html and javascript independent of any web server or kernel.  It contains 
- an empty placeholder div to place a `cubeviz` ipywidget into
- an HTML table with some placeholders buttons to do eventual server-side calls
- an empty placeholder div for a `table` widget.  
It should load and run locally in your browser.  The HTML table is a sortable placeholder table.  You can select rows and the `doStuff` button alerts you what you've selected.  (To be replaced by server-side call to **do stuff**) . The `getStuff` button alerts you it's ready to get stuff. (To be replaced by server-side call to **get stuff**).  The table content we can update to be more relevant once we start to get the server stuff off the ground. …
=> adding mast index html page

jdaviz/vizcomponents/viewer/viewer1d.py, jdaviz/vizcomponents/viewer/viewernd.py
This PR fixes some oddities I noticed about getSpectrum1D. More specifically it does the following:
1. Fixes the `Spectrum1D` invocation to properly give the spectral axis (see astropy/specutils#466
2. changes the profile viewer `getSpectrum1D` to yield the spectrum as shown in the profile viewer
3. adds a `getSpectrum1D` to the `ViewerND` which gets the subsets *without* the "profile" collapsing.  That is, it gets the true data cube.  (This is probably wrong for some datasets where the wavelength array is not the same at every spaxel, but that's a problem for another day)
4. changes both to `get_spectrum1D`
There's a bit of data-specific hackery I did with the unit parsing... @astrofrog might advise if there's an easy way to get out the "wave" and "flux" units more cleanly.  But if not I …
=> fix up getSpectrum1D

examples/cubeviz-example.ipynb, jdaviz/vizcomponents/applications/cubeviz.py, jdaviz/vizcomponents/viewer/viewer1d.py
This adjusts the cubeviz notebook and some of the corresponding code to demo using the notebook idiom to combine an "interactive" and "notebook" usage.
1. It fixes up the units from the original data file to be in angstroms.  To do this I had to do a slightly hacky thing in the cubeviz initializer, but I think it's probably fine as a stand-in.  Moving forward we'll probably want to instead allow passing in data objects instead of names, but this seemed the fastest route forward.  Note @brechmos-stsci - if you want to keep using the "fixed" file, you could just delete the `process_data` part and I presume it'll be the same
2. It adds some analysis using specutils at the bottom of the notebook.
3. it renames `getRegions` to `get_regions` since that's now showcased in the notebook
The last …
=> Add notebook interactions to spec1d cubeviz example

.gitignore, .rtd-environment.yml, .travis.yml, docs/conf.py, jdaviz/core/registries.py, jdaviz/data/README.rst, jdaviz/tests/test_registries.py, setup.cfg
This supports the effort of designing the default glue-jupyter application infrastructure in which layouts are composed of reference plugin objects living in registries. This PR defines the registries and their interactions.
=> Implement registries for plugins

jdaviz/app.py, jdaviz/components/file_loader/__init__.py, jdaviz/components/file_loader/file_loader.py, jdaviz/components/file_loader/file_loader.vue, jdaviz/components/tray_area/tray_area.py, jdaviz/components/tray_area/tray_area.vue, jdaviz/components/viewer_area/stack.vue, jdaviz/configs/default/plugins/gaussian_smoothing/gaussian_smoothing.vue
This PR introduces a basic file loading dialog that asks the user to input an absolute file path. It checks whether the file exists and disallows loading attempts if it does not.
Note that this does not currently use the specutils loading machinery, but instead directly utilizes glue. This is an on-going conversation about how best to handle this in the UI.
=> Implement basic UI for file loading

jdaviz/container.vue
The v-sheet is added to give the options panel a background-color,
which is otherwise transparent for the part initially outside the
viewport.
Needs https://github.com/glue-viz/glue-jupyter/pull/172 and https://github.com/glue-viz/glue-jupyter/pull/173 to be complete.
=> fix: make glue option tabs look good

jdaviz/app.vue
In the notebook context the Vuetify styles for the ul tag win from
the goldenlayout styles because of the extra .vuetify-styles
prefix used.
=> fix: padding of goldenlayout tabs is different in notebook context

jdaviz/app.vue
Use two selectors, one for Voila and one for the notebook context.
Vuetify styles in the notebook are prefixed with .vuetify-styles
and if that's not repeated here, this selector looses on
specificity.
=> fix: toolbar padding is different in the notebook context

share/jupyter/voila/templates/jdaviz-default/nbconvert_templates/voila.tpl
Viola template vuetify version is incorrect and causes the web browser version to not load. This fixes the issue.
=> Fix vuetify version in template

jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/collapse/tests/test_collapse.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/configs/default/plugins/viewers.py, jdaviz/conftest.py, jdaviz/core/registries.py
In general, glue never silently links data together, so it's always up to the code using glue to set up links if needed. This could include calling the auto-linking helper which suggests links to use, but it's also possible to just specify the links explicitly.
Whenever possible, pixel to pixel links should be used rather than WCS links, since this offers better performance. In the case of collapsing the data or smoothing it, we know that there is a one-to-one mapping of some of the pixel axes, so we can set up the links in this way.
I've added tests for the collapsing and Gaussian smoothing specifically to check the links, but I noticed that there are no tests otherwise. I would highly recommend starting to add tests for simple plugins as this, and hopefully tħe ones I've added can be …
=> Fix linking of smoothed and collapsed data

jdaviz/app.py, jdaviz/app.vue, jdaviz/configs/cubeviz/cubeviz.yaml, jdaviz/configs/cubeviz/plugins/unified_slider/unified_slider.py, jdaviz/configs/default/default.yaml, jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/collapse/collapse.vue, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue, jdaviz/container.vue, jdaviz/core/events.py, setup.cfg
Resolves #102. This PR moves the plugins from modal popups to accordion tray items as shown below.
=> Move plugins to tray area

jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/core/registries.py
This fixes the build errors seen in #127. Currently, the tray registry does not return the stored cls object on call and therefore does not get access to the plugin class proper.
=> Fix failing test by return stored cls in registry

jdaviz/app.py, jdaviz/configs/cubeviz/cubeviz.yaml, jdaviz/configs/default/plugins/model_fitting/initializers.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/container.vue, jdaviz/core/events.py
This PR adds a model fitting plugin, which pulls 1D spectra from the spectrum viewer and gives the user similar options to those in the old specutils. I still have some debugging to do, since it looks like the model parameters aren't being updated after fitting the model, but I wanted to make this available to get other eyes on it for comments/suggestions. Note that this depends on https://github.com/spacetelescope/jdaviz/pull/114.
=> Model Fitting UI Plugin

jdaviz/app.py, jdaviz/configs/__init__.py, jdaviz/configs/mosviz/__init__.py, jdaviz/configs/mosviz/mosviz.ipynb, jdaviz/configs/mosviz/mosviz.yaml, jdaviz/configs/mosviz/plugins/__init__.py, jdaviz/configs/mosviz/plugins/viewers.py, notebooks/concepts/mosviz_overplot_slit_example.ipynb, setup.cfg
This PR adds the mosviz config layout. The mosviz.ipynb file also contains the beginnings of the slit implementation using `bqplot.marks.Lines`. If you run the notebook, the viewer that is created in the bottom cell allows for panning of the image viewer where the red outline ("slit" in this case) follows the viewer. However, if you go back to the top (the main jdaviz app view), panning **does not** move the slit with the image viewer. I will continue to investigate this behavior but I would appreciate input from @nmearl and @mariobuikhuizen on how to proceed from here.
=> MOSViz config and notebook for testing slits

jdaviz/app.py, jdaviz/configs/cubeviz/cubeviz.yaml, jdaviz/configs/cubeviz/plugins/__init__.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/cubeviz/plugins/utils.py, jdaviz/core/registries.py, jdaviz/utils.py
This PR allows for defining a parsing function that takes in data and attempts to place it in the correct viewers. The parsing function is specific to the application instance and the reference is defined in the yaml file.
In this case, we use spectral cube to read the incoming data. There are several issues with this approach, mainly: `SpectralCube` doesn't handle uncertainties, and `SpectralCube` is only capable of parsing three dimensional data. Thus, with this approach, we do not load non-cube like data.
Alternatives include fixing specutils to properly handle and parse all aspects of cube data, but that may be for a future PR.
=> Auto-populate cubeviz viewers

jdaviz/app.py, jdaviz/configs/specviz/helper.py
This PR allows for extracting subsets as `SpectralRegion` objects from the specviz app. Requires #159.
=> Extract SpectralRegions from specviz app

jdaviz/app.py
=> Include data units in plot axes

notebooks/Minimal Specviz.ipynb
The version of the minimal specviz notebook from #179 was somewhat incomplete as a science workflow.  This PR updates it to be a complete (if short) scientific "story". 
There's still one cell that has a "needs to be fixed" element (related to issues with the window machinery in `specutils.analysis.fit_lines`), but that will  require a specutils update so I think we can do one more follow-on when that's in specutils.
=> Update minimal specviz notebook for more complete workflow

jdaviz/configs/default/plugins/data_tools/data_tools.vue, setup.cfg
This is now fixed in ipyvuetify 1.4.1
See: #123
=> fix: prevent notebook from capturing key events from overlay content

jdaviz/app.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/specviz/helper.py
Previously, datasets loaded after the first were not able to be plotted at the same time as previous datasets in the profile viewer. This fixes that by "blindly" linking subsequent datasets to ones that were loaded earlier, without any consideration of whether their units are the same and such. It sounded from discussion offline today that we intend to add intelligent unit conversion to have datasets match in a later PR.
I ended up putting this in the top level jdaviz app rather than at a lower level like the spectrum viewer, with the assumption that we're going to be standardizing around the parser model of data loading, rather than what I was seeing currently with a separate load_data function in the specviz helper.
=> Enable overplotting additional data via linking

jdaviz/app.py, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, jdaviz/utils.py
Resolves #185. Fixes an issue when manipulating the data collection that could result in an infinite loop occurring with the toggled data list items.
🚨**NOTE FOR FUTURE REFERENCE**🚨 Please, do not attempt to alter application state from within plugins! This can have obviously unintended consequences due to event ordering!
=> Fix infinite toggle loop

jdaviz/app.py
Resolves #219. Copies the original subset state, which seemed to have attribute assignment back-propagated when constructing new subset groups (which we did not want).
=> Copy subset state to avoid storing attribute reference

docs/index.rst, docs/specviz/displaying.rst, docs/specviz/import_data.rst, docs/specviz/index.rst, docs/specviz/notebook.rst, docs/specviz/plugins.rst
Just what it says on the tin - a currently-unpopulated outline of the docs to be followed with PRs populating the sections.
=> add outline of specviz docs

jdaviz/app.py, jdaviz/configs/specviz/helper.py
Two small fixes: a typo in the meta data label in the returned data from `app.get_subsets_from_viewer`, and a factor of two in the region edge calculations in `specviz.get_spectral_regions`.
=> Fix two minor bugs in spectral subset/region retrieval

jdaviz/cli.py
Resolves #224. The problem was that, by default, Voila will attempt to read command line arguments, which includes the arguments that are provided to Click. The issue described in #224 is not actually a Click problem, it was the result of `argparse` being used in the traitlet's `Application` class. This PR ensures that argument handling is only done in Click. It also improves the cli help and adds some built-in Click argument value checkers.
=> Fix command line parsing

jdaviz/app.py, jdaviz/app.vue, jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/container.vue, jdaviz/core/events.py
Implements a new option in the model fitting plugin to apply a fit to the entire cube.
Outstanding issues:
The first implementation of the parallelized code was extremely slow because the limiting factor was the communication overhead from the processors. _Every_ spaxel was queued to run on a separate processor (or the next available), so the couple million cross-processor shuttling of serialized data added up. Instead, we now parse the spaxel array into as many chunks as there are processors and let all spaxel subsets run on their respective processor, and only return after _all_ fitting for the subset has occurred. This provides the expected speed.
Likewise, I've also extended the snackbar to support a loading state so that there is feedback to the user while fitting is occuring.
=> Parallel cube fitting

jdaviz/app.py, jdaviz/configs/cubeviz/cubeviz.yaml, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/default/plugins/line_lists/line_list_mixin.py, jdaviz/configs/specviz/helper.py, jdaviz/configs/specviz/plugins/viewers.py
This PR adds line list plugin to the `cubeviz` configuration, and adds helper functions to the `cubeviz` helper to enable the associated command line functionality. From testing, all the UI plugin functionality seems to work as expected in `cubeviz`. I also fixed a bug where the line list plugin would error if all data was unchecked from the spectrum viewer.
This also fixes a bug in the data linking, so that it doesn't attempt to link world coordinates for data that has none.
=> Add line list plugin to cubeviz and do associated debugging

jdaviz/configs/default/plugins/line_lists/line_lists.py
What it says on the tin - fixes a failing test, although I think the root issue is that the data being added in the test isn't compatible with the data translators on the backend and thus cause `get_data_from_viewer("spectrum-viewer")` to fail. So this should be considered a stopgap that gets the tests to pass (since the line list plugin method no longer fails) but doesn't address the underlying issue that the tests might need to be updated to pass better constructed data.
=> Add snackbar warning if data not retrieved

jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/collapse/collapse.vue
Add Subset selection or manual bound entry to the `Collapse` plugin, which are only visible when the spectral axis is selected. This largely duplicates some relevant code from the `Moment Maps` plugin, but I didn't immediately see an elegant way to pull the shared code out to something both could import from. It's not that much code, so a little duplication is probably alright.
=> Enable collapsing over a spectral region

jdaviz/configs/specviz/specviz.yaml
That's it. Just that. It kind of pained me to go through the whole process for just a single line change... but I have to be a "good developer" or something :P
For actual detail, the collapse plugin only makes sense in a cube scenario (collapsing the multiple dimensions of a cube down into a 2D product). Thus, it should only be included in cubeviz, and not in specviz
=> Remove collapse plugin from SpecViz

jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py
What it says in the title. The only hitch I'm seeing is that adding the smoothed data cube to the data collection seems to hit an amount of data that's a bit hard for the app to handle - I'm occasionally getting some `IOPub` message rate limitation errors after adding the smoothed data.
I'll also note that I was never able to get `SpectralCube.spatial_smooth` (which uses parallelization) to work, so this is using the `astropy.convolution.convolve` funtion directly.
=> Add spatial smoothing option for Gaussian Smooth in Cubeviz

jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/mosviz/tests/test_helper.py
Adds `observe` methods on the x-axes of the Mosviz spectrum viewers to update the other spectrum viewer's x scale when one is changed.
Edit: I should also mention that I streamlined the table viewer to send less messages when a row is selected, and not update e.g. the image viewer if the new and old rows share the same image.
=> Link Mosviz spectrum viewer x axes

jdaviz/configs/specviz/plugins/__init__.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/configs/specviz/specviz.yaml, setup.cfg
Adds basic line analysis functionality.
Note that this depends on [glue-astronomy PR 17](https://github.com/glue-viz/glue-astronomy/pull/17)
Also note that it seems that the `specutils.analysis.line_flux` function is broken for masked Spectrum1Ds (this was supposed to be included in [PR 670](https://github.com/astropy/specutils/pull/670) but maybe a bug slipped through?) - do we want to remove that from the analysis options until there's a fix, or should I try to figure out what's wrong in this PR? Currently that function always returns a NaN result for a masked input.
=> Add line analysis plugin

jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
I noticed while testing unit conversion in Cubeviz that if the spectrum had no uncertainty attached, the unit conversion plugin would error out. This fixes that by propagating through a `None` uncertainty properly. Note that actually adding the plugin to the Cubeviz and Mosviz configs is included in #274 .
=> Fix bug with None uncertainty in unit conversion

jdaviz/app.py
We weren't passing the statistic to collapse with in one of the viewer data retrieval cases, leading to a mismatch between some fit/smoothed spectra and what was displayed in the spectrum viewer. This fixes that, so that the fits or smoothing are always performed on the spectrum shown in the viewer.
=> Add missing statistic argument in data retrieval

jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py
Minor code change that removes a Snackbar message telling a user to deselect the PanZoom tool in order to have the slit overlay appear when selecting a different row (since it now happens automatically).
=> Deselect PanZoom when selecting row for slit overlay

jdaviz/configs/default/plugins/model_fitting/model_fitting.py
Updating the displayed parameters after fitting a compound model was failing, due to `specutils.QuantityModel` not being subscriptable with the component model names. I left in the old parameter update code to be triggered if the resulting model isn't a QuantityModel (I don't know if this will actually happen ever, but better safe than sorry). Fixes a bug raised in https://github.com/spacetelescope/jdaviz/pull/263 by @PatrickOgle that fell off my radar earlier in the year (`TypeError: 'QuantityModel' object is not subscriptable`).
=> Fix compound model fit failure

jdaviz/configs/specviz/plugins/viewers.py
The mask/uncertainty plotting overrode the specviz viewer's `_data` property and thus broke the region -> subset operation. This fixes that.
This currently doesn't seem to be plotting the uncertainties for me, but I checked and the master branch doesn't seem to be plotting the uncertainties anymore either. Masks work fine. Can someone else confirm/help figure out if I somehow broke the uncertainty plotting here?
I'll also be making a followup issue for a bug I saw, where the uncertainty line mark (that I somehow can't see as mentioned above) gets duplicated if the displayed data is deselected and reselected without doing `viewer.clean()` before the deselection.
=> Fixing bug introduced by add_data override in spectrum viewer

jdaviz/configs/cubeviz/cubeviz.yaml, jdaviz/configs/mosviz/mosviz.yaml, jdaviz/tests/test_subsets.py
Adds Specviz plugins to the other configs, to operate on the data in their 1D spectrum viewers. Also updates the Mosviz config to use the `specviz-profile-viewer` for its 1D viewer, to enable all the associated functionality.
=> Add Specviz plugins to Cubeviz and Mosviz

jdaviz/app.py, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/specviz/plugins/viewers.py, notebooks/concepts/MOSviz overplot slit example.ipynb
Set axes labels to look better and more accurately represent data. Currently the axes labels for some viewers are hard coded (such as "x: pixels" and "y: pixels" for the image viewer), but once header information is being passed through the `meta` attribute and being used in the plot, we can set these values to be more accurate.
Some examples of how the plots look now:
After readjusting the size of the viewers:
(The spectrum viewer says "Flux Density [Jy]". Once Unit Conversion is usable in mosviz, the user can change the units to mJy so that the numbers are not blocking the y axis label)
I would suggest in the documentation to mention that removing the axes labels all together is an option under the viewer tab, since this looks much better!
=> Set axes labels

docs/cubeviz/index.rst, docs/index.rst, docs/installation.rst, docs/mosviz/index.rst, docs/quickstart.rst, docs/specviz/index.rst
This PR adds a new quickstart docs page, and moves the "Running Jdaviz" section from installation to the new quickstart page.
=> adding quickstart documentation

docs/data_prep.rst, jdaviz/configs/cubeviz/plugins/parsers.py, setup.cfg
Gearing up for `jdaviz` v1.0 release, spectral-cube 0.5 is not compatabile with the current state of the app. With this PR, cubeviz can at least run, however one test is not passing and there is a traceback in cubeviz when loading data.
Fixes #296
=> Attempting to fix cubeviz load data bug

docs/dev/release.rst
Clarifying the release instructions to make it more obvious that the release should occur in a new, temporary directory with a clone of the jdaviz repo so that all commands can be followed exactly.
=> Update release instructions

docs/index.rst
It's not good advertisement practice that a significant real estate of the landing page is occupied by a list of bugs.
This PR fixes the maximum depth in the index file for the known bugs section.
(I overlooked this when I created the list).
=> Remove list of bugs from readthedocs landing page  

setup.cfg
Glue-jupyter [#204](https://github.com/glue-viz/glue-jupyter/pull/204) has been merged and Tom has done a bug release, so the current version is 0.2.1. This PR updates `setup.cfg` to point to that version in order to fix #295 in jdaviz.
=> Increase glue-jupyter dep to 0.2.1

docs/known_bugs.rst, setup.cfg
This PR fixes #305 by requiring the latest version of vispy which has fixed the install issue (and also giving an recommended workaround that we can leave in for a few versions for anyone who might already have hit #305 and wants to know how to work around it).
=> Vispy fix update

jdaviz/configs/cubeviz/plugins/parsers.py
Closes #312 by applying the `data_label` argument of `load_data` to the created Glue Data objects in the case of Cubeviz parsing string filenames or astropy `HDUList` objects.
=> Fix custom data labels in cubeviz filename/HDUList parsing

jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py, jdaviz/configs/specviz/plugins/viewers.py
The `plot_spectral_line` method of the spectrum viewer wasn't behaving correctly, since the primary key on the `spectral_lines` table is now a combination of line name and wavelength rather than just the line name. This PR ensures that users can input the line name to the `plot_spectral_line` method as expected.
=> Use linename index for plot_spectral_line string input case

docs/specviz/displaying.rst
Found this in helping Ricky diagnose CI failures for #344. Forgot to suppress the app rendering in the docs
=> Docs: Skip rendering of specviz app

docs/specviz/displaying.rst, setup.cfg
The Traitlets 5.0 release (they are now on 5.0.5) broke all of our tests. Pinning to <5.0 for now until we figure out what needs to change to be compatible with the new version.
=> Pinning the traitlets requirement to <5.0 for now

docs/mosviz/displayspectra.rst, docs/specviz/displaying.rst
Some mosviz documentation for pan/zoom and spectral regions. For the most part, I just linked the specviz docs as they're basically the same with a few caveats:
1. I added special section talking about the linked 1D and 2D spectral viewers
2. I am restricting the spectral region to the 1D spectral viewer, ignoring the 2D spectral viewer and image viewer. Playing around with them, I don't think those features are finalized and I struggled to get consistent behavior to document. Also because we are considering creating a dedicated 2D spectral viewer anyways, I think we shouldn't invest too heavily into docs of the 2D spectral viewer just yet
=> Docs: Mosviz Pan/Zoom and Spectral Regions

tox.ini
Edits the tox config to fix compatibility failure.
=> Pin GWCS for astropy 4.0.3 compatibility in tests

jdaviz/app.py, jdaviz/cli.py, jdaviz/configs/specviz/plugins/parsers.py
This PR fixes Jdaviz to support the windows desktop, along with some minor improvements to the CLI (desktop) starting behavior:
1. Primarily, it addresses [#583](https://github.com/voila-dashboards/voila/issues/583); an update to the Tornado webserver used by Voila broke support for Windows. There's a workaround that I've included that we can probably remove once Voila addresses the bug; we'll need to keep an eye on it
2. I removed the `CONFIG` keyword from the CLI starter. We have default notebooks for each configuration, so we don't actually use it anymore
3. I spent much more time than I should have struggling with path recognition. I've updated the notebooks to use python's new pathlib to do some basic path formatting for us.
=> Fix support for Windows Desktop

docs/specviz/plugins.rst, jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue
This is the current draft of the refactor of the unit conversion plugin. I originally tried to make it as viewer agnostic as possible, but the smoothest implementation requires some reliance on the 1d spectrum viewer. This also makes it easier to make unit tests for this plugin. Some other thoughts:
1. Fixes #280 
2. The ghost bqplot marks bug appears if you create subsets for different unit versions of the same spectra and then deselect them.
3. The plugin no longer automatically switches to new units spectrum after the `apply` button is pressed. Instead, it behaves like other jdaviz plugins where the data is created and added to the drop down, along with a snackbar message notifying the user of the status of the conversion.
4. If a spectrum is converted, a "_units_copy_" version will be …
=> Unit conversion refactor

.bandit.yaml, .github/workflows/ci_workflows.yml, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, tox.ini
This PR ~(if/when it's working...)~ should close #289 .  ~It's also built off of #369 so I'm opening it as a draft until we merge that~.
This basically just ports the bandit configuration that I discovered had already been done in spacetelescope/stsci-package-template#25 over here.  The problem is that it is currently failing for a bunch of reasons - see https://github.com/eteq/jdaviz/actions/runs/373207713 .
It's not clear to me if any of these are "real" security concerns - it's basically all about `assert` statements.  We may just want to exclude that particular check because it feels to me like whoever wrote bandit is really just asserting their opinion that `assert` is bad.  But we can discuss since this can't be merged until #369 anyway.
=> Add Bandit to the github actions build

notebooks/concepts/concept_programmatic_viewers_from_blank_default.ipynb
This PR adds a concept notebook highlighting a use case of creating viewers, and adding data, programmatically, starting from a blank default jdaviz application.  Or, more accurately, highlights the current failure modes and subsequent hacks to enable the use case.
=> Concept notebook for programmatic viewers from a default blank app

jdaviz/app.vue
More information on editing the Snackbar message can be found here: https://vuetifyjs.com/en/api/v-snackbar/
=> Move snackbar message to the top of the UI

jdaviz/configs/cubeviz/plugins/parsers.py
This PR fixes #322.   It changes the first loop that assigns finds the wcs to use the individual hdu.   To both loops, it also adds an additional check to skip extensions when they are not image extensions, e.g. BinTable HDUs.  I believe those extensions currently cannot be parsed and loaded into an image viewer.
=> Fix for parsing of cube extensions

jdaviz/configs/specviz/plugins/viewers.py
Closes #381. Lines hidden by the list "Hide All" button no longer get replotted when using the "Show All" button in another list or when calling `specviz.plot_spectral_lines()`. The cause here was that setting a new column value for multiple rows at a time in an astropy Table silently fails.
=> Fix setting 'show' column to False when hiding lists

jdaviz/app.py
Closes #181 . For some reason the case where the input filename didn't really exist wasn't raising the `FileNotFoundError` successfully (so the "Data Loaded" snackbar message was appearing despite no data loading). I changed that case to send an error snackbar message instead and then return.
=> Fix nonexistent file load

jdaviz/configs/specviz/helper.py
At some point we accidentally duplicated most of the methods in the Specviz helper class. In checking that everything still worked after deleting those, I noticed that one of my redshift slider changes had broken the autoscale methods (it was always trying to loop through keys even if a label was provided to get a single spectrum), so I also fixed that.
=> Remove duplicate methods, fix a bug introduced by the redshift slider

jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/plugins/parsers.py
Minor edits to the Mosviz 2d parser to enable Specviz2d to use it instead of using a mostly duplicate parser, to ease maintainability and specifically enable Specviz2d to take advantage of #377 .
=> Refactor specviz2d parser

jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/specviz2d.yaml
This PR fixes the `specviz2d` configuration name which was previously set as `mosviz`.  It also adds args and kwargs into the `Specviz2d` helper class to enable passing in an `app` object, similar to the other helpers.  This was useful for MAST app/helper logic.  For example
```
app = Application(configuration=custom_specviz2d_config)
helper = Specviz2d(app)
```
=> Fixes for specviz2d configuration and helper

jdaviz/app.py, jdaviz/configs/default/plugins/collapse/tests/test_collapse.py
Thanks to @astrofrog for pointing out that we don't need to link every dataset to every other dataset, we can just link all subsequent data to the first. This change makes the performance scale linearly instead of exponentially as more datasets are added, which vastly improves the behavior of #394 and also helps in cases of loading large quantities of data into Specviz. We'll likely want to do some follow up work to further restrict when things get linked, since I don't think we need to link the spectra at all in the Mosviz case.
=> Link subsequent data world coords to only the first compatible

jdaviz/app.py, jdaviz/app.vue
Fixes #185
One part of the issue is a GUI update loop when the checkboxes are toggled in quick succession, which is fixed by ba773e0. 
The other part is interacting with the UI while data is loading. We can't think of a good way to update the state of the application from the front-end and backend simultaneously, so this is worked around by locking the GUI while data is loading:
https://user-images.githubusercontent.com/46192475/108078308-cd1e6700-706d-11eb-8be4-4ef6547d7988.mp4
=> Fix GUI update loop

setup.cfg
=> MNT: Unpin pytest and move it to test requirement

jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py
Fixes #438 
The solution adds the standard deviation and type of smoothing to the label, and cancels the smoothing operation if that label already exists. This way, the user can use Gaussian Smooth multiple times and not crash the application.
=> Fix gaussian smooth bug

jdaviz/cli.py
This allows user to provide non-default browser for Jdaviz to use with. Implementation based on answer from voila-dashboards/voila#843 .
For instance, I need this because WebGL doesn't work on machine's Firefox but it works on Chrome, but default browser is Firefox and I don't have enough admin access to change it.
=> ENH: Add --browser option to CLI

setup.cfg, tox.ini
It is just gonna come back and bite us. Except for `traitlets`, I cannot find any documentation on why these are pinned to older versions.
As for `traitlets`, https://github.com/mariobuikhuizen/ipyvue/issues/18#issuecomment-785790175 says it is no longer a problem.
Close #345
=> MNT: Unpin max versions

jdaviz/configs/specviz/plugins/redshift_slider/redshift_slider.py
Sets the default precision of the redshift slider to 5 decimal places. I also dropped the default max to 0.1 - let me know if there's a better choice there.
=> Increase default redshift slider precision

setup.py
I opened up `setup.py` and Emacs reported undefined variables. I tried to fix it as best I can understand what I think it is trying to do. Someone familiar with Jupyter internals should double check.
=> MNT: Fix setup.py errors

jdaviz/app.py, jdaviz/container.vue
A better fix for #185.
Reverts 95f3e8e and replaces v-treeview with a list of checkboxes.
=> A better fix for the GUI update loop #185 

jdaviz/configs/default/plugins/line_lists/line_list_mixin.py, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/specviz/plugins/viewers.py
No longer display all the lines of a preset line list when it's loaded, for performance reasons. I made the snackbar messages when loading presets a little more informative to point users to the plugin to display the lines. I also fixed a bug where the redshift check broke loading presets from the notebook in Specviz, although the workaround means that they aren't currently inheriting the redshift on load if it's set in the slider. I haven't decided if I want to fix that here or open another bug issue, but I'm done for the day right now.
Fixes #459
=> Update preset line list loading behavior

jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/tests/test_helper.py
What it says in the title. Takes `filename` (string) and `selected` (boolean, default False) optional inputs, e.g. `mosviz.to_csv(filename="test.csv", selected=True)`.
Edit: closes #464
=> Extract Mosviz table with to_csv method

jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
With the introduction of #456, we now have a good foundation for some cleanup of the model fitting plugin. This PR implements the following changes:
1) The model can be automatically added to the spectral viewers immediately without fear of this looping bug that's been plaguing us
2) The "Apply to Cube" option only applies to the "Cubeviz" configuration, and therefore is only visible in Cubeviz
3) With the introduction of #458, we can now extract models via code. This, combined with MAST's request that we don't allow saving to local resources in anticipation of Cloud Hosting, means the "Save to Disk" button is removed
I reviewed the docs, and these changes aren't actually mentioned in the docs, so there's nothing to change as far as I can see
=> Model Fitting Cleanup

docs/known_bugs.rst
1. "Specviz Unit Conversion with subset selected" fixed by #360 
2. "Flashing display when data is added or removed too quickly" fixed by #427 
3. "Gaussian smooth crashes after selecting smoothed data in spectrum viewer" fixed by #441 
@rosteen and @ibusko , can you check the other bugs listed to see if they are still present? I was not able to replicate the "Cubeviz Collapse and Moment Maps: Spectral bounds do not match Region selection" bug and I have not seen "Ghost subsets and models in spectrum viewer" in a while. "Collapse Plugin spectral bounds don't match selected region" may also be a duplicate of "Cubeviz Collapse...", unless I'm missing something there.
=> Remove fixed bugs from docs

jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/tests/test_helper.py
This fixes a test that was writing a file to the current directory, which meant that the tests failed the second time when run twice
=> Write test file to temporary directory

jdaviz/app.py
This fixes a bug in _viewer_item_by_id: if multiple stack items were present and the first had children but not the requested viewer, then find_viewer_item would incorrectly return None instead of checking the next stack item. I've also improved an error message related to finding viewers.
=> Fix bug in _viewer_item_by_id

.github/CODEOWNERS
Rather than having to manually request reviews from the same people every time, this will automate that process. These are the people that I was told would review all PRs, no?
See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
=> MNT: Add codeowners 

jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py, notebooks/MosvizExample.ipynb
The Mosviz example notebook exercises this mode.
=> Allow a "no-image" mode for mosviz

jdaviz/_astropy_init.py
This is probably leftover from package template. This package does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497
=> MNT: Remove unused astropy config code

jdaviz/configs/cubeviz/helper.py, jdaviz/configs/mosviz/helper.py
This implements the feature I suggested in #329. This PR should probably also include some doc updates showing its use a la what @PatrickOgle originally was thinking about in https://github.com/spacetelescope/jdaviz/pull/257#discussion_r483014900.  The idea is that with this you can do something like:
```
cubeviz = CubeViz()
cubeviz.load_data(...)
cubeviz.specviz.some_specviz_helper(...)
```
and that should be documented as the intended approach to using specviz helpers in the cubeviz context. But I'm not doing that now because I want to make sure others are ok with this idea before I complete this. Hence the "draft" status.
=> add specviz property to cubeviz/mosviz helpers

jdaviz/app.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
It seems like a numpy update (maybe?) cause the existing syntax (`array is False`) to no longer work as it once did, which was causing the `centroid` handling in the line analysis plugin to fail. Switching to `array == 0` fixes it.
I also fixed a bug I found while testing this that caused `get_subsets_from_viewer` to fail if you called the function with a `data_label` specified.
=> Fix centroid error in line analysis plugin

jdaviz/configs/cubeviz/plugins/parsers.py
I don't think "applicad" is a word?
=> BUG: Fix typo in cubeviz parser docstring, remove duplicate code

CODE_OF_CONDUCT.md
Code of conduct is from https://github.com/spacetelescope/stsci-package-template/blob/main/CODE_OF_CONDUCT.md
=> DOC: Add STScI code of conduct

jdaviz/app.py
In glue, the default opacity for data layers is 0.8 - while it might make sense to change the default there, for now the quickest and most past- and future-proof fix is to simply set the default for jdaviz here.
Fixes https://github.com/spacetelescope/jdaviz/issues/535
Fixes https://github.com/spacetelescope/jdaviz/issues/537
=> Change default data layer opacity to 1

jdaviz/app.vue, share/jupyter/nbconvert/templates/jdaviz-default/app.html
Using height: 100% is enough here to always take up all space of
the parent. The total height of the entire app can then be
specified elsewhere.
Part of #503
=> fix: make height controllable in other context

.github/workflows/ci_workflows.yml, jdaviz/app.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/imviz.yaml, jdaviz/configs/imviz/plugins/__init__.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_parser.py, notebooks/ImvizExample.ipynb, setup.cfg
Fix #510 
~I cannot test this until #540 is resolved because `jwst` is not compatible with Windows.~
Reference: https://github.com/glue-viz/glue/blob/master/glue/core/data_factories/fits.py
Successfully loaded the following locally in notebook:
```python
imviz.load_data('/path/to/jw1069001001_01203_00002_nrca1_level2_cal.fits')  # SCI
imviz.load_data('/path/to/jw1069001001_01203_00002_nrca1_level2_cal.fits[DQ,1]')
imviz.load_data('/path/to/jw1069001001_01203_00002_nrca1_level2_cal.fits[VAR_POISSON]')
imviz.load_data('/path/to/jbt7a3020_drz.fits')  # SCI
imviz.load_data('/path/to/jbt7a3020_drz.fits[WHT,1]')
imviz.load_data('/path/to/jbt7a3020_drz.fits[CTX]')
```
As you can see, JWST filenames are a little long, so I need to scroll to get the full screenshot(s).
=> Imviz parser

jdaviz/configs/specviz/plugins/parsers.py
We shouldn't be passing `data_label` to `get_data_from_viewer` here, because we want whatever data is currently displayed regardless of label.
=> Remove unwanted data label input

setup.cfg
Until we are ready to deal with #478 , this will suppress all the warnings in test logs. Otherwise, it is annoying to scroll up to get to the parts of the logs that matter.
If this is merged, #478 should be updated with a reminder to undo this change.
```
...
..\..\docs\specviz\notebook.rst .                                        [100%]
============================== warnings summary ===============================
(a lot of stuff)
d:\a\jdaviz\jdaviz\.tox\py38-test\lib\site-packages\glue\core\data.py:1803: FutureWarning: ...
full_result[result_slices] = result
-- Docs: https://docs.pytest.org/en/stable/warnings.html
================= 44 passed, 566 warnings in 81.25s (0:01:21) =================
___________________________________ summary ___________________________________
py38-test: …
```
=> TST: Suppress warnings in test logs

jdaviz/cli.py
With this patch, you will see something like this:
```
$ jdaviz --version
jdaviz, version 1.0.4.dev505+g3568f7c.d20210429
```
Fix #576 and fix #378
=> Add --version to CLI

jdaviz/configs/imviz/helper.py, notebooks/ImvizExample.ipynb
BUG: Handle loading of obj in Imviz.
ENH: Do not show second image in example.
This is a direct follow-up of #541
=> Imviz: Minor fixes

jdaviz/configs/cubeviz/plugins/tests/test_data_retrieval.py
`test_data_retrieval` in Cubeviz accesses Internet. It should only run in a job that enables `--remote-data`. Otherwise, you'll hit timeout a lot when all the jobs hit the server at once and you get marked as spammer.
=> TST: Mark test_data_retrieval to require remote_data

.github/workflows/ci_workflows.yml, tox.ini
* General clean-ups of CI workflow syntax.
* Update `tox` env list to be consistent with what is actually used.
* PEP 517 check now fails on warnings.
* Change OSX job to use Python 3.7 because that Python version is currently untested.
But mainly I just want to see if the labeler works... 😹
=> TST: Test workflow clean-ups

.github/workflows/ci_cron_weekly.yml, jdaviz/conftest.py, setup.cfg, tox.ini
You currently have:
https://github.com/spacetelescope/jdaviz/blob/3568f7ce49c3dcae03e9ce2ae1d6d08e9fdd87bf/setup.cfg#L21
* Bumps Python minversion to 3.7 to match `astropy>=4.2`.
* Drops test matrix for Numpy 1.16 to match `astropy>=4.2`.
* Drops test matrix for `astropy<4.2`.
* Remove dead code and outdated comments from `jdaviz/conftest.py` due to `astropy>=4.2`.
=> MNT: Bump Python minversion based on astropy>=4.2, remove outdated test config

.github/workflows/codeql-analysis.yml
@larrybradley and Lee Quick asked me to do this.
Solution | Run time (s) | Problems found
--- | --- | --- |
`bandit` | 20 | 0
CodeQL (JavaScript) | 60 | 0
CodeQL (Python) | 1800 | 0
CodeQL results: https://github.com/spacetelescope/jdaviz/security/code-scanning?query=ref%3Arefs%2Fpull%2F554%2Fmerge+tool%3ACodeQL
=> TST: Add CodeQL security check

.github/labeler.yml
Noticed that #585 did not auto-label as expected.
=> MNT: Update testing labeler rule

jdaviz/_astropy_init.py
A lot of the code was leftover from `astropy_helpers` days, which you don't use. Probably inherited from old template.
=> MNT: Remove dead code from _astropy_init.py

docs/dev/release.rst
`astropy` no longer publishes dev docs in its stable build. Only `latest` doc has the section now.
=> DOC: Fix broken link to astropy dev docs

jdaviz/cli.py, jdaviz/configs/default/plugins/data_tools/data_tools.py, jdaviz/configs/default/plugins/data_tools/data_tools.vue, jdaviz/configs/default/plugins/data_tools/file_chooser.py, licenses/IPYFILECHOOSER_LICENSE.rst, setup.cfg
This is an experiment with using ipyfilechooser as the file dialog, which allows us to select file paths on disk as opposed to having to upload the data as #186 does. This does mean the file browser is not 'native' but instead implemented using ipywidgets, so it is not as pretty, but on the other hand it is better than passing a file path! Here is a preview:
I had to hack around and use private API on ipyfilechooser to hide some of their buttons so this should be treated as experimental. If people like this I can work on trying to expose what we need in a public API in ipyfilechooser or in the worst case forking it and bundling the modified version here (it is pretty simple code)
This should otherwise be functional so feel free to try it out!
Fix #156, fix #546
=> Use ipyfilechooser for file dialog

conftest.py, setup.cfg
Fix test header for CI. Also add more info.
This is part of #476 that deals with test header. Close #628.
```
============================= test session starts ==============================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py38-test-alldeps-cov/.pytest_cache
Running tests with Astropy version 4.2.1.
Running tests in jdaviz docs.
Date: 2021-04-28T20:52:17
Platform: Linux-5.4.0-1046-azure-x86_64-with-glibc2.2.5
Executable: /home/runner/work/jdaviz/jdaviz/.tox/py38-test-alldeps-cov/bin/python
Full Python Version: 
3.8.9 (default, Apr  8 2021, 12:01:33) 
[GCC 9.3.0]
encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15
Package versions: 
Numpy: 1.20.2
Scipy: 1.6.3
Matplotlib: 3.4.1 …
```
=> TST: Fix test header for CI, add more info

jdaviz/cli.py
Fix #44 
Whitelisting alone wasn't enough. Also needed to invoke logger magic.
=> MNT: Silence tornado warnings

jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/plugins/viewers.py, notebooks/ImvizExample.ipynb
Fix #520 
Out of scope: Nice UI/UX stuff.
=> Imviz: Add simple blink tool

jdaviz/app.vue
Fixes the missing content in Jupyter Lab:
=> fix: also set the height for the app in a lab context

conftest.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/conftest.py, setup.cfg
The less controversial part of #600 (JDAT-1486). This adds support for `astropy.nddata.NDData` and `numpy.ndarray` in Imviz.
With this patch, the following is now possible (I copy-pasted the code from notebook cells):
```python
import warnings
warnings.simplefilter('ignore')
```
```python
from jdaviz import Imviz
imviz = Imviz()
viewer = imviz.app.get_viewer('viewer-1')
imviz.app
```
```python
import numpy as np
from astropy.nddata import NDData
a = np.zeros((10, 10))
a[1:-1, 1] = 1
a[1:-1, 8] = 1
a[1, 1:-1] = 1
a[8, 1:-1] = 1
imviz.load_data(a, data_label='ndarray')
b = NDData(a, mask=~a.astype(np.bool_))
imviz.load_data(b, data_label='nddata')
```
=> Imviz: Load NDData and ndarray

jdaviz/configs/imviz/plugins/parsers.py
Apparently, HLA pipeline adds a lot of distortion info as separate FITS extensions, so you need to pass in the whole `HDUList` into the `WCS` constructor. This patch is possible thanks to advice from @mcara .
Example file extensions:
```
Filename: jbt7a3k7q_flc.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
0  PRIMARY       1 PrimaryHDU     281   ()      
1  SCI           1 ImageHDU       249   (4096, 2048)   float32   
2  ERR           1 ImageHDU        56   (4096, 2048)   float32   
3  DQ            1 ImageHDU        48   (4096, 2048)   int16   
4  SCI           2 ImageHDU       245   (4096, 2048)   float32   
5  ERR           2 ImageHDU        56   (4096, 2048)   float32   
6  DQ            2 ImageHDU        48   (4096, 2048)   int16   
7  HDRLET        1 …
```
=> BUG: Fix loading of HLA product in Imviz

jdaviz/cli.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_parser.py
With this patch, the following calls are now possible:
```
jdaviz --layout=imviz s12_ch1_v0.30_sci.fits,s12_ch2_v0.30_sci.fits,s12_ch3_v0.30_sci.fits,s12_ch4_v0.30_sci.fits
```
```
jdaviz --layout=imviz "jbt7a3020_drz.fits[SCI],jbt7a3020_drz.fits[CTX]"
```
Out of scope: Wildcard matching.
Because listing them on the terminal is faster and more reproducible than clicking through the "IMPORT" button, despite #573 .
A little, as I have to disable check for `FILENAME` at the `click` level. So if you pass in garbage, it is up to the lower level parsers to handle that as appropriate. Hopefully this is not too controversial, and the benefit outweighs the cost.
=> Imviz: Support file list input in CLI

docs/reference/api.rst
This adds Imviz API doc in a way that is consistent with the rest of the package, except where other Viz only includes "plugins" doc, I opt to include the whole "imviz" at one level up because I want `load_data` info to show.
Out of scope: Re-organize package-level docs.
Rendered doc: https://jdaviz--647.org.readthedocs.build/en/647/reference/api.html#module-jdaviz.configs.imviz
=> DOC: Add Imviz API documentation

jdaviz/app.py
Fix #663 
Now "x" no longer does tiling roulette.
<details>
<summary>Older notes</summary>
```
IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.
Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)
```
</details>
=> Fix Imviz tiling bug

docs/known_bugs.rst
@rosteen said I should document this.
=> DOC: Known bottleneck install issue

jdaviz/container.vue
=> Rename Test to Viewer

jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, setup.cfg
Now removes units from model parameters before cube fitting as the single model fit does, to avoid some problems with complex parameter units in specutils fitting. 
Depends on https://github.com/astropy/specutils/pull/823 to remove a recursion error when pickling during multiprocessing result collection.
=> Fix cube fitting failures on Polynomial and Linear models

notebooks/concepts/generate_mosviz_photometry.ipynb
I've opened this PR to get this notebook that I wrote with @robelgeda on the record, but please consider it a draft until we hear more from other stakeholders in the JWST data pipeline discussion. I realize the notebook still contains some paths that are specific to my laptop and that the style may not be fully compliant with `jdaviz` standards.
=> Wrote notebook on synthetic Mosviz image creation

jdaviz/app.py, jdaviz/app.vue, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/utils.py
Attempt at fixing ticket JDAT-1559: stacking snackbar messages.
Snackbar vuetify elements (\<v-snackbar \>) cannot be drawn at arbitrary places on screen; they just support `top`, `bottom`, `left`, `right` properties. Thus there is no way to stack them say, as a column on screen. People found a solution via a `VSnackbarQueue` that displays snackbar messages one after the other, as the `Close` button is clicked, or each message times out in turn. Unfortunately, this class is not implemented in `ipyvuetify`.
As a stopgap solution, I implemented a queuing mechanism here.
=> Snackbar fix

jdaviz/utils.py
I just found out the bug reported by @rosteen on PR #701 (`IndexError: pop from an empty deque`). This didn't happen to me before when testing for the PR itself, but now I saw it when reviewing PR #687.
This PR fixes the bug.
=> Fix bug with empty snackbar queue

jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/conftest.py, notebooks/ImvizExample.ipynb
Implement some of #631 and #632.
Out of scope: Unable to use this API on a tiled viewers; i.e., it only works on the first viewer that the app opened. See #643
=> Imviz: astrowidget API for center_on and offset_to

share/jupyter/nbconvert/templates/jdaviz-default/index.html.j2
See #666
Before:
After:
I never saw this issue because I have scroll bars turned off. To see the difference in MacOS "Show scroll bars" has to be set to "Always":
=> fix: don't show the scrollbar in the app template

docs/known_bugs.rst, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/configs/imviz/tests/utils.py, notebooks/ImvizExample.ipynb
Fix #662 
MVP markers portion of #632 .
Also see https://github.com/astropy/astrowidgets/blob/main/astrowidgets/core.py
=> Imviz: astrowidgets markers API

jdaviz/configs/specviz/tests/test_helper.py
Fixes a pytest error I was seeing in addition to specviz helper tests for `get_spectra()`.
=> Add specviz helper tests

jdaviz/app.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_regions.py, notebooks/ImvizExample.ipynb, setup.cfg
Fix #622. Second attempt of #630. (It is easier to open a new PR than to resolve conflicts of that one...)
Note to self: Open follow-up issues about modifying regions, roundtripping, GWCS support...
=> Imviz regions setter/getter API

jdaviz/app.py, jdaviz/conftest.py, jdaviz/container.vue, jdaviz/tests/test_viewer_ids.py
* Fix #372
* Fix #643 
With this patch, such a thing is now possible (though the contour stuff is another issue, see #530).
```python
>>> # After creating tiled viewers
>>> imviz.app.get_viewer_reference_names()
['viewer-1', None]
>>> imviz.app.get_viewer_ids()
['imviz-0', 'imviz-1']
>>> viewer = imviz.app.get_viewer('viewer-1')
>>> viewer2 = imviz.app.get_viewer_by_id('imviz-1')
>>> viewer2.state.layers[0].contour_lim_helper = viewer.state.layers[0].contour_lim_helper
>>> viewer2.state.layers[0].contour_visible = True
```
With this patch, this is how different layouts now behave.
```python
>>> from jdaviz.configs.cubeviz import CubeViz
>>> x = CubeViz()
>>> print('Reference names:', x.app.get_viewer_reference_names())
Reference names: ['flux-viewer', 'uncert-viewer', 'mask-viewer', …
```
=> Viewers now have human-readable IDs

jdaviz/app.py, jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/specviz/helper.py, jdaviz/tests/test_subsets.py
Fixes a bug when calling `cubeviz.specviz.get_spectral_regions()` where it would crash if there were circular spatial subsets defined in the image viewer (and would return rectangular spatial subsets like they were spectral regions). 
Also prevents rectangular spatial regions from showing up as spectral regions in the Collapse plugin (see screenshot below), and opens up other usage that would require this capability. 
Someone more familiar with Glue should look at this as well in case there are any pitfalls with doing the check this way that I don't appreciate. This is the best attribute on the Subsets I could find to determine whether they are spatial or spectral.
=> Add ability to retrieve only spectral or spatial subsets

jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/configs/imviz/tests/utils.py, notebooks/ImvizExample.ipynb
=> Imviz: Add zoom and zoom_level API

jdaviz/configs/specviz/helper.py, jdaviz/configs/specviz/tests/test_helper.py
This PR addresses #738 by:
1. Falling back on the reference data's spectral_axis units or
~2. If it can't, defaults to `Counts` as the astropy unit of choice, as opposed to Angstroms.~ Found a bug for this one. Will need to address https://github.com/astropy/specutils/issues/846 and possibly https://github.com/astropy/specutils/issues/847 first. 
I would really appreciate feedback on (2), specifically. I recall us having a conversation about whether Counts are a good fallback unit or whether they actually have a very specific meaning (e.g. like in photo-multiplier tubes :/)
Fixes #738 
=> Specviz Spectral Region Getter falls back to reference data units

jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py
This pull request is to address the slit overlay plugin issuing a traceback anytime NIRISS data is loaded and different rows are selected.
Fixes #433 
=> Add way to turn off slit overlay if data is not NIRSpec

conftest.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/conftest.py, setup.cfg, tox.ini
Fix #725 
<details>
<summary>This is no longer an issue.</summary>
But I am not convinced this works because I get this error locally. Test image is https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/stellar_photometry/jw01072001001_01101_00001_nrcb1_cal.fits
```
...
gwcs: 0.16.1
asdf: 2.7.3
...
_____________________________________ TestParseImage.test_parse_jwst_nircam_level2 _____________________________________
@pytest.mark.skipif(not HAS_JWST_ASDF, reason='asdf and gwcs not installed')
@pytest.mark.remote_data
def test_parse_jwst_nircam_level2(self, imviz_app):
from gwcs import WCS as GWCS
filename = download_file(self.jwst_asdf_url_1, cache=True)
>       parse_data(imviz_app.app, filename, show_in_viewer=False)
jdaviz/configs/imviz/tests/test_parser.py:193:
_ _ _ _ …
```
=> MNT: Remove jwst as dependency for Imviz

setup.cfg
This pull request is to bump minversion of glue-astronomy from dev hash to 0.2 release. This is needed for #706. 
Fixes #711
Also see glue-viz/glue-astronomy#37
=> MNT: Bump glue-astronomy minversion to 0.2

jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, notebooks/ImvizExample.ipynb
This pull request is to implement the `save` method as per `astrowidgets` API definition.
Fixes #719 
xref #632 
Would be nice to have some inputs from @maartenbreddels though I think this PR is still acceptable without:
- The popup makes browser warns me of "multiple downloads" (Wombat alert!).
- The popup pops up twice for a single save attempt; not sure why.
What you actually see on browser:
What it saves out:
I did blink to another image, and it does save out the one that is displayed.
=> Imviz astrowidgets API: save

jdaviz/app.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/imviz/tests/test_regions.py
This pull request is to allow `imviz.get_interactive_regions()` to support GWCS. The solution here is to bypass the complicated and unnecessary processing in the high-level app level, hence removes the need for `CDDData`, which currently does not work with GWCS. The underlying Glue machinery follows Astropy APE 14, so it should be compatible with GWCS already.
Fixes #781
Follow-up of #721
p.s. I know I am supposed to wait till next sprint but it bothers me too much. 😬 
p.p.s. Apparently Windows endlines snuck into `test_regions.py`. If it bothers you, I can run `dos2unix` on it, but the result is the whole file gets diff-ed, which is hard to review. I left it alone for now.
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things …
=> BUG: Imviz get_interactive_regions now supports GWCS

jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
This pull request is to allow successful "apply to cube" operation in this workflow:
1. Load cube (left viewer)
2. Generate collapsed cube by sum (middle viewer).
3. Draw X-range region on the spectrum at bottom.
4. Use model fitting plugin, fit on SCI data, use linear model, label it "L1", add the model with default values, type "L1" in equation, label it "LinFit".
5. Select "Subset 1", click "Fit", and it should succeed as expected. See fit shown on spectrum.
6. Click "Apply to cube". Without this patch, it shows error (in notebook but not in lab). With this patch, a fitted cube is shown in right viewer without error (someone familiar with Cubeviz should check if the result is correct or not; I cannot tell).
Fixes the second bug in https://jira.stsci.edu/browse/JDAT-1671
This checklist …
=> Cubeviz: Allow model fitting to operate on spectral Subset

jdaviz/core/data_formats.py, jdaviz/tests/test_data_formats.py
This PR expands the data format identification to include JWST multi extension data.   It expands the spectrum formats table to also include `SpectrumList` objects.  Passing `SpectrumList` into `identify_spectrum_format` is a more general solution that now allows for e.g. `JWST x1d multi` formats in addition to the standard single `JWST x1d`, `JWST s3d`, etc.  to be properly identified.
=> Multi-extension data format identification

jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/tests/test_helper.py
I didn't see an issue for this, but it seemed like the easiest thing to do out of the outstanding features from Jenn's wireframe that we haven't implemented yet so I just did it. Nice little quality of life change.
=> Automatically load first object on data load in Mosviz

docs/conf.py, docs/dev/index.rst, docs/dev/links.rst
I've discussed various aspects of linking with some of you in Slack but I thought it would be good to write up some developer docs about the most recent state of linking and what I think should be best practices going forward with linking. I plan to expand this over time - and whenever someone asks me a question about linking that is not covered by this page, I will do by best to add some information to the page.
In principle we could improve this page by adding intersphinx links to the glue docs for classes and methods, but I've run out of time for today - I'll gladly accept suggestions/commits that add intersphinx links, or I can try and add it later this week or next week at some point (but would rather we merge this and then fix the intersphinx links later than delay merging for a …
=> Added initial developer docs on linking

jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py
While testing out https://github.com/spacetelescope/jdaviz/pull/762 I ran across a bug which was that the code to remove the slit overlay was assuming things about the order and number of marks in the figure, which caused an error of the type ``x not in list``. This PR should fix it by making sure we remove the right mark.
=> Make sure we remove the right patch from the image viewer when removing the slit overlay

jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/tests/test_helper.py
This pull request is to allow Mosviz to parse image data like Imviz does. This gives you additional data format support for free. This also gets rid of the need for `CCDData` in that particular parsing algorithm (though I see you still use it somewhere else) because `CCDData` will choke on GWCS (see astropy/astropy#11727) and you don't really need it.
This might be a bit controversial and needs a lot of testing and discussions. But with this patch, something like this is now possible:
```python
import numpy as np
mosviz.load_data(spectra_1d, spectra_2d)
my_image = np.array(...)  # Create your favorite array here
mosviz.load_images(my_image, share_image=5)
```
This solution is not as clean as it could be but I am trying not to refactor everything.
(Link JIRA ticket here if you have a …
=> ENH: Mosviz to use Imviz image parser

jdaviz/configs/mosviz/plugins/parsers.py
Removes checking for `__len__` attribute and uses `isinstance` instead. Also some other minor related code efficiency improvements. Fixes #314 .
=> Standardize/improve list coercion in Mosviz parsers

jdaviz/app.py, jdaviz/cli.py, jdaviz/configs/cubeviz/cubeviz.ipynb, jdaviz/configs/default/default.ipynb, jdaviz/configs/imviz/imviz.ipynb, jdaviz/configs/mosviz/mosviz.ipynb, jdaviz/configs/specviz/specviz.ipynb, jdaviz/core/helpers.py
This pull request is to introduce a new option named `verbosity` to control what snackbar messages get passed through.
Motivation: When I am developing the code, I only want to see warnings or errors, not 3 "success" messages per data load.
With this patch, you can now call your favorite viz with a new `verbosity=` keyword. For example: `imviz = Imviz(verbosity='warning')`
p.s. I cannot test the `voila` option due to https://github.com/voila-dashboards/voila/issues/773#issuecomment-868593863 , though theoretically it should work but someone should test it.
=> ENH: verbosity to control snackbar messages

.github/workflows/publish.yml, docs/dev/release.rst
With this, GitHub release would upload tarball and noarch wheel straight to PyPI.
Updated release instructions: https://jdaviz--469.org.readthedocs.build/en/469/dev/release.html
[🐱](https://jira.stsci.edu/browse/JDAT-1684)
=> ENH: Automated PyPI release from GitHub release

jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py, setup.cfg
This pull request is to have slit overlay plugin to not try to recreate the WCS itself, but rather use the WCS or GWCS that already comes with the data object.
Fixes #849 
=> Mosviz: Slit overlay to use Data WCS

jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/viewers.py
=> fix: buggy 1D/2D spectrum viewer x-axis links

notebooks/CubevizExample.ipynb, notebooks/ImvizExample.ipynb, notebooks/MosvizExample.ipynb, notebooks/SpecvizExample.ipynb
This is a quick PR that does exactly what it says: updates all the example notebooks to use the same structure.
(Also has the unintended but I guess good side-effect of making the kernels all consistent).
=> update the first cell of the example notebooks to be consistent

jdaviz/configs/mosviz/helper.py
Sometimes the scientific notation for the Y-axis is not applied.
When it happens, it's resolved by resizing the browser window,
which causes a re-render of bqplot, so looks to me like bqplot is
sometimes not re-rendering when the tick_format is changed.
To work around this, set the tick_format before the plot is
rendered with the first data.
See: #865
=> fix: scientific notation of Y-axis not shown on first load

jdaviz/configs/mosviz/plugins/viewers.py
This pull request is to address a bug where using the Unit Conversion plugin in Mosviz will lead to the data in the spectrum viewer becoming "stuck", meaning selecting a new row will not change the data in the viewer. The table viewer code now loops through all data collection labels to find labels that contain the original Spectrum 1D label within it (Unit Conversion appends the details of the conversion to the original label).
This PR also removes a print statement that made it into main.
=> Remove converted spec1ds in mosviz when row changes

jdaviz/configs/default/plugins/model_fitting/model_fitting.py
Our reductions in linking in Mosviz seem to have left fitted models out in the rain. This fixes it so that they once more plot over the selected data in the 1D spectrum viewer automatically after being fit. Seems a bit slower than I expected at the moment, but I think that's a separate issue.
=> Link model fitting results so they plot in Mosviz

jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py
When creating the new Spectrum1D with different units, the old WCS was preserved and inconsistent with the spectral axis. I'd almost call that a Spectrum1D bug *except* that this is ``_copy`` and private API. I'd highly recommend that this be done via public API in future but for now dropping the original WCS does the trick since the WCS is then produced from the provided spectral axis.
Fixes https://github.com/spacetelescope/jdaviz/issues/886
=> Fix cubeviz unit conversion

jdaviz/container.vue
This pull request moves the alignment of the "hammer and screwdriver" toolbar to the right and the child "save" menu to the left so it does not overflow past the far right of the viewer.
Fixes #659
=> viewer toolbar: align to right

.github/workflows/ci_cron_weekly.yml, setup.cfg
This pull request is to fix the failing cron job in CI, and also allow manual trigger on a as-needed basis, given the scheduled job only runs weekly.
=> TST: Ignore numpy.ufunc size warning in cron job CI

jdaviz/container.vue
This pull request fixes the lack of an initial tab underline on the slider of the viewer/layer menu, by wrapping with a `v-lazy` component, because that makes perfect sense.
=> wrap tab items in lazy component to fix initial tab selection

jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
This pull request is to avoid setting "results" in every iteration, but only set it once at the end. Does not change any user facing functionality.
=> BUG: Fix line analysis results logic

jdaviz/container.vue
This pull request ensures that the tools menu closes when opening the layer/viewer menu (the opposite was already the case as the layer/viewer menu closes on any click away from the menu, whereas the plot tools must remain open in order to function).  This can be extended to any future menu (i.e. the currently empty "more" menu), or to the data button on the left (which is currently excluded).
Fixes #791 (note: there was an issue opened upstream.  Not sure if that should be closed or left for consideration within glue itself)
=> close plot tools menu when opening layer/viewer menu

tox.ini
Temporarily disable bqplot dev in devdeps job so it is green again to catch other possible but unknown failures.
Related: bqplot/bqplot-gl#12 #949 #955 #966
=> TST: Temporarily disable bqplot dev in devdeps job.

jdaviz/configs/default/plugins/model_fitting/model_fitting.py
Fixes an error trace when selected a subset in the model fitting plugin in Specviz, introduced in #951 due to a last minute change putting code back in for Cubeviz.
=> Fix error trace introduced to Specviz model fitting

jdaviz/app.vue
This pull request fixes some inconsistencies with CSS styling when embedded in voila, including:
* styling of toolbar buttons (circle vs rectangular highlighting)
* horizontal overflow in the plugin tray
**Before**:
Note how the active state on the buttons are incorrect and the plugin tray has a horizontal scrollbar.  Scrolling to the far right shows just how much it overflowed:
**After**:
=> Voila styling tweaks

notebooks/MosvizExample.ipynb, notebooks/MosvizNIRISSExample.ipynb
This pull request makes all example notebooks consistent in importing the viz tools directly from jdaviz (as opposed to  `jdaviz.configs.mosviz.helper`, etc)
=> update mosviz notebooks to import from jdaviz root package

CHANGES.rst, jdaviz/core/helpers.py
This pull request is to remove special unit handling for Gaussian model because it breaks `viz.get_model_parameters`. Not sure why they were added but maybe it was needed at some point but it is no longer the case.
I cannot find any unit tests for the Model Fitting plugin, that this method is affected by. This method is also not in any other existing tests. So maybe adding a test for this fix is out of scope... 😬 
Fixes #975 
=> BUG: Fix get_model_parameters for Gaussian1D

CHANGES.rst, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/tests/test_helper.py
This pull request implements helper methods in mosviz to create and modify custom columns in the table.
* `mosviz.get_column`: access a copy of the array in a column from the table
* `mosviz.add_column`: existed before, but now requires column_name to be passed (instead of defaulting to None), and to overwrite the data if column_name already exists (instead of adding a duplicate column).  ~~Alternatively we could create a separate `mosviz.update_column` and raise an error in `mosviz.add_column` if the label already exists?~~  This PR also changes the order of the arguments so the column name comes first to be more intuitive and self-consistent with other new methods.
* ~~`mosviz.add_redshift_column`: wrapper around `add_column` that sets `column_name='Redshift'` so that we know the exact …
=> Mosviz: redshift column in table

CHANGES.rst, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.vue, jdaviz/configs/imviz/plugins/viewers.py
This pull request is to address the first point mentioned in #598 .
[🐱](https://jira.stsci.edu/browse/JDAT-1930)
@jenneh, would be nice to have your input on this. Thanks!
*Without* this patch (HST/ACS):
*With* this patch:
| Data source | Screenshot |
| --- | --- |
| HST/ACS | ![Screenshot 2021-11-24 012013](https://user-images.githubusercontent.com/2090236/143185709-af75775a-a63a-4630-8c14-e0aadfd3b0af.jpg) |
| HST/ACS (out of bounds) | ![Screenshot 2021-11-24 012714](https://user-images.githubusercontent.com/2090236/143186229-4e0b9e07-776d-4f5f-9ff9-eef9930679c3.jpg) |
| JWST/NIRCam | ![Screenshot 2021-11-24 011923](https://user-images.githubusercontent.com/2090236/143185706-2254e799-ac36-45c6-a036-b17789053eca.jpg) |
| JWST/NIRCam (out of bounds) | ![Screenshot 2021-11-24 …
=> Imviz: Show coordinates in degrees too

jdaviz/configs/imviz/helper.py
This pull request is to fix broken intersphinx. As soon as RTD passes, I'll merge so unrelated PRs won't see this failure. I don't think any review is needed.
=> DOC: skimage removed deprecated rgb2grey in 0.19.0

jdaviz/configs/mosviz/plugins/viewers.py
This pull request sets the toolbar tools on the spectrum-2d-viewer (in both mosviz and specviz2d) to match those in spectrum-viewer (1d and 2d pan/zoom, but only xrange region selection).  This was a blocker for #776 and confirms that that is still a remaining issue even with xrange subsets.
=> spectrum-2d-viewer: set custom toolbar tools

jdaviz/configs/specviz/plugins/redshift_slider/redshift_slider.vue
This pull request fixes a minor annoyance in the width of the select element (between redshift and RV) in the specviz redshift slider.  See before and after screenshots below.
=> redshift slider select wide enough to avoid overflow

CHANGES.rst, jdaviz/app.py, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue, jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/collapse/collapse.vue, jdaviz/configs/default/plugins/collapse/tests/test_collapse.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/specviz/plugins/viewers.py
This pull request provides immediate feedback from all plugins by showing (or replacing) data in the viewers.  In cases where data would be replaced in an image viewer, these currently default to NOT replacing, but still provide the option to replace the image in any of the available viewers and text ~(*should be reviewed by @Jenneh*)~ to explain that the new data will be available in the data menu.  
The following plugins are affected:
* gaussian smooth (slightly different behaviors in specviz, cubeviz, and mosviz due to spectral vs spatial smoothing)
* collapse (cubeviz)
* model fitting (specviz, with additional capabilities for apply to cube in cubeviz)
* moment maps (cubeviz)
~This also implements a color cycler for the spectrum viewer - so that new data entries default to have a new …
=> add data to viewers when created by plugins

CHANGES.rst, docs/specviz/import_data.rst, jdaviz/app.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_linking.py, notebooks/ImvizExample.ipynb
This pull request is to fix inaccurate coordinates info on dithered data linked by WCS.
Also add in backend to show which data is currently visible. Adding this info to GUI is a separate ticket and directly tied to Imviz wireframe work.
Suggested workflow for review:
1. Fire up Imviz example notebook.
2. Load the ACS images.
3. Zoom in so you get a nice view of some pixels.
4. Mouse over a pixel of interest.
5. Press `b` to blink. Currently, they are linked by pixels, so X/Y should stay the same but WCS and value will change.
6. Run the cell at the bottom to link them by WCS.
7. Mouse over a pixel of interest.
8. Press `b` to blink. Now, they are linked by WCS, so X/Y and value will change, but WCS still stay the same.
If you also run with the JWST data, please note that there is upstream …
=> BUG: Fix inaccurate coordinates info on dithered data linked by WCS

CHANGES.rst, docs/mosviz/index.rst, docs/mosviz/redshift.rst, docs/specviz/redshift.rst, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/mosviz.yaml, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/mosviz/tests/test_helper.py, jdaviz/configs/specviz/helper.py, jdaviz/configs/specviz/plugins/redshift_slider/redshift_slider.py
This pull request is an extension of #961 and adds a redshift slider in Mosviz along with new `mosviz.get_spectrum_1d(row=None)` and `mosviz.get_spectrum_2d(row=None)` (defaults to the currently selected row if `row` is not provided) helper methods to access the underlying data products with their respective redshifts applied.
Note: support for RVs in the slider dropdown is supported, but roundtripping is not perfect.  Support for an RV column in the table connected to the slider is not (currently) included.
This also currently includes #980 (which would preferably be merged first and then this PR rebased onto main)
Wishlist:
* roundtripping internally is confirmed to be fine.  Issue is that the _step_ of the slider itself is forcing values to round when switching between redshift and RV. …
=> Mosviz redshift slider

CHANGES.rst, setup.cfg
Does what it says in the title - I removed empty headings in the changelog for readability. #991 is the reminder to update the `glue-astronomy` pin once they do a release.
=> Update changelog for release, pin dev version of glue-astronomy for now

CHANGES.rst, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py
This pull request is to recreate missing MJD-OBS for JWST data so it will load into Cubeviz.
Proper GWCS support is not possible currently due to glue-viz/glue-astronomy#59 (the cube would load but it chokes on 1D spectrum part).
With this patch:
Fixes #690
=> BUG: Recreate JWST MJD-OBS if it is missing

docs/dev/index.rst, docs/dev/ui_style_guide.rst, jdaviz/app.py, jdaviz/app.vue, jdaviz/components/docs_link.vue, jdaviz/components/plugin_section_header.vue, jdaviz/components/tooltip.vue, jdaviz/components/tray_plugin.vue, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue, jdaviz/configs/default/plugins/collapse/collapse.vue, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue, jdaviz/configs/default/plugins/line_lists/line_lists.vue, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/plugins/links_control/links_control.vue, jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.vue, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue
This pull request attempts to minimize padding (i.e., maximize usable space) in plugins and create a consistent styling across all plugins.
If accepted and merged, all future plugin work should adopt the [new style guide](https://github.com/kecnry/jdaviz/blob/plugin-styling/docs/dev/ui_style_guide.rst) (also added to the docs as part of this PR/review).
The screenshots below show a few places with noticeable changes at the default plugin tray width (which also becomes the **minimum allowed width in a default notebook** in this PR) and with the cell extended to 100% width (with the plugin tray still at 25%). 
Changes that *might* be controversial:
* model fitting & line lists: move check boxes from right to left and remove column headers
* model fitting: rename "add model" button to "add …
=> consistent plugin padding & styling

CHANGES.rst, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue
Separates out the Subset selection from the Data selection in the Line Analysis plugin, in case there are multiple datasets that a subset might be applied to. Also removes some defunct code that was still there, probably from an older version that did things differently.
I'll note here, because it's given us problems before, that I ended up removing the `SubsetCreate` message handling entirely. There is no guarantee of which order message handlers will be executed in in Glue, so I was hitting an error where the handler was getting called (and trying to retrieve the created subset) before the handler that actually adds the subset to the viewer, which is apparently also triggered off the `SubsetCreate` message. As far as I can tell, the `SubsetUpdate` message always gets triggered after a …
=> Line analysis subsets

jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/conftest.py
This pull request is to re-enable and fix a failing test.
Fixes #948 
Follow-up of #547
=> TST: Re-enable test_moment_maps

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py
Fixes #1022 , ended up being very simple. The displayed parameters for models with multiple components now update properly with the fitted values again.
=> Fix model parameter updating after fit for compound models

jdaviz/configs/default/plugins/model_fitting/model_fitting.vue
This pull request fixes dark theme support for model parameter names in the model fitting plugin.
Fixes #1028 
=> Fix dark theme support for model parameter names

CHANGES.rst, docs/dev/ui_style_guide.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/core/custom_traitlets.py, jdaviz/core/tests/test_custom_traitlets.py
This pull request removes the traceback caused by emptying the poly_order input in the polynomial component of the model fitting plugin.
If adopted, similar logic should be applied across all number input fields across all plugins in the future (created separate ticket).
Before:
https://user-images.githubusercontent.com/877591/150211150-b90ebb49-5286-40ca-9153-360b3ce95400.mov
After:
https://user-images.githubusercontent.com/877591/150211182-fca10802-d928-46f4-a6b6-8414c73b5a22.mov
**TODO**:
=> model fitting: handle empty poly order input

CHANGES.rst, jdaviz/app.py, jdaviz/tests/test_viewer_ids.py
This adds a reference to the global jdaviz application in the global glue session object so that the jdaviz application can be accessed e.g. in viewers using ``viewer.session.jdaviz_app``. This is needed for https://github.com/spacetelescope/jdaviz/pull/983 and supersedes https://github.com/glue-viz/glue-jupyter/pull/274 and https://github.com/glue-viz/glue/pull/2256
=> Add reference to jdaviz app in glue session object

.github/workflows/ci_workflows.yml, tox.ini
This is mainly to investigate if there is a way we can fix the remote data job timeout, which is blocking other PRs. While I am at it:
* Update test matrix
* ~Make tox verbose.~
* Delete unused tox configs.
* Fix #1053 
Note to reviewers: Ignore the yellow "Python 3.8 with coverage checking, all deps, and remote data" as the job name has changed now that I updated that job to use Python 3.9. I'll have to update branch protection rules *after* this PR is merged.
Note to self: Open follow-up issue to unpin coverage in the future.
=> TST: Update test matrix, etc

CHANGES.rst, docs/imviz/plugins.rst, docs/mosviz/plugins.rst, docs/specviz/plugins.rst, jdaviz/configs/default/plugins/__init__.py, jdaviz/configs/default/plugins/metadata_viewer/__init__.py, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.vue, jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py, jdaviz/configs/imviz/imviz.yaml, jdaviz/configs/mosviz/mosviz.yaml, jdaviz/configs/specviz/specviz.yaml
This pull request implements a new generic plugin to display whatever metadata attached to the selected glue Data, as long as it is a dictionary. For FITS, this is the header of the loaded extension. We can make it pretty later...
Would be nice if it auto-detects which one is the actively displayed Data and just display metadata for that, but it is hard to implement because layouts allow multiple viewers.
=> POC: Simple metadata viewer plugin

.gitignore, CHANGES.rst, jdaviz/app.vue, jdaviz/core/helpers.py, jdaviz/tests/test_show.py, notebooks/CubevizExample.ipynb, notebooks/ImvizExample.ipynb, notebooks/MosvizExample.ipynb, notebooks/SpecvizExample.ipynb, setup.cfg
This PR adds a methods to the `jdaviz` helpers that allow them to be popped out into new tabs in jupyterlab. This video shows the two new ways of doing it in action.
https://user-images.githubusercontent.com/346587/139784545-a1e9011c-b9f6-4263-a2eb-feb256e216c7.mp4
This works as-is, but I have several standing questions which might need implementation of something before I'm ready to call this done:
```
def show_in_sidecar(self, **kwargs):
return self.app.show_in_sidecar(**kwargs)
```
=> Implement mechanism for helpers to create new tabs for apps.

jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py, jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/imviz/tests/test_regions.py, jdaviz/configs/imviz/tests/test_viewers.py, jdaviz/configs/imviz/tests/utils.py, jdaviz/configs/mosviz/tests/test_helper.py, jdaviz/configs/mosviz/tests/test_parsers.py, jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/conftest.py, jdaviz/tests/test_show.py, jdaviz/tests/test_viewer_ids.py
I ran into a small nomenclature discrepancy with our pytest fixtures that tripped me up after returning to jdaviz in who knows how long! Our test fixtures for the viz helpers are called `<spec | cube | mos | im>viz_app` which is slightly confusing to me at least, since they are the helpers and not the underlying apps (i.e. `<spec | cube | mos | im>viz.app`). This PR renames the test fixtures to `<spec | cube | mos | im>viz_helper` to be more explicit, and substitutes this change through all the unit tests. Since this has a lot of small changes, I figured I'd put this into its own PR
This naturally impacts all the devs in writing their unit tests, so we should advertise this change to everyone, and all should rebase before we stray too far.
This checklist is meant to remind the package …
=> Rename helper test fixtures from 'app' to 'helper'

CHANGES.rst, docs/imviz/plugins.rst, docs/known_bugs.rst, jdaviz/app.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/tests/test_simple_aper_phot.py, jdaviz/core/template_mixin.py
This pull request is to add radial plot to simple aperture photometry plugin in Imviz.
Close #962
[🐱](https://jira.stsci.edu/browse/JDAT-2055)
HST/ACS data (dark mode):
JWST simulated data:
`photutils` example data (no WCS nor unit):
=> FEAT: Radial profile in Imviz simple aperture photometry plugin

jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py
This pull request updates all remaining mentions of spectral_subset = "None" in plugins to be "Entire Spectrum" for self-consistency.
=> plugins: spectral_subset choice from "None" to "Entire Spectrum"

jdaviz/configs/mosviz/tests/test_helper.py
This pull request is to handle new warning that pops up due to astropy/specutils#922 in newly released specutils.
=> TST: Silence specutils warning in fixture

jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
Fix displayed decimals for X/Y centers in Imviz Simple Aperture Photometry plugin. Pretty sure this is a regression. It used to limit the number of decimals. Not sure what happened, maybe a careless force push by me at some point. 🤷 
=> BUG: Fix displayed decimals for X/Y centers in Imviz Simple Aperture Photometry plugin

CHANGES.rst, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/tests/test_parser.py, notebooks/concepts/imviz_load_3d_slices.ipynb
This pull request is to enable:
* Loading a data cube as individual 2D slices at `axis=0`.
* Enable option to disable linking at every iteration when user wants to call `imviz.load_data(...)` in a loop.
Fixes #1055
Fixes #1058
=> Imviz: Load 3D slices, enable delayed_linking

docs/imviz/import_data.rst, jdaviz/configs/imviz/helper.py
This pull request is follow-up on #1056 by documenting the limitation in performance when user wants to load too many images into Imviz (because it is easier now to do so).
=> DOC: Clarify Imviz load_data performance limitation

CHANGES.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
As pointed out by @orifox , Simple Aperture Photometry plugin should not depend on what is shown in the default viewer because it should work for data shown on any viewer. To avoid overcomplicating the logic, I am simply displaying data and subsets across the whole app, not depending on the viewer anymore. So now the plugin should even work if no data is displayed as long as it is loaded, but why would anyone do that... who knows?
=> Imviz: Aperture photometry plugin with viewer-agnostic data/subset dropdown menus

docs/dev/ui_description.rst
This pull request is to use intersphinx to an important link for devs that @astrofrog mentioned this morning. Not sure how to make it easier to find though.
http://docs.glueviz.org/en/stable/customizing_guide/viewer.html
=> DOC: Use intersphinx in glue dev doc link

docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/tests/test_simple_aper_phot.py, licenses/IMEXAM_LICENSE.txt
This pull request is to address the need to add more plot options to the simple aperture photometry plugin in Imviz.
Partially fixes #1049 although a new ticket needs to be made to implement curve of growth. (The rest of #1049 will be part of #1048 anyway.)
=> Imviz: Add a different radial profile approach

CHANGES.rst, jdaviz/core/tools.py
This pull request silently ignores clicks (without drags) when using box or xrange zoom.  Previously this would result in a TypeError traceback.
=> box zoom: ignore click without drag events

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/imviz/tests/test_simple_aper_phot.py, notebooks/concepts/imviz_simple_aper_phot.ipynb
This pull request is to implement the most minimal version of background auto-population as proposed at https://github.com/spacetelescope/jdaviz/issues/1050#issuecomment-1048278800 .
Fixes #1050 
=> Simple Aperture Photometry Plugin: Auto-populate background

CHANGES.rst, jdaviz/configs/specviz/plugins/viewers.py
This pull request removes the index error caused by #1060 and reported in #1113, but also occurring before (#908, #1010) by ensuring the index to `figure.marks` is pointing to a `Lines` object rather than other marks added (spectral lines, continuum indicator, etc).
The full intention of the `self.data_trace_pointer` is a little unclear to me and may need to be revisited in the future.  But this PR attempts to reproduce the original intent of updating the index with the latest data entry in `self.figure.marks` by searching that list in reverse order and taking the first that is an actual `Lines` object instead of one of our custom marks that might be appended later.
Fixes #908 #1113 …
=> Fix figure marks index error

CHANGES.rst, jdaviz/app.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/tests/test_subsets.py
This pull request is to address the bug where the upper value of the subset is off by one index value (i.e. stops one index value short of the correct upper value for the subset). This PR also updates related tests.
Fixes #1114 
=> Fix bug for subsets not having the correct upper value

jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_parser.py
Imviz: Limit cube slices to 16 for performance reasons. A direct follow-up of a yet to be released feature from #1056 , so no change log is necessary here.
This was requested by PO during sprint review on 2022-02-28.
=> Imviz: Limit cube slices to 16

CHANGES.rst, docs/dev/ui_style_guide.rst, jdaviz/components/tray_plugin.vue, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/line_lists.vue, jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.vue, jdaviz/core/template_mixin.py
This pull request is to use #1106 to disable Unit Conversion plugin if Subset exists in data collection. This is because Subset does not react well to unit conversion. This will require users to do all the unit conversion they want before they create any Subset. If they want to do Unit Conversion after creating Subset, they must first delete the Subset.
Close #1106 
=> Disable Unit Conversion plugin if Subset exists

setup.py, tox.ini
This pull request is to remove `build_docs` tox env because we don't use it in CI (we use RTD PR builder that does not use tox) and @rosteen cannot get it to work locally, so it is basically useless.
I think the important thing is an approval from @rosteen since he originally reported this problem.
=> MNT: Remove build_docs in tox

jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/specviz/plugins/viewers.py, jdaviz/core/astrowidgets_api.py
This pull request is to remove `minversion` checks that is no longer needed.
https://github.com/spacetelescope/jdaviz/blob/f7ccdcf236a5bb04201e0274dc3ae27a82dc055f/setup.cfg#L21
=> MNT: Remove unused minversion check

CHANGES.rst, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/core/astrowidgets_api.py, notebooks/ImvizExample.ipynb
This pull request is to allow unfilled circles in marker API for astrowidgets.
Needs:
* glue-viz/glue-jupyter#292
Blocked by:
* #1117
Fixes #713 
=> Astrowidgets API: Allow unfilled circles

jdaviz/configs/imviz/plugins/compass/compass.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/core/registries.py, jdaviz/core/template_mixin.py
This pull request moves the logic in LineAnalysis to act differently if the plugin is opened or closed into the `PluginTemplateMixin` to be available to all plugins, and then used in the compass plugin to only re-draw the compass when the plugin is opened.
=> Mixin for plugin_opened and use for compass

CHANGES.rst, jdaviz/app.py, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py
This pull request is to address the problem with over-plotting contours in cubeviz. It uses `pixel_component_ids` to do this, so data is linked by pixel rather than by WCS.
Fixes #318 
Close #1159
GIF shows contours of cubes on top of each other.
GIF shows contours of moment map plotted over a cube.
=> Fix data linking to allow contour over-plotting

jdaviz/configs/cubeviz/cubeviz.yaml, jdaviz/configs/default/default.yaml, jdaviz/configs/imviz/imviz.yaml, jdaviz/configs/mosviz/mosviz.yaml, jdaviz/configs/specviz/specviz.yaml, jdaviz/configs/specviz2d/specviz2d.yaml
It just bothers me that it is not listed last because usually you export at the end of the workflow. 😆 
With this patch (example below from Imviz):
=> Move export plot plugin to last in the listing

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py
Fixes #1144, as well as a bug I noticed that doesn't have an issue, where the data dropdown menu wasn't properly getting populated with spatial subsets when they were created.
=> Fix model fitting plugin bugs

CHANGES.rst, jdaviz/app.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/tests/test_parser.py
This pull request is to fix #1126
=> BUG: Fix load data after imviz.app does not show last loaded data

CHANGES.rst, jdaviz/app.py
This pull request is to fix a bug where data set to not visible after blinking remains invisible even if it is the only Data left in the viewer.
Fixes #1107 
=> BUG: Surviving Data in viewer must be visible

CHANGES.rst, docs/cubeviz/plugins.rst, docs/specviz/plugins.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/specviz/plugins/viewers.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/core/marks.py
This pull request is to allow the user to show the uncertainty of a spectrum in the specviz viewer using a UI toggle. It also fixes the code for showing uncertainties and masks, allowing them to work for multiple data selected in the specviz viewer.
Fixes #1146 fixes #285
=> Add UI option to show uncertainties in specviz viewer

CHANGES.rst, jdaviz/components/plugin_subset_select.vue, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue, jdaviz/configs/default/plugins/collapse/collapse.vue, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/tests/test_simple_aper_phot.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/core/template_mixin.py
This pull request extends upon #1156 to support both spatial and spectral subsets (including in the same dropdown, although we don't have any uses for that, yet).  Most of this is just a generalization of logic, with a new Mixin for `SpatialSubsetSelectMixin`.
For the aperture photometry plugin, the dropdowns now look like:
Although not actually in use, a mixed dropdown would look like:
=> generalize subset select component to handle spatial and spectral

jdaviz/app.py, jdaviz/components/plugin_viewer_select.vue, jdaviz/configs/default/plugins/export_plot/export_plot.py, jdaviz/configs/default/plugins/export_plot/export_plot.vue, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/imviz/plugins/compass/compass.py, jdaviz/configs/imviz/plugins/compass/compass.vue, jdaviz/core/template_mixin.py, jdaviz/core/tests/test_template_mixin.py, jdaviz/core/tools.py
This pull request continues the pattern in #1156 to pull up duplicated logic from plugins and into a re-usable component for viewer select dropdowns.  In doing so, it also gives flexibility for reference vs ID (so that cubeviz will show the more user-friendly "uncert-viewer" names instead of "cubeviz-2" but imviz will still work with IDs since references are never created).  All other functionality should be unchanged - this is mostly just a code refactoring.
=> re-usable component for viewer dropdown

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue
This pull request is an extension of #1189 that makes the uncertainty toggle per-viewer instead of per-app to address https://github.com/spacetelescope/jdaviz/pull/1189#discussion_r836748804.
Fixes #1207
=> Per viewer uncertainty toggle

CHANGES.rst, jdaviz/configs/specviz/plugins/viewers.py
This pull request changes the default collapse function in the Specviz viewers to sum, instead of maximum. 
=> Change default collapse function to sum

docs/dev/index.rst, docs/dev/win_dev.rst, setup.py
This pull request is to improve quality of life for developers that have to develop Jdaviz on Windows.
@maartenbreddels , does this patch look reasonable to you from the voila side?
Fixes #925 
Fixes #1213 
=> DEV: Fix editable install on Windows

CHANGES.rst, jdaviz/configs/cubeviz/plugins/parsers.py
This pull request is to address esa pipeline data not being loaded into cubeviz.
=> Add esa data parser to cubeviz

CHANGES.rst, jdaviz/configs/specviz/plugins/viewers.py
This pull request is to address the problem that the Specviz viewer would reset it limits every time data was added. That line of code has been removed and the original code to set the collapse function to sum is in the init method
Follow-up of #1229 .
Close #1236
=> Move set collapse function to init method

jdaviz/configs/cubeviz/plugins/parsers.py
This pull request is to address the axes not appearing correctly in the original ESA parser implementation. The wavelength axes also did not appear correctly because it used `WAVE-LOG` instead of a barebones wavelength value for `CTYPE1`.
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive. I think no change log needed since no users (except for @PatrickOgle) can tell that anything is even different!
=> Fix ESA axes

CHANGES.rst, jdaviz/app.py, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/collapse/tests/test_collapse.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/conftest.py, jdaviz/tests/test_subsets.py, setup.cfg, tox.ini
This implements compatibility with https://github.com/glue-viz/glue-astronomy/pull/68, which stops reordering Cube axes and leaves things the way they are in the `specutils.Spectrum1D` object. Opening as draft since this is very experimental and still needs work - I've fixed the data loading and slice plugin, but I'm sure a couple other things were broken by this. Mainly I wanted other people to see it if they're curious.
xref #1190 
=> Update Cubeviz to work on data with spectral axis last

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/utils.py
This pull request is to address loading snackbar messages from being ignored if a current snackbar is being displayed.  The new behavior is that a message with `loading=True` will immediately interrupt the current queue and will show indefinitely until another message is pushed to the queue, at which point THAT message will show first and then the queue will continue with the message that was first interrupted.
This should be thoroughly tested in the app with real use-cases, but can also be tested manually with something like:
```
from jdaviz.core.events import SnackbarMessage
from time import sleep
for i in range(5):
msg = SnackbarMessage(f"message {i}", color='info', sender=None)
specviz.app.hub.broadcast(msg)
sleep(6)
msg = SnackbarMessage(f"LOADING INTERRUPT (3s)", loading=True, …
```
=> snackbar queue: better handling of loading interrupts

CHANGES.rst, README.rst, docs/mosviz/import_data.rst, docs/quickstart.rst, jdaviz/cli.py
This pull request changes the `--layout` option in the CLI to a positional (required) argument.  So `jdaviz FILENAME --layout=cubeviz` is now `jdaviz cubeviz FILENAME`.  This also removes `'default'` as an option for layout until it is properly supported.  In doing all of this, the CLI outputs change for the following:
**BEFORE**
`jdaviz`:
```
Usage: jdaviz [OPTIONS] FILENAME
Try 'jdaviz --help' for help.
Error: Missing argument 'FILENAME'.
```
`jdaviz --help`:
```
Usage: jdaviz [OPTIONS] FILENAME
Start a Jdaviz application instance with data loaded from FILENAME.
Options:
--layout [default|cubeviz|specviz|mosviz|imviz]
Configuration to use on application startup
[default: default]
--browser TEXT                  Browser to use for application  [default:
default]
--theme [light|dark] …
```
=> CLI: change layout from an option to a positional argument

docs/cubeviz/import_data.rst, docs/imviz/import_data.rst, docs/mosviz/import_data.rst, docs/specviz/import_data.rst, docs/specviz/plugins.rst
These are the only inconsistencies I could find between the doc page titles in the different configs. I'm trying to be good and resist making more changes here 😆 .
=> Homogenize doc page titles/subheadings between the configs

CHANGES.rst, jdaviz/app.py, jdaviz/app.vue
This pull request implements a search bar at the top of the plugin tray with simple exact-match search on plugin titles to filter plugins in the expansion panels.
* currently synced across multiple instances of the app - may want to have it per-instance in the future (but using 'data' on the app-level seems not to work)
* currently exact match on the plugin label only.  Could extend this to search full text or tags, etc.  Could also create a "command palette" and/or keyboard shortcut to immediately focus the search field (as future work).
* NOTE: cannot filter the input list to `v-expansion-panels` as that disrupts the `tray_items_open` list of indices, so instead we hide the child `v-expansion-panel-header`/`v-expansion-panels-content` items. …
=> basic plugin search

CHANGES.rst, jdaviz/components/toolbar_nested.py, jdaviz/components/toolbar_nested.vue
This pull request is to address the extra click produced in Safari on MacOs when using ctrl-click as right-click.
Fixes #1256
=> fix: workaround for extra click when using ctrl-click in safari

docs/dev/index.rst, docs/dev/win_dev.rst, setup.py
This pull request is another attempt to improve quality of life for developers that have to develop Jdaviz on Windows. This is the basic fix from #1218 before we tried to get too fancy. The logic should not affect Linux/OSX at all but devs should check.
* Fixes #925
* Fixes #1213
=> DEV: Fix editable install on Windows (try 2)

docs/cubeviz/import_data.rst, jdaviz/core/region_translators.py
This pull request is to:
* directly follow up on #1286 
* fix wrong numpydoc section name (it has the warning in the log but did not trigger RTD to fail on warning)
=> DOC: Minor fixes

jdaviz/components/number_uncertainty.vue
This pull request adds support in the `<j-number-uncertainty>` (implemented in #1244) to support not passing uncertainties (and still rounding the number).  This should not have any affect on existing internal uses in line analysis (so I don't think it warrants a changelog entry?), but will make the component usable in #1292.
=> uncertainty rounding component: smarter default if uncertainty isn't passed at all

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/viewers.py
This pull request is to report correct X and Y when "l" is pressed over dithered data that is not the reference data. You can try this out by linking the Imviz example notebook by WCS and then press "l" and then blink and then press "l" again.
I also moved entries from #1224 to the correct section. They were bug fixes, not API changes.
Fixes #1285 
=> BUG: Fix Line Profile not handling dithered data in Imviz

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/tests/test_simple_aper_phot.py
This pull request is to add curve of growth plot in Simple Aperture Photometry plugin.
[:cat:](https://jira.stsci.edu/browse/JDAT-2325)
=> Imviz: Curve of growth plot

CHANGES.rst, jdaviz/configs/specviz2d/helper.py
This pull request is to fix traceback for some simulated NIRSpec s2d data that used to work.
Fixes #1306
Also see https://github.com/glue-viz/glue-jupyter/pull/306
=> BUG: Fix specviz2d traceback for NIRSpec s2d data

CHANGES.rst, jdaviz/configs/specviz/plugins/viewers.py
This PR clears the internal string storing the identified line if the currently identified line is removed.  Should ~resolve~ take care of https://github.com/spacetelescope/jdaviz/pull/1318#discussion_r872588309 in #1318.
=> Fixing clearing identified spectral line when removed

CHANGES.rst, docs/cubeviz/displaycubes.rst, docs/imviz/displayimages.rst, jdaviz/configs/cubeviz/cubeviz.yaml, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/cubeviz/plugins/viewers.py
This pull request is to add Imviz-like coordinates display for Cubeviz image viewers.
This is all UI so I am not sure how to add tests. There is currently no unit test for this equivalent capability in Imviz. Reviewers should interactively load a few different datasets that we are supposed to support and see what happens...
Here is a screenshot with data from Cubeviz example notebook (the mouse was at the center of flux viewer for this one):
Fixes #1090 
Imviz's display was originally done by @astrofrog (e.g., #557).
=> Cubeviz image viewer coordinates display

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py
This pull request is to fix #1168 .
It is more stable to grab remaining indices as new table than to in-place remove a bunch of rows. Reviewers should manually test with different scenarios as I am not sure what are all the possible combos.
=> BUG: Avoid crashing when line list is removed

CHANGES.rst, docs/imviz/displayimages.rst, jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/plugins/viewers.py
This pull request is to enable "click to center" when in pan/zoom mode (either linked or unlinked)
This is driven by interactive actions, and by precedence, I didn't write any non-interactive unit tests for it. The underlying `center_on()` method is already tested in `test_astrowidgets_api.py`.
=> Imviz click to center in pan/zoom

CHANGES.rst, docs/cubeviz/plugins.rst, jdaviz/configs/cubeviz/cubeviz.yaml, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.vue, jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/tests/test_data_loading.py, jdaviz/configs/mosviz/tests/test_parsers.py, jdaviz/configs/specviz/plugins/parsers.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/configs/specviz2d/plugins/parsers.py, jdaviz/configs/specviz2d/specviz2d.yaml, jdaviz/configs/specviz2d/tests/test_parsers.py, jdaviz/conftest.py, jdaviz/tests/test_metadata.py, jdaviz/utils.py
This pull request is to parse metadata for Cubeviz and show it in Metadata Viewer plugin.
When there is primary header:
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Fixes #1324 
=> ENH: Cubeviz metadata viewer

docs/cubeviz/plugins.rst, docs/imviz/plugins.rst, docs/mosviz/plugins.rst, docs/specviz/plugins.rst, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.vue
This pull request is to address doc and styling comments from #1325.
* @kecnry -- *maybe worth a mention explaining the primary switch here?*
* @havok2063 -- *My only comments are about the styling. When the plugin tray size is small, everything gets squished together and word wraps. This improves when the plugin tray is expanded out, but that takes up real estate. Could we tweak the styles here to try to mitigate some of this? Maybe reducing the font size of the values and comments? Or making the header key bold? Something to try to reduce the amount of whitespace/padding and to visually distinguish a header key with the comment underneath when the plugin tray is small. Jenn might have some thoughts for this.* cc @Jenneh
This is a direct follow-up of #1325. Also see  #1324 .
This …
=> Metadata Viewer: Doc and styling

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/tests/test_parser.py
This pull request is to fix a bug where aperture sum counted npix twice when converting from MJy/sr to MJy. Thanks to @orifox for finding this bug and @larrybradley for the fix suggestion!
=> BUG: aperture sum counted npix twice

jdaviz/utils.py
This pull request is to avoid Metadata Viewer from crashing when user loads a file with invalid FITS header. Also see https://github.com/spacetelescope/dat_pyinthesky/issues/177 . This is split from #1333 . As noted in the other PR, I have a very hard time creating invalid FITS header by hand and I do not want to download a whole cube to test this one thing, so I did not add any test.
This fixes an unreleased feature (#1325), so it does not need a change log.
Would be nice to merge this fast so I can build #1333 on top of this.
=> BUG: Metadata viewer to ignore invalid FITS header

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
This pull request is to address reported bug where a failed cube fit would silently return a cube with all zeroes because multiprocessing swallowed all the exceptions. This PR intents to:
* fix the bug that caused the exception in the first place
* allow bypassing multiprocessing when `n_cpu` is set to 1 (this feature is for developers only)
Fix #1245
=> Cubeviz cube fitting: Fix fitted cube all zeroes, allow MP bypass

CHANGES.rst, jdaviz/configs/default/plugins/data_tools/data_tools.py
This pull request is to fix a bug where Imviz behaves weirdly because image loaded via file chooser (`IMPORT DATA`) is not linked to anything. File chooser itself is GUI driven and not tested, so I did not add any test for this.
Fixes #1364
=> BUG: Fix Imviz linking data from file chooser

CHANGES.rst, docs/cubeviz/displaycubes.rst, jdaviz/configs/cubeviz/plugins/tests/test_tools.py, jdaviz/configs/cubeviz/plugins/tools.py
This pull request changes the spectrum-at-spaxel tool to use subsets instead of new Spectrum1D objects.
Fixes #1375
Fixes #1374
=> Use subsets for spectrum-at-spaxel tool

CHANGES.rst, jdaviz/app.py
This pull request is to change the default percentile from min/max to 95% so typical astronomical images show better on load.
Fixes #577 
Previous failed attempts:
* #605 
* #710 
* https://github.com/glue-viz/glue/pull/2199
=> Change default image viewer percentile to 95%

setup.py
This pull request is to address https://github.com/spacetelescope/jdaviz/pull/1218#issuecomment-1095105519 by allowing symlink on Windows when it is possible.
For my own Windows setup, symlink is impossible because Miniconda is on C drive by source code in on D. With this patch, I confirmed that it still makes a full copy as in #1218 without crashing. Imviz seems to work in notebook and standalone modes.
For my WSL2 setup, I can confirm that this patch still does symlink, as expected. Imviz seems to work in notebook but I cannot test the standalone portion due to voila-dashboards/voila#773 , though I don't see why it wouldn't work.
Devs who review this should check that the files are copied or symlinked properly and at least run a quick example notebook. You should install this PR branch …
=> DEV: Allow symlink in Windows for editable install

docs/known_bugs.rst
This pull request is to document a known upstream issue that @javerbukh reported at https://github.com/spacetelescope/jdaviz/pull/1373#issuecomment-1150001663 . Also see jupyterlab/jupyterlab#11934 .
=> DOC: Add Jupyter Lab IndexError as known issue upstream

tox.ini
This pull request is to update the incantation to grab "nightly" wheel for numpy for the dev job. It started to fail for unrelated PRs.
xref numpy/numpy#21715 and astropy/astropy#13322
=> TST: Fix numpy nightly wheel install for dev job

CHANGES.rst, jdaviz/configs/specviz/plugins/viewers.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/core/helpers.py
This pull request changes the default subset layer thickness (introduced in #994) to be dependent on whether it is a spatial subset (collapsed in the spectrum-viewer) or a spectral subset.
Before:
After:
=> default width of subset for spectral vs spatial

CHANGES.rst, jdaviz/app.py, jdaviz/cli.py, jdaviz/core/helpers.py, notebooks/concepts/imviz_compass_mpl.ipynb, notebooks/concepts/imviz_line_profiles.ipynb, notebooks/concepts/imviz_load_3d_slices.ipynb, notebooks/concepts/imviz_simple_aper_phot.ipynb
This pull request is to stop emitting popup messages unless it is warnings or worse. This is because you can still see the mundane info stuff in the history logger. I have always been annoyed by all the popup messages when I load any of the viz.
With this patch, for instance, you will only see these when you open up the history logger thingy if nothing goes wrong on load.
This is a direct follow-up of #1352 
=> Set popup verbosity to warnings

CHANGES.rst, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/utils.py, jdaviz/configs/imviz/wcs_utils.py
This pull request is to fix some bugs. The fixes were part of #1340 but now separated out into a proper bugfix PR.
1. Fix #1299
2. Fixed a bug where Compass zoom box is wrong when the second image is rotated w.r.t. the reference image and they are linked by WCS.
3. Fixed a bug where Line Profile might crash when the second image is rotated w.r.t. the reference image and they are linked by WCS, causing insufficient data for plot limit calculations.
=> BUG: Imviz bug fixes ported from PR 1340

CHANGES.rst, jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/tests/test_viewer_tools.py
This pull request is an alternate to #1394 (although still needs to pull in the tests and perhaps contrast inversion from that PR) to optimize the drag behavior by replacing the rejection of events based on timestamp with debouncing in python (and caching the state and viewer size on dragstart).
Fixes #1359
=> contrast-bias tool: debounce instead of reject based on time

CHANGES.rst, jdaviz/core/template_mixin.py
This pull request is to rename One Color Per Layer to Monochromatic for image viewers. This is built upon #1343.
=> Rename One Color Per Layer to Monochromatic

CHANGES.rst, jdaviz/app.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py
This pull request is to add reversed version for several colormaps.
=> Add reversed colormaps

CHANGES.rst, jdaviz/data/linelists/HeI-HeII.csv
This pull request is to add a missing comma to the CSV data file.
Fixes #1430
=> BUG: Fix HeI-HeII data file

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/tests/test_simple_aper_phot.py, notebooks/concepts/imviz_simple_aper_phot.ipynb
This pull request is to enable Gaussian1D fitting for radial profile in the Simple Aperture Photometry plugin.
(Screenshots a bit outdated, but you get the idea.)
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Simple Aperture Photometry: Gaussian1D fitting for radial profile

CHANGES.rst, docs/notebook/display.rst, docs/notebook/index.rst, docs/quickstart.rst, jdaviz/configs/specviz/helper.py, jdaviz/core/helpers.py, jdaviz/tests/test_show.py, notebooks/CubevizExample.ipynb, notebooks/ImvizExample.ipynb, notebooks/MosvizExample.ipynb, notebooks/MosvizNIRISSExample.ipynb, notebooks/SpecvizExample.ipynb
Ok I'm going to finally admit to a nearly 18 month secret I've been hiding since I originally wrote the first helper for specviz. I've always had negative opinions about `viz.app`. I feel like it's not intuitive and not apparent to a brand new user, and almost forces them to read the documentation first before even trying to take it for a spin (which I imagine some may see as a good thing, but I'm going to argue I don't have to read Chrome's documentation when I launch it!). So I added `specviz.show()` as a wrapper to the `specviz.app` call:
https://github.com/spacetelescope/jdaviz/blob/392e1b626c2ac0dbe314bb103cadf001e1b9db4c/jdaviz/configs/specviz/helper.py#L200-L201
Here's the secret... it doesn't work. It never worked. I struggled for SO LONG at the time but I couldn't fix it; I just …
=> Add show() method as preferred entrypoint

CHANGES.rst, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py
This pull request limits the data dropdown in the gaussian smooth plugin in mosviz to only include data entries in the (1d) spectrum-viewer.
Fixes #1451
=> mosviz gaussian smooth: only include data from spectrum-viewer

CHANGES.rst, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/cubeviz/plugins/viewers.py
Coordinate display for Cubeviz was added in #1315 . But without this patch, when multiple dataset are loaded into an image viewer, it shows the info from the bottommost layer, not topmost. This is the most apparent when you load a moment map (it currently has no WCS) on top of the flux cube in the flux viewer. You see the moment map displayed but the coordinate display would still show WCS from the flux cube. With this patch, coordinate display will now show correctly.
This was discovered during my investigation of another bug in #1328 . 
=> BUG: Cubeviz coordinate display should follow top visible layer

CHANGES.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/tests/test_simple_aper_phot.py
This pull request is to ensure Simple Aperture Photometry plugin is aware of Subset that is updated *after* it is created, if relevant to calculations. Most things will not recalculate until user presses "Calculate" but the background is calculated "live" before the button is pressed. There are 3 dropdowns. The dataset dropdown already triggers all recalculations, so I don't think it is affected but this bug.
This patch fixes the following cases:
1. When aperture is selected, editing the aperture Subset will cause: (a) background to update immediately in "Annulus" mode, and (b) the rest to update when pressing "Calculate".
2. When background is from Subset, editing the background Subset till cause the background to update immediately.
Fixes #1443  …
=> BUG: Simple Aperture Photometry plugin to update when Subset updates

CHANGES.rst, jdaviz/app.vue
This pull request hides the "popout in new window" button for the golden layout tabs in imviz.  The current implementation is buggy as it loads the whole notebook in a new window.  In the future, we could make use of #977 instead and re-enable the button.
=> imviz tabs: hide popout button

.readthedocs.yml, MANIFEST.in
This updates our configuration to no longer packaged the docs (due to the large GIF file sizes) in the release tar files, and instead generates PDF and zipped HTML version of the docs that can be downloaded by the users for offline use.
=> Update docs packaging and build

CHANGES.rst, jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/tests/test_linking.py
This pull request fixes the coordinate display (in imviz or cubeviz) to update when blinking via clicking (the "b" hotkey worked already).
~This is failing coverage checks - but we never had coverage on the click event and don't have a good way to simulate that afaik.~
=> Fix updating coordinate displaying when blinking via click

docs/known_bugs.rst
Does what it says on the tin. This is the workaround for https://github.com/glue-viz/bqplot-image-gl/issues/94.
=> Add Linux VM spectrum viewer problem to known bugs

CHANGES.rst, jdaviz/core/template_mixin.py
This pull request fixes setting the plot options state for colormap when set through the API (either by manually setting the glue-state or through the astrowidgets API).
Fixes #1506
=> fix setting plot options state when setting cmap through API

CHANGES.rst, jdaviz/app.vue, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/default/plugins/data_tools/data_tools.vue, jdaviz/configs/mosviz/helper.py
Here is an attempt that would close #1345. Do we like keeping the buffer on the left of the subset creation button or should it be flush with the left app border after the import button disappears?
https://user-images.githubusercontent.com/12895749/179110595-e8ad1339-5533-48ce-9e23-b414d5611bfe.mov
I also added a `load_data()` method to the `Cubeviz` class in order to raise an error if someone attempts to programmatically add a cube when one is already present in the app. I didn't allow for keyword arguments like some of the other configs' versions do: specifying a `data_type` (flux, mask, uncert) doesn't make sense if we only allow data to be loaded once, and using `data_label` to apply labels with glue seems like it should be internal.
Thanks to @kecnry for helping me get started.
This …
=> Hide Cubeviz import button after importing data

CHANGES.rst, jdaviz/components/plugin_layer_select.vue, jdaviz/components/plugin_viewer_select.vue, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/default/plugins/viewers.py, jdaviz/core/template_mixin.py
This pull request includes spectral subset layers in the layer dropdowns for image viewers in cubeviz's plot options plugin.  In order to do so, it includes a workaround to prevent the layer visibility default logic (which was otherwise firing after the _next_ state change rather than the original creation of the layer itself, which resulted in buggy behavior when trying to manually change the visibility of these layers).  This also improves some styling of the multiselect dropdowns for layers/viewers in the plot options plugin.
=> Cubeviz spectral subset tweaks

CHANGES.rst, jdaviz/app.py, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/default/plugins/collapse/tests/test_collapse.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py
Fixes #1525, although this should be considered a temporary workaround until (hopefully) upstream fixes happen. The root cause of the issue is that Glue's `WCSLink` looks for a `has_celestial` attribute on the `data.coords` object. In the case of a `Spectrum1D` that's initialized with a spectral_axis array rather than a WCS (and thus creates a lookup table GWCS), glue_astronomy creates a special `SpectralCoordinates` object for the `data.coords` that was missing the `has_celestial` attribute. This caused an `AttributeError` every time and thus the linking to fall back on pixel links. 
Unfortunately, after I locally added `has_celestial=False` to the `SpectralCoordinates`, the `WCSLink` seemed to still fail. So here we fall back on the old explicit manual linking for this case while more …
=> Add workaround for Spectrum1D GWCS links

CHANGES.rst, docs/mosviz/import_data.rst, jdaviz/configs/mosviz/plugins/parsers.py
I updated `mos_niriss_parser()` to sort files into categories (image, 1d spectrum, etc.) by examining their FITS headers instead of matching their filenames to a pattern. I chose distinctive keywords based on the headers of the current NIRISS example's data files. The `'DATAMODL'` key is particularly useful.
I can run the NIRISS example in full and don't see any glaring errors.
Open questions include:
- Are these the best ways to sort NIRISS' data files into the categories Mosviz desires?
- ~~What is the expected structure of the .ecsv source catalog? Two columns for RA and Dec or one with them in a tuple?~~
- ~~Should we still allow users to provide an `obs_label` argument to select a subset of NIRISS files in a directory? If so, what keyword is best? I left some examples in the …
=> Parse NIRISS data files by header instead of name

CHANGES.rst, jdaviz/app.py
This should have been grabbing the last world coordinate, not the first, in case the reference data is multi-dimensional.
Closes #1530
=> Correct the linking for 1D model results in Cubeviz

CHANGES.rst, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue
This pull request improves the UI-validation of the moment number in the moment map plugin.  Previously, it used to trigger "This field is required" when setting moment to 0, but now will only trigger that message when empty and with a separate validation message when negative
=> improve moment validation message

CHANGES.rst, jdaviz/configs/default/plugins/subset_tools/subset_tools.py
This pull request fixes unexpected behavior when switching to create a new subset with the subset mode on something other than replace (especially when not clicking away to finalize the previous subset selection).
Previous behavior:
https://user-images.githubusercontent.com/877591/181807105-5acf6917-4d02-49e6-bc19-0f62db7340d8.mov
New behavior (still temporarily shows the highlighting when not finalizing selection before changing subsets, but the final result is as expected):
https://user-images.githubusercontent.com/877591/181807133-819a43d5-6f6e-4b71-a33a-7d0ee8dc33db.mov
=> reset subset mode to "replace" when changing selection to "Create New"

setup.cfg
This pull request bumps the version requirement of ipypopout to 0.0.11 to gracefully fallback on not showing the popout button (instead of raising an error) when the jupyter kernel is not detected.
Full diff of changes in ipypopout: https://github.com/mariobuikhuizen/ipypopout/commit/5e7570de0e99c66a93b5305398b49311d35117a8 
Fixes #1533
=> bump required version of ipypopout to 0.0.11

CHANGES.rst, jdaviz/components/plugin_add_results.vue, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/core/template_mixin.py
This pull request addresses an issues discovered in the review of #1514 with wider implications.  When adding results from a plugin to a viewer that will overwrite an existing data entry, selecting to not show in the viewer raised a traceback error.  This traceback alone could be fixed and could result in "unloading" the data entry from the viewer, but this then will result in issues if that data entry was the reference data (which usually isn't allowed, but #1514 provides an exception where the original reference data was created by a plugin and allowed to be overwritten).
**Previous behavior**:
https://user-images.githubusercontent.com/877591/182617186-9a769e00-f03a-42bd-887d-ddf5546088f7.mov
**Proposed new behavior**:
https://user-images.githubusercontent.com/877591/182617352-e1b1bb07-7 …
=> add results to viewer: smarter defaults when overwriting

CHANGES.rst, jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_helper.py, jdaviz/core/helpers.py
This is a quick patch PR for #1544, where the helper will check to see if the `jdaviz_helper` attribute is already set. If it is, it will NOT overwrite the existing helper reference there, assuming it is a nested helper within a larger helper.
I could theoretically see a user wanting to get the nested helper in some scenarios, but I think getting the "highest" helper is going to be more intuitive for most users. If we get some complaints down the line, we can adjust the strategy here.
Fixes #1544 
=> Nested helpers don't overwrite helper reference 

CHANGES.rst, docs/index.rst, docs/reference/api.rst, docs/specviz2d/index.rst, docs/specviz2d/plugins.rst, jdaviz/app.py, jdaviz/components/plugin_dataset_select.vue, jdaviz/components/plugin_layer_select.vue, jdaviz/components/plugin_viewer_select.vue, jdaviz/components/viewer_data_select.vue, jdaviz/components/viewer_data_select_item.vue, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/default/plugins/viewers.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/plugins/__init__.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/configs/specviz2d/specviz2d.yaml, jdaviz/configs/specviz2d/tests/test_parsers.py, jdaviz/core/marks.py, jdaviz/core/template_mixin.py, setup.cfg
This pull request implements a new plugin in specviz2d for spectral extraction via specreduce.  ~~It currently only implements the functionality for Trace creation, offsetting, loading from the API, and visualizing in the 2d spectrum viewer.  The UI elements for the other "steps" (background, extraction) are implemented (in order to plan for the necessary interaction between the steps), but are currently non-functional.~~ (woops! - that was a nice plan, but planning for how things would interact with each other eventually became just an API call away from actually implementing and devs decided it would be easier to review/merge in a complete form anyways)
**IMPORTANT**: this PR fixes the units on the x-axis to be shown in pixels instead of erroneously in meters, but by doing so _disables_ …
=> Plugin: spectral extraction

CHANGES.rst, docs/imviz/displayimages.rst, jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/test_tools.py
This pull request is to add the ability to press Shift + b to blink backwards.
Fixes #1424
=> Allow Shift+b to blink backwards

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue, jdaviz/core/template_mixin.py, jdaviz/tests/test_subsets.py
This pull request is to allow basic shape editing. Also shows rotation angle for some shapes.
Related:
* https://github.com/glue-viz/glue/pull/2235
* https://github.com/spacetelescope/jdaviz/pull/729
Address the centering part of #634 because rotation is blocked by https://github.com/glue-viz/glue-astronomy/issues/74 .
=> Allow basic editing for supported shapes and display rotation for rectangle and ellipse

CHANGES.rst, docs/imviz/export_data.rst, docs/imviz/import_data.rst, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/test_regions.py, jdaviz/core/region_translators.py, jdaviz/core/tests/test_region_translators.py, notebooks/ImvizExample.ipynb, notebooks/concepts/imviz_simple_aper_phot.ipynb
This pull request is to allow loading DS9 regions into native Glue subset ROIs instead of the "static regions" that do not work with most plugins.
This is a breaking change for the following APIs:
https://github.com/spacetelescope/jdaviz/blob/cbcd65c6a85f83cd23777a97d224912ad5e20182/jdaviz/configs/imviz/helper.py#L198
https://github.com/spacetelescope/jdaviz/blob/cbcd65c6a85f83cd23777a97d224912ad5e20182/jdaviz/configs/imviz/helper.py#L236
https://github.com/spacetelescope/jdaviz/blob/cbcd65c6a85f83cd23777a97d224912ad5e20182/jdaviz/configs/imviz/helper.py#L343
Pre-requisite for:
* #1432
Close #1141 
- Open follow-up issue to remove the deprecated methods in a future release.
- Open follow-up issue to move region translation code upstream to `glue-astronomy`.
This checklist is meant to …
=> Load DS9 regions into Subsets

CHANGES.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
This pull request: 
* clarifies some of the input parameter descriptions in the UI,
* adds a note in the plugin when the extraction input data is selected to something other than "From Plugin" to explain that the spectrum preview will no longer update in real time,
* exposes specreduce errors in the plugin (for live-preview of the extraction) and in a snackbar (when exporting the background or background-subtracted image fails).
=> spectral-extraction: clarification improvements

setup.cfg
This pull request is to pin maxversion of jsonschema because a new release broke asdf, which in turn broke our CI.
Once this is merged, we need to open a follow-up issue to unpin it when upstream is fixed.
Related: https://github.com/asdf-format/asdf/pull/1171
=> MNT: Pin jsonschema maxversion

CHANGES.rst, jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
This pull request improves the automatic initial input parameter determination for input to spectral extraction, particularly for cases where the previous defaults would result in a window outside the range of the image which would throw an error from specreduce.  This also prevents other cases like this from throwing a traceback by instead raising an error snackbar message on load and pointing to the plugin for manual extraction.
**Re failing coverage checks**: I did add test coverage for the near-edge example to ensure it forces a one-sided background, but since the parser only accepts files, its difficult to add coverage for the "brightest pixel on edge" logic and the complete try/except snackbar.
**TODO**:
This checklist is meant to remind the package maintainer(s) who will review …
=> spectral-extraction: improved initial parameter estimation

CHANGES.rst, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/tests/test_data_selection.py, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/default/plugins/viewers.py, jdaviz/configs/specviz/plugins/viewers.py, jdaviz/core/helpers.py, jdaviz/core/marks.py, jdaviz/tests/test_subsets.py
This pull request implements spectral subset highlighting of automatically-collapsed spectra of spatial subsets in the profile viewer of cubeviz.  It does so by a new custom bqplot mark which "shadows" the position of the mark corresponding to the spatial-spectrum, but the nan-mask and styling of the mark corresponding to the spectral-subset on the full spectrum.  Everytime a new subset _layer_ is added, a mark is created for each combination of the corresponding subset mark and all marks of the _other_ (spatial vs spectral) type.  Everytime a subset is removed, the marks are pruned to remove any where one of the referenced marks no longer exists.  Pure hacky dark magic at its ugliest/finest.... and because of that this should be tested thoroughly. …
=> Spatial-Spectral highlighting

CHANGES.rst, jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/configs/default/plugins/export_plot/export_plot.py, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py, jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/core/template_mixin.py, jdaviz/core/tools.py
This pull request adds a convenience method on the plugin object to open the sidebar and open the plugin entry (if not already opened).  This essentially moves existing object in the tool (to open plot options or export) to the plugins, to be more easily accessible from the API.
For example:
```
plugin = viz.app.get_tray_item_from_name('g-metadata-viewer')
plugin.open_in_tray()
```
I'm mainly proposing this because I'm sick of having code in notebooks to manually find the index and set the state to reproduce workflows.
=> plugin method to open in tray

docs/imviz/plugins.rst
Added a sentence to the "aperture photometry" plugin docs to tell the user that only standard regions (created with "replace") are acceptable as background regions. Please double check that the link I added takes you [here](https://jdaviz.readthedocs.io/en/latest/imviz/displayimages.html#defining-spatial-regions). I am not sure I got it right.
=> Disclaimer for background region

setup.cfg
This pull request pins the max version of ipywidgets until we can fix support with ipywidgets 8.0
=> MNT: pin max version of ipywidgets

CHANGES.rst, jdaviz/app.py, setup.cfg
This pull request attempts to support ipywidgets 8 change in `.widgets` becoming a private `._active_widgets` while still supporting the old syntax.
xref https://github.com/jupyter-widgets/ipywidgets/pull/3122
=> fix support for ipywidgets 8 and remove max pin

CHANGES.rst, docs/specviz2d/plugins.rst, jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, setup.cfg
This PR extends on #1514 with a more flexible user-API for 2D to 1D spectral extraction.
[Updated spectral extraction docs](https://jdaviz--1554.org.readthedocs.build/en/1554/specviz2d/plugins.html#spectral-extraction)
Proposed public methods on the spectral-extraction plugin, accessed with `specviz2d.app.get_tray_item_from_name('spectral-extraction')`:
* `import_trace(trace)` - takes a specreduce trace object and loads the _input parameters_ into the plugin.  Supports `FlatTrace` and `KosmosTrace`.
* `export_trace(add_data=False, **kwargs)` - creates and returns a trace from the input parameters in the plugin.  If `add_data=True`, this adds a new data entry (once supported by glue-astronomy).
* `import_bg(bg)` - takes a specreduce background object and loads the _input parameters_ into …
=> spectral-extraction: API

CHANGES.rst, jdaviz/app.py, jdaviz/components/glue_state_sync_wrapper.vue, jdaviz/components/layer_viewer_icon.vue, jdaviz/components/plugin_dataset_select.vue, jdaviz/components/plugin_layer_select.vue, jdaviz/components/plugin_viewer_select.vue, jdaviz/components/viewer_data_select_item.vue, jdaviz/configs/default/plugins/viewers.py, jdaviz/configs/imviz/plugins/compass/compass.vue, jdaviz/configs/imviz/plugins/coords_info/coords_info.vue, jdaviz/container.vue
This pull request adds an indication of the linewidth to the layer labels/legends. 
* replaces the previous stock icon in a box with custom letter with underline depending on linewidth (up to a max of 6px)
* replaces the previous stock icon for viewers with matching number styling
* image layers have no underline or box
* uses same icon in dropdowns/menus/mouseover (but without color/linewidth styling since often can correspond to multiple layers across different viewers)
NOTE: "UN" flash in the legend has been fixed and the bottom entry has a little extra padding and the rounded-corner removed so the line indicator is more visible.
https://user-images.githubusercontent.com/877591/186232908-8de8dcd7-8831-4424-bc90-80415664dc24.mov
And I even remembered to make sure dark mode still works! …
=> linewidth indicator in legend labels

CHANGES.rst, jdaviz/configs/cubeviz/helper.py
This pull request future-proofs the slicing wavelength to slice logic for when a future release of glue-jupyter includes https://github.com/glue-viz/glue-jupyter/pull/309.  That PR, when `layer.as_steps=True`, doubles the length of the bqplot Lines object, which has been used since #1550 to quickly access the wavelength array to map wavelength to slice.
I suspect this will fail coverage, as we have no way within CI to force entering that if-statement.  Covering the if-statement within CI should probably be added to #1595 (I added a TODO entry there to make sure that is done once that is rebased on top of this).
=> future-proof slicing logic for glue-jupyter as_steps support

CHANGES.rst, docs/specviz/plugins.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
Implements retrieving and displaying uncertainties from the fit models in the Model Fitting plugin. Opening as draft since I need to mess around with the plugin layout to accommodate the new information in a way that's visually appealing.
=> Expose parameter uncertainties

.github/workflows/open_actions.yml
This pull request is to tell the auto PR labeler bot to not remove a label if it was added manually prior to opening the PR. This is the same setting as `astropy` so should be uncontroversial.
Currently, if you manually apply a label but it is not defined in the rules for that label when the bot runs, it removes the label. This is annoying in cases where you already know what label you want so you manually apply it when you open the PR. Only affects contributors who can apply labels.
=> BOT: Labeler to not remove labels

setup.cfg
`ipywidgets` 8.0 broke compatibility with `voila`, so we'll have to pin it at least for now. I got a jinja2 error after a fresh install with this pin though, could someone else test and see if that's just something messed up in my local env?
* https://github.com/voila-dashboards/voila/issues/1188
=> Pin ipwidgets to avoid breaking standalone app

CHANGES.rst, jdaviz/configs/mosviz/plugins/parsers.py
This pull request transposes the input data before creating the Spectrum1D object for 2d spectra for all R grism inputs.
Fixes #1353
=> mosviz niriss parser: transpose R 2d spectra

CHANGES.rst, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py
Previously, it was not possible to perform line analysis on the spectrum generated by Cubeviz' autocollapse for spatial subsets. This PR adds that feature. 
BIG THANKS to @pllim for fixing the mysterious test failure!
=> Add Spatial Collapsed Spectrum selection to Line Analysis

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/tests/test_simple_aper_phot.py
This pull request is to address a critical but subtle bug where aperture photometry gives inaccurate result when photometry is performed on a non-reference data that is dithered from reference data and they are linked by WCS.
This works around https://github.com/glue-viz/glue-astronomy/issues/52
Fixes #1508
=> Fix aperture photometry result for WCS linked dithered non-reference data

CHANGES.rst, docs/specviz2d/plugins.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
This pull request adds support for optimal extraction (in addition to the existing boxcar extraction) to the spectral extraction plugin in specviz2d.
**TODO**:
=> spectral-extraction: support for optimal extraction

CHANGES.rst, docs/reference/api.rst, jdaviz/configs/imviz/plugins/catalogs/catalogs.py, jdaviz/configs/imviz/plugins/catalogs/catalogs.vue
This pull request extends on #1401 and provides user-API access to the catalog search plugin.
[Plugin User API docs](https://jdaviz--1636.org.readthedocs.build/en/1636/api/jdaviz.configs.imviz.plugins.catalogs.catalogs.Catalogs.html#jdaviz.configs.imviz.plugins.catalogs.catalogs.Catalogs)
**TODO**:
=> (minimal) user API for catalog search

CHANGES.rst, jdaviz/configs/default/plugins/collapse/collapse.py, jdaviz/configs/default/plugins/collapse/collapse.vue
This pull request extends on #1401 and provides user-API access to the collapse plugin.
[Plugin User API docs](https://jdaviz--1641.org.readthedocs.build/en/1641/api/jdaviz.configs.default.plugins.collapse.collapse.Collapse.html#jdaviz.configs.default.plugins.collapse.collapse.Collapse)
**TODO**:
=> user API for collapse plugin

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/viewers.py
This pull request fixes the case where removing and then re-adding a data layer in a viewer results in "as steps" being enabled by default.  Plot options are lost anyways when the layer is deleted, so we need to re-apply any jdaviz-implemented layer defaults (as-steps, line-width, etc) when a data layer is removed and then re-added to a viewer.
This also fixes the case of "as steps" defaults only being applied to the first subset layer when the same subset is being drawn on multiple data layers simultaneously.
=> fix subset layer default behavior

CHANGES.rst, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py
This pull request extends on #1401 and provides user-API access to the metdata viewer plugin.
[Plugin User API docs](https://jdaviz--1634.org.readthedocs.build/en/1634/api/jdaviz.configs.default.plugins.metadata_viewer.metadata_viewer.MetadataViewer.html#jdaviz.configs.default.plugins.metadata_viewer.metadata_viewer.MetadataViewer)
**TODO**:
=> user API for metadata viewer plugin

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
Requires: https://github.com/astropy/specutils/pull/979
Allows model fitting to use the uncertainty of spectra as weights.
This does not work for a 0 order polynomial in Specviz and does not work at all with Cubeviz since we split the uncertainty and flux data into separate cubes. Is re-adding the uncertainty information into the flux cube part of this PR?
=> Use spectrum's uncertainty as weight when doing model fitting

CHANGES.rst, jdaviz/app.py, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/specviz/helper.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/core/helpers.py
This pull request is to allow common user mistake passing in data_label as positional argument. This approach is kinda hacky but is less disruptive than throwing error if data_label is not a keyword argument.
Fixes #1617 
=> BUG: Allow data_label as pos arg

CHANGES.rst, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
Suppresses the `W/m2/m` warning from astropy.units when using the line analysis plugin.
=> Suppress Units warnings from Line Analysis plugin

CHANGES.rst, docs/specviz2d/plugins.rst, jdaviz/app.py, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/viewers.py, jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/core/template_mixin.py
This pull request extends on #1514 to add support for displaying traces as glue data objects (and therefore importing trace objects via `app.add_data`).  
This also supports flexible workflows where the background and extraction step reference different traces (including the case of offsetting an auto/kosmos trace within the app, or loading a custom trace from the API):
https://user-images.githubusercontent.com/877591/189728882-90cb90be-257c-4a9a-8813-dd56ef36454c.mov
[updated spectral extraction docs](https://jdaviz--1556.org.readthedocs.build/en/1556/specviz2d/plugins.html#spectral-extraction)
=> spectral-extraction: support import/export trace via glue-astronomy

CHANGES.rst, jdaviz/configs/default/plugins/data_tools/data_tools.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/specviz2d.yaml, jdaviz/configs/specviz2d/tests/test_parsers.py, setup.cfg
This pull request is an attempt to parse Level 2 NIRSpec s2d files.
Please install ~dev~ v0.5.1 or later of glue-astronomy to get these fixes from upstream:
* https://github.com/glue-viz/glue-astronomy/pull/77
* https://github.com/glue-viz/glue-astronomy/pull/78
=> Specviz2d to parse NIRSpec level 2 s2d

CHANGES.rst, jdaviz/configs/imviz/plugins/links_control/links_control.py, jdaviz/configs/imviz/plugins/links_control/links_control.vue, jdaviz/configs/imviz/tests/test_links_control.py
This pull request extends on #1401 and provides user-API access to the links control plugin.
[Plugin User API docs](https://jdaviz--1640.org.readthedocs.build/en/1640/api/jdaviz.configs.imviz.plugins.links_control.links_control.LinksControl.html#jdaviz.configs.imviz.plugins.links_control.links_control.LinksControl)
**TODO**:
=> user API for links control

CHANGES.rst, jdaviz/components/plugin_dataset_select.vue, jdaviz/components/plugin_layer_select.vue, jdaviz/components/plugin_subset_select.vue, jdaviz/components/plugin_viewer_select.vue, jdaviz/configs/default/plugins/collapse/collapse.vue, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.vue, jdaviz/configs/default/plugins/line_lists/line_lists.vue, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/plugins/catalogs/catalogs.vue, jdaviz/configs/imviz/plugins/line_profile_xy/line_profile_xy.vue, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/data/linelists/linelist_metadata.json
Historically, we've always had an issue with dropdown menus floating around when the user scrolls the notebook. When working on #1656, I found an `attach` property that effectively docks the dropdown menu to the `v-select`:
Before:
https://user-images.githubusercontent.com/25206008/191856631-a79393ee-2892-4d06-add1-5ce9a9d06e94.mp4
After:
https://user-images.githubusercontent.com/25206008/191853995-8c469bc2-9be6-4f47-b12e-3b32b518dd2a.mp4
The only consequence that we have to consider here is entries whose names are larger than the plugin bar. Before, the floating menu could accommodate any sized item by overflowing:
When the menu is attached, the menu is restricted to the size of the `v-select`:
Ideally, we could combine the two, attach the menu and allow the overflow, but I haven't found …
=> Attach select menus

CHANGES.rst, jdaviz/configs/default/plugins/export_plot/export_plot.py
This pull request extends on #1401 and provides user-API access to the export plot plugin.
[Plugin User API docs](https://jdaviz--1657.org.readthedocs.build/en/1657/api/jdaviz.configs.default.plugins.export_plot.export_plot.ExportViewer.html#jdaviz.configs.default.plugins.export_plot.export_plot.ExportViewer)
**TODO**:
=> user API for export plot plugin

notebooks/concepts/imviz_load_fits_hdu.ipynb
This pull request is to add to concept notebook how to change colormap for all images in Imviz all at once. Since Astrowidgets API is specific to the image being displayed only, this uses the new Plot Options API that Kyle implemented in #1637 .
=> DOC: Imviz plot options example with select all

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py
This pull request is to fix #1669 
Close #1690
=> Disable Line Lists when there is no data

CHANGES.rst, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/default/plugins/subset_plugin/tests/test_subset_plugin.py
This pull request fixes the IndexError raised in the subset plugin when modifying a subset (color in plot options, for example) while "Create New" is selected.
Fixes #1693
=> subset plugin: fix IndexError

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py, jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py, jdaviz/core/template_mixin.py, jdaviz/core/user_api.py
This pull request implements the ability for:
* `SelectPluginComponent` (and all inheriting classes) and `AutoTextField` supports == and !=
* `PlotOptionsSyncState` support == and != and compares against both the user-friendly (text shown in dropdown in UI) and glue values.  For example, `image_colormap` would support checking against both 'Yellow-Green-Blue' and 'YlGnBu' (does not currently implement other operators (for float glue state objects to have >, <, >=, <=, etc) - these will still raise a TypeError)
The general motivation is to allow common logic on these objects without the user needing to know whether they need to compare against `plugin.component.selected` or `plugin.component.value` and also don't need to think about the difference between user-facing text in a dropdown and …
=> plugin components support for == and != comparisons

CHANGES.rst, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/tests/test_data_loading.py, jdaviz/configs/mosviz/tests/test_parsers.py
This PR improves the loadtime performance of the Mosviz NIRISS parser. It addresses a specific inefficiency brought up by @ojustino from the viz stress test hack hour regarding redundant loading. Currently, the parser loads all hdus into Spectrum1Ds via SpectrumList.read(), regardless of whether the user specified those hdus in the provided catalog. This PR modifies the logic to, instead, filter out the relevant SOURCEIDs (and metadata hdus) before passing them to specutils, rather than after. In testing, this leads to a speed up of roughly 20% in parsing time:
<details>
<summary>Before: 102033062 function calls (100890412 primitive calls) in 49.951 seconds</summary>
```
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
492    8.429    0.017 …
```
=> Filter HDUs before loading to SpectrumList

CITATION.cff
I forgot to update the Citations file for the 3.0 release, this is updated for 3.0.1 and will be backported to the v3.0.x branch after merging into main.
=> Update Citations file for 3.0.1, to be backported

CHANGES.rst, jdaviz/app.py, jdaviz/configs/cubeviz/plugins/parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/specviz/plugins/line_analysis/tests/test_lineflux.py, jdaviz/configs/specviz/plugins/parsers.py, jdaviz/configs/specviz2d/plugins/parsers.py, jdaviz/tests/test_app.py
This pull request is to address inconsistent data labeling throughout jdaviz.
Currently implemented:
Fixes #727 
=> Centralize data label generation

CHANGES.rst, jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/tests/test_parsers.py
This pull request is to fix #1711 .
I don't know if we want to backport this or not. Feel free to change the milestone if we need to backport this.
=> BUG: Specviz2d to load both s2d and x1d when both provided separately

docs/imviz/displayimages.rst
This pull request is to add user facing examples for plot options API for Imviz so users can operate on multiple images at once.
Fixes #1477 
=> DOC: Add plot options API examples for Imviz

CHANGES.rst, jdaviz/app.py, jdaviz/core/tests/test_data_menu.py
This pull request avoids re-calling `viewer.add_data` if the data is already loaded in the viewer.  This both saves time and avoids resetting some plot options that are passed as default (percentile and color from the cycler).  Note that unloading and re-loading data from the viewer (either through the API or with the "x" button) will still reset plot options as that entirely destroys the layer.
Fixes #1723
=> skip viewer.add_data if already in viewer

CHANGES.rst, docs/conf.py, docs/imviz/plugins.rst, jdaviz/configs/default/plugins/data_tools/data_tools.py, jdaviz/configs/imviz/plugins/catalogs/catalogs.py, jdaviz/configs/imviz/plugins/catalogs/catalogs.vue, jdaviz/configs/imviz/tests/test_catalogs.py
This pull request adds the capability to search and display markers from a catalog in an ecsv selected from the local machine.
[Updated plugin docs](https://jdaviz--1707.org.readthedocs.build/en/1707/imviz/plugins.html#catalog-search)
https://user-images.githubusercontent.com/877591/194627281-a9c7aef4-ce9b-4fe6-bc61-e810de5e1cd8.mov
TODO:
Out-of-scope (deferred for later):
* spinner while searching: pressing search/clear can take a few seconds depending on the size of the catalog so should really have some UI feedback.  Since we're intending a redesign in the near future to support loading multiple catalogs and changing marker colors similar to line lists, I propose we defer this to be a part of that effort.
* styling of file dialog (this is the same dialog used for importing data... so …
=> Catalogs plugin: support loading catalog from ecsv

CHANGES.rst, jdaviz/app.vue
Fixes #1677
- Open a follow-up issue to revert this PR when https://github.com/bqplot/bqplot/pull/1531 is released upstream and we also would have to bump our bqplot minversion.
=> fix: workaround for blank tabbed viewers after selection

CHANGES.rst, jdaviz/app.py
This PR addresses a bug reported by @camipacifici. When replacing an existing moment map, if you set the "output data label" to a path for an existing file, jdaviz will try to load data from that file path. This PR dodges the bug by pushing off the attempt to load data. Data loading from the label's path is now only triggered as a last resort before an error is raised.
* delays loading data from a label that is also a path, now only used as a last resort
* changes the `data_path` arg name to `data_label` within `add_data_to_viewer` and `remove_data_to_viewer`
* removes now unnecessary extension kwarg `ext`
* checked that no notebooks need updates …
=> Label-based lookups in [add/remove]_data_from_viewer

CHANGES.rst, jdaviz/app.py, jdaviz/configs/imviz/tests/test_helper.py
If the user creates a new image viewer from `Imviz` like so:
```python
imviz = Imviz()
viewer_2 = imviz.create_image_viewer(...)
imviz.app.add_data_to_viewer(...)
imviz.app.remove_data_from_viewer(...)
```
the `Application.remove_data_from_viewer` method calls `Application._viewer_item_by_reference` to find the viewer to remove. But in the first line, when `Imviz.create_image_viewer` initializes a new viewer, it calls `Application._on_new_viewer`, which until now only defines the following kwargs: `viewer=viewer, vid=vid, name=name`. There's one last kwarg in the call signature for the method, which by default is `reference=None`. Since we don't yet specify `reference` in the `_on_new_viewer` method, the default is passed as `None`, triggering the bug in #1740.
This PR passes the missing …
=> Bugfix for #1740: add/remove data from user-created viewer

CHANGES.rst, docs/index.rst
The link at the bottom of the RTD homepage was linking to a static older version's Zenodo link. This will now properly link to the "cite all version" link, which resolves to the latest version of the Zenodo record.
=> Fix Zenodo link to always resolve latest version

CHANGES.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
This addresses the issue of not having enough significant figures in the coordinates in the aperture photometry plugin.
=> Change RA/Dec significant figures from 4 to 6 in aperture photometry plugin

CHANGES.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
This pull request improves the logic for the initial guess for the position of the "Manual" background trace.  Previously it started at the same guess as the extraction trace (based on the brightest flux medianed over the dispersion direction).  Now it uses the same location that would be adopted for a OneSided background, with the "direction" determined on whether the extraction trace is in the top or bottom half of the image, and the separation at 10% of the cross-dispersion "height".
Motivated by @ojustino's comment: https://github.com/spacetelescope/jdaviz/pull/1682#pullrequestreview-1142409128 …
=> spectral extraction: improved logic for initial position of "Manual" background trace

CHANGES.rst, docs/specviz2d/plugins.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue, jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
This pull request adds live-visualization and export (UI and API) support for the 1D spectrum representing the background region within the spectral extraction plugin.
~NOTE: this requires https://github.com/astropy/specreduce/pull/143 (until then, the new test coverage will fail)~
[Rendered updated plugin docs](https://jdaviz--1682.org.readthedocs.build/en/1682/specviz2d/plugins.html#background)
https://user-images.githubusercontent.com/877591/192842956-2fba147d-d027-48e7-96e2-fc0f75d7cb77.mov
New Features > Specviz2d:
Spectral extraction plugin now supports visualizing and exporting the 1D spectrum associated with the background region. …
=> spectral extraction: live-preview and export of background spectrum

jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py
This pull request is to re-enable the remote test skipped in #1736 by replacing it with another file suggested by Tyler Pauly from pipeline team.
*[The old file] should no longer be created - it was the result of a duplicate association created (`jw01529-o004_spec3_001_asn.json == jw01529-c1002_spec3_001_asn.json`), and so the file `jw01529-o004_t002_miri_p750l_s2d.fits` should hold the relevant data. The duplicate association bug has been fixed, so some `c1xxx` associations are intentionally no longer created. If the old `c` type association is on hand, you can check to see if it fell under this issue by checking the full member list - if all listed members fall under one observation group (i.e., `o004`), the association will no longer be generated.*
Out of scope:
* #1739
list the …
=> TST: Use new remote data for test_spectrum_on_top

jdaviz/configs/imviz/tests/test_catalogs.py
This pull request is to fix #1755 . This is a direct follow-up of #1707 .
=> TST: Offline Catalogs ECSV test

README.rst
In #1743 we changed the Zenodo links to always point to the latest release. I found one remaining URL to change in the README, which is fixed in this PR.
=> Correcting Zenodo link in readme

notebooks/CubevizExample.ipynb, notebooks/SpecvizExample.ipynb
Apparently MAST changed these paths....
Fix https://github.com/spacetelescope/jdaviz/issues/1758
=> Update to new MAST URIs in example notebooks

CHANGES.rst, docs/specviz2d/import_data.rst, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/specviz2d/helper.py, jdaviz/configs/specviz2d/tests/test_parsers.py
Rather than always loading extension 1, Specviz2d will now allow the user to specify an `extension` keyword in the `load_data` method, which will be applied to the input 2D spectrum file. The user can also set `transpose=True` to transpose the data in that extension in case it isn't in the correct orientation. See https://stsci.box.com/s/cocuykc0bqivkz5rtl7kexrrrk84y8hb for an example file to test this with.
=> Enable loading specific extension for 2D spectrum in Specviz2d

CHANGES.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py
Hopefully this will make CI green again. astropy v5.1.1 was released this morning.
=> BUG: Fix astropy version check for filter_non_finite in modeling within aper phot plugin

CHANGES.rst, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/plugins/viewers.py
This pull request fixes the nested toolbar in the 2d spectrum viewers in specviz2d and mosviz (see #1679 - which was supposed to replace the original toolbar with the nested toolbar, but forgot to change the inheritance order of this viewer).
**Before**:
**After**:
=> fix nested toolbar in specviz2d/mosviz 2d profile viewer

jdaviz/app.py, jdaviz/app.vue
Triggering a resize/rerender of bqplot is done in the front-end since 3dcfe344.
See: #1720
=> feat: remove vue_relayout, this is no longer needed

CHANGES.rst, jdaviz/app.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py
This pull request is to add requested colormaps to image viewer.
=> Add rainbow and reverse rainbow colormaps

.github/workflows/ci_workflows.yml, tox.ini
This pull request is to see how badly things break in Python 3.11 (using RC2).
* https://github.com/glue-viz/glue/issues/2340
* https://github.com/astropy/regions/issues/475
* https://github.com/astropy/regions/pull/476
* https://github.com/h5py/h5py/issues/2146 (glue stopped pulling it for Python 3.11, see https://github.com/glue-viz/glue/pull/2321)
=> TST: Test against Python 3.11

CHANGES.rst, jdaviz/components/viewer_data_select.vue
Found in the `MosvizNIRISSExample` notebook: when the row isn't set properly the visibility filters seem to misbehave. This PR fixes the logic to detect when rows don't have a row assigned, which properly hides them under the data dropdown.
Before/After
Looks like the NIRISS parser only assigns rows for the 2D spectra, resulting in this bug appearing: https://github.com/spacetelescope/jdaviz/blob/8b136cc385c4569a50cc2ff84c90ebf184f52a90/jdaviz/configs/mosviz/plugins/parsers.py#L760
=> Fix None Row Detection

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py, jdaviz/core/template_mixin.py
This pull request adds a spinner overlay in the contour setting of plot options when there is a change in any of the contour settings (as they can take a while to be processed).
Approximately 85% of the time spent during this is in skimage `find_contours` so although it would be nice to optimize, it might be difficult for us to do so.  If contours are ever optimized to the point where the lag would not result in user-confusion, the overlay can easily be removed (or this entire PR reverted if no other plot option makes use of the infrastructure for a spinner).
https://user-images.githubusercontent.com/877591/199064421-b8c3ab63-3c64-44a7-9fc6-f780053f2e08.mov
should add a …
=> plot options: spinner for contour settings

CHANGES.rst, jdaviz/components/viewer_data_select.vue
Hi again... 😅
So #1798 didn't quite do what @kecnry and I were expecting, so I'm going to reintroduce the original solution I was proposing. After a much thorough second lookthrough, I'm further convinced this is the correct logic we want.
The reason why the missing row elements were visible was because the mosviz visibility fallback for when the object's row is `None` was to return `!returnExtraItems`. This flag is intended for the "show/hide all other data" dropdown. Effectively, if it the row information was missing, it would always show the item as visible.
Instead, I propose any data without a row should follow the same visibility rules of whether the user manually visualizes the dataset or not. FWIW, this PR brings the mosviz visibility logic in line with the default fallback: …
=> Make mosviz visibility fallback more robust

CHANGES.rst, jdaviz/configs/mosviz/plugins/viewers.py
This pull request fixes a small bug introduced in #1681 where the image from the previous row (in mosviz) was not removed from the image viewer when changing rows in the table.
=> FIX: mosviz image remove on row change

CHANGES.rst, docs/specviz/import_data.rst, jdaviz/configs/specviz/helper.py, jdaviz/configs/specviz/plugins/parsers.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/conftest.py, setup.cfg
This pull request is to address #1621. By default on main, specviz will read multi-order x1d spectra into a `SpectrumList`, and then cobble together every order into a concatenated 1D spectrum. This behavior may have made sense for MIRI data products but doesn't give us a sensible default view for NIRISS. This PR adds ~a small check for the instrument: if the observations were recorded by MIRI jdaviz will use the old behavior~ a check if the various HDUs originated from the same FITS file. If the loaded orders are from the same FITS file, specviz will compute a "combined" spectrum with all spectral channels. 
Fixes #1621 
This checklist is meant to remind the package maintainer(s) who will review this pull …
=> Fix for #1621: only concat x1d spectra from MIRI

CHANGES.rst, jdaviz/app.py, jdaviz/components/viewer_data_select.vue, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/tests/test_data_loading.py
You may be asking yourself, why in {insert deity name of choice}'s name would you want that!? I think a picture is worth 1000 words (even if it's a picture of words :P)
You're reading that right; 200 targets, which used to take 1 hour and 11 minutes (!!) loaded in under two minutes.
This PR is part of a 3 part strategy in changing the linking strategy in Mosviz, developed with @camipacifici. In Mosviz, data navigation is mainly intended to be done with the Table Viewer. I recall us having discussions about removing the data dropdowns from Mosviz because of this. Though it may have been stopped due to a desire to plot multiple 1D spectrum in the same viewer.
After some profiling, I discovered supporting multi-plotting 1D spectrum was a VAST majority of the load time issues with Mosviz …
=> Disable 1D linking and Simultaneous Row Plotting in Mosviz

CHANGES.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
This pull request is to address slow performance for the raw profile plot in aperture photometry when using large subsets.  This does ~two things~ the following to attempt to address this case:
1. ~reorders so the results table appears above the plots.  Any size image/subset that jdaviz currently handles _should_ return the results almost immediately... if this is ever not the case, then we should consider adding a spinner while computing the results.~
2. adds a warning below the dropdown box if the user selected the raw profile AND the selected aperture has an area of over 5000 pixels.  This is a somewhat arbitrary cutoff, but can be adjusted if reviewers/users see significant performance degradation at smaller subsets.
https://user-images.githubusercontent.com/877591/199300596-96c72fda-3 …
=> large subset warnings in aperture photometry

CHANGES.rst, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/links_control/links_control.py, jdaviz/configs/imviz/plugins/links_control/links_control.vue, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/test_links_control.py, jdaviz/core/astrowidgets_api.py, jdaviz/core/events.py
This pull request makes waaaay more small changes than I'd like so that markers can stay in place when adding new data to Imviz.  The expected behavior when changing linking type is not clear so is deferred until a refactor - for now a new confirmation overlay is added to the links control plugin to clear markers.  When interacting from the API, markers will need to be cleared manually first (as stated in the error message if failing to do so).  This also fixes a bug where the markers data_collection entry was not showing as loaded in the data menu.
Note: using the plugin API to change the link type will still result in the overlay (and no error).  Calling the astrowidgets API will raise an error (if applicable) and suggest calling `viewer.remove_markers()`.  We could consider other API …
=> Markers stay when adding new data

CHANGES.rst, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/tests/test_data_loading.py
This pull request is to address `mosviz.load_data()` not working if only spectra 1d or 2d are provided. Also, if valid values are not provided in `load_data`, the method should return after sending a Snackbar message.
EDIT: This is only implemented for NIRSpec data since it is the only instrument with separate loaders for 1d and 2d spectra.
=> Allow mosviz load_data to load only 1d or 2d spectra

CHANGES.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py
This pull request fixes a small typo that combined the "Centroid" and "Max" options in the dropdown for peak method in the spectral extraction plugin.
=> FIX: added missing comma in choices for trace peak method

docs/imviz/import_data.rst, docs/imviz/plugins.rst
This pull request is to clarify centroid subtlety that it requires background subtraction to be accurate.
Related PRs:
* #1823
* #1841 
=> DOC: Clarify centroid subtlety

CHANGES.rst, jdaviz/app.py, jdaviz/tests/test_utils.py, jdaviz/utils.py
(Ok, technically 702 layers). This pull request improves support for more than 26 layers by lettering with "AA" through "ZZ" instead of going to random characters that happen to be after `char(97 + 26)`.
For inputs larger than `701`, this will begin to use non-alphabet characters in the first digit.  `702` gives `'{a'`, for example.
=> layer-lettering to handle 2 "digits" (up to 700 layers)

CHANGES.rst, docs/imviz/export_data.rst, docs/imviz/plugins.rst, docs/known_bugs.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/imviz/tests/test_simple_aper_phot.py
This pull request is to remove partial centroiding in Simple Aperture Photometry plugin. We reintroduce fitting of `mean` in Gaussian (the code was in one of the commits in #1409 but later removed before merged but still in Git history). Radial profile was added in #1030 and this plugin in #938 (there were other PRs too in between).
Also removes an outdated known issue that was already fixed in #1524 .
Fixed a minor bug where Gaussian Fit section shows on GUI even when not applicable. This happens when user enables Gaussian fitting for radial profile, and then redid the calculation with Curve of Growth immediately after without disabling Gaussian fitting option.
Fixes #1442 
should add a …
=> No more centroiding in Simple Aperture Photometry plugin

CHANGES.rst, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/core/marks.py, jdaviz/tests/test_subsets.py
This pull request prevents the shadowing logic introduced in #1528 from crashing (with a traceback in the viewer output-widget) when creating a subset after adding another spectral data-entry, including from plugins such as model fitting or gaussian smooth, which was then interfering with future subset creation.
Previous workflows to reproduce:
* add results from gaussian smooth to the spectral-viewer
* create spectral subset (originally crashed with traceback in output-widget and future clicks would create multiple subsets simultaneously)
* create spatial subset
Fixes #1853
This checklist is meant to remind the package maintainer(s) who …
=> FIX: shadowing/subsets after adding plugin data

setup.cfg
This pull request is to temporarily workaround:
* astropy/astropy#14025
Also see:
* https://github.com/numpy/numpy/issues/22623
* https://github.com/pypa/setuptools/issues/3693
=> DOC: Pin setuptools to work around ImportError

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/viewers.py
In #1674 I introduced a color cycler so that each new `data` added to an instance of the `Application` would have a distinct color (up to N colors). While testing #1864, @kecnry pointed out that (1) the cycler was accidentally broken by #1742, and (2) the color cycler should cycle on the _viewer_ level rather than the app level. I implement that here.
=> Moving color cycler to JdavizViewerMixin

jdaviz/configs/cubeviz/plugins/slice/tests/test_slice.py, jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py, setup.cfg
Numpy v1.24.0 triggers several deprecation warnings in scikit-image. See progress on fixes in scikit-image/scikit-image#6633, and failure in #1834.
This PR tries to filter out that specific deprecation warning.
=> numpy deprecation warning filter for v1.24.0

tox.ini
This pull request is to omit dev version of specreduce from devdeps because that package is undergoing a lot of API changes.
Close #1877 
=> TST: Omit specreduce dev from devdeps

CHANGES.rst, docs/mosviz/import_data.rst, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/tests/test_data_loading.py, jdaviz/configs/mosviz/tests/test_parsers.py
Does what it says on the tin. In-progress, currently (mostly) working for NIRSpec level 2.
EDIT: ready for review, now also loads NIRCam data. I have NIRCam test data, I can upload that to Box (I trimmed a couple real files from ~1200 sources down to 20 to speed things up) and add a test.
=> Update Mosviz parser to load level 2 data

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/fitting_backend.py, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py
Specutils tries to use 1/sigma as weights if `weights='unc'`, leading to non-finite weights if we pass 0s in `spectrum.uncertainty`. This fixes the model fitting problem that @kecnry encountered in Mosviz, but the ultimate fix should probably be upstream in `specutils`.
=> Avoid astropy model fitting error if all uncertainties are 0

CHANGES.rst, setup.cfg
HOOOLLEY CRAP I finally fixed it!!
At some point in the past (probably a year), I completely lost console logging whenever I launched jdaviz in "desktop" mode. I was going to report it as a bug, but no one else was complaining about it, so I figured it was just me. And I've been flying blind ever since!
But then I found a little gem in the [python docs](https://packaging.python.org/en/latest/specifications/entry-points/#use-for-scripts):
> The difference between console_scripts and gui_scripts only affects Windows systems. console_scripts are wrapped in a console executable, so they are attached to a console and can use sys.stdin, sys.stdout and sys.stderr for input and output. gui_scripts are wrapped in a GUI executable, so they can be started without a console, but cannot use standard …
=> Restore console log for Windows

CHANGES.rst, jdaviz/components/plugin_add_results.vue, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py, jdaviz/core/template_mixin.py
This pull request implements the option to expose the residuals from a model fit as an additional entry in the data collection.
Open questions:
* should the residuals be automatically added to the viewer (if the switch to add the model is checked), should it have an independent switch, or should it not be added (current behavior)?
https://user-images.githubusercontent.com/877591/203401264-dfa904e6-a1ed-4a41-b66f-33bd6c8c8d2f.mov
=> Model fitting residuals

docs/cubeviz/plugins.rst
While investigating #1869, @camipacifici suggested we put a caveat in the docs so users understand that the uncertainties are being visualized in the `uncert-viewer` but not propagated in the collapsed spectrum calculations. This PR adds such a note to the Cubeviz Line Analysis plugin docs. 
=> Add caveat to Cubeviz line analysis docs on uncertainties

.github/workflows/ci_cron_weekly.yml, .github/workflows/ci_workflows.yml
Pin tox<4 because it has breaking change. See https://github.com/tox-dev/tox/issues/2612
- After merge, open up follow-up issue to unpin in the future when we can.
=> TST: Pin tox<4

.github/workflows/ci_cron_weekly.yml, .github/workflows/ci_workflows.yml
This reverts commit f36f3b2cca7d1f91eafb7220c4c4835af48e0a17.
This pull request reverts #1901 
Fixes #1903
=> unpin tox < 4

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
This pull request is a follow-up to #1864 and renames "expose residuals" to "calculate residuals" (and the underyling traitlet from `residuals_expose` to `residuals_calculate` after feedback.
=> rename residuals_expose to residuals_calculate

CHANGES.rst, jdaviz/app.py, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/utils.py
The color cycler update in #1866 unintentionally changes the color of each spectrum visualized with Mosviz. Though the colors are fun, this isn't useful or intended. 
This PR only applies the color cycler for configs other than Mosviz. For Mosviz, only the default (gray) color is used. 
I've tested locally that Mosviz produces gray lines in the spectrum viewer, and e.g. Cubeviz still cycles colors. 
[🐱](https://jira.stsci.edu/browse/JDAT-2957)
=> Bugfix: skip color cycler in Mosviz

CHANGES.rst, jdaviz/app.py, jdaviz/configs/imviz/tests/test_viewers.py
This pull request is to fix #1919
=> Do not set reference for Imviz

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py
This pull request avoids resetting the redshift to zero everytime results from a plugin are added back to the app/viewer.  Note that adding new data _not from a plugin_ will reset the app-wide redshift to the value (defaulting to zero) in that spectrum - we may want to reconsider this behavior in the future.
Fixes #1692
=> don't reset redshift when adding results from plugins

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py
manual backport of #1915 onto 3.1.x
=> Backport PR #1915: don't reset redshift when adding results from plugins

CHANGES.rst, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/configs/imviz/tests/test_tools.py, jdaviz/configs/imviz/tests/test_viewers.py, jdaviz/configs/imviz/tests/utils.py, jdaviz/core/astrowidgets_api.py
This pull request is to fix https://github.com/spacetelescope/jdaviz/issues/1927 .
I also have to allow centering on off-limit pixel locations to accommodate dithered images because the underlying calls all assume reference image coordinates frame.
=> Fix viewer.center_on for dithered images

CHANGES.rst, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py, jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.vue
This pull request provides a dropdown to choose between median and average for the background statistic passed to specreduce.
https://user-images.githubusercontent.com/877591/207668428-1fdca88e-0fd9-4a1c-9333-86cca13b1347.mov
=> spectral extraction: background median vs average dropdown

setup.cfg
Jdaviz won't show in the notebook with ipykernel 6.19.3, pinning to avoid that version.
=> Exclude bad ipykernel version

CHANGES.rst, docs/imviz/displayimages.rst, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.vue, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/utils.py, jdaviz/configs/imviz/wcs_utils.py, jdaviz/core/region_translators.py, notebooks/concepts/imviz_dithered_gwcs.ipynb
This pull request fixes WCS without fast-approximation resulting in layer cropping for images with GWCS by disabling the bounding box.  This also allows the mouseover coordinates to extrapolate across the entire viewer based on the G/WCS of the reference image.
Fixes #1905, fixes #1899, fixes  #1509
=> set bounding box to None to avoid layer cropping

CHANGES.rst, docs/imviz/displayimages.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.vue, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/utils.py, jdaviz/configs/imviz/wcs_utils.py, notebooks/concepts/imviz_dithered_gwcs.ipynb
Manual backport of #1908, removing logic for `if reverse` introduced by #1823 which is milestoned for 3.2.
=> Manual backport PR #1908: set bounding box to None to avoid layer cropping

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/initializers.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
This pull request cleans up some duplicating caching and subset handling in model fitting while working on the solution to #1910 (whose actual fix is blocked by significant subset refactoring).  It also improves on the intializer of `Linear1D` to estimate both the slope and intercept.
=> model fitting tweaks and cleanup

jdaviz/app.py
This pull request removes the unused functionality of parsers returning a string to be emitted as a snackbar message.  The only parser with a return statement is in mosviz from #1835, but that return is used elsewhere and is not expected to be exposed to the user as a snackbar message.
If we ever want a parser to warn the user, they have access to `app` so can emit snackbar messages themselves.
Note: since #1835 is milestoned as 3.2 and not yet released, this doesn't qualify as a bugfix and isn't user-facing, so I don't think a changelog entry is necessary.  If anyone thinks otherwise, let me know where you think it should belong.
Fixes #1888 …
=> do not interpret return from parsers as message

CHANGES.rst, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/tests/test_parsers.py
I think this is all that needs to be done to allow for direct image loading, but I need @camipacifici to test on her data.
=> Add Direct Image to expected file list for NIRCam

CHANGES.rst, jdaviz/components/tooltip.vue, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py
This pull request implements a plugin API and UI to re-estimate the initial values of free model parameters for individual or all model components.
https://user-images.githubusercontent.com/877591/209963319-f1bcd4f9-19ec-4422-9b8b-38e51306a51c.mov
**TODO**:
=> Model fitting: re-estimate model parameters

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.vue, jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py, jdaviz/core/template_mixin.py
This pull request prohibits the user selecting a spectral subset that does not overlap at all with the selected dataset.  This is done through a new plugin mixin which is then used in both model fitting and line analysis, showing red text in the plugin UIs, disabling the "fit" button in model fitting, and raising a traceback if calling the `fit` or `get_results` API methods, respectively.
**IMPORTANT NOTE**: adding the subset to the right (reference) data will result in a traceback because of #1868.  Once that bug is fixed, this logic should then handle that case as well.  Notes are added in the test cases if we want to update the test for either line analysis or model fitting to handle the opposite scenario as a regression test for #1868. …
=> prohibit subsets that do not overlap data range within plugins

CHANGES.rst, jdaviz/app.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/tests/test_data_loading.py, jdaviz/configs/mosviz/tests/test_parsers.py, setup.cfg
This PR fixes a bug found by a user with a private dataset where mosviz fails to find and populate the `SOURCEID` column, despite `SOURCEID` being registered in the metadata plugin. The main fix does this by introducing a new, preferred method of finding the `SOURCEID` by searching through the `.meta` attached to the data object rather than re-reading the file and searching through the header. This requires https://github.com/glue-viz/glue-jupyter/pull/336 to ensure the `.meta` is available before the metadata is parsed
This new strategy requires the data to be parsed and loaded first, to populate the data collection and associated `.meta` entries. Then, after all the data is loaded, then search for the metadata afterwards. Because the data already has its metadata attached to it, no need …
=> Mosviz Retrieve SourceID from meta

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/mosviz/plugins/slit_overlay/slit_overlay.py
This pull request fixes a bug in the slit overlay plugin in Mosviz which resulted in a snackbar error being raised complaining about `S_REGION`.  The underlying cause was that the plugin was accessing data from the image viewer instead of the spectrum-2d-viewer because of faulty default viewer assignment introduced in #1681.  This PR does not change the actual parsing or treatment of the slit itself, which still needs validation/testing.
=> fix default spectrum 2d viewer assignment for slit overlay plugin

setup.cfg
This pull request is to fix #1613 and fix https://github.com/spacetelescope/jdaviz/issues/1787 and fix #1926 and fix #1938
xref #1791 .
Multiple devs should check that things are truly fixed by this new voila release since several things were broken before. Make sure your ipywidgets is at least v8 and voila is v0.4 when you test.
* https://github.com/jupyter-widgets/ipywidgets/issues/3635 that requires reverting https://github.com/jupyter-widgets/ipywidgets/pull/3271, see https://github.com/jupyter-widgets/ipywidgets/pull/3642
* https://github.com/jupyter-widgets/jupyterlab-sidecar/pull/86
* #1937 …
=> MNT: Unpin maxversion of ipywidgets now that voila 0.4 is out, minversion ipywidgets now 8

setup.cfg
This pull request is to ignore ioloop DeprecationWarning from pyzmq because it comes from at least 3 upstream packages. We do not call this.
Relevant upstream PRs:
* https://github.com/jupyter/jupyter_client/pull/915
* https://github.com/glue-viz/glue-jupyter/pull/343
* https://github.com/widgetti/ipyvolume/pull/423
=> TST: Ignore ioloop DeprecationWarning from pyzmq

CHANGES.rst, docs/specviz/displaying.rst, jdaviz/app.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.vue, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/mosviz/tests/test_data_loading.py, jdaviz/configs/specviz/plugins/viewers.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/configs/specviz2d/tests/test_parsers.py, jdaviz/core/marks.py
This pull request is to implement the following feature request:
* The display should show the pixel in x on the first line and spectral axis and flux on the second line with appropriate units.
* The cursor should lock to the spectrum in x only.
- Is marker behavior acceptable? Is it too confusing to have both marker and the cursor?
- Are different display formats acceptable when tool is toggled on and off?
=> Improve coordinates display panel for spectrum viewer

CHANGES.rst, jdaviz/configs/imviz/tests/test_astrowidgets_api.py, jdaviz/core/freezable_state.py
This pull request is to prevent crashing in Imviz when Home is clicked on after markers are added.
Fixes #1964 
=> BUG: Home after markers no longer crash Imviz

CHANGES.rst, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py
Our traitlet messaging infrastructure does not support `nans` in the payload, as they are not JSON serializable. I changed the default fallback for missing RA/Dec values from `nan` to our default `Unspecified` we use for the Filter and Grating. Unfortunately this means it's a string rather than a float, and thereby a different type, but oh well.
I also add a preemptive sanitization check in `_add_to_table` to convert any `nans` to string 'nan's in case the user actually provides a `nan` directly. The issue/slightly controversial step here is the need to add `pandas` to our dependencies to actually perform the nan check. `numpy.isnan` doesn't support complex objects and will spit an error, as opposed to `pandas.isna`. We can debate whether we want this or not; I can easily remove it
Fixes …
=> Change nan fallback in MOS Table to avoid JSON Serialization Warning

CHANGES.rst, jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py
This is a quick PR to fix a (potential?) bug where the first smoothed dataset generated by the Gaussian Smooth plugin is missing the dataset name. As requested by Cami, all smoothed datasets should have consistent naming by having the original dataset represented in its name. I replaced the custom labeling logic with Jesse's app-wide data label generator for consistency.
Before:
After:
This is due to some weird (potentially buggy) behavior where the dataset field is unavailable until multiple "smoothable" data products are available:
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common …
=> Generate Gaussian Smooth data labels via App-wide data labeler

CHANGES.rst, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/tests/test_parsers.py
Oops...
Pretty alarming we didn't have a test for this. I added a quick and dirty one just to get this in ASAP.
=> Fix Mosviz Zoom Bug Typo

jdaviz/core/helpers.py
This pull request is to downgrade the snackbar message from error to warning when some Subsets are unable to be processed by `get_interactive_regions` that is supposed to only work for spatial Subsets.
=> Make get_interactive_regions snackbar message less alarming

setup.cfg
Once https://github.com/y-crdt/ypy/issues/114 and https://github.com/jupyterlab/jupyterlab/issues/13920 are resolved we can unpin this. Currently this is causing users to be unable to install Jdaviz on python 3.9.
=> Avoid installation error by pinning y_py < 0.5.5

.github/workflows/ci_cron_weekly.yml, .github/workflows/ci_workflows.yml, .github/workflows/codeql-analysis.yml, .github/workflows/predeps_workflows.yml, jdaviz/configs/imviz/plugins/catalogs/catalogs.py, jdaviz/configs/imviz/tests/test_catalogs.py, tox.ini
This pull request is to enable any maintainer to activate the workflow dispatch to test the next astropy release candidate instead of having to create a one-off throwaway PR.
Also minor updates to existing workflows.
* #1613
=> TST: Add RC testing workflow and update existing

docs/imviz/displayimages.rst, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/cubeviz/plugins/tests/test_parsers.py, jdaviz/configs/cubeviz/plugins/tests/test_tools.py, jdaviz/configs/cubeviz/plugins/viewers.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/configs/default/plugins/viewers.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.vue, jdaviz/configs/imviz/plugins/tools.py, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/configs/imviz/tests/test_tools.py, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/mosviz/tests/test_data_loading.py, jdaviz/configs/specviz/plugins/viewers.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/configs/specviz2d/tests/test_parsers.py, jdaviz/core/template_mixin.py
This pull request refactors/renames the logic in the coordinates info display so that:
* viewer callbacks are handled by the plugin itself rather than various viewers
* traitlets for the coordinate info are named based on their position in the widget.  Previously they were named based on their meaning in the original Imviz implementation, and then re-used for other viewers.  This became quite confusing to develop.  This change then also means all tests needed to be updated for the new formatting.
The behavior should essentially be the same as in #1894, except that the top line in specviz now reads "Cursor" instead of the previously hard-coded "Pixel".
Fix #1645 
should add a …
=> refactor mouseover coords info display

CHANGES.rst, docs/imviz/export_data.rst, jdaviz/app.py, jdaviz/components/plugin_table.vue, jdaviz/components/tooltip.vue, jdaviz/components/tray_plugin.vue, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue, jdaviz/core/template_mixin.py
This pull request implements a user-clearable table which displays the history of results from the aperture photometry plugin.  The previous `imviz.get_aperture_photometry_results` still works, but now serves as a shortcut to `plugin.export_table()` (once the user API is enabled for the aperture photometry plugin).
Future planned work includes the ability to display the table in a panel in the golden-layout section of the main app (below all other viewers), but for now support for popping out into a new window exists.
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look …
=> Aperture photometry table (with popout support)

CHANGES.rst, jdaviz/core/freezable_state.py
Avoid JSON serialization warning when loading valid data but axis not ready yet.
I started seeing JSON serialization warnings even when I load handmade data that I know to be valid. I tracked it down to `x_min` and `x_max` being set to `-inf` and `inf` (see diff). The warnings are harmless but also annoying and unnecessary.
=> Avoid JSON serialization warning

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/gaussian_smooth/tests/test_gaussian_smooth.py, jdaviz/conftest.py
Big thanks to Jesse and Kyle for the hack session that found this solution! This PR fixes #1956 by borrowing the linking logic from the Spectral Extraction plugin for any non-cube linking scenarios.
Turns out the fix is *slightly* more complicated than the one we figured out together; the linking logic for Spectral Extraction doesn't work for smoothed data being linked against cubes (mainly in the case of Cubeviz). Because Cubeviz wasn't impacted by this bug to begin with, and the observation that the Spectral Extraction linking logic works for Specviz too, I preserved the original logic for gaussian smooth linking in Cubeviz, while using the Spectral Extraction linking logic for the `ndim < 3` usecase.
Fixes #1956
list the proposed change log here for review and add to `CHANGES.rst` …
=> Fix 2D smooth visibility bug by utilizing SpectralExtraction linking logic

jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
This code block was getting triggered on app startup while the traitlet was still the default empty string rather than the assigned default value. This is a negligible performance increase but avoiding this block on startup matters for some other work I'm doing.
=> Prevent unneeded get_data_from_viewer call on app startup

jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py
This pull request removes `dataset_items` from the `@observe` for setting the default data label in the gaussian smooth plugin.  As of #1973, the number of items is no longer needed to determine the default label, so is not necessary to be included in the observe.  This change should have no influence on behavior, just will save some unnecessary callbacks that wouldn't do anything.
=> gaussian smooth default results label no longer needs dataset_items

setup.cfg
This pull request ignores that astropy unit warning: `The unit 'Angstrom' has been deprecated in the VOUnit standard. Suggested: 0.1nm.`
=> TST: ignore astropy angstrom unit warning

jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py
On [recent dev tests](https://github.com/spacetelescope/jdaviz/actions/runs/4315440387/jobs/7529820535), there's an error from within specutils saying:
```
def _compute_equivalent_width(spectrum, continuum=1, regions=None,
mask_interpolation=LinearInterpolatedResampler):
if regions is not None:
spectrum = extract_region(spectrum, regions)
if hasattr(spectrum, 'mask') and spectrum.mask is not None:
mask = spectrum.mask
spectrum = Spectrum1D(
>               flux=spectrum.flux[~mask],
spectral_axis=spectrum.spectral_axis[~mask])
E           TypeError: bad operand type for unary ~: 'NoneType'
```
This PR is a candidate fix for the spatial subset mask troubles caused by changes on dev. It seems some `Spectrum1D` objects have masks containing `None` in addition to True/False. Casting to `bool` …
=> TST: temporary fix for spectrum1d mask containing None

CHANGES.rst, jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/configs/cubeviz/plugins/slice/tests/test_slice.py
This pull request fixes the initial state of the uncertainty viewer (and any additional viewers created after).
Fixes #2045
=> fix initial slice of uncert-viewer

CHANGES.rst, jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_helper.py, jdaviz/configs/specviz/helper.py
This pull request is to avoid redshift slider warning when setting `[cubeviz.]specviz.y_limits(...)`. The added test is confirmed to fail in current `main` without this patch.
I am not familiar with redshift slider logic, so please double check the code. Thanks!
Fixes #2029 
=> BUG: Avoid redshift slider warning when setting y_limits

CHANGES.rst, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py, jdaviz/configs/specviz/plugins/viewers.py
This pull request fixes the redshift slider re-acting to helper methods: ``load_line_list``, ``plot_spectral_line``, ``plot_spectral_lines``, or ``erase_spectral_lines``.
Fixes #2013
=> fix redshift slider enabled/disabled from helper methods

CHANGES.rst, jdaviz/configs/specviz/helper.py
This pull request is to manually backport #2033 to v3.3.x. In this branch, the modified test does not exist.
=> Backport of PR 2033 to v3.3.x (BUG: Avoid redshift slider warning when setting y_limits)

CHANGES.rst, jdaviz/core/template_mixin.py, jdaviz/tests/test_subsets.py
This pull request fixes assigning composite subsets to the correct dropdowns (spatial vs spectral) by _assuming_ the subset is not mixed and taking the first item in the composite's tree and checking that type.
Fixes #2046
=> SubsetSelect: fix type-detection of composite subsets

CHANGES.rst, jdaviz/configs/imviz/plugins/viewers.py, jdaviz/configs/imviz/tests/test_line_profile_xy.py
This pull request is to manually backport #2073 to v3.3.x branch.
=> Backport PR 2073 to v3.3.x (BUG: Pressing l no longer update when Line Profiles plugin is closed)

CHANGES.rst, docs/cubeviz/export_data.rst, docs/specviz/export_data.rst, docs/specviz/plugins.rst, docs/specviz2d/export_data.rst, jdaviz/configs/cubeviz/plugins/tests/test_regions.py, jdaviz/configs/default/plugins/line_lists/line_lists.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/imviz/plugins/coords_info/coords_info.py, jdaviz/configs/specviz/helper.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/parsers.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/core/template_mixin.py, notebooks/CubevizExample.ipynb, notebooks/SpecvizExample.ipynb
Note that I left the call in `app.get_subsets_from_viewer`, since I think that will be part of @javerbukh's subset work, although I did implement something rather related in `specviz.get_spectra`. 
I believe there is one last failing test, and I probably need to get rid of some references to the old method in the docs. Other than that I think this is ready for other eyes.
=> Use get_data internally instead of get_data_from_viewer

CHANGES.rst, jdaviz/configs/imviz/tests/test_linking.py, jdaviz/core/freezable_state.py
Pressing HOME no longer crashes when images are linked by WCS and viewer is additional viewer and is empty. This bug is so obscure that I don't see much point in backporting.
Fixes #2079 
=> BUG: Pressing HOME no longer crashes

.github/ISSUE_TEMPLATE/bug_report.yaml, CHANGES.rst, conftest.py, jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/tests/test_parser.py, jdaviz/configs/specviz2d/tests/test_parsers.py, jdaviz/conftest.py, setup.cfg, tox.ini
This pull request is to use ASDF-in-FITS code from `stdatamodels` instead of `asdf`.
~Unfortunately, this is blocked by~:
* https://github.com/spacetelescope/stdatamodels/issues/133 that needs https://github.com/spacetelescope/stdatamodels/pull/134
* https://github.com/spacetelescope/stdatamodels/issues/135
Fixes #1980
=> Use stdatamodels for ASDF-in-FITS support

jdaviz/configs/specviz/helper.py
This fixes two bugs:
- `cubeviz.specviz.get_spectra` now properly retrieves the collapsed spectra rather than the whole cubes.
- `mosviz.specviz.get_spectra` no longer hits an `AttributeError` if there's a spatial subset defined. 
In regards to the second one, I think that is actually a `get_data` bug, since it's returning a Glue Data objects even with `cls=Spectrum1D` set in the internal `get_data` call. A better fix would be to either filter out spatial subset here in `get_spectra` if the config is Mosviz, or to fix the underlying behavior in `get_data`. But this simple fix was the fastest thing to get in - if there are objections to this, I'll look into more later this afternoon.
=> Bug fixes for get_spectra in other configs

CHANGES.rst, docs/specviz/export_data.rst, docs/specviz/plugins.rst, jdaviz/configs/default/plugins/markers/markers.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.py, jdaviz/configs/default/plugins/model_fitting/model_fitting.vue, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py, jdaviz/core/template_mixin.py, setup.cfg
This pull request uses the table subcomponent to log results from model fitting.
[updated model fitting plugin docs](https://jdaviz--2093.org.readthedocs.build/en/2093/specviz/plugins.html#model-fitting)
* does not store initial state ~or fixed state~ of parameters (do we want this?)
* ~does not account for the possibility of different model components having the same parameter name and index combination.  This just stores the information as it is stored internally in astropy (see video for example)~
* "model" is stored when it is added.  If the user overwrites an existing model, there will be two table entries with the same model label and would need to realize that the later one corresponds to the one currently loaded in the app (and available via `viz.get_models()`.
* doesn't really …
=> Model fitting table

README.rst
The README suggests displaying the app with `specviz.app`, when we usually recommend `specviz.show()`, so I updated it.
Also, @orifox once requested that we center-align the logo. I tried to sort that out, but it looks like github still doesn't fully support the necessary rst features.
=> DOC: readme tweaks

CHANGES.rst, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py, jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.vue
This pull request prevents resetting the internal traitlets in aperture photometry when failing to find a dataset/subset or raising an error, and only clears them when needed for the next successful run.  This also then keeps the log table visible.
Fixes #2111
=> aperture photometry: do not hide prev results when resetting

CHANGES.rst, jdaviz/app.py, jdaviz/tests/test_subsets.py
This pull request is to address the ordering of composite subset regions. These regions show what pixel region and subset mode operations (i.e. and, or, xor, andnot) went into creating a composite subset, and in what order. The order is now newest pixel region at the end  of the list (what is returned when running `viz.app.get_subsets(subset_name='Subset 1')` and indexing `region` or by setting `object_only=True` when calling `get_subsets()`).
This PR continues work from #2087 .
=> Reverse order of composite subset regions

CHANGES.rst, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_helper.py
This pull request extends #1984, #2072, and #2106 to add support for `cubeviz.get_data(..., function=True)` which looks up and adopts the collapse-function from the spectrum-viewer to return the collapsed spectrum.
Compare the following:
```
cubeviz.get_data(...) # cube
cubeviz.get_data(..., function=True) # collapsed spectrum
cubeviz.specviz.get_data(...) # collapsed spectrum, same as above
cubeviz.get_data(..., funtion='minimum') # collapsed spectrum, overrides function from that set in the viewer
```
Should this motivate changing the kwarg from "function" to "collapse"?  Would that be more intuitive to the user?  (Ah, but that was already released in 3.4 so probably shouldn't break existing API... would `function='viewer'` be better?
list the proposed change log here for review and add …
=> support cubeviz.get_data(function=True)

CHANGES.rst, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, jdaviz/core/events.py
This pull request updates the line analysis plugin to support changes to the display unit.
https://user-images.githubusercontent.com/877591/229872890-afc62640-67e5-4519-b2ab-5590abe72a98.mov
(Note that the limits resetting are reported in #2126)
Changelog will point to #2127 so is ignored from CI here.
=> Display units line analysis

setup.cfg
=> MNT: glue-core v1.9.0 is bad glue

jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, jdaviz/core/helpers.py, jdaviz/core/marks.py
This pull request enables the unit conversion plugin in cubeviz and adds support for the slice plugin/indicator.  The slice slider is always in order of _increasing slice_, so will not necessarily correspond to the positive x-direction on the viewer if switched from wavelength > frequency (or vice versa, depending on the original native units).  
https://user-images.githubusercontent.com/877591/230168474-3b19792e-4d3a-4bde-bb96-8ccd250e812c.mov
Note that we might want to generalize some of this logic more into the mark's `_update_data` when adding support for spectral lines as well.
This checklist is meant to remind the package maintainer(s) …
=> display units: cubeviz/slice plugin

CHANGES.rst, jdaviz/core/data_formats.py, jdaviz/core/tests/test_data_menu.py
Standalone and MAST interfaces would benefit from automatically launching the "best" jdaviz helper/configuration for a given data file. This PR is one step down that path, providing a new function for suggesting a helper based on the contents of the file. 
The function does the following:
* if `filename` ends in `asdf`, give "imviz" (the only ASDF-supporting helper so far)
* check WCS/gwcs for a spectral axis
* check if the file is recognized by [`astropy.io.registry`](https://docs.astropy.org/en/stable/io/registry.html). If there's only one unique match, return the corresponding helper.
* if the extension is a `fits.BinTableHDU` or `fits.fitsrec.FITS_rec`, look for standard spectral columns and return "specviz" if you find them
* if there are multiple possible matches in the …
=> Auto-configuration identification 

CHANGES.rst, jdaviz/app.py, jdaviz/tests/test_subsets.py
This pull request is to allow us to access the full glue state tree for creating a composite spectral subset. The way to access it is:
`specviz.app.get_subsets(simplify_spectral=False)`
This PR also gives access to the subset state object in the dictionary that is returned by `get_subsets`. That can be accessed using:
`specviz.app.get_subsets('Subset 1')[0]['subset_state']`
Fixes #2134 
=> Add option to see full glue state tree for spectral subsets

jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py, jdaviz/core/marks.py
This pull request updates the line lists plugin so that existing lines are unit-aware.  This does not yet update the display of lines in the plugin itself to show in the display units - that work will likely be deferred for the refactor of the line list plugin as both of those efforts will require changing the way the information is stored internally.
https://user-images.githubusercontent.com/877591/231570983-c7be856b-bba2-4d16-9228-41482e4e735d.mov
Changelog will point to https://github.com/spacetelescope/jdaviz/pull/2127 so is ignored from CI here.
Closes #2028 
This checklist is meant to remind the package maintainer(s) who will review …
=> Display units: line lists

jdaviz/core/tests/test_data_menu.py
The tests are currently failing because MAST removed a deprecated data product, which we happened to be using in a remote-data test to verify that the automatic config detector would choose Specviz. 
In this PR, I substitute the deprecated URI with another URI for a `JWST x1d` data product, which should also be opened with Specviz. I changed the cache setting to "update" to make for easier local debugging if/when other URIs are no longer available on MAST.
I also reverted a single change in the Imviz parser tests from https://github.com/spacetelescope/jdaviz/pull/2069 to match updated (recalibrated?) files from MAST.
This checklist is meant …
=> Fix bad MAST URI

CHANGES.rst, docs/mosviz/import_data.rst, jdaviz/configs/cubeviz/plugins/slice/tests/test_slice.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/mosviz/plugins/parsers.py, jdaviz/configs/mosviz/plugins/viewers.py, jdaviz/configs/mosviz/tests/test_data_loading.py, jdaviz/configs/mosviz/tests/test_helper.py, jdaviz/configs/mosviz/tests/test_parsers.py, notebooks/MosvizExample.ipynb
This pull request is to update Mosviz doc on importing data, and also enable NIRSpec auto loader to take a single image.
And then the scope expanded and now it also fixes #2144
=> Update Mosviz parser doc and fix NIRSpec auto-load

docs/imviz/plugins.rst
This pull request is to clarify that `photutils` does not use the Subset mask being displayed. Well, not exactly. 🤪 
=> DOC: What you see is not what you get when it comes to Subset shape in aperture photometry

docs/imviz/plugins.rst
This pull request is to slap a warning on the doc until we can properly fix it over at #2154 since that one is dragging on much longer than I had hoped for and now also #2164 is in play and needs upstream fixes in glue-core and glue-astronomy.
[🐱](https://jira.stsci.edu/browse/JDAT-3272)
=> DOC: Add warning to aperture photometry plugin about apertures

jdaviz/configs/imviz/tests/test_regions.py, tox.ini
This pull request is to:
* workaround #2165 
* update test to reflect glue-viz/glue-astronomy#90
=> TST: Fix devdeps failures

jdaviz/app.py
Downstream, LCviz will show light curves as profiles of flux over time. In order give LCviz a subset API that's consistent with jdaviz, we need to generalize a few things here.
The `get_data_from_viewer` and `get_subsets` methods in `Application` make some assumptions about the dimensionality of data in jdaviz (data with ndim=1 is spectral; dim options are only spectral or spatial). This PR generalizes the `get_data_from_viewer` method to work with non-spectral profiles, and introduces a temporal subset option.  
I've milestoned this to 3.4.1 just in case we can get a release ASAP.
This checklist is meant to remind the package maintainer(s) …
=> adding support for temporal subsets

CHANGES.rst, jdaviz/configs/default/plugins/model_fitting/tests/test_fitting.py, jdaviz/core/helpers.py
Fixes #2158 . I also removed the `_3d` that was getting tacked on to the label for the cube models, since by default the labels for those in the plugin now get `cube-fit ` prepended to the suggested label. Basically, there might not be fitted parameters for every spaxel (due to masking and such), so relying on the length of the arrays of x and y spaxel locations was unreliable.
=> Fix size calculation for model parameters array

.github/workflows/ci_workflows.yml, .github/workflows/publish.yml, CHANGES.rst, docs/installation.rst, setup.cfg
Numpy is imminently dropping support for Python 3.8
=> drop support for Python 3.8

docs/index.rst, setup.cfg
As of #2152 , we no longer support python 3.8. This adds a warning to the home page of the docs, and drops a pin that was only needed because of 3.8 support.
=> Add note about python 3.8 and remove ipython pin

CHANGES.rst, jdaviz/configs/imviz/plugins/parsers.py, jdaviz/configs/imviz/tests/test_parser.py
Imviz, and especially its parser, will do some heavy lifting for Roman files. I'm doing some profiling, and found that the parser tweaks in this PR speed up the parser by a factor of 3 on my machine (the machine matters for reasons I'll explain below).
The speedups come from the following corrections:
* The top-level image parser decides how to parse a given file based on its file extension. This doesn't work on astropy-cached files, since they all have the file name `contents`. I worked around this earlier by making a reverse-lookup dict to find source URLs for each file in the cache (see below), which is actually quite slow if the cache is heavily used. Since I have *12,000* files in my cache (😱), this lookup took up a lot of time. In this PR, I avoid the lookup unless the filename is …
=> ENH: Imviz parser optimizations

CHANGES.rst, jdaviz/configs/default/plugins/plot_options/plot_options.py, jdaviz/configs/default/plugins/plot_options/plot_options.vue, jdaviz/configs/default/plugins/plot_options/tests/test_plot_options.py, jdaviz/conftest.py
This pull request ports the histogram from #2097 into the plot options plugin.  This is currently limited to a single layer (in a single viewer) and will clear itself when that is not the case.
(Note: shouldn't be this laggy in real life)
https://user-images.githubusercontent.com/877591/232864726-6bd3af42-727e-4fee-914d-bd7b7863945d.mov
**TODO**:
Future efforts:
* display current vmin/max on histogram [:cat:](https://jira.stsci.edu/browse/JDAT-3270)
* multiviewer/layer support [:cat:](https://jira.stsci.edu/browse/JDAT-3277)
* ability to set bin size and limits of histogram [:cat:](https://jira.stsci.edu/browse/JDAT-3269)
* logarithmic scale [:cat:](https://jira.stsci.edu/browse/JDAT-3268) (blocked by https://github.com/bqplot/bqplot/issues/1300)
* interactivity (ability to click/drag to …
=> basic single-viewer/layer histogram in plot options

jdaviz/configs/imviz/plugins/coords_info/coords_info.py
Without this patch, when you run `notebooks/concepts/imviz_compass_mpl.ipynb` for the first use case (where I pass in `WCS()` as the image WCS), you mouse over the data in Imviz, mouseover display will blink a lot but always go back to "auto". This is because while the WCS still has enough info to draw a compass, its `pixel_to_world` returns a tuple of dimensionless Quantity, not SkyCoord, causing mouseover logic to go into a special place in the logic route.
With this patch, mouseover will still display pixel coords and value but not the sky coordinates. 
I tried to add a test like this but I could not get it to fail even without this patch, so I decided not to include it. I also decided not to include a change log since this should not happen with real data.
```diff
--- …
```
=> Fix obscure mouseover bug when empty WCS is used for Imviz

jdaviz/app.py
This pull request is a direct follow-up of #2087 .
=> DOC: get_subsets do not return masked subset state

jdaviz/app.py, jdaviz/configs/imviz/tests/test_viewers.py
This pull request is to implement something that has been annoying me.
When you create a second viewer in Imviz, it has no reference. But the generic call `imviz.app.get_viewer()` chokes on that fact and then I have to do one extra call to `imviz.app.get_viewer_by_id()` when I forget about that and it happens to me again.
Since we told ourselves that `.app` stuff is not "public," I didn't bother with a change log.
=> Let app.get_viewer() fallback to ID when reference is None

jdaviz/configs/specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py, jdaviz/core/tests/test_data_menu.py, pyproject.toml
This pull request removes the max-pin on glue but forbids the broken 1.10 version.
Fixes #2183
=> unpin max glue

CHANGES.rst, docs/imviz/plugins.rst, jdaviz/components/tray_plugin.vue, jdaviz/configs/imviz/plugins/rotate_canvas/rotate_canvas.vue
As requested after having issues with rotation in non Chrome browsers. this PR implements a JS script check to enter a `disabled_msg` if it detects a non-Chromium browser, which disables the plugin, referring the user to the documentation, where I included a new line that mentions only supporting Chrome browsers.
As you can see from the screenshot, this PR also, by suggestion from reviewers, displays the description and documentation field even when the plugin is disabled:
Of importance to note: This PR does NOT disable the plugin's API. After talking with @kecnry, this effort should be considered for followup work, though consideration should be made whether the effort should be undertaken depending on if we are planning on ditching this plugin entirely eventually anyways. We thought of …
=> Disable Canvas Rotation Plugin in non-Chromium Browsers

CHANGES.rst, jdaviz/app.py, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py, jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/tests/test_subsets.py
This pull request is to address editing of composite subsets in the Subset Plugin. ~~Still working on issues related to spectral subsets but updating is at least possible, if not a little inconvenient at the moment.~~ That issue is being tracked [here](https://github.com/spacetelescope/jdaviz/issues/2061) and on slack. It is not introduced by this PR.
XOR functionality has been added to this PR and the ADD mode has been fixed. A previous version did not cover all possible cases and tests have been added to make sure those cases are covered for the future.
Fixes #2162 
Fixes #1568 
This checklist is meant to remind the package maintainer(s) …
=> Enable editing of composite subsets in the subset plugin

CHANGES.rst, jdaviz/configs/cubeviz/helper.py, jdaviz/configs/cubeviz/plugins/tests/test_cubeviz_helper.py, jdaviz/configs/imviz/helper.py, jdaviz/configs/mosviz/helper.py, jdaviz/configs/specviz/helper.py, jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py, jdaviz/configs/specviz2d/helper.py, jdaviz/core/helpers.py, jdaviz/core/template_mixin.py, jdaviz/core/tests/test_helpers.py
This pull request is to add API to retrieve a data cube with a spatial subset applied to it, with a spectral subset then applied to that. The way to do that (using the CubevizExample notebook) is:
```
data_label = "jw02732-o004_t004_miri_ch1-shortmediumlong_s3d.fits[SCI]"
spatial_subset = "Subset 1"
spectral_subset = "Subset 2"
cubeviz.get_data(data_label, spatial_subset=spatial_subset, spectral_subset=spectral_subset, function=True)
```
There are also now `get_data` methods in Imviz and Specviz2D since the core `get_data` method no longer allows a subset to be applied.
Todo:
Fixes #1354 
Fixes #1490  …
=> Add option to get_data to apply spectral subset to collapse spatial

CHANGES.rst, jdaviz/core/helpers.py
This pull request reintroduces the flexibility needed for downstream apps (including lcviz - see updates in https://github.com/spacetelescope/lcviz/pull/20) to use `get_data` with non-spatial/spectral masking subsets as an extension of #2199.
=> generalize to allow downstream apps to set masked subset

jdaviz/app.py, jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/core/marks.py
Our custom unit converter needed to account for the case where the viewer y-limits are converted, and the PluginMark y-unit conversion needed to include the `spectral_density` equivalencies.
The tests that need dev glue will still fail, should be 37 of those I think.
=> Fix unit conversion for PluginMarks and y-limits

docs/cubeviz/export_data.rst, docs/specviz/export_data.rst, jdaviz/configs/cubeviz/helper.py, jdaviz/core/marks.py, notebooks/SpecvizExample.ipynb
The dang marks plugin keeps flubbing unit conversion. This time it was trying to convert an empty flux array, so the shape of the spectral axis didn't match.
=> Fix ci again

tox.ini
Change PIP_EXTRA_INDEX_URL because packages moved where they upload nightly builds. This is one of the things they did at Scientific Python Developers Summit 2023.
=> TST: Change PIP_EXTRA_INDEX_URL

jdaviz/components/plugin_add_results.vue, jdaviz/core/template_mixin.py
This pull request extends the support for the plugin results mixin to properly handle overwriting an existing data entry when that data entry is already loaded in _multiple_ viewers (the case of a single viewer was previously supported).  This is not currently used in jdaviz, but will be by lcviz (and could be by jdaviz if we ever want to support creating multiple spectrum viewers in any of the configs).
=> plugin results: support overwriting when data loaded in multiple viewers

jdaviz/app.py, jdaviz/configs/default/plugins/viewers.py
This pull request fixes a bug in the `dev-display-units` (#2127) branch with the axes labels on cube viewers in cubeviz.  An internal call to `set_plot_axes` when new data is added to a viewer was inadvertantly removed in https://github.com/spacetelescope/jdaviz/pull/2048/files#diff-33416aee3e2d4c0d86f96811f082119130c8598ef01ce1c9a7e852ecc39779b3L1595 . 
=> reverts removal of call to set_plot_axes when loading data into viewer

docs/create_products.rst, docs/cubeviz/import_data.rst, docs/index.rst, docs/mosviz/import_data.rst, docs/specviz/import_data.rst, docs/specviz2d/import_data.rst
This pull request is to add a documentation page to explain how to create products that can be read into Jdaviz. This is to address a request from the community.
Under "Other changes": documentation page to explain how to create products that can be read into Jdaviz.
=> Add docs page to explain how to create jdaviz-readable products

CHANGES.rst, jdaviz/app.py, jdaviz/tests/test_subsets.py
This pull request is to fix #2241 quickly without having to wait for upstream.
=> BUG: Fix ellipse translation in app.get_subsets()

CHANGES.rst, jdaviz/app.py, jdaviz/tests/test_subsets.py
This pull request is to manually backport #2244 to v3.5.x.
=> Backport PR 2244 to v3.5.x (BUG: Fix ellipse translation in app.get_subsets())

jdaviz/configs/default/plugins/subset_plugin/subset_plugin.py
This pull request implements a patch so that temporal subsets (as currently [used in lcviz](https://github.com/spacetelescope/lcviz/pull/29)) do not crash the subset plugin.  Note that there are still bugs with the way that simplifying and updating these subsets are handled for the temporal case, but those will require more in-depth generalization [:cat:](https://jira.stsci.edu/browse/JDAT-3475).
This bug was introduced since the latest release, so does not need a change log entry as a bug fix.
This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not …
=> temporary subset plugin patch to handle non-spectral range subsets

CHANGES.rst, jdaviz/configs/imviz/plugins/coords_info/coords_info.py
This pull request is to fix mouseover behavior in Cubeviz spectrum viewer when spatial subset is present. This was originally part of #2242 by @duytnguyendtn but we need to backport this. If this works, you should see two fixes:
1. Mouseover now does not ignore collapsed spectrum from spatial subset when you mouseover collapsed spectrum in spectrum viewer in Cubeviz.
2. You no longer see mouseover lag on Windows when you have spatial subset drawn and you are mousing over in spectrum viewer.
@javerbukh should review this. …
=> BUG: Fix mouseover behavior in Cubeviz

docs/known_bugs.rst
This pull request is to reference the ongoing work at #2263 to diagnose the Windows OS slowdown when using subsets in cubeviz.
=> Add doc for windows latency issue

CHANGES.rst, docs/cubeviz/plugins.rst, jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py, jdaviz/configs/cubeviz/plugins/moment_maps/tests/test_moment_maps.py, jdaviz/configs/cubeviz/plugins/slice/slice.py, jdaviz/configs/cubeviz/plugins/tests/test_export_plots.py, jdaviz/configs/default/plugins/export_plot/export_plot.py, jdaviz/configs/default/plugins/export_plot/export_plot.vue, jdaviz/conftest.py, notebooks/concepts/cubeviz_ndarray_gif.ipynb, pyproject.toml, tox.ini
This pull request is to add functionality to export Cubeviz slices into a movie file.
Doc: https://jdaviz--2264.org.readthedocs.build/en/2264/cubeviz/plugins.html#movie
Example video generated from flux viewer: https://www.youtube.com/watch?v=KticlwspGV4
Fixes #2245 and fixes https://github.com/spacetelescope/jdaviz/issues/2271
- Open follow-up issue about GIF support.
- Open follow-up issue about https://github.com/spacetelescope/jdaviz/pull/2264#issuecomment-1612052525
=> Button to export Cubeviz movie

CHANGES.rst, docs/cubeviz/import_data.rst, docs/specviz/export_data.rst, docs/specviz/import_data.rst, jdaviz/configs/default/plugins/line_lists/tests/test_line_lists.py, jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py, jdaviz/configs/default/plugins/subset_plugin/tests/test_subset_plugin.py, jdaviz/configs/specviz/helper.py, jdaviz/configs/specviz/plugins/line_analysis/tests/test_line_analysis.py, jdaviz/configs/specviz/plugins/line_analysis/tests/test_lineflux.py, jdaviz/configs/specviz/plugins/unit_conversion/tests/test_unit_conversion.py, jdaviz/configs/specviz/tests/test_helper.py, jdaviz/core/data_formats.py, jdaviz/core/tests/test_data_menu.py, jdaviz/core/tests/test_helpers.py, jdaviz/core/tests/test_template_mixin.py, jdaviz/tests/test_app.py, jdaviz/tests/test_subsets.py
This pull request brings specviz in line with the other viz tools by deprecating `specviz.load_data` and replacing it with `specviz.load_data`. I think I got all the documentation changes as well here. Should be pretty uncontroversial, as we've been asking for this for a long time
The decreased coverage is due to the deprecated method
=> Replace load_spectrum with load_data
